### ISSUE TITLE
Unable to run 'x3dom' in strict mode,Uncaught TypeError: Cannot use 'in' operator to search for 'Zlib' in undefined

### ISSUE THREAD

**Issue by masx200** [x3dom/x3dom#1000]
Unable to run 'x3dom' in strict mode

```js
var temp1=document.createElement('script')
temp1.src='https://cdn.jsdelivr.net/npm/x3dom@1.8.1/x3dom.min.js'
temp1.type='module'
document.head.appendChild(temp1)
```
Uncaught TypeError: Cannot use 'in' operator to search for 'Zlib' in undefined
![image](https://user-images.githubusercontent.com/34191203/66306589-9e9a6300-e934-11e9-9973-c6cf7fec28ff.png)

```js
 function s(e, i) {
        var s, r = e.split("."), n = o;
        !(r[0]in n) && n.execScript && n.execScript("var " + r[0]);
        for (; r.length && (s = r.shift()); )
            r.length || i === t ? n = n[s] ? n[s] : n[s] = {} : n[s] = i
    }
```
![image](https://user-images.githubusercontent.com/34191203/66306840-4f086700-e935-11e9-9cca-5aeecddb3025.png)

**Comment by tsturm** [comment]
Can you try it with the current dev version:
https://x3dom.org/download/dev/x3dom.js

**Comment by masx200** [comment]
> Can you try it with the current dev version:
> https://x3dom.org/download/dev/x3dom.js

The new version '1.8.2' is not reporting an error and is running normally.

**Comment by tsturm** [comment]
Great :)
