### ISSUE TITLE
npm build script depends on git

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#1003]
Since the builder script uses git to get version information, the build directory needs to be a proper git repo. It would be great if the script has a fallback for the situation when somebody just downloads the zip archive from github for a quick try without having to learn git or to install git.
It may suffice to have a try/catch or default values for the version strings in the build script.

**Comment by tsturm** [comment]
fixed with 80305d2

**Comment by andreasplesch** [comment]
Thanks
