### ISSUE TITLE
keep components ?

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#1004]
X3D has components to load when needed: #28 
The new builder does not build those anymore. They were rarely used.
Nevertheless, should we keep the component bundles around until require or modules are used ?
I am not sure. It is not much effort to provide these but for full effect X3D profiles would need to be supported as well which was never the case.
Most author's probably would not want more fine grained control than the three current versions: x3dom, x3dom-full, x3dom-physics. But some may.

**Comment by tsturm** [comment]
I have decided to remove the components because I don't know anybody who has ever used the single components.

I think we should get rid of old, unused stuff like this to get a more clean codebase over the time.

**Comment by andreasplesch** [comment]
Well, let's keep the issue around but I also doubt that there is a demand for the component bundles.

**Comment by andreasplesch** [comment]
https://github.com/x3dom/x3dom/blob/d4e99575f49b4bc9f16c23b2f649ccc16c4d1f30/src/Main.js#L85-L93

may then also be removed as far as I can tell.

**Comment by tsturm** [comment]
Yes. And maybe the part below too.
The ```src``` attribute was never documented.

https://github.com/x3dom/x3dom/blob/d4e99575f49b4bc9f16c23b2f649ccc16c4d1f30/src/Main.js#L95-L102

**Comment by tsturm** [comment]
Removed with fc16d26ca253d881b742c462313d8f52ecb4f9c0
