### ISSUE TITLE
Picking binary geometry stopped working in v1.8.1

### ISSUE THREAD

**Issue by tomssd** [x3dom/x3dom#1009]
After using AOPT to transform X3D models to binary geometry, picking no longer works.

This works in v1.7.2
http://cowanland.com/pick_binaryGeom_problem/index.1.7.2.html

This stopped working in v1.8.1 (current release)
http://cowanland.com/pick_binaryGeom_problem/index.1.8.1.html

This also does not work in the current development version (build 6974 1.8.2-dev) that was posted recently.

**Comment by tsturm** [comment]
Can you try the latest dev build (6977):
https://x3dom.org/download/dev/

**Comment by tomssd** [comment]
The new dev build (6977) appears to be working correctly when selecting binary geometry. 
I will continue testing and let you know if anything else turns up.

Thank You!
