### ISSUE TITLE
eslint

### ISSUE THREAD

**Issue by tsturm** [x3dom/x3dom#1010]
I have added eslint and lint the whole source code:

https://github.com/x3dom/x3dom/tree/eslint

@andreasplesch Is it okay for you if I merge it back to master?

The current rules are:

```{
    "parserOptions": {
        "ecmaVersion": 5
    },
    "rules": {
        "indent": ["error", 4, { "SwitchCase": 1 }],
        "no-tabs": ["error"],
        "array-bracket-spacing" : ["error", "always"],
        "comma-dangle": ["error", "never"],
        "comma-spacing": ["error", { "before": false, "after": true }],
        "space-in-parens": ["error", "always", { "exceptions": [] }],
        "computed-property-spacing": ["error", "always"],
        "brace-style" : ["error", "allman", { "allowSingleLine": true }],
        "no-trailing-spaces": "error",
        "padded-blocks": ["error", "never"],
        "prefer-const": "error",
        "space-before-function-paren": "error",
        "keyword-spacing": "error",
        "space-infix-ops": "error",
        "semi": "error",
        "curly": "error",
        "quotes": ["error", "double", { "allowTemplateLiterals": true }],
        "one-var-declaration-per-line": ["error", "always"],
        "no-multiple-empty-lines": ["error", { "max": 1 } ],
        "new-parens": "error",
        "lines-between-class-members": ["error", "always"],
        "key-spacing": ["error", {
            "multiLine": { "beforeColon": true, "afterColon": true },
            "align": { "beforeColon": true, "afterColon": true, "on": "colon" }
        }],
        "func-call-spacing": ["error", "never"]
    }
}```

**Comment by andreasplesch** [comment]
Do you want me to test a bit the examples since it is a very large change ? I am sure eslint is battle tested but ...

**Comment by tsturm** [comment]
I have already tested everything inside test/functional and test/regression.

If you want, we can test some more examples.

**Comment by jamesleesaunders** [comment]
Wow good move!
When I get time I will get back on the JSDoc tidy also.

**Comment by jamesleesaunders** [comment]
It is of course up to you, but is it intentional that you have switched brace-style to 'allman'?
It was previously the majority '1tbs' style.

```
// 1tbs
while (x == y) {
    something();
    somethingelse();
}
```
vs:
```
// allman
while (x == y)
{
    something();
    somethingelse();
}
```

FWIW My preference is 1tbs (more commonly used in JS).

**Comment by andreasplesch** [comment]
https://www.x3dom.org/examples/ comes to mind. But if testing those examples is too involved without merging into master, I do not have objections since the test/ examples should cover a lot.
#1011 is a PR on text improvements from a branch of current master. Do you want to merge this first and then redo the eslinting, or do you want me to redo the PR afterwards ?

**Comment by andreasplesch** [comment]
I have created a build of the eslint branch here:
https://5db5d697ab6df745cc5dde59--x3dom.netlify.com/
For easy additional exploration, testing.

**Comment by tsturm** [comment]
@jamesleesaunders I prefer the allman style, especially for the x3dom source code where the blocks between the braces are often really long. 

@andreasplesch I have merged your PR to master and pull it down to the eslint Branch.

Thanks, for the build :)

**Comment by andreasplesch** [comment]
Thanks. I updated the eslint branch build here: https://5db6132529624200094c7228--x3dom.netlify.com/
This is largely automated, just a matter of setting a deploy branch, and pulling over to my fork,

**Comment by tsturm** [comment]
I have merged the eslint branch into master, now.
