### ISSUE TITLE
render texture for PointSet

### ISSUE THREAD

**Issue by styxsys0927** [x3dom/x3dom#1020]
I'm trying to put image texture at each point's coordinate in a PointSet, scale the size of each texture image by my gl_PointSize value, and mix the color of the texture and each point's original color. 

For example, I now have three points and a texture picture looks like a ball. Point #1 is red with a size of 20; Point #2 is green with a size of 30; Point #3 is blue with a size of 50.  With the shader, I want to display three balls: red+diameter=20, green+diameter=30, and blue+diameter=50.

It seems that there is a feature called "point sprite" after OpenGL 2.0, which enables one draw image texture centered at a point. I basically copied the glsl part of a OpenGL code, which is claimed working, but it does not work in my html... 

Here is my code:
`<shape>
            <Appearance>

                <ImageTexture  url="circle_texture.png"><ImageTexture/>
                <ComposedShader>
                    <ShaderPart type='VERTEX' style="display:none;">
                        attribute vec4 position;
                        attribute vec3 color;
                        attribute vec2 texcoord;

                        uniform mat4 modelViewMatrix;
                        uniform mat4 modelViewMatrixInverse;
                        uniform mat4 modelViewProjectionMatrix;
                        uniform mat4 normalMatrix;

                        varying vec3 col;
                        varying vec2 fragTexcoord;

                        void main()
                        {

                            gl_Position = modelViewProjectionMatrix * vec4(position.xyz, 1.0);
                            gl_PointSize = max( 200.0 / gl_Position.w, 1.0);
                            fragTexcoord = texcoord;
                            col = color;
                        }
                    </ShaderPart>
                    <ShaderPart type='FRAGMENT' style="display:none;">
                        #ifdef GL_FRAGMENT_PRECISION_HIGH
                        precision highp float;
                        #else
                        precision mediump float;
                        #endif

                        uniform sampler2D tex;

                        varying vec3 col;
                        varying vec2 fragTexcoord;

                        void main()
                        {
                            gl_FragColor = texture2D(tex, fragTexcoord) * col;
                        }
                    </ShaderPart>
                </ComposedShader>
            </Appearance>
            <pointSet>
                <coordinate DEF='mypts' point='0 0 0 2 2 2 3 3 3'></coordinate>
                <color color='1 0 0 0 1 0 0 0 1'></color>
            </pointSet>

        </shape>`

And my texture PNG:
![circle_texture](https://user-images.githubusercontent.com/25677396/68650544-3f131280-04f3-11ea-98e0-1f671bb69efb.png)

Besides, I also tried to debug my code in Spector.js. It shows that it did get the texture file and run some glsl code... Though the shader codes are not written by me. I assume that those codes are from X3DOM project, but I cannot find my own code anywhere in Spector.js... So I just wonder, how the combination of glsl codes works? Or my codes are just replaced by X3DOM's codes when I use appearance nodes (ImageTexture here) other than composed shader? (I can see my own code when there is only composed shader node)

Thank you so much!

**Comment by tsturm** [comment]
Hi @styxsys0927,

to render point sprites you can use `gl_PointCoord` to retrieve the texture coordinates of your points inside the fragment shader.

Followed you can find a modfied version of your shader. A live version is available [here](https://examples.x3dom.org/example/pointspriteShader/pointspriteShader.html)



```
<x3d>
    <scene>
        <transform>
            <shape>
                <appearance>
                    <imagetexture url="./circle_texture.png"></imagetexture>
                    <composedshader>
                        <field name="tex" type="SFInt32" value="0"></field>

                        <shaderpart type='VERTEX' style="display:none">

                            attribute vec3 position;
                            attribute vec3 color;
                            uniform mat4 modelViewProjectionMatrix;

                            varying vec3 col;

                            void main()
                            {
                                gl_Position = modelViewProjectionMatrix * vec4(position, 1.0);
                                gl_PointSize = max( 200.0 / gl_Position.w, 1.0);
                                col = color;
                            }

                        </shaderpart>

                        <shaderpart type='FRAGMENT' style="display:none">
                            #ifdef GL_FRAGMENT_PRECISION_HIGH
                            precision highp float;
                            #else
                            precision mediump float;
                            #endif

                            uniform sampler2D tex;

                            varying vec3 col;

                            void main()
                            {
                                vec2 texCoord = clamp(gl_PointCoord, 0.01, 0.99);
                                vec4 texColor = texture2D(tex, texCoord);
                                gl_FragColor = vec4(texColor.rgb * col, texColor.a);
                            }

                        </shaderpart>
                    </composedshader>
                </appearance>
                <pointset>
                    <coordinate point='0 0 0 2 2 2 3 3 3'></coordinate>
                    <color color='1 0 0 0 1 0 0 0 1'></color>
                </pointset>
            </shape>
        </transform>
    </scene>
</x3d>
```

**Comment by tsturm** [comment]
You can also use the x3dom [ParticleSet](https://doc.x3dom.org/author/Rendering/ParticleSet.html)-Node for use cases like this.

Here the x3d and the live [example](https://examples.x3dom.org/example/pointspriteShader/particleSet.html).

```
<x3d>
    <scene>
        <transform>
            <shape>
                <appearance>
                    <material></material>
                    <depthmode readOnly='true'></depthmode>
                    <imagetexture url="./circle_texture.png"></imagetexture>
                </appearance>
                <particleset drawOrder='backToFront' size="2 2 2, 3 3 3, 5 5 5">
                    <coordinate point='0 0 0 2 2 2 3 3 3'></coordinate>
                    <color color='1 0 0 0 1 0 0 0 1'></color>
                </particleset>
            </shape>
        </transform>
    </scene>
</x3d>
```

**Comment by styxsys0927** [comment]
Hi tsturm,

Thank you so much for your reply! Your code works perfectly fine on the three-point example but when I try to apply it to a larger pointset data, it seems that the alpha channel is not working
![image](https://user-images.githubusercontent.com/25677396/68695968-15390a80-054a-11ea-902a-052df4d4c884.png)
Any idea how this happens?

Thanks!

**Comment by tsturm** [comment]
Hi @styxsys0927,

that is really strange. The alpha channel should not be affected by the number of points.

Can you provide me with one of the larger data sets?

**Comment by tsturm** [comment]
You can also try to discard pixels with a low alpha value inside the fragment shader.

```
if(texColor.a < 0.1)
{
    discard;
} 
```

**Comment by styxsys0927** [comment]
Here is my data
[catawba1000.zip](https://github.com/x3dom/x3dom/files/3837547/catawba1000.zip)

I just tried the discard code and all the points are gone...

**Comment by tsturm** [comment]
The discard code works for me:

![points](https://user-images.githubusercontent.com/864076/68701923-1ab54580-0588-11ea-91f5-9033664fbe46.PNG)

Without the `discard` you have to sort your points back-to-front every frame, which is performance wise not the best idea. Here is a short code snippet for the sorting, but be careful, It uses internal variables. This means nobody can guarantee that the script will work for a longer time.

```
document.querySelector("scene").addEventListener("viewpointChanged", ( camera ) =>
{
	const pointSet  = document.querySelector("pointset"),
              points    = document.querySelector("coordinate").requestFieldRef("point");
              model     = document.querySelector("transform")._x3domNode._trafo,
              modelView = camera.matrix.mult(model);

    points.sort( function(a, b)
    {
	return modelView.multMatrixPnt(a).z - modelView.multMatrixPnt(b).z
    });

    pointSet._x3domNode.fieldChanged("coord");

} );
```

I think the best solution for you is to use the ParticleSet.

**Comment by styxsys0927** [comment]
Just found that the discard code actually worked... My point cloud disappeared because it was not centered at the screen... Sorry for the stupid question...

Thank you for the help! The problem is solved!

**Comment by tsturm** [comment]
Great to hear that!

Maybe you have to try different discard thresholds. For me 0.01 worked fine.

**Comment by styxsys0927** [comment]
Sure! Thank you again and wish you all the best！

**Comment by andreasplesch** [comment]
If you decide to use an inline, make sure to use a CDATA section for the shaders:

https://raw.githack.com/andreasplesch/Library/e5ec12f9ed32aa3da86299f6510a83dfb7df3c52/Examples/pointshader/pointshader.html

Here is the x3d:
https://raw.githubusercontent.com/andreasplesch/Library/gh-pages/Examples/pointshader/catawba1000.x3d

(I also played a bit with luminosity adjustments in the shader).

**Comment by styxsys0927** [comment]
OMG it seems amazing! Guess that there are a lot more features for me to explore in shaders and X3DOM!
