### ISSUE TITLE
PlaneSensor and SphereSensor are not working correctly with HiDPI displays

### ISSUE THREAD

**Issue by SMuehle** [x3dom/x3dom#1021]
I'm currently working with a Microsoft Surface Pro and noticed that transformations of shapes don't work properly on devices with HiDPI which don't have a 1:1 display-to-logical pixel ratio.

Picking with an onclick attribute works fine but the use of PlaneSensor und SphereSensor leads to some issues.
In [this example](https://doc.x3dom.org/tutorials/animationInteraction/transformations/index.html) the cyan handle immediately jumps to the far left when I move it and gets stucked afterwards.

When I'm using a PlaneSensor in combination with a Route-Node the shape moves with an offset like in [this example](https://jsfiddle.net/0mdrcfes/)
The SphereSensor doesn't react at all so the shape stays fixed like [in this example](https://jsfiddle.net/o9n8htg5/)

**Comment by tsturm** [comment]
Can you try it with the current dev build

https://x3dom.org/download/dev/

**Comment by SMuehle** [comment]
With the current dev build everything works fine, thank you.
I was not aware that the official examples are working with older versions.
Issue can be closed.

**Comment by andreasplesch** [comment]
Hm, the now reverted commit was in response to a similar issue earlier this year. It may be necessary to test on iOS and Android as well.

**Comment by andreasplesch** [comment]
#959 has the reverted commits. Will look for the original issue.

**Comment by andreasplesch** [comment]
https://sourceforge.net/p/x3dom/mailman/message/36676349/ is the thread on the mailing list.

**Comment by tsturm** [comment]
Works on Pixel 2 ( Android 10 ) with a devicePixelRatio of 3.5

**Comment by andreasplesch** [comment]
A few more scenes to test:
https://raw.githack.com/x3dom/x3dom/master/test/regression-suite/test/cases/picking/picking.html
https://raw.githack.com/x3dom/x3dom/master/test/functional/widgetPlaneSensor.html
