### ISSUE TITLE
Animation Finished Event

### ISSUE THREAD

**Issue by alssdllc** [x3dom/x3dom#1026]
I was wondering if there was an animation finished event currently in x3dom. If not, is that something that is being worked on?

There are several places in our code where it is critical to do work but only after the animations between viewpoints is complete. Currently we have no easy way of figuring out when it is complete.

**Comment by andreasplesch** [comment]
It may work to check in the viewpointchanged handler if reported location is (close to) the target location and then trigger the work to do. An example scene may help.

**Comment by alssdllc** [comment]
I implemented a solution just like you suggested and it seems to work pretty well. Thank you for your help.

**Comment by andreasplesch** [comment]
It turns out there is a runtime.onAnimationFinished hook which is called when the transition to the new Viewpoint is completed.
