### ISSUE TITLE
Can one rotate Transform via javascript?

### ISSUE THREAD

**Issue by molteber** [x3dom/x3dom#1027]
Hello.

I'm new to using x3dom and trying everthing i can to rotate an object on the click of a button.
The button which should be clicked on is not a part of the x3d element.

So the button should somehow set the new rotation on a transform, and the transform should update accordingly (smooth is preferable, but I can accept straight jump to new rotation.

I have tried making a orientationInterpolator, fetching the generated x, y, z, w numbers (element._x3domNode._vf.keyValues), but haven't had any luck applying it to the transform element.
```
<orientationInterpolator id="test" DEF='spinThings' key='0 0.25 0.5 0.75 1' keyValue='0 1 0 0  0 1 0 1.5708  0 1 0 3.14  0 1 0 4.7124  0 1 0 6.28'></orientationInterpolator>
```

I also tried to dispatch a custom event to use `Route`
```
<Route fromNode="spinThings" fromField="value_changed" toNode="figure" toField="rotation"></Route>
```

No luck there as well.

Tried applying each keyValues (element._x3domNode._vf.keyValues) to the transform by overwriting the transformElement._x3domNode._vf.rotation, but no luck there as well.

So is it possible to do this via javascript, or some other way?

The main goal of what I'm trying to do, is to add 2 buttons to rotate left and right.
This is because I need to only rotate on the X-axis, and haven't found any ways to that as well.

**Comment by andreasplesch** [comment]
Leaving aside an animated transition for now, you can use `transformNode.setAttribute('rotation','1,0,0,1.57')` in the handler for the button click to rotate to an orientation which is rotated 90 degrees around the x axis from the default orientation. If you want to accumulate rotations on each click, you can keep track of the current orientation, or get the current attribute or field value and add to it. Do you have simple example as a fiddle or gist ?

**Comment by andreasplesch** [comment]
Here is a simple example:

https://jsitor.com/embed/XcBZURCAh?html&result&light&

Please feel free to reopen with another example.

**Comment by molteber** [comment]
Hi again
Sorry for the delay of feeback here.

I used your example to make another example here:
https://jsitor.com/embed/rWTrpmdJl

Rotation through setAttribute worked quite well, thanks!

However, the next thing on my list is to add a marker, but I realize the hitpoint is not based on the transform, but the current camera angle(?)

Is there a way to get a more accurate hit point, @andreasplesch? Could open a new issue for this if you want since it is not a part of the original issue

**Comment by andreasplesch** [comment]
You are mixing up coordinate systems. hitPnt is always in world coordinates but you were subjecting the marker transform to the rotation. So the marker ends up in the wrong location.
https://jsitor.com/embed/rWTrpmdJl is now putting the marker under scene.

**Comment by molteber** [comment]
Is there a way to make the marker to stick to it's place?
End goal is probably something like this: https://doc.x3dom.org/tutorials/animationInteraction/picking/example.html

But only with rotation along Y axis

**Comment by andreasplesch** [comment]
Actually, the marker sticks to its position. It is the brick which keeps changing its position.

If you want to keep the viewpoint fixed, you will need to rotate the marker with the brick. So each time the marker gets reset, you also reset its rotation to 0.

**Comment by molteber** [comment]
Amazing.
Thank you so much for your assistance!

Have a good one!
