### ISSUE TITLE
Updating the USE attribute via Javascript not supported

### ISSUE THREAD

**Issue by t-oster** [x3dom/x3dom#1028]
Hi,
suppose you have two imagetexture nodes e.g.
```
<imagetexture DEF="tex1" url="tex1.jpg"/>
<imagetexture DEF="tex2" url="tex2.jpg"/>
```
(of cause in the right place). And then you have a shape which uses the first one:
```
<shape id="testshape">
<appearance>
<imagetexture USE="tex1"/>
</appearance>
<box/>
</shape>
```
This works as intended, but if you change the USE attribute via Javascript (e.g. `$("#testshape imagetexture").attr("USE", "tex2")`, the change is not reflected. However if you afterwards re-parse the thing e.g. with (`$("#testshape").html($("#testshape").html())`) it works

**Comment by t-oster** [comment]
here is an example https://jsfiddle.net/gtvfL2qk/1/

**Comment by andreasplesch** [comment]
The x3d spec.  does not treat the USE attribute as a settable field. The spec. does not allow for modifying it. Instead, USE is a statement which inserts the referenced node (not a copy) into the scene graph. The reference node then has multiple parents.

The Switch node lets you choose between different nodes.

**Comment by andreasplesch** [comment]
https://jsfiddle.net/1ow6bnxg/ uses a switch node to switch.

**Comment by t-oster** [comment]
ok thanks for the clarification. The switch not does not help in my case, since I am using knockout js in order to create the x3d scene dom nodes. But the appearance node is instanciated before the use attribut is set and then x3dom does not see my update. I worked around it by using knockout's html binding instead of the attribute binding, but a way to let x3dom reevaluate the node or a whole subtree would be a better fit.

**Comment by andreasplesch** [comment]
It should be fine to keep using the workaround, as a two step solution.
I think what jquery does in the fiddle is to first detach the Appearance node, and then reappend it as a child to the Shape node.
This would be seen by x3dom as two mutations of the Shape node, so there may be a bit of a flicker.

**Comment by FrankBuchholz** [comment]
If you do not use jquery you can reassign the material node directly: https://jsfiddle.net/FrankBuchholz/7w9zhcv2/
This example shows following options:
- Replace USE (does not work)
- Recreate Material (ok)
- Reassign Material (perfect)

**Comment by t-oster** [comment]
How does x3dom recognize the reassignment? Maybe there is an event which we could trigger manually?

**Comment by andreasplesch** [comment]
I believe in the example, the reassignMaterial function works by replacing the Material node with a modified version of itself (with a different USE reference). This is a mutation of the DOM which x3dom recognizes by installing a MutationObserver watching over the x3d subdom. In the example, the reassignment is triggered by the Appearance.appendChild(material) call.

This solution is quite similar to the previous workaround, except that instead of the Appearance node, only the Material node is replaced., eg. reappended.

**Comment by FrankBuchholz** [comment]
> How does x3dom recognize the reassignment? Maybe there is an event which we could trigger manually?

Maybe it's here:
```
x3dom.X3DDocument.prototype._setup
	[...]
	var domEventListener = {
		onAttrModified: function (e) { [...] }
		onNodeRemoved: function (e) { [...] }
		onNodeInserted: function (e) { [...] }
	[...]
	sceneDoc.addEventListener('DOMNodeRemoved', domEventListener.onNodeRemoved, true);
	sceneDoc.addEventListener('DOMNodeInserted', domEventListener.onNodeInserted, true);
```
