### ISSUE TITLE
json Prototype expander problem

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#1044]
A json scene with ProtoBodies which use other ProtoInstances:

https://gist.github.com/andreasplesch/4fb27cb9f3db9ee423066ae74d4aaae1#file-t1good-json

is expanded to

https://gist.github.com/andreasplesch/4fb27cb9f3db9ee423066ae74d4aaae1#file-expandedjson-x3d

This is mostly ok but the sphere protos (org) are in the wrong location, eg. not expanded correctly.
It may have to have to do with the nesting.

**Comment by andreasplesch** [comment]
@coderextreme, I think I could confirm that Protobodies which use use ProtoInstances are not expanded quite correctly. In the ProtoInstance the field value is not filled in properly.
In VRML:
```
PROTO org [ field SFVec3f posi 0 0 0 field SFColor col 0 0 0 ] {
	Transform {
	    translation	IS posi
	    children [
		Shape {
			appearance Appearance {
				material Material {
					transparency	.4
					emissiveColor	IS col
				}
			}
			geometry Sphere {
				radius	1.1
			}
		}
	    ]
	}
}
PROTO n [ field SFVec3f pos 0 0 0 ] {
	org { posi IS pos col 0 0.6 0 } 
}
n { pos 400 0.1 -385 }
```
The transform translation field of the n instance is not filled in.

**Comment by coderextreme** [comment]
It would be easier to see and for me to fix this if the encoding were XML
or JSON.   I’ve never dealt with VRML PROTO before.

**Comment by andreasplesch** [comment]
https://gist.github.com/andreasplesch/4fb27cb9f3db9ee423066ae74d4aaae1#file-t1good-json

is the full scene in JSON encoding. It has these Protos.

https://gist.github.com/andreasplesch/4fb27cb9f3db9ee423066ae74d4aaae1#file-t1-x3d is the xml encoding.

**Comment by andreasplesch** [comment]
This is how the ProtiInstance is expanded"
```xml
<Transform  translation="0,0,0" >
  <Shape >
    <Appearance >
      <Material containerField="material" transparency="0.400000005960464" emissiveColor="0 0.300000011920929 1" ambientIntensity="0.2" diffuseColor="0.8,0.8,0.8" shininess="0.2" specularColor="0,0,0"></Material>
    </Appearance>
    <Sphere containerField="geometry" radius="1.10000002384186" ></Sphere>
  </Shape>
</Transform>
```
Note that the translation field of the Transform node is not filled in with the value of the pos field of the "l" proto which should be passed on as value to the posi field of the "org" proto.

**Comment by coderextreme** [comment]
Suggest that your stylesheet didn't work.  See code like:
```
 "ProtoBody": {
                  "-children":[
                    { "Transform":
                        "-IllegalChildNodeFieldNameNotFound":[
                          { "Shape":
                              "-IllegalChildNodeFieldNameNotFound":[
                                { "Appearance":
                                    "-IllegalChildNodeFieldNameNotFound":[
                                      { "Material":
                                        {
                                          "@diffuseColor":[0.5,0,1],
                                          "@transparency":0.200000002980232
                                        }
                                      }
                                    ]
                                }
                              ],
                              "-IllegalChildNodeFieldNameNotFound":[
                                { "IndexedFaceSet":
                                  {
```
This is normally caused by running a stylesheet on XML in the browser. Please fix this code and run through jsonlint before running through the ProtoExpander.

Thanks,

John

**Comment by coderextreme** [comment]
Let me know when you close the issue.  Thanks!

John

**Comment by andreasplesch** [comment]
The problem is with the Protos which are properly translated with the stylesheet which I excerpted above. I can cut down the example if necessary.

**Comment by coderextreme** [comment]
I've seen that error with the stylesheet processor (the text I pasted above
is the issue..."Illegal..."). Use the stylesheet processor on the server
saxon9he.jar, not the client.

At least run JSON through jsonlint if the JSON is "good" then, we will try
the proto expander.
Thanks,

John

**Comment by coderextreme** [comment]
Suggest that you fix this issue with the XML:

org.web3d.x3d.sai.InvalidFieldException: ERROR_ILLEGAL_VALUE insufficient X3D profile='Interchange' for parent X3D model containing 'Inline' node, add head statement <component name='Networking' level='2'/>
or Java source-code assignment:  findAncestorX3DObject().getHead().addComponent("Networking").setLevel(2);
org.web3d.x3d.sai.InvalidFieldException: ERROR_ILLEGAL_VALUE insufficient X3D profile='Interchange' for parent X3D model containing 'Inline' node, add head statement <component name='Networking' level='2'/>
or Java source-code assignment:  findAncestorX3DObject().getHead().addComponent("Networking").setLevel(2);
        at org.web3d.x3d.jsail.Networking.InlineObject.validate(InlineObject.java:1882)


I will proceed with testing in the X3DJSONLD GUI now

**Comment by andreasplesch** [comment]
I think your are looking the wrong json. Look at:

https://gist.github.com/andreasplesch/4fb27cb9f3db9ee423066ae74d4aaae1#file-t1good-json

**Comment by coderextreme** [comment]
Yes, thanks. I've got the JSON produced by X3dToJson.xslt, currently.   As far as I can tell, the sphere's aren't showing up in X3DOM? Or they are small?

See attached picture, X_ITE above, X3DOM below.

![image](https://user-images.githubusercontent.com/705783/81589869-89306000-937f-11ea-9e1d-2458330be3c5.png)

**Comment by coderextreme** [comment]
> The problem is with the Protos which are properly translated with the stylesheet which I excerpted above. I can cut down the example if necessary.

Yep, smaller example would be helpful for running in the got here debugger. Otherwise, I have to wade through 80 ProtoInstances.   I will now run through the  protoexpander on the serversite with X3DJSONLD/src/main/shell/runppp.sh (or a derivative thereof.

**Comment by coderextreme** [comment]
Here are the examples I'm working from now. I can duplicate what you are seeing.

**Comment by coderextreme** [comment]
Here's a much smaller example of at least one issue with the ProtoExpander (parameters don't get passed):

https://raw.githubusercontent.com/coderextreme/X3DJSONLD/master/src/main/data/t3.x3d

https://raw.githubusercontent.com/coderextreme/X3DJSONLD/master/src/main/data/t3.json

Note that the translation doesn't get overridden with final value.

**Comment by andreasplesch** [comment]
Thanks for cutting this down. Yes, my suspicion was that the nesting of ProtoBody inside ProtoDeclare could be a problem.

**Comment by coderextreme** [comment]
My guess is it has something to do with overriding fieldValue values.  I have other examples in X3DJSONLD/src/main/data/rubik.x3d that work for example, with nested proto instances..

What I originally imagined was the the first ProtoInstance got processed first, so that the "4 4 4" in the fieldValue shows up in the final result.  Note that this field value was not specifically mentioned in the original with a fieldValue: See:
```xml
                <ProtoBody>
                        <ProtoInstance name="org">
                                <fieldValue name="posi" value="4 4 4" />
                                <IS>
                                        <connect nodeField="posi" protoField="pos" />
                                </IS>
                        </ProtoInstance>
                </ProtoBody>
```'

Still thinking about it.  I am hoping that we can find something

**Comment by coderextreme** [comment]
See this code from rubik.x3d that works in X3DJSONLD and has been working for a long time:

        <ProtoDeclare name="nine">
            <ProtoInterface>
                <field name="ztranslation" accessType="inputOutput" type="SFVec3f" value="0.0 0.0 0.0"/>
            </ProtoInterface>
            <ProtoBody>
                <Transform translation="0 0 0">
                    <IS>
                        <connect nodeField="translation" protoField="ztranslation"/>
                    </IS>
                    <ProtoInstance name="three">
                        <fieldValue name="ytranslation" value="0 0 0"/>
                    </ProtoInstance>
                    <ProtoInstance name="three">
                        <fieldValue name="ytranslation" value="0 2 0"/>
                    </ProtoInstance>
                    <ProtoInstance name="three">
                        <fieldValue name="ytranslation" value="0 -2 0"/>
                    </ProtoInstance>
                </Transform>
            </ProtoBody>
        </ProtoDeclare>
        <ProtoDeclare name="twentyseven">
            <ProtoInterface>
                <field name="ttranslation" accessType="inputOutput" type="SFVec3f" value="0.0 0.0 0.0"/>
            </ProtoInterface>
            <ProtoBody>
                <Transform translation="0 0 0">
                     <IS>
                        <connect nodeField="translation" protoField="ttranslation"/>
                    </IS>
                    <ProtoInstance name="nine">
                        <fieldValue name="ztranslation" value="0 0 0"/>
                    </ProtoInstance>
                    <ProtoInstance name="nine">
                        <fieldValue name="ztranslation" value="0 0 2"/>
                    </ProtoInstance>
                    <ProtoInstance name="nine">
                        <fieldValue name="ztranslation" value="0 0 -2"/>
                    </ProtoInstance>
                </Transform>
            </ProtoBody>
        </ProtoDeclare>
        <ProtoInstance name="twentyseven">
            <fieldValue name="ttranslation" value="0 0 0"/>
        </ProtoInstance>

**Comment by coderextreme** [comment]
The difference seems to be that there's a Transform node, not a fieldValue for the IS.

**Comment by coderextreme** [comment]
There's X3DJSONLD/src/main/node/PPP.js to help with debugging.  Also some run scripts in X3DJSONLD/src/main/shell, like runppp.sh, but trim it way down to a single line, like:

ls ../data/t1.json | xargs ${NODE} ${NODEDIR}/PPP.js

Produces files in ../ppp/t1.json (outfile in code), I'm fairly sure, so it won't overwrite.

I normally do console.log's to debug.  It may be more useful to run in a debugging environment, if you have one.

**Comment by coderextreme** [comment]
I've heard that debugging is twice as hard as writing the code!  So we can either rewrite, or start using better debugging tools than the GHD (got here debugger).

John

**Comment by andreasplesch** [comment]
The difference to rubik.x3d is that for rubik.x3d the 'twentyseven' instance field value of 'ttranslation' is not used in the inner/nested Protoinstances. The 'twentyseven' protodeclare does not use ttranslation inside its 'nine' protoinstances.

Sorry to admit that I do not think I would be very useful in debugging.

**Comment by coderextreme** [comment]
Luckily, I got the debugger working in Visual Studio Code.  Let me know if
you want to learn the debugger (it's similar to chrome dev tools, I
guess).  So I've track it down to a proto instance not being present in an
object, I think.

**Comment by coderextreme** [comment]
There's a problem with the JSON containing a .wrl Inline, in X3DOM I think.

I've had pretty good progress, but X_ITE and X3DOM look very different,
then it will look more similar.

I'll try to check in soon, but the changes caused a regression.

John

Try using X_ITE to use the North viewpoint.
John

**Comment by coderextreme** [comment]
I've spent about 36 hours straight in the debugger. I tried
applying patches which caused rubik.x3d to break.  Then I tried to patch
PrototypeExpander.js to make rubik.x3d to work, ending in me backing out
the patches.  I've still got a problem with the spheres disappearing in
t1.json, but now they're also disappearing in X_ITE.

I got some sleep last night and today, but I still must rest.

Maybe we should take Don's approach and copy someone else?

What I'm going to try now is trying Don's X3dToJson.xslt.
John

**Comment by coderextreme** [comment]
Okay, I've still identified the missing inline file, t.wrl.  I am not sure what to do about that. X_ITE and X3DOM versions look pretty similar now.  Please confirm and close issue.  I am currently running the netlify version,
```
<script type="text/javascript" src="https://code.create3000.de/x_ite/latest/dist/x_ite.min.js"></script>
<script type="text/javascript" src="https://raw.githack.com/andreasplesch/x_ite_dom/master/release/x_ite_dom.1.3.js"></script>
<script type="text/javascript" src="https://5efa06157960e80256fa5d6b--x3dom.netlify.app/x3dom-full.debug.js"></script>
```

I do not know if there are some mixture issues when X3DOM and X_ITE are on same page.  It would be good if they were tested separately and together.

John

**Comment by coderextreme** [comment]
Can we close this issue yet?

**Comment by andreasplesch** [comment]
Just feel free to reopen if there is something specific to check.
