### ISSUE TITLE
x3d inline example not working in internet explorer

### ISSUE THREAD

**Issue by venkatrajgm** [x3dom/x3dom#1045]
is the inline x3d example still working fine in IE11. For me it's not working. It takes a long time to load the deer model. Its working fine on chrome, firefox, even edge. I've a project based on this example. Also found out that the following code is not working even if the model loads. IE couldn't find 'MA_Nose' material node inside the x3d file. How can I fix this. 
(https://doc.x3dom.org/tutorials/models/inline/example.html)
`if(document.getElementById('Deer__MA_Nose').getAttribute('diffuseColor')!= '1 0 0')`

**Comment by andreasplesch** [comment]
Your best bet is trying older versions of x3dom. I do not think there will be contributions directed towards supporting IE11.

**Comment by brutzman** [comment]
Works for me in latest Windows 10 Microsoft Edge.
- Microsoft Edge 44.17763.831.0
- Microsoft EdgeHTML 18.17763

**Comment by andreasplesch** [comment]
While 1.8,1 still works in IE11 for many nodes (but not inline), later x3dom versions will essentially stop working. A large reason is that

https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach

is not supported in IE11.

**Comment by venkatrajgm** [comment]
Is there any work around for this? or is it better to declare in my website that IE won't work?

**Comment by andreasplesch** [comment]
Your best best bet is try an older x3dom:

https://x3dom.org/download/

Try 1.7.2 maybe first.

Most user may have Edge.
