### ISSUE TITLE
Error: "this" is undefined in X3DCanvas.load mainloop when in strict mode

### ISSUE THREAD

**Issue by slichte** [x3dom/x3dom#1048]
Hi,
I'm using x3dom along with angular. Its compiler applies strict mode to every node module. Unfortunately, there's a bug in x3dom in X3DCanvas.load: the embedded function mainloop() uses "this" in some if-statements, intending to refer to X3DCanvas, but that's not working inside the mainloop-closure.

https://github.com/x3dom/x3dom/blob/47c55368b1f1af4c9c740677854895f17964185f/src/X3DCanvas.js#L1438-L1457

Replacing "this" with x3dCanvas seems to solve the problem.

**Comment by andreasplesch** [comment]
https://github.com/x3dom/x3dom/commit/7057e2f7effa5608884831a6f6e879e534aa276d introduces that section, with "this" used in it. @tsturm : Would replacing 'this'  with  'x3dCanvas'  be ok ? It looks like it should be, and be more robust.

**Comment by tsturm** [comment]
fixed with ce14f87
