### ISSUE TITLE
Incorrect tessellation of rational NURBS curves and surfaces

### ISSUE THREAD

**Issue by cmasia** [x3dom/x3dom#1059]
## Summary

Rational NURBS curves  and surfaces are not tessellated correctly. NURBS are rational when (at least) one of the weights is different from the default value of 1.

## Steps to reproduce

Problem is illustrated for curves (NurbsCurve node) in this [X3DOM 1.8.1 NURBS Curve evaluation bug](https://codepen.io/cmasia/pen/XWmxKLo) codepen.

This [X3DOM 1.8.1 NURBS Surface evaluation bug](https://codepen.io/cmasia/pen/JjYmNWJ) codepen replicates the problem for surfaces (NurbsPatchSurface node).

## Expected result

In the curve codepen, the red curve should look like the green one (which is an Arc2D node). Both are circle arcs, although on translated planes.

For the surface codepen, the geometry should be a arc of a cylinder (in this example, it is the extruded version of the arc in the first example).

## Actual result

The NURBS arc (red) does not look like an arc:
![image](https://user-images.githubusercontent.com/26604712/82141039-83c98e80-9833-11ea-95a9-6e3aa60921d7.png)

The NURBS cylinder arc does not look like a cylinder arc:
![image](https://user-images.githubusercontent.com/26604712/82141060-a0fe5d00-9833-11ea-81d4-8f1cfd22a32b.png)

## Additional information

The evaluation of points on the NURBS seems to be the culprit, but only for rational NURBS entities. Polynomial NURBS (all weights equal to 1.0) are rendered correctly.

The equation for a NURBS curve is:
![image](https://user-images.githubusercontent.com/26604712/82141188-72cd4d00-9834-11ea-8e8c-aeda69d54e69.png)

For a NURBS surface, the equation is:
![image](https://user-images.githubusercontent.com/26604712/82141216-a0b29180-9834-11ea-89ad-ca703238f767.png)

## Analysis and fix

After locating the code that evaluates a point on NURBS curves and surfaces, it appears that the weights (w_i) in the numerator of the formulas are not applied.

In x3dom/src/nodes/NURBS/NurbsCurve.js, function curvePoint3DH(). 

```javascript
                for ( k = 0; k <= p; k++ )
                {
                    i = indu + k;
                    temp[ 0 ] += Nu[ k ] * P[ i ].x;
                    temp[ 1 ] += Nu[ k ] * P[ i ].y;
                    temp[ 2 ] += Nu[ k ] * P[ i ].z;
                    temp[ 3 ] += Nu[ k ] * W[ i ];
                }

                return new x3dom.fields.SFVec3f(
                    temp[ 0 ] / temp[ 3 ],
                    temp[ 1 ] / temp[ 3 ],
                    temp[ 2 ] / temp[ 3 ] );
```

In x3dom/src/nodes/NURBS/x3dom-nurbs-web-worker.js, function surfacePoint3DH().
```javascript
                for ( k = 0; k <= p; k++ )
                {
                    i = indu + k + ( indv * ( n + 1 ) );
                    temp[ j + 0 ] += Nu[ k ] * P[ i ].x;
                    temp[ j + 1 ] += Nu[ k ] * P[ i ].y;
                    temp[ j + 2 ] += Nu[ k ] * P[ i ].z;
                    temp[ j + 3 ] += Nu[ k ] * W[ i ];
                }
```

In neither case the coordinates of the control points are multiplied by the weight (W[i]).

I'll submit a PR with the fix soon.

**Comment by andreasplesch** [comment]
Thanks for this detailed analysis. The code is taken from http://ayam.sourceforge.net/ayam.html which generally works well with Nurbs. But I agree that the weight factor is missing in the numerator. Could you please try another weighted Nurbs with a known outcome tomorrow with the x3dom dev version, after the automatic rebuild ?

**Comment by cmasia** [comment]
Sure! I'll do that.

**Comment by andreasplesch** [comment]
Here is the original source: https://sourceforge.net/p/ayam/mercurial/ci/Release_1_27/tree/ayam/src/scripts/x3dom-nurbs/

**Comment by cmasia** [comment]
I am aware of ayam, very nice piece of software!

Maybe Randolf stores the control points pre-multiplied by the weights, in which case he does not need to do the multiplication during evaluation (it can save quite a lot of multiplications actually). Does the name of the functions comes from that fact (surfacePoint3DH,  H for homogeneous)? 

I guess an alternative fix to mine could be to store the points pre-multiplied by the weights. However the fact that the stored points are already pre-multiplied  should be made very clear: if someone wanted to display the control points somehow, he would have to divide the coordinates by the weights:

![image](https://user-images.githubusercontent.com/26604712/82156178-083f0000-987a-11ea-9beb-860fa15822e8.png)

(control points of the arcs are the blue dots)

I could not find Randolf on github to cite him. Maybe he can confirm whether he pre-multiplies the control points when storing them.

**Comment by andreasplesch** [comment]
Let's assume that ayam does store control points premultiplied for now. Randolf seems responsive to inquiries on the ayam forum:

https://sourceforge.net/p/ayam/discussion/89661/

Please feel free to point to this issue.

**Comment by cmasia** [comment]
Finally found some time to check against dev. Here are two updated codepens and a new one:

- circle arc [X3DOM dev NURBS Curve evaluation OK](https://codepen.io/cmasia/pen/OJyaNYG)

![image](https://user-images.githubusercontent.com/26604712/82287149-d1630a00-999f-11ea-9d78-39d85bc27b71.png)

- cylinder arc [X3DOM dev NURBS Surface evaluation OK](https://codepen.io/cmasia/pen/jObQYje)

![image](https://user-images.githubusercontent.com/26604712/82287215-fa839a80-999f-11ea-8dd8-e309a5c7ad2d.png)

- sphere octant [X3DOM dev NURBS Surface sphere octant](https://codepen.io/cmasia/pen/XWmyZJr)

![image](https://user-images.githubusercontent.com/26604712/82287244-0d966a80-99a0-11ea-9cd6-0a4dcd9c40bf.png)

The sphere octant is derived from this [Blender](https://docs.blender.org/manual/en/latest/modeling/surfaces/structure.html#preset-weights) documentation page, although the weights are different for only one octant (1.0, sqrt(2)/2 and 0.5).

As to contacting Randolf, my sourceforge account happens to be suspended (I guess for not logging in for 6 years). I am trying to get it back. If I cannot get it back I'll create a new one.

**Comment by andreasplesch** [comment]
Thanks for the tests. Over at https://github.com/andreasplesch/OCCToX3D/issues/8 we discovered that other X3D viewers actually expect the control points to be premultiplied. The X3D spec. itself seems silent on this.  So we will have to clarify this.

**Comment by tpaviot** [comment]
what do you mean @andreasplesch with premultiplied ? is that to say that the weight vectors becomes useless ?

**Comment by andreasplesch** [comment]
See above discussion. The weight vector is weirdly still needed because the weights also occur in the denominator, for normalization.
My preference would be to _not_ have authors have to premultiply since it is confusing. But for some reason, there seems to be a consensus that the provided control points already should be weighted, eg. premultiplied by thecsorresponding weight.

**Comment by andreasplesch** [comment]
premultiplied torus Nurbs:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE X3D PUBLIC "ISO//Web3D//DTD X3D 3.3//EN" "https://www.web3d.org/specifications/x3d-3.3.dtd">
<X3D profile='Immersive' version='3.3' xmlns:xsd='http://www.w3.org/2001/XMLSchema-instance' xsd:noNamespaceSchemaLocation='http://www.web3d.org/specifications/x3d-4.0.xsd'>
<head>
    <meta name='generator' content='pythonocc-7.4.1-dev X3D exporter (www.pythonocc.org)'/>
    <meta name='creator' content='pythonocc-7.4.1-dev generator'/>
    <meta name='identifier' content='http://www.pythonocc.org'/>
    <meta name='description' content='pythonocc-7.4.1-dev x3dom based shape rendering'/>
</head>
    <Scene>
    <Shape><Appearance><Material></Material></Appearance>
<NurbsPatchSurface DEF='nurbs_1' solid='false' uClosed='true' vClosed='true' 
uDimension="7" uOrder="3" vDimension="7" vOrder="3" 
uKnot='-2.0944 0 0 2.0944 2.0944 4.18879 4.18879 6.28319 6.28319 8.37758 ' 
vKnot='-2.0944 0 0 2.0944 2.0944 4.18879 4.18879 6.28319 6.28319 8.37758 ' 
weight='1 0.5 1 0.5 1 0.5 1 0.5 0.25 0.5 0.25 0.5 0.25 0.5 1 0.5 1 0.5 1 0.5 1 0.5 0.25 0.5 0.25 0.5 0.25 0.5 1 0.5 1 0.5 1 0.5 1 0.5 0.25 0.5 0.25 0.5 0.25 0.5 1 0.5 1 0.5 1 0.5 1 ' containerField='geometry'>
<Coordinate containerField='controlPoint' point='4 0 0, 2 3.4641 0, -2 3.4641 0, -4 4.89859e-16 0, -2 -3.4641 0, 2 -3.4641 0, 4 0 0, 2 0 0.866025, 1 1.73205 0.433013, -1 1.73205 0.866025, -2 2.44929e-16 0.433013, -1 -1.73205 0.866025, 1 -1.73205 0.433013, 2 0 0.866025, 2.5 0 0.866025, 1.25 2.16506 0.433013, -1.25 2.16506 0.866025, -2.5 3.06162e-16 0.433013, -1.25 -2.16506 0.866025, 1.25 -2.16506 0.433013, 2.5 0 0.866025, 0.5 0 1.22465e-16, 0.25 0.433013 6.12323e-17, -0.25 0.433013 1.22465e-16, -0.5 6.12323e-17 6.12323e-17, -0.25 -0.433013 1.22465e-16, 0.25 -0.433013 6.12323e-17, 0.5 0 1.22465e-16, 2.5 0 -0.866025, 1.25 2.16506 -0.433013, -1.25 2.16506 -0.866025, -2.5 3.06162e-16 -0.433013, -1.25 -2.16506 -0.866025, 1.25 -2.16506 -0.433013, 2.5 0 -0.866025, 2 0 -0.866025, 1 1.73205 -0.433013, -1 1.73205 -0.866025, -2 2.44929e-16 -0.433013, -1 -1.73205 -0.866025, 1 -1.73205 -0.433013, 2 0 -0.866025, 4 0 0, 2 3.4641 0, -2 3.4641 0, -4 4.89859e-16 0, -2 -3.4641 0, 2 -3.4641 0, 4 0 0, '/></NurbsPatchSurface></Shape>
    </Scene>
</X3D>
```

**Comment by andreasplesch** [comment]
torus Nurbs with unweighted control points:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE X3D PUBLIC "ISO//Web3D//DTD X3D 3.3//EN" "https://www.web3d.org/specifications/x3d-3.3.dtd">
<X3D profile='Immersive' version='3.3' xmlns:xsd='http://www.w3.org/2001/XMLSchema-instance' xsd:noNamespaceSchemaLocation='http://www.web3d.org/specifications/x3d-4.0.xsd'>
<head>
    <meta name='generator' content='pythonocc-7.4.1-dev X3D exporter (www.pythonocc.org)'/>
    <meta name='creator' content='pythonocc-7.4.1-dev generator'/>
    <meta name='identifier' content='http://www.pythonocc.org'/>
    <meta name='description' content='pythonocc-7.4.1-dev x3dom based shape rendering'/>
</head>
    <Scene>
    <Shape><Appearance><Material></Material></Appearance>
<NurbsPatchSurface DEF='nurbs_1' solid='false' uClosed='true' vClosed='true' 
uDimension="7" uOrder="3" vDimension="7" vOrder="3" 
uKnot='-2.0944 0 0 2.0944 2.0944 4.18879 4.18879 6.28319 6.28319 8.37758 ' 
vKnot='-2.0944 0 0 2.0944 2.0944 4.18879 4.18879 6.28319 6.28319 8.37758 ' 
weight='1 0.5 1 0.5 1 0.5 1 0.5 0.25 0.5 0.25 0.5 0.25 0.5 1 0.5 1 0.5 1 0.5 1 0.5 0.25 0.5 0.25 0.5 0.25 0.5 1 0.5 1 0.5 1 0.5 1 0.5 0.25 0.5 0.25 0.5 0.25 0.5 1 0.5 1 0.5 1 0.5 1 ' containerField='geometry'>
<Coordinate containerField='controlPoint' point='4 0 0, 4 6.9282 0, -2 3.4641 0, -8 9.79717e-16 0, -2 -3.4641 0, 4 -6.9282 0, 4 0 0, 4 0 1.73205, 4 6.9282 1.73205, -2 3.4641 1.73205, -8 9.79717e-16 1.73205, -2 -3.4641 1.73205, 4 -6.9282 1.73205, 4 0 1.73205, 2.5 0 0.866025, 2.5 4.33013 0.866025, -1.25 2.16506 0.866025, -5 6.12323e-16 0.866025, -1.25 -2.16506 0.866025, 2.5 -4.33013 0.866025, 2.5 0 0.866025, 1 0 2.44929e-16, 1 1.73205 2.44929e-16, -0.5 0.866025 2.44929e-16, -2 2.44929e-16 2.44929e-16, -0.5 -0.866025 2.44929e-16, 1 -1.73205 2.44929e-16, 1 0 2.44929e-16, 2.5 0 -0.866025, 2.5 4.33013 -0.866025, -1.25 2.16506 -0.866025, -5 6.12323e-16 -0.866025, -1.25 -2.16506 -0.866025, 2.5 -4.33013 -0.866025, 2.5 0 -0.866025, 4 0 -1.73205, 4 6.9282 -1.73205, -2 3.4641 -1.73205, -8 9.79717e-16 -1.73205, -2 -3.4641 -1.73205, 4 -6.9282 -1.73205, 4 0 -1.73205, 4 0 0, 4 6.9282 0, -2 3.4641 0, -8 9.79717e-16 0, -2 -3.4641 0, 4 -6.9282 0, 4 0 0,'/>
</NurbsPatchSurface>
</Shape>
    </Scene>
</X3D>
```

**Comment by andreasplesch** [comment]
Here is a confirmation:
https://castle-engine.io/x3d_implementation_nurbs.php#section_homogeneous_coordinates

**Comment by cmasia** [comment]
@andreasplesch, thank you for all the research!

Looking at this [example](https://www.web3d.org/x3d/content/examples/Basic/NURBS/NurbsPatchSolidIndex.html) is seems that X_ITE also expects the control points to be pre-multiplied.

It is a pity that the spec is not clear on this. I could only find this passage of the [spec](https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/nurbs.html#X3DNurbsSurfaceGeometryNode)

![image](https://user-images.githubusercontent.com/26604712/82342345-cc2eab00-99f1-11ea-8b62-6c9b21d789e3.png)

**If** one considers that P[i,j] is in homogeneous coordinates, the passage **implies** that the control points are pre-multiplied. But I think this is open to interpretation, as I believe the passage is here to illustrate the arrangement of the points in the controlPoints array in the case of a surface. 

I also generate IGES files. and the IGES spec clearly states for entity type 126 (rational B-Spline curve):
> Note that the control points are in the definition space of the curve.

Of course, IGES spec states the same for the surface (entity type 128). The DXF spec states that control point are expressed in WCS (World Coordinate System).

I also find pre-multiplication to be confusing because you loose the geometrical relation between the control points and with the curve. If somebody wanted to display them in the 3D, he would have to divide the coordinates by the weight before doing so. It is also inconsistent with other formats like IGES, DXF...

I guess you have to weigh in the fact that all other viewers expect the coordinates to be pre-multiplied. I guess it is difficult to have a different behavior for these nodes.

@andreasplesch let me know whether I should submit a PR reverting my changes.

Would it make sense to suggest the Web3D consortium to clarify the spec in X3D 4.0? Do you have contact with them?

**Comment by andreasplesch** [comment]
Yes, you found the appropriate section in the spec. It does look like we may have to revert the change. I had contacted x3d-public list earlier, with exactly that question:

http://web3d.org/pipermail/x3d-public_web3d.org/2020-May/012644.html

I agree that spec. is essentially silent on this and needs clarification. There probably will not be a lot of appetite for change even if there is more agreement but you never know. If you want you join the list and mention IGES and DXF as other examples.

Let's give it a few days.

**Comment by andreasplesch** [comment]
There was an exchange and the discovery that VRML 2.1 actually shows the equation with the weights being used in the numerator. But maintaining backward compatibility seemed to outweigh the benefits from such a change.

**Comment by andreasplesch** [comment]
Please feel free to reopen.
