### ISSUE TITLE
Help needed for getAttribute for children after inline for x3d file

### ISSUE THREAD

**Issue by bob53050** [x3dom/x3dom#1067]
Hello all,
The use case I am researching is: As a user I want to view large CAD assembly models where I can select on a part and get it's name.

Based on the documentation, it looks like I can use getAttribute("children") after I use inline for the .x3d file.

I was looking for an example of something like this but none found.

Thanks in advanced for any help,

Bob

**Comment by andreasplesch** [comment]
https://doc.x3dom.org/tutorials/models/inline/index.html shows how to access nodes inside an Inline node, using the namespacename attribute.

**Comment by bob53050** [comment]
Thanks Andrea,
Is there a way to gather the list of nodes in the file?
