### ISSUE TITLE
Help needed for determining shape clicked on from .x3d file

### ISSUE THREAD

**Issue by bob53050** [x3dom/x3dom#1069]
Hello all,
The use case I am researching is: As a user I want to view large CAD assembly models where I can select on a part and get it's name.

After loading the .x3d file using inline, how can I click on the screen and determine which shape or the multiple shapes I had selected?

Thanks in advanced for any help,
Bob

**Comment by andreasplesch** [comment]
Here are two examples which show information on the shape clicked on:

https://examples.x3dom.org/example/x3dom_onClickEvent.xhtml
https://examples.x3dom.org/example/x3dom_uiEvents.html

**Comment by andreasplesch** [comment]
Please feel free to reopen as necessary.
