### ISSUE TITLE
alphaClipThreshold no longer being applied

### ISSUE THREAD

**Issue by dmorehead** [x3dom/x3dom#1071]
alphaClipThreshold is no longer affecting the render in dev version (1.8.2)

https://codepen.io/mrmernan/pen/bGEEOxN

toggle alphaClipThreshold via the button ..then change the src in line 5 from
https://www.x3dom.org/download/1.7.2/x3dom.js
to
https://www.x3dom.org/download/dev/x3dom.js

**Comment by andreasplesch** [comment]
https://jsitor.com/_WT9bLI73 for a minimal test.

**Comment by andreasplesch** [comment]
I found a small fix for the shader which I think is correct, Please give this build here a try:

https://5ee2c0d76dd7c36dc589dcd3--x3dom.netlify.app/

**Comment by dmorehead** [comment]
Excellent!  ..checked this build against several of my legacy 1.7.2 renders and the results match. Happily closing this issue!

**Comment by andreasplesch** [comment]
The dev version should have the fix by tomorrow.
