### ISSUE TITLE
Javascript code sequence 'if (...) {...} {...}' or 'while (...) {...} {...}' might be correct or wrong 

### ISSUE THREAD

**Issue by FrankBuchholz** [x3dom/x3dom#1084]
By chance I came across a Javascript code sequence `if (...) {...} {...}`  without any `else` token in the npm version of x3ddom.js. Then I verified the corresponding files in x3dom master.

I wonder if code like the following works as expected - it might be correct or it might be wrong:

PrototypeExpander.js
x3dom.PROTOS.prototype
```
            // Wait for expectedreturn tasks to finish
            while ( expectedreturn > Object.keys( newobject ).length + 1 ){;} {  // when they are equal, we exit
                // console.error(expectedreturn, '=', Object.keys(newobject).length);
                setTimeout( function () { }, 50 );
            }
```

src/nodes/Navigation/modes/DefaultNavigation.js
x3dom.DefaultNavigation.prototype.zoom
```
    if ( x3dom.isa( viewpoint, x3dom.nodeTypes.OrthoViewpoint ) )
    {
        viewpoint.setZoom( Math.abs( viewpoint._fieldOfView[ 0 ] ) - vec.z );
    }
    //else
    {
        if ( navi._vf.typeParams.length >= 6 )
        {
            var min = -navi._vf.typeParams[ 5 ];
            var max =  navi._vf.typeParams[ 4 ];

            view._movement.z = Math.min( Math.max( view._movement.z, min ), max );
        }

        view._movement = view._movement.add( vec );
        var mat = view.getViewpointMatrix().mult( view._transMat );
        //TODO; move real distance along viewing ray
        view._transMat = mat.inverse().
            mult( x3dom.fields.SFMatrix4f.translation( view._movement ) ).
            mult( mat );
    }
```

src/nodes/Navigation/modes/DefaultNavigation.js
x3dom.DefaultNavigation.prototype.onDrag
```
       if ( x3dom.isa( viewpoint, x3dom.nodeTypes.OrthoViewpoint ) )
        {
            viewpoint.setZoom( Math.abs( viewpoint._fieldOfView[ 0 ] ) - vec.z );
        }
        //else
        {
            if ( navi._vf.typeParams.length >= 6 )
            {
                var min = -navi._vf.typeParams[ 5 ];
                var max =  navi._vf.typeParams[ 4 ];

                view._movement.z = Math.min( Math.max( view._movement.z, min ), max );
            }

            view._movement = view._movement.add( vec );
            mat = view.getViewpointMatrix().mult( view._transMat );
            //TODO; move real distance along viewing ray
            view._transMat = mat.inverse().
                mult( x3dom.fields.SFMatrix4f.translation( view._movement ) ).
                mult( mat );
        }
```

**Comment by andreasplesch** [comment]
Standalone { } blocks are ok.
The commtented out //else is from
https://github.com/x3dom/x3dom/commit/dbc0d711d23fb61915ad0e899b7aaa3d2b384f45
You can use the blame button to see which commits are responsible for a line.
This is intentional, and probably left in there because the commiter was not quite sure if that change is actually correct, and may have to be reverted after more extensive testing and use.
Not sure about the weird while in PrototypeExpander. The json based PrototypeExpander may be replaced soon by another, dom based prototype implementation.

**Comment by microaaron** [comment]
The second { } block is nothing to do with "if" or "while". It is a standalone block.  Sometimes standalone block is very useful.

e.g.

...//some codes
{
    var a1;
    a1 = 1;
    console.log(a1);  //a1 = 1
}
console.log(a1);  //a1 undefined
...//some codes

This variable a1 is only available in the standalone block.
standalone block is very common in many languages such as C/C++/java.

**Comment by FrankBuchholz** [comment]
Sometimes you need stand alone blocks, but as andreasplesch wrote, here it a left-over block from a commented "else" in the code (which is not visible in the optimized file because comments are stipped off):

> The commtented out //else is from
> [dbc0d71](https://github.com/x3dom/x3dom/commit/dbc0d711d23fb61915ad0e899b7aaa3d2b384f45)

**Comment by andreasplesch** [comment]
Please feel free reopen as required.
