### ISSUE TITLE
setFieldValue() can't change HTML node. So getAttribute() may not get the real value

### ISSUE THREAD

**Issue by microaaron** [x3dom/x3dom#1095]
```
myTransformNode.setAttribute("translation","5 5 5");		//position changed, HTML node changed
myTransformNode.setFieldValue("translation",new x3dom.fields.SFVec3f(1,0,1));		//position changed, HTML node unchanged	
console.log(myTransformNode.getFieldValue("translation"));	//x3dom.fields.SFVec3f {x: 1, y: 0, z: 1}	This is real psition
console.log(myTransformNode.getAttribute("translation"));	// 5 5 5	getAttribute() can't get the real position
```

**Comment by andreasplesch** [comment]
This is as designed.  If you want to change the attribute, you could just use .setAttribute.

**Comment by microaaron** [comment]
> This is as designed. If you want to change the attribute, you could just use .setAttribute.

It's werid. If it's as designed, It should be pointed out in the documentation. The Introduction on https://doc.x3dom.org/author/index.html is confusing.

**Comment by andreasplesch** [comment]
Suggestion to improve the documentation always welcome: https://github.com/x3dom/x3dom/tree/master/build/jsdoc/jsdoc-template/base/author
