### ISSUE TITLE
SFRotation type does not exise

### ISSUE THREAD

**Issue by microaaron** [x3dom/x3dom#1096]
According to the official documentation on https://doc.x3dom.org/author/Grouping/Transform.html, the type of rotation is SFRotation. But this type does not exist in X3DOM. getFieldValue("rotation")  return an x3dom.fields.Quaternion value. setFieldValue("rotation") can only set Quaternion value, not SFRotation value. And getAttribute() may not get real value. Is it necessary to improve this issue?

**Comment by microaaron** [comment]
OK, Quaternion.toAxisAngle() can change Quaternion to SFRotation.

**Comment by andreasplesch** [comment]
SFRotation gets immediately converted to Quaternion:

https://github.com/x3dom/x3dom/blob/90b00070ae0bab1b475146cbaa23a382f7f399d0/src/nodes/Core/X3DNode.js#L783

For better X3D SAI spec. conformance a real SFRotation type with methods would be good but for web use it would be mostly just overhead.

**Comment by microaaron** [comment]
> SFRotation gets immediately converted to Quaternion:
> 
> https://github.com/x3dom/x3dom/blob/90b00070ae0bab1b475146cbaa23a382f7f399d0/src/nodes/Core/X3DNode.js#L783
> 
> For better X3D SAI spec. conformance a real SFRotation type with methods would be good but for web use it would be mostly just overhead.

Thank you. 😀

**Comment by andreasplesch** [comment]
Let me close this.
