### ISSUE TITLE
getAttribute('rotation') causes an error

### ISSUE THREAD

**Issue by microaaron** [x3dom/x3dom#1097]
getAttribute('rotation') causes an error:

Uncaught TypeError: Cannot set property 'rotation' of undefined

That means I can't read this attribute.

**Comment by microaaron** [comment]
OK, forget getAttribute(). It's useless. Use getFieldValue("rotation") to get a Quaternion value. And Quaternion.toAxisAngle() can change it to SFRotation.

**Comment by andreasplesch** [comment]
Please feel free reopen as required,
