### ISSUE TITLE
Shared geometry buffer is deleted if a single inline node that uses that buffer is removed from DOM.

### ISSUE THREAD

**Issue by Sharian** [x3dom/x3dom#1113]
Hello, 

in my use case I am adding gltf meshes dynamically to my scene and to be able to access their textures, I am setting their nameSpaceName. When removing only one of multiple meshes referencing the same gltf, all of the meshes that reference the gltf get removed. 

An example app can be found here: 
https://fervent-panini-6422c5.netlify.app/
"Add Node" adds an inline node referencing an example gltf file. 
"Remove single node" is supposed to remove only one node but the geometry data gets deleted and the other nodes cannot be rendered anymore.

In case I do not set "nameSpaceName" for the inline nodes everything works as expected, but then I'm not able to access the textures.

**Comment by Sharian** [comment]
I get the expected functionality if "_cleanupGLObjects" is not forced here: https://github.com/x3dom/x3dom/blob/master/src/X3DDocument.js#L630

**Comment by andreasplesch** [comment]
I think what happens is that the gl.buffers are shared between the inlined shapes. Then the cleanup deletes the buffer if one Inline is removed. The reason why they are shared is a cache, the bufferGeoCache which currently does not anticipate this case. The cache works by using the URL of the gltf buffer as an index to look up if the data is already cached. So a simple workaround is to circumvent the caching by making the URL of each inline unique with a noop path:

```js
inlineElement.setAttribute('url', 'https://examples.x3dom.org/gltf2/cerberus/glTF/'+'./'.repeat(numNodes)+'cerberus.gltf');
```

An option may be to not cache the gl.buffers but still keep the gltf buffer data (easier). Or somehow check on cleanup if the gl.buffers are still needed by another shape (harder).

**Comment by Sharian** [comment]
Thank you! I will look into the usage of bufferGeoCache and see what I can do. As a workaround I removed the force flag for _cleanupGLObjects but I was not able to test what issues this may cause.

**Comment by andreasplesch** [comment]
Here is a potential solution as outlined for x3dom.BinaryContainerLoader.setupBufferGeo

```js
        x3dom.BinaryContainerLoader.bufferGeoCache[ URL ].promise.then( function ( arraybuffer )
        {
            if ( shape._webgl == undefined )
            {
                x3dom.BinaryContainerLoader.bufferGeoCache[ URL ] = undefined;
                return;
            }

            initBufferViews( arraybuffer );
            initAccessors();
            computeNormals( arraybuffer );
            ///// START, AP 090720
            x3dom.BinaryContainerLoader.bufferGeoCache[ URL ].shapes.push( shape );
            shape._webgl._bufferGeoCache = x3dom.BinaryContainerLoader.bufferGeoCache[ URL ];
            //patch cleanupGLObjects to check for cache
            var cleanupGLObjects = shape._cleanupGLObjects;
            shape._cleanupGLObjects = function ( force, delGL )
            {
                var cache = this._webgl._bufferGeoCache;
                var found = cache.shapes.indexOf( this );
                if ( found > -1 )
                {
                    cache.shapes.splice( found, 1 );
                }
                if ( cache.shapes.length > 0 )
                {
                    return;
                }
                cleanupGLObjects.call(this, force, delGL );
            }
            ///// END, AP 090720

            if ( x3dom.BinaryContainerLoader.bufferGeoCache[ URL ].decrementDownload )
            {
                x3dom.BinaryContainerLoader.bufferGeoCache[ URL ].decrementDownload = false;
                shape._nameSpace.doc.decrementDownloads();
                shape._nameSpace.doc.needRender = true;
            }
        } ).catch( function ()
        {
            if ( x3dom.BinaryContainerLoader.bufferGeoCache[ URL ].decrementDownload )
            {
                x3dom.BinaryContainerLoader.bufferGeoCache[ URL ].decrementDownload = false;
                shape._nameSpace.doc.decrementDownloads();
            }
        } );
```
There is probably a more elegant fix rather than patching a function but could you test this please ?
Thanks.

**Comment by andreasplesch** [comment]
Here is a build with this fix: https://5f5691f4e319ee84045d8091--x3dom.netlify.app/x3dom-full.debug.js

**Comment by andreasplesch** [comment]
It would be great if you could test this build: https://5f5691f4e319ee84045d8091--x3dom.netlify.app/x3dom-full.debug.js

**Comment by Sharian** [comment]
Thank you very much! I will look into this and come back to you :)

**Comment by Sharian** [comment]
Just out of curiousity: Does the bufferGeoCache need to know about the shapes using it or would a reference counter be sufficent? A reference count came first to my mind when thinking about how to solve this issue.

**Comment by andreasplesch** [comment]
Yeah, it probably works with a reference counter but it seemed safer and easy to use references to the actual shapes. These are all references, not copies. I am a bit more concerned about redefining the cleanup function. It works but wlll be harder to track down later.

**Comment by Sharian** [comment]
I updated the netlify example above and the buffers is not removed in case there are still shapes holding it left. Only when the last shape is removed, the deleteBuffer calls are made. Adding and removing the mesh after this also works as expected. Is there anything else I should test?

**Comment by andreasplesch** [comment]
Presumably the netlify example above was extracted from another application ? If you have another example to test that would be great. If not I think let's just use what we have.

**Comment by Sharian** [comment]
Sorry for the delay. I just tested inside our application and also there the behaviour is correct. Thank you very much for your help!

**Comment by andreasplesch** [comment]
Thanks for testing.
