### ISSUE TITLE
Report an error in documentation "Accessing and Manipulating Fields in X3DOM"

### ISSUE THREAD

**Issue by pandolia** [x3dom/x3dom#1115]
Documentation url: https://doc.x3dom.org/tutorials/basics/fields/index.html

Error code:
```javascript
var myColorArray = document.getElementById('myColorNode').requestFieldRef('color');
myColorArray[23].r = 1.0;
document.getElementById('myColorNode').releaseFieldRed('color');
```

Correct code:
```javascript
var myColorArray = document.getElementById('myColorNode').requestFieldRef('diffuseColor');
myColorArray.r = 1.0;
document.getElementById('myColorNode').releaseFieldRef('diffuseColor');
```

**Comment by andreasplesch** [comment]
Thanks for noticing this. The example for requestFieldRef differs deliberately from the other examples to show use of a field which has an _array_ value. The color field of a Color node is an array of colors. It is a bit unexpected to have that change in the series of examples but ultimately more informative. Would it be ok to leave as is ?

**Comment by pandolia** [comment]
Thanks for your answer. I think it may be less misunderstanding that the x3d-html code are provided with these javascript code.

**Comment by andreasplesch** [comment]
It is in the linked examples page: https://doc.x3dom.org/tutorials/basics/fields/example.html
