### ISSUE TITLE
Random ghost artefacts (d3-x3d transitions broken)

### ISSUE THREAD

**Issue by jamesleesaunders** [x3dom/x3dom#1118]
Morning!

I have noticed that the most recent dev version of x3dom seems to be manifesting some weird artefacts left behind in d3-x3d, in particular when entering or transitioning shapes.

I have put together 3 examples each with one using x3dom release (1.8.1) and again with dev:

### Multi Series Bar Chart
- [with x3dom dev](https://raw.githack.com/jamesleesaunders/d3-x3d/master/examples/X3DOM/chart/BarChartMultiSeries.html)
- [with x3dom release]( https://raw.githack.com/jamesleesaunders/d3-x3d/transition-bug/examples/X3DOM/chart/BarChartMultiSeries.html)
- [with x_ite](https://raw.githack.com/jamesleesaunders/d3-x3d/master/examples/X_ITE/chart/BarChartMultiSeries.html)
- If you add a new series to the chart (e.g click on 'Italy' tick box), a new area series will enter. However there is a weird small blue box which appears on the axis in the dev version which is not there in release. This happens whenever you add or remove a series. The weird thing is I cant find any evidence of these small blue boxes in the DOM though the element inspector?

### Area Chart
- [with x3dom dev](https://raw.githack.com/jamesleesaunders/d3-x3d/master/examples/X3DOM/chart/AreaChartMultiSeries.html)
- [with x3dom release](https://raw.githack.com/jamesleesaunders/d3-x3d/transition-bug/examples/X3DOM/chart/AreaChartMultiSeries.html)
- [with x_ite](https://raw.githack.com/jamesleesaunders/d3-x3d/master/examples/X_ITE/chart/AreaChartMultiSeries.html)
- If you add a new series to the chart (e.g click on 'Italy' tick box), a new area series will enter. In the release version the new series area is semi-transparent like its counterparts, in the dev version it is not transparent - I suspect this is because in actual fact the newly added plane is doubled and there are two of them (although this is not evident in the DOM).

### Ribbon Chart
- [with x3dom dev](https://raw.githack.com/jamesleesaunders/d3-x3d/master/examples/X3DOM/chart/RibbonChartMultiSeries.html)
- [with x3dom release](https://raw.githack.com/jamesleesaunders/d3-x3d/transition-bug/examples/X3DOM/chart/RibbonChartMultiSeries.html)
- [with x_ite](https://raw.githack.com/jamesleesaunders/d3-x3d/master/examples/X_ITE/chart/RibbonChartMultiSeries.html)
- If you remove all series (untick UK, France, Germany), then add series France, then Spain there is a weird second ribbon which appears under France. Also, unlike the release version the ribbons no longer seem to auto resize when adding/removing series. Again weird artefacts which are not found in the DOM. Or sometime you seen two ribbons on top of each other of different widths.

Although subtly different, I suspect all the bugs above are possible of the same origin?
Tested with both Chrome and Safari.
The same issues are not seen in x_ite.

All the shapes for these are generated outside of D3 in HTML before being appended to the chart, so I don't think this is the issue e.g:
```
const shape = (el) => {
		const shape = el.append("Shape");
		
		/*
		// FIXME: x3dom cannot have empty IFS nodes, we must to use .html() rather than .append() & .attr().
		shape.append("IndexedFaceset")
			.attr("coordIndex", (d) => d.coordIndex)
			.append("Coordinate")
			.attr("point", (d) => d.point);
		
		shape.append("Appearance")
			.append("Material")
			.attr("diffuseColor", colorParse(color))
			.attr("transparency", transparency);
		*/
		
		shape.html((d) => `
			<IndexedFaceset coordIndex="${d.coordIndex}"  solid="false">
				<Coordinate point="${d.point}"></Coordinate>
			</IndexedFaceset>
			<Appearance>
				<Material diffuseColor="${colorParse(color)}" transparency="${transparency}"></Material>
			</Appearance>
		`);
};
```

**Comment by jamesleesaunders** [comment]
![Screenshot 2020-09-09 at 10 27 01](https://user-images.githubusercontent.com/13055416/92581060-167cb600-f287-11ea-88e5-20d7d0c70d34.png)
![Screenshot 2020-09-09 at 10 27 19](https://user-images.githubusercontent.com/13055416/92581063-17ade300-f287-11ea-9186-edc2ce80f0ad.png)
![Screenshot 2020-09-09 at 10 26 26](https://user-images.githubusercontent.com/13055416/92581065-18467980-f287-11ea-9ea8-3940bb7fa454.png)

**Comment by andreasplesch** [comment]
Weird. I somehow suspect it has to do with Prototype support but I don't know how it could be that.

The shared problem is that an additional shape is introduced (box, copy, offset copy).

It is probably necessary to reproduce that behaviour without D3 which should be possible.

Then we need to bisect to find out which commit introduced this behaviour. Could you help with that ?

**Comment by andreasplesch** [comment]
If you look into the x3d graph rather than the dom, under _x3domNode, each series is added twice, in _childNodes, after checking a button. Not sure why. I guess checking a button is different from assembling the graph initially.

**Comment by jamesleesaunders** [comment]
Thanks @andreasplesch I will try and put together a couple of examples without D3.

**Comment by jamesleesaunders** [comment]
They are a bit dirty, but I think I have managed to recreate the 'bug' removing D3 from the equation:

with x3dom dev:
https://raw.githack.com/jamesleesaunders/d3-x3d/master/examples/test-dev.html

with x3dom release:
https://raw.githack.com/jamesleesaunders/d3-x3d/master/examples/test-release.html

Click on the 'Add One' button twice to add two additional boxes.
Click on the 'Remove One' button twice to remove two boxes.
In dev version the boxes are removed from the DOM but not the x3dom canvas (there is a 'ghost' box). 
In release version all boxes are removed as expected.

One point to note in this demo is when clicking 'Add One' it is adding boxes with the same id attribute 'shape2' (which is a bit wrong as should be unique), perhaps this is the issue? Either way the issue manifests itself in dev but not release akin to the d3-x3d issue.

This could perhaps be improved but we have something to start with?

**Comment by andreasplesch** [comment]
Yeah, using an "idd" attribute instead (and querySelector to find it ), makes it work with dev. This suggests it has to do how id is used as a DEF name by x3dom. It could be the same issue as above. Looking into it.

**Comment by andreasplesch** [comment]
Hm, I disabled the the mapping from id to DEF in NodeNameSpace.js. This fixes the test-dev example but not the original problem. So it is probably something else.

**Comment by andreasplesch** [comment]
[x3dom.debug (1).zip](https://github.com/x3dom/x3dom/files/5198896/x3dom.debug.1.zip)
has a potential one line fix, in X3DDocument.onNodeAdded()
It is just a guard to not add a node to the X3D graph if it already has an attached X3D node which indicates that it was already added.
(In theory this could come from another graph, so it would be safer to additionally check if it already is a child of the parent but it should be rare to detach a dom node and then reattach the same node somewhere else, in the x3d graph).
Please give it a try. I think the issue is the switch from MutationEvent to MutationObserver, and not the Prototype code.

**Comment by jamesleesaunders** [comment]
Great! That seems to have fixed it! Thanks @andreasplesch 
If any help in pin pointing the commit I first noticed the issue on 21st Aug (in https://github.com/jamesleesaunders/d3-x3d/issues/168). But it could be any time before then!..
