### ISSUE TITLE
Release v1.8.2

### ISSUE THREAD

**Issue by jamesleesaunders** [x3dom/x3dom#1120]
Hi @tsturm @andreasplesch @fibo 
Is it time for another release (v1.8.2)?
There have been LOTS of great additions and bugfixes in the last year and I think it is important to keep regular incremental releases flowing so people can see x3dom is a active project.

I am happy to throw throw out some comms on mailing lists, twitter, reddit etc if needed.

**Comment by andreasplesch** [comment]
Let me mention @chrstein as well. Traditionally, the Web3D conference is the time for a new release, and it is coming up. I also think that would be great. In preparation, could you put together highlights from the Changelog, or even write a draft for a summary announcement ?

**Comment by jamesleesaunders** [comment]
Sure! I will have a go at condensing the changelog into highlights.

**Comment by fibo** [comment]
I can package it and release it on npm, to do that I need the x3dom.js and x3dom.css files updated to v1.8.2, where can I get them?

**Comment by andreasplesch** [comment]
@fibo This is what we are trying to do. We will need FHGs input for that.

**Comment by tsturm** [comment]
Hi all, sorry for the late response.

Sounds good!
If everything is prepared I can update the Homepage & the Server.

**Comment by andreasplesch** [comment]
Timo, do you know if there any plans for the Web3d conference ?

**Comment by tsturm** [comment]
Currently I don't know about any special plans, but I will bring it up in our department round tomorrow.

**Comment by jamesleesaunders** [comment]
Hi, as promised, I have had a go at writing up release notes. I hope these are of use? I struggled to boil down the plethora of great features and improvements down to a few points, some I may have simplified too much? (and to be honest I am no sure what a number of the points in the change log are)? Please feel free to amend / change as you feel appropriate...

```
# X3DOM 1.8.2 Released

We are happy to announce the release of X3DOM 1.8.2! This release contains a handful of new features, improvements along with a number of bug fixes since the last release.
We would like to thank all users and, of course, all the contributors, that make X3DOM such a great project.
For a detailed list of changes see the [changelog](https://github.com/jamesleesaunders/x3dom/blob/master/CHANGELOG.md) on Github.

## New Features

* New Exploration Modes.
* Experimental support for X3D prototypes.
* Added X3D 4.0 support for visible field, enhanced viewpoint options and Point Properties and cylinder/code options.
* Automatic origChannelCount detection.
* New NPM based build system.

## Fixes and Enhancements

* Improved support for shadow & transparency on text.
* Animation improvements for shapes and viewpoints and play controls.
* Improved event and TouchSensor support.
* Improved support for addition / removal of nodes from the tree.
* Replaced deprecated MutationEvents with a MutationObserver.
* Make it possible to run x3dom in strict mode.
* Text node improvements.
* More robust collisions in walk mode.

## Changes

* Remove support for compressed BinGeo files & Zlib.
* Remove support for ImageGeometry.
* Remove support for MultiPart.
* Remove support for ExternalShape/ExternalGeo and glTF 1.0.
* Remove support for loading single components.

## Get It!

Grab the frozen 1.8.2 version [here](https://x3dom.org/download/1.8.2/). The cutting-edge development version (nightly build of git head) can be found [here](https://x3dom.org/download/dev/).

```

**Comment by andreasplesch** [comment]
Looks good ! Let's see what Timo can report.

**Comment by jamesleesaunders** [comment]
@tsturm Is there any new on this?

**Comment by jamesleesaunders** [comment]
What do we recon to a new release?

**Comment by andreasplesch** [comment]
Unfortunately, FHG did not actively participate in web3d2020. So it looks like we have to find a strategy to release 1.8.2 using github and email channels.

I think I can tag a version. I can also

**Comment by andreasplesch** [comment]
- [ ] define a commit as release: probably just current head

- [ ] build and make sure file names are correct

- [ ] tag and make release

- [ ] push out announcement

- [ ] npm

- [ ] ask to update x3dom.org

**Comment by tsturm** [comment]
Hey all,

sorry that I'm not really active here in the last month's, but currently instant3Dhub & our new Company take up my whole time.

I don't have an overview of the current state and the stability, but if you say:

> "GO, the current head is ready for a release"

I can do everything release related expect for the npm update

**Comment by andreasplesch** [comment]
Hi @tsturm ! Yes, let's GO, the current head is ready for release. @fibo offered to update npm.

Best of success with instant3Dhub and your new company !

**Comment by tomalbrc** [comment]
x3dom.org is still lacking any sort of announcement regarding the release of 1.8.2

**Comment by tsturm** [comment]
Sorry, should we plan it for this weekend?

**Comment by andreasplesch** [comment]
Yes, any time really.

**Comment by fibo** [comment]
@tsturm I can give you permissions to publish on npm, currently I am the only one that can do it and in my opinion it would be better to give rights also to other users.

**Comment by tsturm** [comment]
Hi all,

I have released 1.8.2 on github and updated [x3dom.org](https://www.x3dom.org/)

@jamesleesaunders, @andreasplesch: Can one of you announce the Release on the mailing lists?

@fibo: Can you update the version on NPM?
I think it would be nice if you can give permissions to publish to @andreasplesch & me.

Big thanks to all of you!

**Comment by jamesleesaunders** [comment]
Yay! Great news! I'll send out some comms to the mailing list.

**Comment by andreasplesch** [comment]
Fantastic, ! Thanks. https://www.x3dom.org/news/ look good.

**Comment by fibo** [comment]
@tsrurm I invited @andreasplesch on npm/x3dom

I cound not found your username on npm https://www.npmjs.com/~tsturm

**Comment by jamesleesaunders** [comment]
Thanks all! I have send out messages to X3D and x3dom mailing lists.

minor: 
I noticed a small little typo on the website on the downloads page:
I think these should read:
* Version: 1.8.1, Sep 27, 2019
* Version: 1.8.0, July 24, 2019
(and if i am being really picky the dates on all these could do with standardising .. later down  they are in format 06.11.2012)

Also: Few instances of 'Documetation'  should be 'Documentation'

example:
```
Previous Stable Releases
Version: 1.8.1, Juli 24, 2019
URL: download

Version: 1.8.0, Juli 24, 2019
URL: download
...
Version: 1.6.1, July 24, 2014
URL: download
...
Version: 1.4, 06.11.2012
URL: download
Documetation: Nodes and Components, Official Documentation, Release Notes
```

Just me being nit-picky ;-)

**Comment by andreasplesch** [comment]
Thank you for sending out the announcement !

**Comment by tsturm** [comment]
@jamesleesaunders: I unified the Download-Page a bit ;)

@fibo: Now, you should be able to find me ;)

https://www.npmjs.com/~tsturm
