### ISSUE TITLE
Regression Canvas resource leak in version 1.8.2

### ISSUE THREAD

**Issue by sudsy** [x3dom/x3dom#1136]
The current development version seems to have a resource leak that wasn't there under the previous version. I have created a couple of fiddles to demonstrate.

In the current stable version, if you remove the x3dom node from the document tree, the canvas is automatically destroyed as demonstrated in : http://jsfiddle.net/w2zsx6ne/7/

In the latest development version as you remove and re-add the x3dom node back to the document tree it doesn't release the resources from the removed x3dom nodes : http://jsfiddle.net/w2zsx6ne/8/

**Comment by andreasplesch** [comment]
Thanks, I see the difference, and the leaking.
Here is a more concise example for debugging purposes:
https://raw.githack.com/x3dom/x3dom/master/test/regression-suite/test/cases/reload/reload.html
Clicking create will create a new canvas, with the previous one not being released from the list of canvases.

**Comment by andreasplesch** [comment]
https://github.com/x3dom/x3dom/pull/1058 looks like it is related.

**Comment by andreasplesch** [comment]
Would it be possible to create an example without knockout ?

**Comment by andreasplesch** [comment]
A problem was introduced some time ago when switching from MutationEvents to MutationObservers which resulted in not dealing with the removal of the X3D element.

Here is a build with a possible fix:

https://5f93186316bbef00073ece01--x3dom.netlify.app/
https://5f93186316bbef00073ece01--x3dom.netlify.app/x3dom.debug.js

Coud you please give this a try ?

**Comment by andreasplesch** [comment]
Here is the example with the test build:

http://jsfiddle.net/8m2nqa74/

Looks like it is working but could you please try it also in your application ?

**Comment by sudsy** [comment]
Thanks, that certainly seems to have fixed my fiddle but when I deployed the fix in my application I still had the same problem of the resource leak.

It seems that the real situation is more like this fiddle: http://jsfiddle.net/k1ygpvc7/

I think in my case there is a large tree of nodes being removed from the dom and the x3d node is nested within that tree.

I forked the repo to see if I could create a regression test for you but I noticed that the suite was windows only as far as I can see. I actually wasn't sure where the appropriate place to put this type of test would be.

**Comment by andreasplesch** [comment]
Yes, replicated. It looks like the only way is to have an observer for the complete document. Let me try a few things.
The testing is not well maintained for lack of manpower.

**Comment by sudsy** [comment]
I guess that it would be good to test with multiple x3dom nodes in the
fragment that gets removed too.

I understand about lack of manpower. Sorry I couldn't be more helpful.

**Comment by andreasplesch** [comment]
Ok, I added an addition MutationObserver dedicated to X3D elements which observes the whole document. When a node is removed anywhere it checks if it or if any of its descendants is a X3D element and cleans it up. It uses querySelectorAll for that which may become a performance issue if there are many mutations. Unfortunately, x3dom itself creates mutations each tick to update its status panel.

Here is a build to check out:

https://5f94c6094f3d8900087f3bba--x3dom.netlify.app/

**Comment by sudsy** [comment]
Brilliant!

That has fixed the problem in my application. Thanks!

So far there doesn't seem to be any performance issues with the mutation observer but I will keep an eye on it. If it ever does become a performance issue perhaps this library will be helpful which seems to be optimised for handling mutation events. https://github.com/rafaelw/mutation-summary (found it referenced on MDN). Thought it worth logging it in this issue if ever this needs revisiting.

**Comment by andreasplesch** [comment]
Great. The setup is now two separate observers. One dedicated to observing the whole document for X3D element mutations, and one for mutations inside the X3D. The X3D observer does not observe attributes. Childlist mutations inside the X3D are observed by both observers which is a bit wasteful. But typically there are not many unless somebody tries to do animation this way which is not necessary. Still, it would be possible to just use a single document wide observer. But then there needs to be a check if a mutated element is inside an X3D element which in itself could be relatively slow.
mutation-summary looks nice. It does not seem to explain how it optimizes over direct MutationObserver usage. Perhaps worth looking for some benchmarks. Generally, x3dom's perhaps outdated philosophy (from the deep past) was to avoid external dependencies and that had benefits. But that could change.

**Comment by andreasplesch** [comment]
The fix should be available in the dev version tomorrow. Please feel free to reopen as appropriate.

**Comment by andreasplesch** [comment]
I found this:
https://github.com/rafaelw/mutation-summary/blob/master/DOMMutationObservers.md#mutation-observers-vs-mutation-summary-this-library
That sounds like mutation-summary does work which makes use of mutations more robust, but not always more performant. It may be ok to leave that responsibility to the application itself, eg. it should not introduce unnecessary mutations. For example if the the goal is to change an existing X3D scene, it may be better to change the content rather than to completely replace the X3D element. But that may depend on the change itself.

**Comment by andreasplesch** [comment]
Just a note:
https://stackoverflow.com/questions/31659567/performance-of-mutationobserver-to-detect-nodes-in-entire-dom/39332340 has a lot of good, up-to-date tips on performance.
An easy one is to use querySelector before using the more expensive querySelectorAll.
