### ISSUE TITLE
not able to get left and right matrix in WebXR

### ISSUE THREAD

**Issue by leoull** [x3dom/x3dom#1137]
I am porting x3dom to WebXR and I couldn't get the left and right matrix. This is more of a WebXR question.

In the current WebVR implementation of x3dom, we are able to get leftViewMatrix and rightViewMatrix from VRFrameData object but I couldn't do this in WebXR.

The sample WebXR code I am using just gets projectionMatrix from XRView object and I am not sure how they are getting and rendering the left and right matrix.

Sample WebXRCode: https://github.com/immersive-web/webxr-samples/blob/master/immersive-vr-session.html

**Comment by andreasplesch** [comment]
It looks like the pose has views for each eye:

https://developer.mozilla.org/en-US/docs/Web/API/XRViewerPose/views

A view

https://developer.mozilla.org/en-US/docs/Web/API/XRView

then has an eye (left | right) and projectionMatrix property to get the matrix.

**Comment by andreasplesch** [comment]
Please feel to reopen as appropriate.
