### ISSUE TITLE
Lack of FEM visualization examples, broken link

### ISSUE THREAD

**Issue by jr23mx** [x3dom/x3dom#1156]
Dear community 

I have been looking into the documentation, there are very few examples of FEA or FEM data visualization, and the only one close example, the link is broken, can you kindly provide more information.

http://i-fx.net/demo/airplane.xhtml

Best regards

**Comment by andreasplesch** [comment]
http://www.caeplex.com/ has some cool examples.

**Comment by jr23mx** [comment]
I couldn't see any X3DOM code on the caeplex website, I am looking how to implement the FEA visualization. can you share some direct link if those really exist?

**Comment by andreasplesch** [comment]
http://www.caeplex.com/project/results.php?id=0ef14d1595f84c9d012fb5ad477ac0d8 is a sample project.
