### ISSUE TITLE
<PixelTexture DEF="Displacement_vector-Magnitude" 

### ISSUE THREAD

**Issue by jr23mx** [x3dom/x3dom#1157]
Hello Everyone

I have exported a file using parawiew, the file contains the scene where FEA results can be visualized. There is a typical legend with colors, and those can be added as an optional on the Paraview GUI.

What I can see on the x3d file is that data is stored like the following lines

<PixelTexture DEF="Displacement_vector-Magnitude" coordIndex="
      91 279 4
0x000000ff
0x00000052 0x00000057 0x0000006e 0x000000ff 0x00000052 0x00000057 0x0000006e 0x000000ff
0x00000052 0x00000057 0x0000006e 0x000000ff 0x00000052 0x00000057 0x0000006e 0x000000ff
0x00000052 0x00000057 0x0000006e 0x000000ff 0x00000052 0x00000057 0x0000006e 0x000000ff
0x00000052 0x00000057 0x0000006e 0x000000ff 0x00000052 0x00000057 0x0000006e 0x000000ff

My question is, how can I plot this legend? I have tried many things, but I cannot find any example similiar.

Best regards

**Comment by andreasplesch** [comment]
PixelTexture is just a raster image and the format is defined here:

https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/texturing.html#PixelTexture and here

https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/fieldsDef.html#SFImageAndMFImage

Typically you would make one dimension 1px wide and then scale the image or texture.

**Comment by andreasplesch** [comment]
Please reopen when appropriate.
