### ISSUE TITLE
"Unrecognised X3D element Extrusion"

### ISSUE THREAD

**Issue by aanastasiou** [x3dom/x3dom#1161]
Hello

I faced a lot of problems trying to depict extrusions which used to work in an application but for some reason disappeared (?).
I thought it was my code but I isolated a small example and it behaved as if the extrusion was not even there.
Still thinking I have missed some kind of standard update, I tried to depict [this file](https://github.com/x3dom/x3dom/blob/master/test/functional/extrusion.html) and was really surprised when I noticed the warnings in the component's log.

The **only** difference between that example and my code is that I do not load the viewer script from a local file (which I have not tried yet) but link it from http://www.x3dom.org/x3dom/release/x3dom.js OR http://www.x3dom.org/download/x3dom.js . (I noticed that this last link is redirected to `1.8.2`).

Either of these options still fetches a viewer but that viewer fails to load the extrusions.

Any ideas what I might be missing here?

**Comment by andreasplesch** [comment]
Please try x3dom-full.js .

**Comment by aanastasiou** [comment]
@andreasplesch Thank you very much, that did it.
