### ISSUE TITLE
CONTEXT_LOST_WEBGL

### ISSUE THREAD

**Issue by npolys** [x3dom/x3dom#1164]
I am getting this error on larger scenes, lots of inlines and texture memory :-(

WebGL: CONTEXT_LOST_WEBGL

Is see some fixes catching this event on a canvas object 
and reloading
eg
https://www.khronos.org/webgl/wiki/HandlingContextLost
applied in a toolkit:
https://stackoverflow.com/questions/61020416/how-to-handle-webgl-context-lost-webgl-errors-more-gracefully-in-pixijs

**Comment by npolys** [comment]
Everything is loaded, its after a few viewpoints arte visited and navigations happen.

**Comment by npolys** [comment]
There are over a dozen LODs in the scene

**Comment by npolys** [comment]
Updated graphics driver (did not solve)
 and forced Chrome to use OpenGL 
 with chrome:.//flags  ANGLE settings (seems to have solved)

**Comment by andreasplesch** [comment]
There is a TODO:

https://github.com/x3dom/x3dom/blob/83ce36310eda365a35ece8391e9a8c3f78800c38/src/X3DCanvas.js#L457

**Comment by npolys** [comment]
recurring problem in Edge and Chrome: 
unsure for the reason of the crash:

       WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
5x3dom.js:7 
        
       Uncaught TypeError: Failed to execute 'shaderSource' on 'WebGL2RenderingContext': parameter 1 is not of type 'WebGLShader'.
    at x3dom.shader.DynamicShaderPicking.generateVertexShader (x3dom.js:7:510309)
    at new x3dom.shader.DynamicShaderPicking (x3dom.js:7:506487)
    at x3dom.Cache.getShaderByProperties (x3dom.js:7:270061)
    at e.renderPickingPass (x3dom.js:7:177108)
    at e.pickValue (x3dom.js:7:202163)
    at x3dom.X3DDocument.onMove (x3dom.js:7:284666)
    at HTMLCanvasElement.onMouseMove (x3dom.js:7:30585)

**Comment by andreasplesch** [comment]
If we can have an example which reliably reproduces, there is a chance to find out more.

**Comment by npolys** [comment]
Thanks I am checking the models more closely today
It does not show up on local files... Just online ones as far as I can yell

**Comment by npolys** [comment]
The cause of this particular problem was a massive amount of image textures
in the scene (high-res geo imagery) 
   ... and the nature of those textures:

So, this should be a good note for future developers working in laptops or thin clients: 

X3DOM does its best to manage textures and rendering quality and  is quite flexible in that it will try to use your supplied image and scale it for rendering, even if not powers of two. 
However we must remember this old rule for GL efficiency, esp. if your target WWW clients are thin. 

Some relevant points in the x3dom codebase 
(Thanks Andreas :-):
"
...  Try elevation tiles without textures to help debug ?

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices has some interesting info. Perhaps turning on mipmaps for the scenery helps:
https://doc.x3dom.org/author/Texturing/TextureProperties.html : generateMipMaps=true . That would be easy to add.

Using gpu friendly compressed textures may also help:
https://www.x3dom.org/x3dom-supports-compressed-textures/

...
I also noticed that the terrain textures are not power of two. Rescaling them to 1024, and 2048 may help as well.

Forcing scale=false for all ImageTextures also helped. By default it is true, which means a 1280px image will be scaled to 2048px, a large increase in memory use. Unscaled non-pot textures probably only works for webgl2 devices which is ok, not sure about Apple.
You could modify x3dom.js to change the default if it is difficult to add the field to the x3d. This also loads faster because no scaling is done.

So I would recommend using pot textures, or if not feasible or too degraded resolution, switch off scaling, eg. scale=false.
"

Resampling textures to PoT was a powerful fix and let us load on a bunch of devices we did not think possible!

We will also try a test build with the scale=false as default and report the difference...

**Comment by andreasplesch** [comment]
Super. Yes, please report results for scale=false.

**Comment by npolys** [comment]
Performance was very much improved; I imagine X3DOM is resampling the images in cpu
