### ISSUE TITLE
Loading the inline node is too slow and some button events are frozen, responded with annoying delay.

### ISSUE THREAD

**Issue by molicaca** [x3dom/x3dom#1171]
I use the <inline> to load my x3d file, whose size is about 60Mb. But when the source is downloaded, the whole page seems frozen and cant respond to my click event for a while. And after the whole x3d obj is loaded, it returns normal and handled my button-click event. It is rather annoying since if i use the "loaded=false" and load it afterward, the loading process is still slow and it would seems dumb. Can it be that the browser loaded the object in the backstage and handle some click event at the same time, and just then I can show the whole 3d model to the user?  Or any other trick when loading the inline object. As I am concerned, the 60 Mb file would not be so large to be rendered in several seconds,, maybe. Anyway, any repliy helps

**Comment by andreasplesch** [comment]
There may not be much which can be done other than optimizing the large model. Sometimes it is possible to reduce the number of shapes substantially, for example.

**Comment by molicaca** [comment]
Oh, it does provide some ideas. Thx!
But is there any method to show the loading process of the x3d object? Maybe something just like 99%, 70% would help.
Here is my demo. And now I want make some text description shown on the page and others can click on some button to make the 3d scene visible. When it is loaded, the button would be frozen and the user would never know what happened. So just some tips to tell the user just to wait the loading process. I guess the visualization of the loading progress can make sense.
https://molicaca.github.io/atlas/mcqatlas.html

**Comment by andreasplesch** [comment]
The webviewer looks great. I think you found that using BinaryGeometry and hiding the canvas until the view button gets clicked works pretty well.

**Comment by andreasplesch** [comment]
It may be possible to pack BinaryGeometry data into a single files by using  an offset (#) in the url. But I could not find an example for that. You may have to read the source code to figure out exactly how that would work. That should help with total loading times but would delay the display of first shapes, so may be not a desirable anyways.

**Comment by molicaca** [comment]
Yes! Using BinaryGeometry really helps a lot!
Thanks for your advice and it really makes sense. I will figure that out later.
