### ISSUE TITLE
What is the difference between CollidableShape.translation and RigidBody.position?

### ISSUE THREAD

**Issue by microaaron** [x3dom/x3dom#1205]
What is the difference between CollidableShape.translation and RigidBody.position? RigidBody.position doesn't seem to be used.

**Comment by andreasplesch** [comment]
I am not familiar with the rigid body physics component. Here are spec. entries:

https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/rigidBodyPhysics.html#CollidableShape

https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/rigidBodyPhysics.html#RigidBody

**Comment by microaaron** [comment]
Thanks.
