### ISSUE TITLE
Navigator.getVRDisplays() is deprecated.

### ISSUE THREAD

**Issue by microaaron** [x3dom/x3dom#1230]
My game pad accidentally triggered an exception.
Uncaught TypeError: [navigator.getVRDisplays](https://github.com/x3dom/x3dom/blob/master/src/util/VRControllerManager.js#L65) is not a function at x3dom.VRControllerManager._onGamePadConnected.
https://github.com/x3dom/x3dom/blob/c4a27a8750f89cead2741620c836b27e8f7e43f6/src/util/VRControllerManager.js#L65
The reason is that [Navigator.getVRDisplays() is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getVRDisplays).
Maybe [Navigator.getGamepads()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getGamepads) is an alternative, but it is an experimental technology.

**Comment by andreasplesch** [comment]
This needs to transition to WebXR: https://developer.mozilla.org/en-US/docs/Web/API/WebVR_API

**Comment by msub2** [comment]
Will try my hand at transitioning things from WebVR -> WebXR this weekend

**Comment by andreasplesch** [comment]
fixed with 1.8.3 .
