### ISSUE TITLE
www.x3dom.org/check fails with mixed active content due to https/http mismatch

### ISSUE THREAD

**Issue by godmar** [x3dom/x3dom#1234]
Hi, I was trying to get a [simple scene running](https://www.web3d.org/wiki/index.php/X3D_and_HTML5_examples#X3D_served_as_text.2Fhtml_.28no_namespace_prefix.29) in Firefox 104.0.2, but didn't see anything, so I went to https://www.x3dom.org/check/ to see if my browser supports X3D.

Unfortunately, this webpage attempts to mix https and http, something modern browsers (I believe) have been rejecting for several years.

```html
<link rel="stylesheet" href="[http://www.x3dom.org/download/dev/x3dom.css](view-source:http://www.x3dom.org/download/dev/x3dom.css)">
<script src="[http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js](view-source:http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js)"></script>
```

also, http doesn't work, either:
```text
$ curl -v http://www.x3dom.org/check/
*   Trying 192.44.35.68:80...
* Connected to www.x3dom.org (192.44.35.68) port 80 (#0)
> GET /check/ HTTP/1.1
> Host: www.x3dom.org
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Date: Wed, 19 Oct 2022 17:14:14 GMT
< Server: Apache/2.4.29 (Ubuntu)
< Location: https://www.x3dom.org/check/
```

Is there a way to test if my browser supports X3D, and perhaps you could update this site.

**Comment by tsturm** [comment]
You can simply test it by navigating to https://www.x3dom.org. The start page directly includes multiple interactive X3D scenes.
Another options is to ckeck your webGL 2 support with help of https://webglreport.com/?v=2

https://www.x3dom.org/check/ should work as well now.

**Comment by godmar** [comment]
Great, appears to work!
