### ISSUE TITLE
TextureTransform is ignored

### ISSUE THREAD

**Issue by ChristopheF** [x3dom/x3dom#1239]
In my tests the **TextureTransform** tag is ignored despite the 'fully implemented' status visible [here](https://doc.x3dom.org/author/Texturing/TextureTransform.html).
Below is my sample HTML page where the TextureTransform tag should apply a 90° (pi/2) rotation to the texture but the texture is still applied without any rotation (tested with latest versions of Edge/FireFox/Chrome). When I open the same X3D code in the [Octaga](https://www.octagavs.com/) player, I do see the texture rotation effect being applied.
Is this a bug in X3DOM or am I doing something wrong?
```
<html>
    <head>
        <script type='text/javascript' src='http://www.x3dom.org/download/x3dom.js'></script>
        <link rel='stylesheet' type='text/css' href='http://www.x3dom.org/download/x3dom.css'></link>
    </head>
<body>
    <X3D>
        <Scene>
            <Shape>
                <Appearance>
                    <ImageTexture url='Texture.png'/>
                    <TextureTransform rotation='1.57' />
                </Appearance>
                <IndexedFaceSet coordIndex='0 1 2 3' solid='false'>
                    <Coordinate point='-2 2 0 2 2 0 2 -2 0 -2 -2 0'/>
                </IndexedFaceSet>
            </Shape>
        </Scene>
    </X3D>
</body>
</html>
```

**Comment by andreasplesch** [comment]
Please try full closing tags: `</TextureTransform>`

**Comment by ChristopheF** [comment]
Thanks a lot, this works around my issue!
I thought both ways to close a tag were valid XML syntax.

**Comment by andreasplesch** [comment]
Yes, both are valid xml. But you will need to serve the html as xhtml for a web browser to recognize the content as xml, in the filename and probably also in the mime type. html is not xml and has a different syntax, albeit similar.

 Inlines with a .x3d extension are always parsed as xml.

**Comment by ChristopheF** [comment]
Thank you for that clarification. I was not aware of that difference between html/xhtml.
I did not suspect this could an issue because in my sample above I also closed other tags in the same way and they worked fine.
This makes perfect sense now.
