### ISSUE TITLE
Please can we create a 'latest' download folder?

### ISSUE THREAD

**Issue by jamesleesaunders** [x3dom/x3dom#1240]
Please can we create a 'latest' download folder (https://x3dom.org/download/latest/) on x3dom.org which is symm linked to the current latest build (currently 1.8.2)?

Currently, in order to now have to update documentation on my project (d3-x3d) I am using the 'dev' URL (https://x3dom.org/download/dev/) as a static URL, however the assets at this URL appears to be inaccessible every 10 minutes (assumedly because they are being build by scheduled CI/CD process every 10 mins).
This means that all my examples, notebooks, Observable etc are 'down' every 10 mins.

I could point directly to 'https://x3dom.org/download/1.8.2/' but then I need to update docs every time there is a new release where as a link to latest would be more static and form a more stable resource for developers.

p.s How are the release [1.8.3](https://github.com/x3dom/x3dom/issues/1213) plans going ;-)

**Comment by tsturm** [comment]
Hi James, to directly access the latest stable Version you can use the following:

https://www.x3dom.org/release

**Comment by jamesleesaunders** [comment]
Oh yes, perfect! Silly me! I am sure I already knew that.. Christmas brain! 
Happy New Year!
