### ISSUE TITLE
X3D 4 implementation status

### ISSUE THREAD

**Issue by anonimo82** [x3dom/x3dom#1249]
Hello everyone.
What's the current X3D 4 implementation status?
How far is it a full profile?

Thanks for any help.

**Comment by andreasplesch** [comment]
An up to date idea of implementation status of current and newer X3D versions may be provided by the Changelog: https://github.com/x3dom/x3dom/blob/master/CHANGELOG.md

Development of missing nodes/fields are largely driven by community contributions as they occur.

**Comment by anonimo82** [comment]
Thanks.
