### ISSUE TITLE
[Question] - 2D game/simulation

### ISSUE THREAD

**Issue by anonimo82** [x3dom/x3dom#1250]
Hello there.
I have this question, is it possible to run a 2D physics simulation with X3D?
Something I could do with SVG and MatterJS, but I'm told SVG is not suitable for complex games, while it looks like X3D is.
So, is it possible?

Thanks for any help.

Regards =)

**Comment by anonimo82** [comment]
P.S.: Look here: https://brm.io/matter-js/demo/#svg

**Comment by andreasplesch** [comment]
X3D has a Rigid Body Physics component: https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/rigid_physics.html

It is designed for 3d but could probably be restricted to 2d by keeping physics in one plane.

x3dom has some support for the physics component using bullet:

https://andreasplesch.github.io/Library/Examples/html5/physics/

**Comment by anonimo82** [comment]
Yes, I knew that.
I was just wondering what you just mentioned, that is, if it's possible to restrict physics to a single plane.
So, how can it be done?

Thanks for your help by the way.

**Comment by andreasplesch** [comment]
This is up to the designer. There is no explicit support, eg. something that would enforce that. So it is necessary to carefully define any movement to stay in the plane.

**Comment by anonimo82** [comment]
Uhm, is it there any working example/literature available?

**Comment by anonimo82** [comment]
By the way, this answers my question, so I'm going to close this

**Comment by thunderbreathing** [comment]
Yes , becz X3D is a file format and a web standard for 3D graphics and multimedia.
