### ISSUE TITLE
WARNING: Some required extension of KHR_draco_mesh_compression not supported.

### ISSUE THREAD

**Issue by MacrayBlackhand** [x3dom/x3dom#1254]
I have a model generating the error in the subject line.

The model is 15MB so I hesitate to attach but certainly can if that's okay.

I'll do my best to answer any questions regarding the model in Blender and the export settings (I used the defaults).

Thanks!

**Comment by MacrayBlackhand** [comment]
Warning, I'm an idiot, take my posts with extreme caution and disregard this one.

Apologies.

**Comment by andreasplesch** [comment]
no problem, please make sure to use x3dom-full.js
