### ISSUE TITLE
support KHR_lights_punctual, KHR_materials_emissive_strength, EXT_meshopt_compression, EXT_texture_webp

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#1259]
These glTF extensions are fairly straightforward to implement:

- [x] [KHR_lights_punctual](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_lights_punctual/README.md) : use regular X3D lights
- [x] [KHR_materials_emissive_strength](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_emissive_strength) : add a single factor in the shader
- [x] [EXT_meshopt_compression](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_meshopt_compression) : small js library available to decompress bufferviews
- [x] [EXT_texture_webp](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_texture_webp) : supported by the image element

**Comment by andreasplesch** [comment]
https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_lights_punctual/README.md

directional -> DirectionalLight
point -> PointLight
spot -> SpotLight
color -> color
name -> DEF ?
intensity -> intensity, may need adjustment
range -> 
  point: radius

**Comment by andreasplesch** [comment]
### Distance Attenuation
glTF and x3d treat attenuation with distance somewhat differently. Both have an absolute cutoff and both have inverse square falloff. But glTF additionally has additionally a smoother transition close the absolute cutoff.
castle just uses x3d defaults: https://github.com/castle-engine/castle-engine/blob/57a899edd0436bfb0ae990ed1078420ed8d97fb9/src/scene/load/x3dloadinternalgltf.pas#L757

**Comment by andreasplesch** [comment]
### Angular Attenuation, umbra
X3D:
```
angle = the angle between the Spotlight's direction vector and
            the vector from the Spotlight location to the point to be illuminated
    if (angle ≥ cutOffAngle):
        multiplier = 0
    else if (angle ≤ beamWidth):
        multiplier = 1
    else:
        multiplier = (angle - cutOffAngle) / (beamWidth - cutOffAngle)
    intensity(angle) = SpotLight.intensity × multiplier
```
![image](https://github.com/x3dom/x3dom/assets/6171115/48e06a78-41d3-4016-8a9c-70e761d2f1b0)


glTF: interpolation of cosines
```
// These two values can be calculated on the CPU and passed into the shader
float lightAngleScale = 1.0f / max(0.001f, cos(innerConeAngle) - cos(outerConeAngle));
float lightAngleOffset = -cos(outerConeAngle) * lightAngleScale;

// Then, in the shader:
float cd = dot(spotlightDir, normalizedLightVector); // cos(angle)
float angularAttenuation = saturate(cd * lightAngleScale + lightAngleOffset);
// cos(angle) / (cos(beamWidth) - cos(cutOff)) - cos(cufOff)/(cos(beamWidth) - cos(cutOff))

// (cos(angle)-cos(cutOff))/(cos(beamWidth) - cos(cutOff))

angularAttenuation *= angularAttenuation;
```

In short, X3D interpolates uses angle difference ratios which glTF uses ratio of the differences of the cosines, then squared for sharper falloff.

Let's see how this compares:

**Comment by andreasplesch** [comment]
### Examples
https://github.com/castle-engine/demo-models/tree/master/gltf/punctual_lights
https://www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter11LightingEnvironmentalEffects/SpotLightVisualizationIndex.html
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/LightsPunctualLamp
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/IridescenceSuzanne

**Comment by andreasplesch** [comment]
[pointlight.zip](https://github.com/x3dom/x3dom/files/12391564/pointlight.zip)
3js: ![image](https://github.com/x3dom/x3dom/assets/6171115/6e44c668-6bf5-4b0a-a54b-b1af20314b9f)
babylonjs: ![image](https://github.com/x3dom/x3dom/assets/6171115/be408777-654a-4533-bb66-a8193720d5d8)

**Comment by andreasplesch** [comment]
[spotlight.zip](https://github.com/x3dom/x3dom/files/12391807/spotlight.zip)
threejs: 
![image](https://github.com/x3dom/x3dom/assets/6171115/bf3bac09-386f-40b8-a9c1-8f851e72d321)

bjs:![image](https://github.com/x3dom/x3dom/assets/6171115/f6c9d649-2db8-421c-8aec-4bb738074cf8)
 
khronos:![image](https://github.com/x3dom/x3dom/assets/6171115/2ec1953e-c228-4dc4-9fb6-02bd09a114c1)

view3dscene:
![spotlight_0](https://github.com/x3dom/x3dom/assets/6171115/4ee8a571-d1c5-49f9-bff7-819db9653353)

**Comment by andreasplesch** [comment]
The Khronos gltf viewer uses a slightly modified version of the recommendation in the glTF spec. for angular attenuation:
```glsl
float getSpotAttenuation(vec3 pointToLight, vec3 spotDirection, float outerConeCos, float innerConeCos) {
    float actualCos = dot(normalize(spotDirection), normalize(-pointToLight));
    if (actualCos > outerConeCos) {
        if (actualCos < innerConeCos) {
            return smoothstep(outerConeCos, innerConeCos, actualCos);
        }
        return 1.0;
    }
    return 0.0;
}
```

**Comment by andreasplesch** [comment]
directional light and point light with specular
https://raw.githubusercontent.com/KhronosGroup/glTF/main/extensions/2.0/Khronos/KHR_lights_punctual/schema/examples/lights.gltf
https://github.com/andreasplesch/x3dom/raw/lights_punctual/test/functional/media/data/lights.glb

khronos:
![image](https://github.com/x3dom/x3dom/assets/6171115/3ea94e41-e1f8-4606-a5d9-a8b9215d7e7d)

view3dscene:
![image](https://github.com/x3dom/x3dom/assets/6171115/0659913b-0ab0-43eb-a7b1-970937db9872)

x3dom:
![image](https://github.com/x3dom/x3dom/assets/6171115/d7968705-a775-4ed4-a166-6eff750ed9dd)

bjs:
![image](https://github.com/x3dom/x3dom/assets/6171115/98bee576-e3a8-49a4-b649-254c871150d2)

threejs:
![image](https://github.com/x3dom/x3dom/assets/6171115/bc9a7018-1ba5-4dd6-ab68-9b4507591fce)

**Comment by andreasplesch** [comment]
PR #1292

**Comment by andreasplesch** [comment]
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/EmissiveStrengthTest

**Comment by andreasplesch** [comment]
PR #1293

**Comment by brutzman** [comment]
Wondering if there are corresponding changes in rendering hardware and APIs.

When ready, we should be prepared to propose potential additions for X3D 4.1.  Once fully ready for ISO with multiple implementations and corresponding examples, mature capabilities can be designated as an X3D Suggested Practice or Web3D Recommended Practice.

If possible, a single simple parameter for appropriate nodes and node types might be useful.  For example, with backwards compatibility:

- [in out] SFBool punctual FALSE

**Comment by andreasplesch** [comment]
I believe you are referring to the light attenuation changes of glTF relative to X3D.
Not sure API/hardware/OpenGL changes. Perhaps the fixed function pipeline had something related as Michalis was referring to it but that is ancient, eg. prepre webGL history. Certainly no recent changes.
glTF made these choices from trends in 3d/game engines I believe.
For a single parameter, another option would be a scalar weighting factor [0-1] for mixing x3d and gltf attenuation: 0=x3d, 1=gltf, 0.5 intermediate, SFFloat attenuationSmoothness 0.
But a boolean with a good name would be simpler.

**Comment by andreasplesch** [comment]
webp example:

https://playground.babylonjs.com/#LSAUH2#2

**Comment by andreasplesch** [comment]
range attenuation: 0,0,1 at radius 100, identical at 0 to 10m distance
![image](https://github.com/x3dom/x3dom/assets/6171115/fb6c88b4-2732-45f2-a2ad-fa16878f4bad)
at 50 to 100m distance strong attenuation and small differences
![image](https://github.com/x3dom/x3dom/assets/6171115/2beb954b-9a3c-4248-956d-327997274c3f)

1,0,0 at radius 100:
at 0 to 10: almost identical, no or very minor attenuation
![image](https://github.com/x3dom/x3dom/assets/6171115/f133d3d7-8d9d-4be6-a852-c84bbb54f57a)
at 50 to 100m distance step with x3d and parabolic transition with gltf
![image](https://github.com/x3dom/x3dom/assets/6171115/2111b168-2da2-4174-9a64-4baa50cf12c9)

infinite range (gltf default):
0,0,1
![image](https://github.com/x3dom/x3dom/assets/6171115/8e0f5cb3-f7f7-4df1-97a4-9fe6a0a375c2)
1,0,0
![image](https://github.com/x3dom/x3dom/assets/6171115/9f8a08d4-22d5-42dc-87b3-0be59065ee14)
for both attenuation settings, gltf and x3d are mathematically the same

**Comment by andreasplesch** [comment]
Meshopt example:
https://github.com/zeux/meshoptimizer/tree/master/demo
https://raw.githubusercontent.com/zeux/meshoptimizer/master/demo/pirate.glb

**Comment by andreasplesch** [comment]
1. combine compressed buffer as is with other buffers, update bufferview compressed byteoffsets, isMeshOpt=true (compressor=MeshOopt/Draco/None)
2. in binarysetup, decompress view

Or
Decompress views in Loader, and reassemble buffer and bufferviews.

**Comment by andreasplesch** [comment]
meshopt_compression is often/almost always used together with mesh_quantization. mesh_quantization was already implemented and needed only to be recognized as supported.
#1292
#1293
#1294
#1295
This concludes efforts on these 'simpler' gltf extensions.
