### ISSUE TITLE
How to achieve the effect of mouse selection

### ISSUE THREAD

**Issue by CYY-1100** [x3dom/x3dom#1263]
How to achieve the effect of mouse selection

**Comment by andreasplesch** [comment]
There are many ways to highlight a shape when hovering or clicking with the mouse pointer.

This tutorial turns the nose red when clicked: https://doc.x3dom.org/tutorials/models/inline/index.html

Here is another example which temporarily turns shapes yellow before returning to the original color:

https://andreasplesch.github.io/Library/Examples/html5/highlight/turnyellow.html

A more X3D way to indicate selection would be to use a Switch node which has the shape to display during selection as a choice. Or use the visible field of a Shape to toggle display based on a TouchSensor.

**Comment by andreasplesch** [comment]
Here is another approach. Dynamically attach an invisible highlight box to each shape of a certain class, scaled using the bounding box, and then simply turn that box on and off when desired.

https://andreasplesch.github.io/Library/Examples/html5/highlight/withBBox.html

**Comment by microaaron** [comment]
Maybe you're trying to highlight the outline of a shape.

**Comment by andreasplesch** [comment]
Outlines could be done using a custom shader:

https://alexanderameye.github.io/notes/rendering-outlines/

and many other shader examples.

Custom shaders:

https://doc.x3dom.org/tutorials/lighting/customShader/index.html

**Comment by andreasplesch** [comment]
Or by duplicating the shape, scaling it a bit larger, and showing only the backfaces:
https://andreasplesch.github.io/Library/Examples/html5/highlight/outline.html

**Comment by CYY-1100** [comment]
ok, i got it  thank you for help

**Comment by CYY-1100** [comment]
> Or by duplicating the shape, scaling it a bit larger, and showing only the backfaces: https://andreasplesch.github.io/Library/Examples/html5/highlight/outline.html

ok, I got it thanks for you help

**Comment by CYY-1100** [comment]
> Maybe you're trying to highlight the outline of a shape.

yes, i do it

**Comment by andreasplesch** [comment]
There is now also the bboxDisplay field.

**Comment by n-polys** [comment]
Cool!

**Comment by npolys** [comment]
IS there an example of the new functionality with nodes like Shape, Transform, and Group? I think bboxDisplay would be a great feature! ... ?

Does X3DOM automatically create a bbox of the correct size? How to do this at runtime?

**Comment by andreasplesch** [comment]
https://github.com/x3dom/x3dom/blob/master/test%2Fregression-suite%2Ftest%2Fcases%2Froutes%2Froutes.html

is an example.

All grouping nodes work, and the size is automatic.

**Comment by andreasplesch** [comment]
Here are the details:

https://github.com/x3dom/x3dom/blob/master/src%2Fnodes%2FGrouping%2FX3DBoundedObject.js

So all bounded objects work, and there is also bboxColor and bboxMargin.

**Comment by andreasplesch** [comment]
live https://raw.githack.com/x3dom/x3dom/master/test/regression-suite/test/cases/routes/routes.html

**Comment by npolys** [comment]
Fantastic!
Thanks for this feature! :-)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
