### ISSUE TITLE
Model Movement

### ISSUE THREAD

**Issue by CYY-1100** [x3dom/x3dom#1264]
How to display the plotted coordinate system in the lower left corner

**Comment by andreasplesch** [comment]
Short of mind reading, there is a better chance to receive constructive responses if some effort is spent on providing a useful  description. It should afford a way to properly understand the issue. Could you please elaborate or be more specific ? It is often best, or even a requirement to provide a live example of what was tried.

Something like
https://examples.x3dom.org/example/x3dom_uiEvents.html from
https://www.x3dom.org/examples/ ?

**Comment by andreasplesch** [comment]
Please feel free to reopen when appropriate.
