### ISSUE TITLE
Window through an low transparent object caused by an enveloping transparent object.

### ISSUE THREAD

**Issue by AxelGHC** [x3dom/x3dom#1279]
In the following code there are three objects:

```
<html>
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
		<title>Window with transparency?</title>
		<script type='text/javascript' src='https://www.x3dom.org/download/x3dom.js'> </script>
		<link rel='stylesheet' type='text/css' href='https://www.x3dom.org/download/x3dom.css'/>
	</head>
	<body>
		<p>Window with transparency?</p>
		<x3d width='500px' height='400px'>
			<scene>
				<shape>
					<appearance>
						<material diffuseColor='1 0 0' transparency='0.9'/>
					</appearance>
					<Box size='0.3,1,1'/>
				</shape>
				<shape>
					<appearance>
						<material diffuseColor='1 0 0' transparency='0.1'/>
					</appearance>
					<Box size='0.2,2,2'/>
				</shape>
				<transform translation='3 0 0'>
					<shape>
						<appearance>
							<material diffuseColor='0 0 1'/>
						</appearance>
						<sphere/>
					</shape>
				</transform>
			</scene>
		</x3d>
	</body>
</html> 
```
When I open the file in edge or chrome I can look through the red box depending on the viewing angle. Attached are two screenshots.
Is the effect intentional and controllable? Or a display error from the browser?

![image](https://github.com/x3dom/x3dom/assets/130909914/1b299844-61e5-4617-902c-30e5260d700c)
![image](https://github.com/x3dom/x3dom/assets/130909914/49801007-1cdc-4369-aff2-4b8e355b84c4)

If the effect is controllable how I can do? Thanks in advance Axel.

**Comment by andreasplesch** [comment]
Thanks. The latest dev version seems to fix this:

https://gist.githack.com/andreasplesch/415d151abee114858c79c20c8c4b49e0/raw/06f4866aaef0059987adb732f696942ce8f521fa/index.html

The transparency fixes will be included in the next release.

**Comment by AxelGHC** [comment]
I have already suspected that it is a bug. Too Bad, I have wished for something like this as a possibility. We have discussed this in #1268. Nevertheless, thank you for the quick answer. Axel.

**Comment by andreasplesch** [comment]
Another possibility may be to use a texture with transparent pixels to define visual holes.

**Comment by andreasplesch** [comment]
It also may be worth to try to experiment with blendmode:

https://andreasplesch.github.io/Library/Viewer/index.html?url=data:text/plan;base64,PHgzZD4KICA8c2NlbmU+CiAgICA8c2hhcGU+CiAgICAgIDxhcHBlYXJhbmNlIHNvcnRrZXk9JzEnPgogICAgICAgIDxtYXRlcmlhbCBkaWZmdXNlQ29sb3I9JzEgMCAwJyB0cmFuc3BhcmVuY3k9JzAuMSc+PC9tYXRlcmlhbD4KICAgICAgPC9hcHBlYXJhbmNlPgogICAgICA8Qm94IHNpemU9JzAuMiwyLDInPjwvQm94PgogICAgPC9zaGFwZT4KICAgIDxzaGFwZT4KICAgICAgPGFwcGVhcmFuY2Ugc29ydGtleT0nMic+CiAgICAgICAgPG1hdGVyaWFsIGRpZmZ1c2VDb2xvcj0nMSAxIDAnIHRyYW5zcGFyZW5jeT0nMC45Jz48L21hdGVyaWFsPgogICAgICAgIDxibGVuZG1vZGUgc3JjRmFjdG9yPSJvbmUiIGRlc3RGYWN0b3I9Inplcm8iID48L2JsZW5kbW9kZT4KICAgICAgPC9hcHBlYXJhbmNlPgogICAgICA8Qm94IHNpemU9JzAuMywxLDEnPjwvQm94PgogICAgPC9zaGFwZT4KICAgIDx0cmFuc2Zvcm0gdHJhbnNsYXRpb249JzMgMCAwJz4KICAgICAgPHNoYXBlPgogICAgICAgIDxhcHBlYXJhbmNlIHNvcnRrZXk9JzMnPgogICAgICAgICAgPG1hdGVyaWFsIGRpZmZ1c2VDb2xvcj0nMCAwIDEnIHRyYW5zcGFyZW5jeT0nMC4xJz48L21hdGVyaWFsPgogICAgICAgIDwvYXBwZWFyYW5jZT4KICAgICAgICA8c3BoZXJlPjwvc3BoZXJlPgogICAgICA8L3NoYXBlPgogICAgPC90cmFuc2Zvcm0+CiAgPC9zY2VuZT4KPC94Mw==

**Comment by andreasplesch** [comment]
Better with depthmode and sortkey:

https://andreasplesch.github.io/Library/Viewer/index.html?url=data:text/plan;base64,PHgzZD4KICA8c2NlbmU+CiAgICA8c2hhcGU+CiAgICAgIDxhcHBlYXJhbmNlIHNvcnRrZXk9JzInPgogICAgICAgIDxtYXRlcmlhbCBkaWZmdXNlQ29sb3I9JzEgMCAwJyB0cmFuc3BhcmVuY3k9JzAuMSc+PC9tYXRlcmlhbD4KICAgICAgPC9hcHBlYXJhbmNlPgogICAgICA8Qm94IHNpemU9JzAuMiwyLDInPjwvQm94PgogICAgPC9zaGFwZT4KICAgIDxzaGFwZT4KICAgICAgPGFwcGVhcmFuY2Ugc29ydGtleT0nMSc+CiAgICAgICAgPG1hdGVyaWFsIGRpZmZ1c2VDb2xvcj0nMSAwIDAnIHRyYW5zcGFyZW5jeT0nMC45Jz48L21hdGVyaWFsPgogICAgICAgIDxkZXB0aG1vZGUgcmVhZG9ubHk9J2ZhbHNlJz48L2RlcHRobW9kZT4KICAgICAgPC9hcHBlYXJhbmNlPgogICAgICA8Qm94IHNpemU9JzAuMywxLDEnPjwvQm94PgogICAgPC9zaGFwZT4KICAgIDx0cmFuc2Zvcm0gdHJhbnNsYXRpb249JzMgMCAwJz4KICAgICAgPHNoYXBlPgogICAgICAgIDxhcHBlYXJhbmNlPgogICAgICAgICAgPG1hdGVyaWFsIGRpZmZ1c2VDb2xvcj0nMCAwIDEnIHRyYW5zcGFyZW5jeT0nMC4wJz48L21hdGVyaWFsPgogICAgICAgIDwvYXBwZWFyYW5jZT4KICAgICAgICA8c3BoZXJlPjwvc3BoZXJlPgogICAgICA8L3NoYXBlPgogICAgPC90cmFuc2Zvcm0+CiAgPC9zY2VuZT4KPC94M2Q+

I believe this is the 1.8.2 behaviour but controlled with sortkey.

**Comment by AxelGHC** [comment]
This is exactly what I was looking for. I have extended the source code with examples and added a few comments.
```

<html>
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
		<title>Window with transparency?</title>
		<script type='text/javascript' src='https://www.x3dom.org/download/x3dom.js'> </script>
		<link rel='stylesheet' type='text/css' href='https://www.x3dom.org/download/x3dom.css'/>
	</head>
	<body>
		<x3d>
			<scene>
				<!--The next shape in red is created in order to later provide it with holes. To make this possible, the shape must be given a sortkey that is larger than the sortkey of the shapes that represent the hole. In addition, the shape must have at least a slight tranzparency.
				transparency='0.01'
				sortkey='2'
				-->
				<shape>
					<appearance sortkey='2'>
						<material diffuseColor='1 0 0' transparency='0.01'/>
					</appearance>
					<Box size='3,3,0.2'/>
				</shape>
				<!--The next shape represents the first hole. This shape must have the geometry and position of the hole. It must protrude a little beyond the surface of the shape that will contain the hole. Here 0.21 at the hole compared to 0.2 at the previous shape.
				transparency='1'
				sortkey='1'
				-->
				<shape>
					<appearance sortkey='1'>
						<material transparency='1'/>
					</appearance>
					<Box size='1,1,0.21'/>
				</shape>
				<!--The next shape represents the next hole. A cone has been used here.
				-->
				<transform rotation='1 0 0 1.5708'>
					<transform translation='1 0 0'>
						<shape>
							<appearance sortkey='1'>
								<material transparency='1'/>
							</appearance>
							<cone bottomRadius='0.1' topRadius='0.1' height='0.21'/>
						</shape>
					</transform>
				</transform>
				<!--The next two shapes show that you can somewhat place in the holes (The cone in yellow)  and that you can actually look through the holes (sphere in blue).
				-->
				<transform rotation='1 0 0 1.5708'>
					<transform translation='1 0 0'>
						<shape>
							<appearance>
								<material diffuseColor='1 1 0'/>
							</appearance>
							<cone bottomRadius='0.05' topRadius='0.05' height='1'/>
						</shape>
					</transform>
				</transform>
				<transform translation='0 0 -3'>
					<shape>
						<appearance>
							<material diffuseColor='0 0 1'/>
						</appearance>
						<sphere/>
					</shape>
				</transform>
			</scene>
		</x3d>
	</body>
</html> 

```
Thanks again. Axel.

**Comment by andreasplesch** [comment]
Here is a version adapted to the latest x3dom.js

https://gist.github.com/andreasplesch/415d151abee114858c79c20c8c4b49e0#file-boxwithholes183-x3d

https://andreasplesch.github.io/Library/Viewer/index.html?url=https://gist.githubusercontent.com/andreasplesch/415d151abee114858c79c20c8c4b49e0/raw/201e73b4e11c1a77ee65690e5c98e03ac1b40d7e/BoxWithHoles183.x3d

Depthmode readonly='false' will be required.

I also noticed that transparency for the holes needs to be at most 0.9 . If it is higher the holes are ignored, unfortunately.

**Comment by andreasplesch** [comment]
One can adjust the alpha clip threshold to allow fully transparent holes:

https://andreasplesch.github.io/Library/Viewer/index.html?url=https://gist.githubusercontent.com/andreasplesch/415d151abee114858c79c20c8c4b49e0/raw/4c70463321df267b28298462af76b869adbfdfdb/BoxWithHoles183.x3d

**Comment by brutzman** [comment]
Wow this is a powerful technique.  We should think about future extensions for X3D 4.1.

It is possible that node and field additions that are beyond X3D 4.0 might be equivalently expressed using Metadata nodes, permitting backwards compatibility and validity.

**Comment by brutzman** [comment]
![image](https://github.com/x3dom/x3dom/assets/7712992/ce0aa092-079d-4b87-95dc-f687eec05dd2)

**Comment by andreasplesch** [comment]
Here is an updated version with a longer cone to see both the cone and the sphere through the openings:

https://andreasplesch.github.io/Library/Viewer/index.html?url=https://gist.githubusercontent.com/andreasplesch/415d151abee114858c79c20c8c4b49e0/raw/0e8e270901077a2165d9d99b139eab27c10b0584/BoxWithHoles183.x3d

https://gist.github.com/andreasplesch/415d151abee114858c79c20c8c4b49e0#file-boxwithholes183-x3d

**Comment by andreasplesch** [comment]
Fine tuning with an interior wall around one hole:

https://andreasplesch.github.io/Library/Viewer/index.html?url=https://gist.githubusercontent.com/andreasplesch/415d151abee114858c79c20c8c4b49e0/raw/8486c2e6c26e1ebc17b8ba6d1f61f91a68575bf2/BoxWithHoles183.x3d

**Comment by AxelGHC** [comment]
![image](https://github.com/x3dom/x3dom/assets/130909914/62ef93ff-7e53-4f19-a996-beb42c0a5ad1)
If I check in the browser I dont found the interior wall. Please see the screenshot.

**Comment by andreasplesch** [comment]
Hm, for me it looks like this:
![image](https://github.com/x3dom/x3dom/assets/6171115/3dab7dd3-b8a9-4540-b57b-2671fd29c4f6)

**Comment by brutzman** [comment]
outstanding!  perhaps worth a Viewpoint or two.

**Comment by andreasplesch** [comment]
@AxelGHC You may just need x3dom-full.js for extrusion.

**Comment by andreasplesch** [comment]
https://andreasplesch.github.io/Library/Viewer/index.html?url=https://gist.githubusercontent.com/andreasplesch/415d151abee114858c79c20c8c4b49e0/raw/41dedbf7976d5db7242088dbc8b72a3dea72e994/BoxWithHoles183.x3d

has a few oblique Viewpoints.

**Comment by brutzman** [comment]
![image](https://github.com/x3dom/x3dom/assets/7712992/22e27f51-7c41-4fd7-a38f-3bf74c319e37)
![image](https://github.com/x3dom/x3dom/assets/7712992/d5a9acfd-2e34-46c5-905e-be4ca7fc21a4)

**Comment by AxelGHC** [comment]
> Here is a version adapted to the latest x3dom.js
> 
> https://gist.github.com/andreasplesch/415d151abee114858c79c20c8c4b49e0#file-boxwithholes183-x3d
> 
> https://andreasplesch.github.io/Library/Viewer/index.html?url=https://gist.githubusercontent.com/andreasplesch/415d151abee114858c79c20c8c4b49e0/raw/201e73b4e11c1a77ee65690e5c98e03ac1b40d7e/BoxWithHoles183.x3d
> 
> Depthmode readonly='false' will be required.
> 
> I also noticed that transparency for the holes needs to be at most 0.9 . If it is higher the holes are ignored, unfortunately.

If i use 
<script type='text/javascript' src='https://www.x3dom.org/download/x3dom.js'> </script> 
than I dont need this adaptations. 

This is particularly surprising because   `<Depthmode readonly='false' />mode readonly='false' />` is default. Please see:
https://doc.x3dom.org/developer/x3dom/nodeTypes/DepthMode.html

There  x3dom-full.js  is working differnt to x3dom.js. (I do not mean extrusion)

Best regards Axel

**Comment by andreasplesch** [comment]
https://gist.githack.com/andreasplesch/415d151abee114858c79c20c8c4b49e0/raw/2b5061724b348ad89090231e5e709c12645c339f/index182.html

has a version for the current stable release, without Depthmode.

The correct link is https://x3dom.org/release/x3dom-full.js, see https://www.x3dom.org/nodes/

Please also not that html unfortunately needs full closing tags for the x3d nodes.

Depthmode is only used when it is explicitly provided. Otherwise, the best mode is used which varies.

**Comment by AxelGHC** [comment]
I have now prepared an example with two walls each a window:

![image](https://github.com/x3dom/x3dom/assets/130909914/75b9370d-e37d-4564-a81e-94d8f496a0a6)

If I look from the other side I can not see the red wall:

![image](https://github.com/x3dom/x3dom/assets/130909914/c4347183-03ea-4dcc-977a-a7de904b3416)
The code show, I use to group of sortkey. One is group is 4 for red wall, 3 for hole and the other is 2 for green wall 1 for hole:

```
<html> 
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge"/> 
		<title>View through two windows</title> 
		<script type='text/javascript' src=' https://x3dom.org/release/x3dom-full.js'> </script> 
		<link rel='stylesheet' type='text/css' href='https://www.x3dom.org/release/x3dom.css'></link> 
	</head> 
	<script>
  
	</script>
	<body> 
		<h1>View through two windows</h1> 
		
		<X3D>
			<Scene>
		<!--This is the group of a red wall with two holes.
    -->	
			
			
			
				<!--The next shape in red is created in order to later provide it with holes. To make this possible, the shape must be given a sortkey that is larger than the sortkey of the shapes that represent the hole. In addition, the shape must have at least a slight tranzparency.
    transparency='0.01'
    sortkey='2'
    -->
				<Group>
					<Shape>
						<Appearance sortkey='4'>
							<Material diffuseColor='1 0 0' transparency='0.01'/>
						</Appearance>
						<Box size='3,3,0.2'/>
					</Shape>
					<!--The next shape represents the first hole. This shape must have the geometry and position of the hole. It must protrude a little beyond the surface of the shape that will contain the hole. Here 0.21 at the hole compared to 0.2 at the previous shape.
    transparency='1'
    sortkey='1'
    -->
					<Shape>
						<Appearance sortkey='3'>
							<Material transparency='0.9' />
							<Depthmode readonly='false' />
						</Appearance>
						<Box size='1,1,0.21'/>
					</Shape>
				</Group>
				
				<!--The next shape represents the next hole. A cone has been used here.
    -->
				<Transform rotation='1 0 0 1.5708'>
					<Transform translation='1 0 0'>
						<Shape>
							<Appearance sortkey='1'>
								<Material transparency='0.9'/>
								<Depthmode readonly='false' />
							</Appearance>
							<Cone bottomRadius='0.1' topRadius='0.1' height='0.21'/>
						</Shape>
					</Transform>
				</Transform>
				
				
				
<!--This is the group of a green wall with one hole.
    -->				
				
				<Group>
					<Transform translation='0 0 -1.5'>	

						<Shape>
							<Appearance sortkey='2'>
								<Material diffuseColor='0 1 0' transparency='0.01'/>
							</Appearance>
							<Box size='3,3,0.2'/>
						</Shape>
						
						<!--The next shape represents the first hole. This shape must have the geometry and position of the hole. It must protrude a little beyond the surface of the shape that will contain the hole. Here 0.21 at the hole compared to 0.2 at the previous shape.
    transparency='1'
    sortkey='1'
    -->
						<Shape>
							<Appearance sortkey='1'>
								<Material transparency='0.9' />
								<Depthmode readonly='false' />
							</Appearance>
							<Box size='0.5,0.5,0.21'/>
						</Shape>
					</Transform>
				</Group>

				
				<!--The next two shapes show that you can somewhat place in the holes (The cone in yellow)  and that you can actually look through the holes (sphere in blue).
    -->
				<Transform rotation='1 0 0 1.5708'>
					<Transform translation='1 0 0'>
						<Shape>
							<Appearance>
								<Material diffuseColor='1 1 0'/>
							</Appearance>
							<Cone bottomRadius='0.05' topRadius='0.05' height='5'/>
						</Shape>
					</Transform>
				</Transform>
				<Transform translation='0 0 -10'>
					<Shape>
						<Appearance>
							<Material diffuseColor='0 0 1'/>
						</Appearance>
						<Sphere/>
					</Shape>
				</Transform>
			</Scene>
		</X3D>
	</body> 
</html> 
```
Because the sortkey for the hole in the green wall is lower then the sortkey of the red wall the  red wall is hidden by the hole in the red wall.

This is to be expected, but it is a weak point.

**Comment by andreasplesch** [comment]
That sounds correct. The technique is limited. For more complicated situations it will be necessary to provide geometry with holes.

**Comment by andreasplesch** [comment]
#### X3DOM documentation page.
https://x3dom.netlify.app/doc/author/shape/depthmode
https://x3dom.netlify.app/doc/author/shape/appearance
needs improvement: sortkey default constant ? relation to sortMode
 #### List of related references and techniques. If none known, so state.
painters algo.
order independent transparency
 #### Open issues and possible enhancements.
https://github.com/search?q=repo%3Ax3dom%2Fx3dom%20sortKey&type=issues
https://github.com/search?q=repo%3Ax3dom%2Fx3dom+depthmode&type=issues
Allow automatic sorting for opaque/transparent while manual sorting for transparent/opaque
#### Readiness for proposal as X3D 4.0 experimental extension and X3D 4.1 capability.
needs prose, outputOnly/InitOnly ?
#### Additional implementations.
none but check view3dscene

**Comment by AxelGHC** [comment]
If I use the follow code with x3dom 1.8.3 the "windows" not working. If I change to 1.8.2 it works.

The code ist the same x3d like Andreas is using before. Only the htmel around x3d is added.

```
<html> 
   <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/> 
     <title>My first X3DOM page</title> 
     <script type='text/javascript' src='https://www.x3dom.org/download/1.8.3/x3dom-full.js'> </script> 
     <link rel='stylesheet' type='text/css' href='https://www.x3dom.org/download/x3dom.css'></link> 
   </head> 
   <body> 
     <h1>Hello, X3DOM!</h1> 
     <p> 
       This is my first html page with some 3d objects. 
     </p> 
	<X3D>
  <Scene>
   
    <!--The next shape in red is created in order to later provide it with holes. To make this possible, the shape must be given a sortkey that is larger than the sortkey of the shapes that represent the hole. In addition, the shape must have at least a slight tranzparency.
    transparency='0.01'
    sortkey='2'
    -->
    <Shape>
      <Appearance sortkey='2'>
        <Material DEF='red' diffuseColor='1 0 0' transparency='0.01'/>
      </Appearance>
      <Box ccw='true' size='3,3,0.2'/>
    </Shape>
    <!--The next shape represents the first hole. This shape must have the geometry and position of the hole. It must protrude a little beyond the surface of the shape that will contain the hole. Here 0.21 at the hole compared to 0.2 at the previous shape.
    transparency='1'
    sortkey='1'
    -->
    <Shape>
      <Appearance sortkey='1' alphaClipThreshold='0'>
        <Material diffuseColor='1 1 1' transparency='1' />
        <Depthmode readonly='false' />
      </Appearance>
      <Box size='1.5,2,0.21'/>
    </Shape>
    <!--The next shape represents the next hole. A cone has been used here.
    -->
    <Transform rotation='1 0 0 1.5708'>
      <Transform translation='1 0 0'>
        <Shape>
          <Appearance sortkey='1' alphaClipThreshold='0'>
            <Material transparency='1'/>
            <Depthmode readonly='false' />
          </Appearance>
          <Cone bottomRadius='0.1' topRadius='0.1' height='0.21'/>
        </Shape>
      </Transform>
    </Transform>
    <!--The next two shapes show that you can somewhat place in the holes (The cone in yellow)  and that you can actually look through the holes (sphere in blue).
    -->
    <Transform rotation='1 0 0 1.5708'>
      <Transform translation='1 0 0'>
        <Shape>
          <Appearance>
            <Material diffuseColor='1 1 0'/>
          </Appearance>
          <Cone bottomRadius='0.05' topRadius='0.05' height='3'/>
        </Shape>
      </Transform>
    </Transform>
    <Transform translation='0 0 -3'>
      <Shape>
        <Appearance>
          <Material diffuseColor='0 0 1'/>
        </Appearance>
        <Sphere/>
      </Shape>
    </Transform>
    <!-- In the same way it is possible add an interior wall to the hole -->
    <Transform scale='0.5 0.5 0.5' rotation='1 0 0 1.5707'>
      <Shape>
        <Appearance>
          <Material USE='red' />
        </Appearance>
        <Extrusion ccw='false' beginCap='false' endCap='false' crossSection='1.5 2,1.5 -2,-1.5 -2,-1.5 2,1.5 2' spine='0 -0.21 0 0 0.21 0'/>
      </Shape>
    </Transform>
  </Scene>
</X3D>
   </body> 
</html> 
```

**Comment by andreasplesch** [comment]
For HTML you will need full closing tags.
