### ISSUE TITLE
x3dom.org unresponsive

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#1283]
Hopefully just a hiccup.

**Comment by andreasplesch** [comment]
Thanks.

**Comment by tsturm** [comment]
Short update:

It seems there is an issue on the Fraunhofer IGD side.
I will try to reach the right people to get it up again as soon as possible.

**Comment by tsturm** [comment]
Short update #2:

I have reached the right people at the IGD and I'm optimistic that we get the Server up-and-running again until the end of the Day (German Time)

**Comment by tsturm** [comment]
Short update 3:

The Issues with [x3dom.org](https://www.x3dom.org) are bigger than expected and we were not able to solve them today. We will continue tomorrow.

In the meantime, I have uploaded all available versions to my own server:

[https.//www.x3dom.de/download]()

**Comment by andreasplesch** [comment]
Thanks for the continued efforts.

**Comment by tsturm** [comment]
Short update 4:

Unfortunately, it's less of a technical issue and more of a compliance concern on the Fraunhofer IGD side, making it challenging to solve as an external party. However, some important points were addressed today, and we are getting closer to being online again.

I will keep pushing to speed up the procedure.

**Comment by andreasplesch** [comment]
Thanks for the updates.

**Comment by jamesleesaunders** [comment]
I see they are in fact also served from the Netlify https://x3dom.netlify.app/

**Comment by andreasplesch** [comment]
https://x3dom.de/download/ is another option for now. I would recommend self-hosting for stability and control.

**Comment by tsturm** [comment]
Short update 5:

We are in the process of transferring our domains from the current external provider to the official Fraunhofer provider. Currently, we are awaiting the completion of the transfer and the final approval from the compliance department.

Meanwhile, you can safely retrieve the files from: https://x3dom.de/download/. The link points to my own server hosted at a trusted data center in Frankfurt am Main.

**Comment by robert-lipman** [comment]
Will the Netlify link always be available?  Is see that the version is 1.8.3 dev.  Is it also possible to make 1.8.1 and 1.8.2 available there?  I use 1.8.1 in my application because 1.8.2 had some problems with transparency.  It's fixed in 1.8.3 but I would like to have an official release of 1.8.3.  Maybe that's something that could happen with whatever changes are going on now.

**Comment by tsturm** [comment]
You can get 1.8.1 from here:
https://x3dom.de/download/1.8.1/

Official 1.8.3 release is already in preparation

**Comment by paroj** [comment]
> You can get 1.8.1 from here:
https://x3dom.de/download/1.8.1/

I would rather recommend putting that stuff into the github pages part of this repository, which will be available at:
https://x3dom.github.io/x3dom

you can even add static html there and redirect the x3dom.org DNS there as described in the docs. This way you will be mostly independent of whatever goes down at FHG.

**Comment by tsturm** [comment]
Looks like we are back online :blush:

I would be happy to get your opinions on the following Topic to avoid situatiuons like that in the future:
[jsdelivery as CDN](https://github.com/x3dom/x3dom/issues/1285)

**Comment by andreasplesch** [comment]
closed, continued #1285.

**Comment by tsturm** [comment]
Again, not reachable 😞 

It seems that the final Domain & DNS transfer is happening now.

**Comment by tsturm** [comment]
Maindomain is back, subdomains are still in progress.
