### ISSUE TITLE
x3dom release URL change?

### ISSUE THREAD

**Issue by Ph03n1xdust** [x3dom/x3dom#1290]
The [ASE](https://gitlab.com/ase/ase) python library has an option to visualize atomic structures using the x3dom backend, and in the current state it seems to be broken.

Based on their [implementation](https://gitlab.com/ase/ase/-/blob/master/ase/io/x3d.py?ref_type=heads) I am guessing that previously the latest stable x3dom version was always available on the https://www.x3dom.org/x3dom/release/x3dom.js URL and currently this is not the case.

Will this URL be restored in the future, or should the ASE code change to include a different one?
If the ASE code needs to be changed is there a guaranteed URL where the files of the latest releases will be available, like https://x3dom.org/release/x3dom.js?

**Comment by tsturm** [comment]
The official link for getting the latest stable version has always been: https://x3dom.org/release/x3dom.js.

We might have had a special rule for https://www.x3dom.org/x3dom/release/x3dom.js on the x3dom server, but it got lost or forgotten when we moved the server a few weeks ago. I'll check if we can bring back the rule tomorrow.

For the future, we're thinking of using jsdelivr to provide x3dom. You can find more details here: https://github.com/x3dom/x3dom/issues/1285.

**Comment by tsturm** [comment]
@Ph03n1xdust https://www.x3dom.org/x3dom/release/x3dom.js is available again
