### ISSUE TITLE
Zoom Not Working in Examine Mode - Console Message: 'CHECK: in WalkNavigation but nav. type is not walk

### ISSUE THREAD

**Issue by Riddhi-Thanki** [x3dom/x3dom#1310]
I am following the tutorial for [navigation](https://doc.x3dom.org/tutorials/animationInteraction/navigation/index.html), specifically focusing on the examine mode. However, I am experiencing an issue where zooming in or out does not function as expected. Attempting to zoom in or out triggers the following message in the console:

Console message:
`#### CHECK: in WalkNavigation but nav. type is not walk !`

**Comment by andreasplesch** [comment]
Thanks, I see that as well, and switching to turntable mode has the same issue. Pressing the 'e' key rather than selecting the mode from the menu still works, however. Investigating.

**Comment by andreasplesch** [comment]
The runtime methods still worked as well.

There was an issue with handling changes to the type field which is addressed in a [new dev. version](https://andreasplesch.github.io/x3dom/dist/x3dom-full.debug.js). Please note that https://doc.x3dom.org/tutorials/animationInteraction/navigation/index.html will not be updated for a while.

So you can use the runtime methods to change navigation modes, or use the dev. version if you want to use changes to the type attribute.

**Comment by andreasplesch** [comment]
Please reopen as appropriate.
