### ISSUE TITLE
SFMatrix4f() documentation for setRotation and translation

### ISSUE THREAD

**Issue by Sheeban-Wasi** [x3dom/x3dom#1322]
Hi everyone,

I need some help with a 3D transformation problem in X3D. Specifically, I'm trying to rotate a hit point around the origin by 90 degrees around the positive x-axis, then translate it by a given offset. Here’s what I'm aiming to do:

1. Rotate the hit point by `1 0 0 1.57079632679` (90 degrees around the x-axis).
2. Translate the rotated hit point by `(440000, 3670000, 0)`.

Here’s a pseudocode illustrating the steps:

```
// Step 1: Define the hit point
SFVec3f hitp = new SFVec3f(x, y, z); // our hit point from X3D

// Step 2: Define the rotation (90 degrees around the x-axis)
SFRotation myRot = new SFRotation(1, 0, 0, 1.57079632679);

// Step 3: Define the translation
SFVec3f myTrans = new SFVec3f(440000, 3670000, 0);

// Step 4: Create the rotation matrix and set the rotation
SFMatrix4f rotMat = new SFMatrix4f();
rotMat.setRotation(myRot);

// Step 5: Create the translation matrix and set the translation
SFMatrix4f transMat = new SFMatrix4f();
transMat.setTranslation(myTrans);

// Step 6: Apply the rotation to the hit point
SFVec3f locR = rotMat.multMatrixVec(hitp);

// Step 7: Apply the translation to the rotated point
SFVec3f locT = transMat.multVecMatrix(locR);
```

Could anyone guide me on this?

Thanks in advance for your help!

**Comment by npolys** [comment]
hm

YES
 It seems there is only a bit of documentation  


eg
https://doc.x3dom.org/tutorials/animationInteraction/transformations/index.html
________________________________
From: Sheeban ***@***.***>
Sent: Wednesday, June 19, 2024 12:38 AM
To: x3dom/x3dom ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [x3dom/x3dom] SFMatrix4f() documentation for setRotation and translation (Issue #1322)


Hi everyone,

I need some help with a 3D transformation problem in X3D. Specifically, I'm trying to rotate a hit point around the origin by 90 degrees around the positive x-axis, then translate it by a given offset. Here’s what I'm aiming to do:

  1.  Rotate the hit point by 1 0 0 1.57079632679 (90 degrees around the x-axis).
  2.  Translate the rotated hit point by (440000, 3670000, 0).

Here’s a pseudocode illustrating the steps:

// Step 1: Define the hit point
SFVec3f hitp = new SFVec3f(x, y, z); // our hit point from X3D

// Step 2: Define the rotation (90 degrees around the x-axis)
SFRotation myRot = new SFRotation(1, 0, 0, 1.57079632679);

// Step 3: Define the translation
SFVec3f myTrans = new SFVec3f(440000, 3670000, 0);

// Step 4: Create the rotation matrix and set the rotation
SFMatrix4f rotMat = new SFMatrix4f();
rotMat.setRotation(myRot);

// Step 5: Create the translation matrix and set the translation
SFMatrix4f transMat = new SFMatrix4f();
transMat.setTranslation(myTrans);

// Step 6: Apply the rotation to the hit point
SFVec3f locR = rotMat.multMatrixVec(hitp);

// Step 7: Apply the translation to the rotated point
SFVec3f locT = transMat.multVecMatrix(locR);


Could anyone guide me on this?

Thanks in advance for your help!

**Comment by npolys** [comment]
Sorry that was sent prematurely;
 the documentation of methods on the X3D Data Types is indeed missing or hard to find...

So likely, it is worth opening an issue on git hub...

Any secret links somwhere  to the 3D math classes being used 🙂 ?


Specifically, docs about X3DOM support for the math functions listed in

https://web3d.org/documents/specifications/19777-1/V3.3/Part1/functions.html#FieldServices

with best regards,
 _nicholas

________________________________

**Comment by andreasplesch** [comment]
Just saw this.

The methods for the field types are defined and documented in:

https://github.com/x3dom/x3dom/blob/master/src/fields.js

This includes most field service functions, and many others. 

You could use matrix4f.fromRotationTranslationScale(rotation, translation, scale);

Since x3dom uses exclusively quaternions to represent rotations, rotation here is a quaternion.

So something like this:
```js
rot90 = x3dom.fields.Quaternion.parseAxisAngle("1, 0, 0, 1.57");
trans = new x3dom.fields.SFVec3f(440000, 3670000, 0);
mat = x3dom.fields.Matrix4f.fromRotationTranslationScale(rot90, trans);
locT = mat.multMatrixPnt(hitp);
```

 I think you need to use multMatrixPnt.

There are many other ways as well (mat.setTranslate, mat.setRotate(quat), mat.parseRotation(axisangle),mat.rotationX ..)

Since the translation looks like UTM coordinates you may also consider geospatial component nodes.

If there is a simple live example that always helps as well.

**Comment by andreasplesch** [comment]
SFRotation field methods are also available but less well tested.

SAI code may look like this:

```
SFRot90 = x3dom.fields.SFRotation(1, 0, 0, 1.57);
locR = SFRot90.multiVec(hitP);
trans = new x3dom.fields.SFVec3f(440000, 3670000, 0);
locT = locR.add(trans);
```

**Comment by andreasplesch** [comment]
Please reopen as necessary. Closing for now
