### ISSUE TITLE
TypeError at x3dom.reload() 

### ISSUE THREAD

**Issue by sankho-t** [x3dom/x3dom#140]
I have just loaded a page with X3D on it, it displays fine, and when I do a `x3dom.reload()`, I get the error `TypeError: can't convert undefined to object` at `x3dom.js`. 

If I change the contents of a node using `innerHTML` the change isn't visible after doing the call.

**Comment by rahilwazir** [comment]
How do I reload individual `x3d` element? I have two x3d scenes in my page
