### ISSUE TITLE
Clipping / Transformation of VolumeData node

### ISSUE THREAD

**Issue by mlimper** [x3dom/x3dom#231]
There seems to be an issue with the x3dom VolumeData node, which causes an unexpected behaviour when zooming into the model:

http://x3dom.org/x3dom/example/x3dom_volrenOpacityTestTF_aorta.xhtml

I have realized that clipping planes are set up manually in this example. However, removing the whole viewpoint node does not change anything, so I guess it's more complicated^^

Another issue is the transform node above the volumeData node: it looks like it wouldn't work, at least with scaling: If I want to scale the volumeData node, the planes are somehow spread over the scene.

A least question at the people who took the time to implement this node:
I saw that the VolumeData node is not a shape node, but it seems to somehow replace the role of the shape in that context... or not? :-) Is it intentionally like that?
There is also this comment in "VolumeRendering.js" on the "ColorBox" node, which seems to be used by VolumeData:

//FIXME: Not a real X3D Node but auxiliary geometry

Can this workaround already be the reason for the weird transform and clipping behavior?

**Comment by aarbelaiz** [comment]
This issue was resolved with pull request #339, and it can be closed.
