### ISSUE TITLE
Extrusion caps not working

### ISSUE THREAD

**Issue by chrstein** [x3dom/x3dom#341]
For rather complex cross-sections the extrusion caps are not generated correctly.

http://x3dom.org/x3dom/test/functional/extrusion.html shows two problematic cases.

Originally, for extrusions with clockwise oriented cross-section vertices the cap 
polygons were created "outside" of the geometry. This was fixed by inverting the list of vertices depending on the "ccw" flag. 

However, this didn't solve the problem for the second case, were the cap simply does not fill the whole cap surface.

![extrusion](https://cloud.githubusercontent.com/assets/2564424/2888867/ce2b500c-d512-11e3-856d-1a4ae7917009.png)

This seems to be resulting from problems in the algorithms of EarClipping.js.

**Comment by andreasplesch** [comment]
issue #379 has a similar issue with an indexedfaceset.

**Comment by andreasplesch** [comment]
fixed: https://rawgit.com/x3dom/x3dom/master/test/functional/extrusion.html
