### ISSUE TITLE
Transparency above 0.9 makes shapes compeletely transparent

### ISSUE THREAD

**Issue by mabuchner** [x3dom/x3dom#391]
Transparency above 0.9 makes shapes completely transparent.

Here is an example:
https://gist.github.com/mabuchner/21ab60134e62929cb1bd

The box in the center has a material transparency of 0.9 and is visible quite clearly.
The box on the right has a material transparency of 0.91 and is suddenly completely invisible.

If I open the same X3D scene with the Instant Player, the box on the right is visible.

**Comment by nikakhov** [comment]
Is there any way to increase the threshold above 0.9?

**Comment by tsturm** [comment]
I've added an 'alphaClipThreshold'-Attribute to the Appearance-Node so you can edit the default threshold.

For example:

```
<Appearance alphaClipThreshold="0.0">
    ...
</Appearance>
```

**Comment by mabuchner** [comment]
Thanks for taking care of the problem, but wouldn't it be better to change the default threshold instead of introducing an obscure non-standard attribute?

**Comment by mlimper** [comment]
I think it's better to provide a dynamical threshold - which threshold would be the right one for everyone?

**Comment by mabuchner** [comment]
1 - (1 / 255) = 0.9960784313725490196078431372549

**Comment by nikakhov** [comment]
Will the alphaClipThreshold be removed?
