### ISSUE TITLE
Interpolator for MFFloat

### ISSUE THREAD

**Issue by ajcyeh** [x3dom/x3dom#398]
Hi All,

In X3D there seems no interpolator that outputs MFFloat. (or have I missed any?)
Could this be considered as a feature request and implemented as an extension of X3DOM?

The reason is that I would like to animate the ElevationGrid's height but could not find the interpolator to do so. Any ideas?

Thanks,

Andy

**Comment by andreasplesch** [comment]
While such a node could be very useful, it is not part of the x3d standard and I am not sure how far x3dom wants to deviate from it. On the other hand Instant Reality has it ..
It is unusual that the number of keys determines the dimension of the interpolated vector. It would be worth to have a log warning message if the number of keyvalues is not divisble by the number of keys.
The inital reparsing of the MFFloat field into an array of MFFloats probably should be in the nodeChanged method to ensure that it is done when such a node gets added later.
Also, I think it is an accident that MFFloat accepts MFFloats as values. It should just accept SFFloats. So you could just use a regular JavaScript array but then just provide your own interp function.
Follow the instructions on how to prepare a pull request (clone, commit, test, commit, PR). Then it is much easier for x3dom to decide what to do with it.
