### ISSUE TITLE
Firefox is crashing

### ISSUE THREAD

**Issue by Sharian** [x3dom/x3dom#422]
Hi, 

I can force Firefox (and Chrome on Android Devices) to crash by loading our website: 

http://www.cuttlefish.de/index/simulation/

multiple times. 

We reduced the problem by using low poly models and compressed textures and I am not really sure this is a x3dom problem as it might be a problem with firefox itself. 

This can be reproduced using a virtualbox virtual machine (in my case running Ubuntu 32bit with 128 MB video memory and enabled 3d acceleration) and opening the given URL two or three times. 

It is possible to reproduce this with your Siena example.  

I'm getting the following error in Ubuntu on the console: 
`out of memory: 0x[random numer] bytes requested
ExceptionHandler::GenerateDump waitpid failed: No child processes`

Shortly before the crash: 

 320 ── webgl-buffer-count
    8.54 MB ── webgl-buffer-memory
          4 ── webgl-context-count
          4 ── webgl-renderbuffer-count
    1.15 MB ── webgl-renderbuffer-memory
         32 ── webgl-shader-count
         80 ── webgl-texture-count
  657.54 MB ── webgl-texture-memory

I think this is a third party issue but maybe something can be done to prevent this? Exceeding the texture memory is causing this I think.

**Comment by Sharian** [comment]
You can use chrome://memory-redirect/ to have a look at the memory usage of each browser. Firefox is listed there and even Internet Explorer :)

**Comment by mlimper** [comment]
Wow, very cool! Thanks for sharing!
