### ISSUE TITLE
Strange rendering of semi-transparent mesh

### ISSUE THREAD

**Issue by pavelvasev** [x3dom/x3dom#437]
Dear colleagues!

I used IndexedTriangleSet to create, for example, the sphere, and set it's transparency to 0.5.
And then I have very strange artifacts.

You can see it here, by rotating with mouse:

http://svn.lact.ru:8888/inline?src=http://svn.lact.ru:4567/files/visual/2014-10-23/2014-10-23-at-18-26-24.jpg.x3d

Could you tell me what I am doing wrong?

**Comment by gwgill** [comment]
> So, to conclude, my recommendation is to re-think your concept of rendering (not
> use transparency, fake it somehow via making the canvas transparent or so) or to
> make all of your objects closed surfaces.

I'm afraid this to me translates into "X3DOM is not ready for prime time yet". It's predecessors such as the vrml Cosmo plugin, and alternatives such as view3dscene don't seem to have these rendering problems with transparency. So I think that fixing such problems is pretty important in making X3DOM a viable choice for 3D in the browser.

**Comment by pavelvasev** [comment]
> I fear it’s not so easy to “fix” this issue. This is really deeply connected to very essential parts of the rendering pipeline.

Maybe it is not. In SceneJS there is a trick: user can specify rendering priority for objects. This lowers the issue greatly. Also, it is not big deal for user to specify such priorities (at least in cases which I met).

**Comment by gwgill** [comment]
Pavel Vasev wrote:

> Maybe it is not. In SceneJS there is a trick: user can specify rendering priority for
> objects. This lowers the issue greatly. Also, it is not big deal for user to specify
> such priorities (at least in cases which I met).

I get the impression that this won't help at all when there are two transparent
inter-penetrating indexed face set objects - the whole set appears to be affected
by the rendering priority, not each polygon that makes up the set, and the priority
needed changes with viewing direction and the part of the set that is visible first.

Presumably the renderer should be sorting each transparent primitive (e.g. polygon)
by depth, including breaking them up into smaller non-intersecting primitives if
they intersect.

Graeme Gill.

**Comment by mlimper** [comment]
Let's get back one steps before making such claims as "x3dom is not ready for use" :D

There are quite some projects using x3dom with transparent objects.

X3dom already sorts ovjects by depth. There are also things such as the depthMode node and the sortKey Attribute, helping if you want to specify an order in your own.

Analysing and cutting geometry dynamically seems not feasible to me: JS has limited performance, and this will get complex and slow. And what about moving objects? Etc.

There are approaches like order-independent transparency, but those are pretty recent and the quality oft results differs from sorted rendering. We can check this.

But I highly doubt that Cosmo Player vor SceneJS do a better job than x3dom currently dies, given that you are using it the correct way.

**Comment by pavelvasev** [comment]
> I get the impression that this won't help at all 

It helped in my cases. (Intersecting objects was not the case.)

> X3dom already sorts ovjects by depth. There are also things such as the depthMode node and the sortKey Attribute, helping if you want to specify an order in your own.

Ok, I missed that. Thank you!

**Comment by mlimper** [comment]
> Ok, I missed that. Thank you!

You're welcome. You made me realize that this topic (rendering transparent objects, using depthMode and sortKey to tweak rendering order, ...) is missing in the current tutorials. We should add one on these topics.

**Comment by gwgill** [comment]
Max Limper wrote:

> There are quite some projects using x3dom with transparent objects.

Sure, and my project is one of them, and X3DOM is not very satisfactory at the moment.

> X3dom already sorts ovjects by depth. There are also things such as the depthMode node
> and the sortKey Attribute, helping if you want to specify an order in your own.

But this is not necessary with other 3D renderers.

> There are approaches like order-independent transparency, but those are pretty recent
> and the quality oft results differs from sorted rendering. We can check this.

Renderers like view3dscene don't appear to have these problems.

> But I highly doubt that Cosmo Player vor SceneJS do a better job than x3dom currently
> dies, given that you are using it the correct way.

See attached.

First and second are x3dom with a slight change in viewing angle -
the (mostly) inner object suddenly "pops" and and becomes much whiter, and you
can no longer see the surface color. This is with "<DepthMode
readOnly='true'></depthMode>" hack within appearance. Without that, things are worse - see
x3dom3.jpg.

Third is view3dscene - no such artifact occurs, no matter how much you change
the view.

x3d file is here: <http://www.argyllcms.com/test.x3d>

Graeme Gill.

**Comment by gwgill** [comment]
> See attached.

Since these files seem to have been stripped from my reply,
I've put them here:

<http://www.argyllcms.com/x3dom1.jpg>
<http://www.argyllcms.com/x3dom2.jpg>
<http://www.argyllcms.com/view3dscene.jpg>
<http://www.argyllcms.com/x3dom3.jpg>

Graeme Gill.
