### ISSUE TITLE
Viewpoint orientation

### ISSUE THREAD

**Issue by ajcyeh** [x3dom/x3dom#451]
Hi All,

I tried: 

console.log(X3D.runtime.getActiveBindable('viewpoint').getFieldValue('position'));
It returns a x3dom.fields.SFVec3f object as expected.

However, if 
console.log(X3D.runtime.getActiveBindable('viewpoint').getFieldValue('orientation'));
It returns "undefined" instead of a SFRotation object. Is that a bug?

Thanks,

Andy

**Comment by tsturm** [comment]
Should be fixed with my last commit.
