### ISSUE TITLE
Cannot Fly beneath elevation values of 0 with GeoViewpoint

### ISSUE THREAD

**Issue by MBARIMike** [x3dom/x3dom#453]
Some use cases require navigating below the surface of the Earth, e.g. oceanographic data visualization.

The current implementation of the GeoViewpoint node does not allow this. To demonstrate, view this example:

https://2102f9aeddfada7ec704a18780238f078f1d50b6.googledrive.com/host/0BwIhFzkLaQ9XbVRFek4wQW9xdFk/GeoviewpointExample_GeospatialCoordinateAxesNsew.html

switch to Fly mode with the 'F' key and hold down the left mouse button while pointing to at a place on the model of the Earth. The viewpoint never goes below the surface (elevation=0). The behavior appears to be the same with  the default value of elevationScaling='true' and with elevationScaling='false'.

A comment in the code (at line 344 in src/nodes/Geospatial/GeoViewpoint.js):

    // at 10m above ground a speed of 1 sounds about right; make positive if below ground

does not seem to be borne out by the implementation.

I can imagine use cases where the content author would want to restrict where viewpoints can end up. Perhaps an optional attribute, say "restrictElevations='positive|negative'", would be a good idea for handling these use cases...

**Comment by andreasplesch** [comment]
Should be resolved by:

https://github.com/x3dom/x3dom/pull/461
