### ISSUE TITLE
text justification problem

### ISSUE THREAD

**Issue by mvidiassov** [x3dom/x3dom#460]
It seems text justification is broken in x3dom.

With the dev version the model
http://www2.iaas.msu.ru/tmp/u3d/justify.xhtml
has all text shown as centered.
But the same model
http://www2.iaas.msu.ru/tmp/u3d/justify.x3d
is shown with text adjusted as intended in InstantPlayer, H3DViewer
and view3dscene.

Is that a bug or a missing feature?

**Comment by andreasplesch** [comment]
Should be fixed with the latest dev. version. Is it ?

**Comment by mvidiassov** [comment]
Yes it is.
