### ISSUE TITLE
Converter Script

### ISSUE THREAD

**Issue by ibuilder** [x3dom/x3dom#466]
Is there any documentation on how I can write a conversion script?

I want to convert a revit file (http://usa.autodesk.com/adsk/servlet/index?siteID=123112&id=2484975)

into x3dom automatically.  I  understand there is an online conversion script as a binary file which can be used, but was wondering if there was a bit more documentation on how it works if I wanted to make one in PHP or Ruby.

**Comment by cecilemuller** [comment]
You could use the commandline tool `aopt` (see [Offline Transcoding](http://www.x3dom.org/?page_id=532)) to convert VRML to X3DOM:
Example:

```shell
aopt -i myfile.wrl -N converted.html
```

If you want to call it from PHP, you could use [shell_exec](http://php.net/manual/en/function.shell-exec.php) to run the command.

**Comment by chintanp** [comment]
But to how to convert .rvt file to vrml ?

**Comment by mlimper** [comment]
-w instead of -N
