### ISSUE TITLE
SSAO sometimes fails on chrome 40

### ISSUE THREAD

**Issue by simonthum** [x3dom/x3dom#468]
Hi,

I'm on Chrome Version 40.0.2214.94 Win x64, and I observe that recently SSAO (in my scene and the example  http://doc.x3dom.org/tutorials/lighting/ssao/example.html ) does not work reliably.

It works well on Firefox and a fresh instance of Chrome, but it seems that after some time (multiple x3dom/webgl sessions open and close) the SSAO  on chrome degresses into a darker scene, again reliably.

The net effect in the example scene is that the radius slider is ineffectual and the amount just makes the whole scene darker.

This obviously points to chrome but you might want to have a second look.

![image](https://cloud.githubusercontent.com/assets/580723/6056760/eae06a94-ad15-11e4-8bfd-ddc392e93e2e.png)

**Comment by simonthum** [comment]
A lighter view:

![image](https://cloud.githubusercontent.com/assets/580723/6056774/12229780-ad16-11e4-899d-0615db76962c.png)

**Comment by simonthum** [comment]
I'm now on Chrome Version 40.0.2214.115 m and if fails reliably, so far.

**Comment by mlimper** [comment]
Thanks!
I'm using Chrome 40.0.2214.111 on Linux, this works nicely.

So, I guess there is something that has changed in ANGLE or so, could be a problem that only occurs for DirectX... hm, how do we proceed now?

Maybe we could try to track down the matching changelog for Chrome on Windows?
I think it worked on Chrome for Windows when we had the last X3DOM release, which was

December 18th, 2014

You submitted the ticket on

February 5th, 2015

Question now: Where can the release notes for the stable channel of Chrome on Windows be found?
I was just doing a google search and ended up here:
http://googlechromereleases.blogspot.de/

But I can't find stable channel release notes... maybe I gotta seach again. Some pointers?

**Comment by bhaettasch** [comment]
I just checked with the Chrome Canary Version 43.0.2315.0 to find the same problem. Thus the bug is still present in the current codebase of chrome/chromium.

I also inspected the changelogs between December 18th and February 5th, the only one dealing with 3D and (web-)graphics is this the update to Chrome 40.0.2214.91. The changelog for this release can be found here:
https://chromium.googlesource.com/chromium/src/+log/39.0.2171.0..40.0.2214.0?pretty=fuller&n=10000

**Comment by mlimper** [comment]
Thanks for posting, seems very useful. There are quite some WebGL related changes in the log.
Do we get any error messages on the Chrome console?

**Comment by simonthum** [comment]
Thanks for the analysis! Note that it might be that it did not work reliably before but went unnoticed. The change in the log does not seem indicative to me, but it might just be the chage that tipped chrome into predictable failure.

**Comment by tsturm** [comment]
@simonthum: Can we close this issue?
It seems the bug is no longer present in the latest Chrome version.

**Comment by simonthum** [comment]
Fine by me.

**Comment by danpaulsmith** [comment]
Very broken on Version 56.0.2924.87 (64-bit). Intel Iris Pro 1536 MB graphics. Macbook Pro. OSX 10.12.3 (16D32).

http://alteredqualia.com/three/examples/webgl_postprocessing_ssao.html
