### ISSUE TITLE
Append x3d at runtime

### ISSUE THREAD

**Issue by clement-igonet** [x3dom/x3dom#469]
Hi,

   I'm looking for a way to append x3d data at runtime.

   Example: at first, I use static inline method with an external file called (sceneBegin.x3d) and later, at runtime, I'd like to append some other part of the whole scene using external files (xxx01yyy02zzz.x3d) dynamically produced at runtime by a server.

   I'm lost. How can I do it?

Clement

**Comment by doczoidberg** [comment]
Just change the url attribute.

**Comment by clement-igonet** [comment]
Well, thanks for your answer.
I must try this solution. I though it re-initializes all the scene with an empty canvas when reloading a lot of data...
Here is my static application: http://web/osm2x3d.net
I hope I'll be able to "dynamize" it.

**Comment by doczoidberg** [comment]
I am not sure what you want to do exact. The url does not work.

your structure should be something like:
```
<x3d id="the_element">      
     <scene>
         <inline id="myElement" url="myurl" ></inline> ....
```

you can then add more inline nodes via javascript

**Comment by clement-igonet** [comment]
"you can then add more inline nodes via javascript"
Could you give me more precision or an example?

My situation in the following one:
I have a tool (home made in C++) that convert osm data (xml OpenStreet Map) to x3d format.
It would be very useful to be able to dynamically inject data as x3d format in my x3dom scene.

**Comment by doczoidberg** [comment]
I think you should learn more about javascript, DOM manipulation and web development in general?
For adding a node to the DOM you can use for example jQuery:
```
$('scene').append('<inline url="newurl" />');
```

**Comment by clement-igonet** [comment]
OK, I will try in that way.
Thanks guy!

**Comment by doczoidberg** [comment]
sorry, I have other work to do. Good luck with your project

**Comment by clement-igonet** [comment]
So, this should work:
```
<div id="container">
    <X3D showlog="true" showstat="false">
        <scene id="scene">
        </scene>             
    </X3D>
</div>     
<script>
    document.onload = function () {
        $('scene').load('<inline nameSpaceName="myX3d" url="result.x3d"></inline>');
        x3dom.reload();
    }
</script>
```
But nothing appends...
Do you see something wrong?

**Comment by mlimper** [comment]
Dunno what exactly the jquery load function does in this case - just to make sure, can you open a DOM element inspector (from Chrome's built-in developer tools, for example) and make sure that the HTML elements within the x3d scene look exactly the same for both cases (with dynamic insertion and without).

**Comment by doczoidberg** [comment]
you need the `append` function and add the jquery src

**Comment by clement-igonet** [comment]
Here is my starting point:
```
            document.onload = function () {
                inline = document.createElement('inline');
                inline.setAttribute('nameSpaceName', 'myX3d');
                inline.setAttribute('url', 'result.x3d');
                scene.appendChild(inline);
            }
```
It works. No need to reload. Thank you.

Now, if I use load() or append() jquery functions on $(#scene), must I reload the x3d scene with a x3dom.reload() ?
When does this reload is necessary?

What should I do if I want to use the the result of a php page
-> osm2x3d.php?ll_lon=21.000296045787998&ll_lat=52.225164674354126&ur_lon=21.015659739025814&ur_lat=52.23147339923343
instead of on existing file
-> result.x3d
???

**Comment by mlimper** [comment]
Great to hear that it works with the standard DOM method!

I'm not exactly sure at which point the reload is necessary - only thing I can tell is that it doesn't have anything to do with any particular DOM manipulation method (jquery, standard DOM API, ...).

I don't know much about php... If you don't mind, I'll close the ticket now, as it seems the X3DOM-related part has been resolved.
