### ISSUE TITLE
x3dom.BinaryContainerLoader.setupBinGeo and Context.prototype.renderShape is using the number of vertices to calculate the number of faces and the number of draw elements

### ISSUE THREAD

**Issue by techkey** [x3dom/x3dom#472]
The vertex count is used to calculate the number of faces in some places, e.g. in file `BinaryContainerSetup.js` around line 397:
```javascript
            for (var i=0; i<geoNode._vf.vertexCount.length; i++) {
                if (shape._webgl.primType[i] == gl.TRIANGLE_STRIP)
                    geoNode._mesh._numFaces += geoNode._vf.vertexCount[i] - 2;
                else
                    geoNode._mesh._numFaces += geoNode._vf.vertexCount[i] / 3;
            }
```
That works ONLY if the number of vertices is the same as the number of indices.

The vertex count is used to determine the number of element in draw calls, e.g. in file `gfx_webgl.js` around line 2498:
```javascript
                if (s_gl.binaryGeometry > 0 || s_gl.popGeometry > 0) {
                    for (v = 0, offset = 0, v_n = s_geo._vf.vertexCount.length; v < v_n; v++) {
                        gl.drawElements(s_gl.primType[v], s_geo._vf.vertexCount[v], s_gl.indexType,
                                        x3dom.Utils.getByteAwareOffset(offset, s_gl.indexType, gl));
                        offset += s_geo._vf.vertexCount[v];
                    }
                }
```
And again, this ONLY works if the number of vertices is the same as the number of indices.

A rectangle for example can be described with 4 vertices and 6 indices using triangles, the vertex count and index count almost never have to be the same.

I've made some quick modifications to a local test setup to use the index counts and that works good. So my question is if it's by design that the vertex count and index count must be the same?

**Comment by yjung** [comment]
As far as I remember vertexCount in fact means index count in case of indexed rendering, just the naming is misleading.

**Comment by techkey** [comment]
Look what happens to a rectangle described with 4 vertices and 6 indices, `geoNode._vf.vertexCount[0]` is already set:
![image6](https://cloud.githubusercontent.com/assets/670271/6261482/9a453340-b822-11e4-9eea-daab893c7088.png)
And here the wrong calculation happened:
![image4](https://cloud.githubusercontent.com/assets/670271/6261378/df619308-b820-11e4-8fb0-b87980cd2f76.png)
And here `s_geo._vf.vertexCount[v]` is used as the number of elements to draw, which should be 6 instead of 4:
![image5](https://cloud.githubusercontent.com/assets/670271/6261443/b36ad48e-b821-11e4-8fc6-a6b5c266c113.png)
And visual:
![image3](https://cloud.githubusercontent.com/assets/670271/6261384/eb465fd2-b820-11e4-9c8e-07ba3db23cd9.png)
As can be seen on the screen shots there are indeed 4 vertices and 6 indices.

Even if the intention was to let `geoNode._vf.vertexCount[0]` hold the number of indices then the below code, which is on line 388 from the file `BinaryContainerSetup.js`, makes sure that it not happens:
```javascript
            if (geoNode._vf.vertexCount[0] == 0)
                geoNode._vf.vertexCount[0] = indexArray.length;
```
Because `geoNode._vf.vertexCount[0]` is already set to the number of vertices, which is 4.
And further on the code on line 397 makes sure that we get a wrong calculated number of faces:
```javascript
            for (var i=0; i<geoNode._vf.vertexCount.length; i++) {
                if (shape._webgl.primType[i] == gl.TRIANGLE_STRIP)
                    geoNode._mesh._numFaces += geoNode._vf.vertexCount[i] - 2;
                else
                    geoNode._mesh._numFaces += geoNode._vf.vertexCount[i] / 3;
            }
```
The outcome of `geoNode._vf.vertexCount[0]` (4) / 3 is 1.3333333333333333

One can imagine what happens with larger objects.

**Comment by yjung** [comment]
Your argumentation seems wrong. As said, in the case of indexed rendering the variable must provide the number of indices, here 6.

**Comment by techkey** [comment]
@yjung Which argument is wrong, which variable and can you please provide a example like I did?

**Comment by yjung** [comment]
Your way to argument - I said before you need to use the number of indices instead. Using aopt you can easily create an example yourself, here is a tutorial: http://doc.x3dom.org/tutorials/models/aopt/index.html
Good luck...

**Comment by techkey** [comment]
I know aopt inside and out and the structures it creates. aopt uses the number of indices to fill the vertexcount in the x3d that it creates. That's also not the correct way to do it. If aopt does something not correct that makes it right to use the incorrection over and over again? If you like to use such code that's up to you. But thank you for your responses. Anyway, I'm not talking about aopt, it's the code I've shown that I'm talking about.

**Comment by yjung** [comment]
It is the correct way to do it and your code is incorrect as it obviously ignores both.
