### ISSUE TITLE
Strange behaviour with shadows

### ISSUE THREAD

**Issue by mikolaskova** [x3dom/x3dom#477]
Hello,

I want to model a building and inside lights. But there are problems with the shadow... I attached two screenshots a) how it should look like (rendered scene in blender) and b) how it looks (x3d, x3dom in browser).
![how_should_look_like](https://cloud.githubusercontent.com/assets/10045367/6616002/b0a50e20-c8a9-11e4-98c8-9eb21abef262.png)
![how_looks_in_browser](https://cloud.githubusercontent.com/assets/10045367/6616003/b3e49236-c8a9-11e4-8bbc-148a817c3925.png)

The light is casting to all sides, not only through the open side of the cube...

Below I'm posting the code of the Lamp and the Cube...

Thanks for any help, how to achieve the light casting out only one side...

Sometimes, with newly built cubed, it works fine, often with models from elsewhere there is similar strange behaviour as here. I don't know on what this depends (how I should treat my models to achieve the expected shadows)

Regards

Adriana

**Comment by tsturm** [comment]
Hi,

i've build a simple test scene in 3ds max and export it to x3d.
The results look like expected.

![unbenannt](https://cloud.githubusercontent.com/assets/864076/6622443/e9b0fcbe-c8dc-11e4-80bd-94f29b1d1942.PNG)

Can you post the code of your scene?

Regards
Timo

**Comment by mikolaskova** [comment]
thank you for testing! the code of the x3d is here: http://www.mikolaskova.cz/downloads/fensterraum.x3d

**Comment by tsturm** [comment]
It seems your Scene is very small and some of the parts of your building fall out of the lightprojection frustum. If I scale up your complete scene a little bit (e.g. scale="5 5 5") it looks correct.

![shadowbug](https://cloud.githubusercontent.com/assets/864076/6637052/0d43cad2-c976-11e4-80fd-db85fe7b00ac.PNG)

**Comment by mikolaskova** [comment]
Thank you very very much! I
