### ISSUE TITLE
Angular

### ISSUE THREAD

**Issue by doczoidberg** [x3dom/x3dom#478]
I have troubles from time to time using Angular with x3dom.

Any ideas why this works:
  `<transform translation="{{x}} {{y}} {{z}}" >`

and this not:
```
<shape>
   <triangleset>
      <coordinate point="{{x1}} {{y1}} {{z1}} {{x2}} {{y2}} {{z2}} {{x3}} {{y3}} {{z3}}" ></coordinate>
   </triangleset>
</shape>
```

In a more complex case I get the webgl errors:
`[.WebGLRenderingContext]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0`
                                                 
F12 DOM tools show the bound values also in the second case. There must be different updating routines?

**Comment by doczoidberg** [comment]
seems to work with a simple example...

http://jsfiddle.net/U3pVM/13992/

**Comment by doczoidberg** [comment]
seems that this is more an angular problem/issue with x3dom than the other way around.

When using  `ng-attr-point` attribute it works also in more complex examples.

**Comment by mlimper** [comment]
thanks for reporting, this insight could also be helpful for other x3dom / angular users.
