### ISSUE TITLE
X3DOM Lighting Error

### ISSUE THREAD

**Issue by MakaziMtingwa** [x3dom/x3dom#479]
I am having a problem with lights when I change models using an `<Inline>` node.  Dr. Behr indicated that there was a bug 3 years ago (http://sourceforge.net/p/x3dom/mailman/message/28957252/). 

Has this been addressed, or have I stumbled across a new problem?

In the example, http://3dprint.nih.gov/discover/3dpx/001107/x3d, I load an X3D scene and using Javascript update the `<inline>` tag's url attribute.  Reloading either the `<x3d>` or `<inline>` element clears the old model but not the old lighting.  What results is a new brighter model, which adds new lights per Javascript update.

I'm using the following Javascript reloadX3D function…
```
function reloadX3D(x3d_file) {
  var x3dscene = document.getElementById("display");
  x3dscene.setAttribute("url",x3d_file);
  x3dscene.runtime.showAll();
}
```

The reloadX3D function works with the corresponding HTML code…
```
<X3D xmlns="http://www.web3d.org/specifications/x3d-namespace" id="inline" width="500" height="400" showStat="false" x="0px" y="0px" >
  <Scene DEF="scene">
    <Background skyColor="1 1 1"></Background>
    <Inline id="display" url="3E1U-ribbon.x3d" />
  </Scene>
</X3D>
```

I've uploaded an example HTML file and 4 linked .x3d files which, combined can run from anyone's local server...
https://gist.github.com/MakaziMtingwa/03f57296e4d4e86e8e86#file-protein-html
https://gist.github.com/MakaziMtingwa/03f57296e4d4e86e8e86#file-3e1u-ribbon-x3d
https://gist.github.com/MakaziMtingwa/03f57296e4d4e86e8e86#file-3e1u-ribbon-secondary-x3d
https://gist.github.com/MakaziMtingwa/03f57296e4d4e86e8e86#file-3e1u-ribbon-bychain-x3d

**Comment by tsturm** [comment]
Should be fixed with my latest commit 78800fc74448cc19d7c56ee7cb052157f8ef06ff
