### ISSUE TITLE
Caps with hotkeys for navigation mode selection

### ISSUE THREAD

**Issue by dost25** [x3dom/x3dom#496]
When having caps lock activated, the navigation mode cannot be changed via hotkeys. For example, pressing 'E' while having caps lock activated will not set the navigation mode to Examine. Is this the intended behavior?

**Comment by yjung** [comment]
Yes, because E is different from e.

**Comment by mlimper** [comment]
In case you want to change the navmode via capital letters, it should be straightforward to write a small JavaScript keypress callback that invokes the corresponding x3dom runtime function.

**Comment by dost25** [comment]
Yes, of course. We already implemented this. We just thought it is worth mentioning, because we imagine that a user will more likely associate switching to a mode with pressing a certain key on the keyboard instead of writing a letter (which can be lower or upper case). But this is a design decision on your side, not a bug.
