### ISSUE TITLE
'viewpointChanged' seems to be broken

### ISSUE THREAD

**Issue by despairblue** [x3dom/x3dom#497]
When I take [that](http://examples.x3dom.org/example/x3dom_uiEvents.html) example an only add a `setInterval` that sets the viewpoint's position and orientation to what the `viewpointChanged` event returns, the scene will keep moving everytime the interval fires.

See [this example](http://plnkr.co/edit/VwSTHtiwUuxTSmpYaaHb?p=preview). Start by moving it a little.

It seems to keep rotating or moving by exactly the offset from the inital position.

**Comment by tsturm** [comment]
Should be fixed with my last commit.

**Comment by despairblue** [comment]
Thx, I'll try it out and let you know.

**Comment by despairblue** [comment]
Works perfectly :+1:
