### ISSUE TITLE
Semi-transparent rendering of occluder randomly hides other opaque geometry

### ISSUE THREAD

**Issue by mlimper** [x3dom/x3dom#498]
This issue was reported on the mailing list.
Depending on the angle of camera rotation, the opaque geometry of the pilot figure is sometimes visible through the glass and sometimes not.

![transparent_cover_issue](https://cloud.githubusercontent.com/assets/1853237/7833084/3624c0e0-0464-11e5-8817-3a094d2034af.png)

The problem can be reproduced with this model:
https://cloud.igd.fraunhofer.de/owncloud/public.php?service=files&t=3c82d1fb24f0351f07eca58cfdc2a5ec

**Comment by mlimper** [comment]
Debugging... seems it does not matter whether the transparency value comes from the "transparency" property of the appearance or from a texture, the result is the same.

**Comment by tsturm** [comment]
The problem is that both, the pilot and the glass have nearly the same center point.
X3DOM uses that point for tranparency sorting and that's why it alternates if the glass or the pilot is in front during navigation.

To prevent this unwanted behavior you can specify the sort order manually with the `sortKey` -Parameter of the `Appearance`-Node

For example:

```html
<shape id="pilot">
    <appearance sortKey="1">...</appearance>
   ...
</shape>

<shape id="glass">
    <appearance sortKey="2">...</appearance>
   ...
</shape>
```

**Comment by mlimper** [comment]
Okay, the problem is the following:

X3DOM has to draw transparent objects in a separate pass. This pass draws transparent objects on top of opaque objects. The transparent objects are sorted and drawn back-to-front before drawing them ("painter's algorithm"). This is already difficult if there is no clear ordering between two objects (i.e., if one object "wraps" another one, like here).

The actual problem, however, is, in this case, that X3DOM draws the pilot as transparent although it is actually not transparent. But it has a PNG texture, which could contain transparent values (but does not). If this PNG texture is replaced by a JPG (without transparency), for example, the rendering problem is solved.

**Comment by tsturm** [comment]
Instead of replacing the PNG texture by a JPG you can also set the `sortType`-Parameter of the pilot to `opaque`.

```html
<shape id="pilot">
    <appearance sortKey="1" sortType="opaque">...</appearance>
   ...
</shape>
```

**Comment by ChemBioScripting** [comment]
Thanks a lot for the solution and explanation.
Best regards,
Riccardo
