### ISSUE TITLE
Misleading warning about index ending with -1

### ISSUE THREAD

**Issue by sevaa** [x3dom/x3dom#501]
X3DOM displays the following warning:

"WARNING: Last index value should be -1."

Throughout the X3D standard they say that the terminal -1 is not required. Quoting:

"The last face may be (but does not have to be) followed by a "−1" index."

http://www.web3d.org/documents/specifications/19775-1/V3.3/index.html

**Comment by tsturm** [comment]
I've removed the misleading warning.
