### ISSUE TITLE
rotation for clipping plane

### ISSUE THREAD

**Issue by zorgglubb** [x3dom/x3dom#516]
Hi
in this example : 
http://examples.x3dom.org/clipPlane/clipplane.html
I want to add two button + and - to make rotation of the clipping plane on x , y or z.
which is the best way?
update proxycoordinate or transform rotation?

Thanks

**Comment by zorgglubb** [comment]
Hi
Here the original code
http://examples.x3dom.org/clipPlane/clipplane.js

I tried this
I add this code for rotation where value1 is the slider and value my rotation in radian.

'<addr>' 	    this.rotate = function ( value1, value )
    {
		var d = 0;
        if ( _axis == "X" )
        {
		d = ((_volume.max.x - _volume.min.x) * value1) + _volume.min.x;
		    _clipPlane.setAttribute("plane", _clipping + " 0 0 " + d);
			_proxyTransform.setAttribute("rotation", "0 0 1 "+ value);
        }
        else if ( _axis == "Y" )
        {
		    d = ((_volume.max.y - _volume.min.y) * value1) + _volume.min.y;
            _clipPlane.setAttribute("plane", "0 " + _clipping + " 0 " + d);
			_proxyTransform.setAttribute("rotation", "0 0 1 "+ value);
        }
        else if ( _axis == "Z" )
        {
		    d = ((_volume.max.z - _volume.min.z) * value1) + _volume.min.z;
            _clipPlane.setAttribute("plane", "0 0 " + _clipping + " " + d);
			_proxyTransform.setAttribute("rotation", "0 1 0 "+ value);
        }
    };
'</addr>'

But the result is that the clipplane rotate around center 0 0 0 and not on him.
should I modify ProxyCoordinates,

Thanx

**Comment by mlimper** [comment]
I have no time to look into that, but if the clip plane is not rotating properly that might be caused by a wrong order of transformations.
You could try to use two transforms, one for rotation and one for translation, and play with their order.

**Comment by tsturm** [comment]
Hi zorgglubb,

I updated the example to demonstrate a way to rotate the clipplanes.

http://examples.x3dom.org/clipPlane/clipplane.html

**Comment by zorgglubb** [comment]
Hi Timo,
Great, excellent
I dont know SFMatrix4f.

Thanks a lot

**Comment by zorgglubb** [comment]
oups another problem
with your code the rotation of the cliplane dont work.
the center is far and the clipping plane make rotation away.
I think it s from my x3d model because is referenced like x=500 y = 517 and z=163.
some variable stay at 0, 0, 0.
Any idea.
Thx

**Comment by zorgglubb** [comment]
any idea 
I m stop by this problem
the far and near dont work too with model with centre like x=500 y = 517 and z=163.
Thanks

**Comment by mlimper** [comment]
Sounds like know-how about the order of 3D transformations could help you, this issue is also briefly mentioned in this X3DOM tutorial:
http://doc.x3dom.org/tutorials/animationInteraction/transformations/index.html

Also, basically, it sounds like you could either move all the clip planes by adding an additional translation, or you could just center your model to "0 0 0" by adding a translation of "-500 -517 -163", which seems to be a simple solution

**Comment by zorgglubb** [comment]
thans mlimper,
I think you re right.
I use the simple solution by translation of my model to 0,0,0;
tx

**Comment by mlimper** [comment]
thanks for the feedback.
