### ISSUE TITLE
Box node does not react on changing center

### ISSUE THREAD

**Issue by mlimper** [x3dom/x3dom#517]
Sometimes it is useful to manipulate boxes directly (for example, as debug visualization of a volume).
However, to place a box somewhere in the world, we currently always need a transform node, since the "center" field of the box is not used at all to construct the box coordinates (the box node only reacts on changes of the "size" field):
https://github.com/x3dom/x3dom/blob/master/src/nodes/Geometry3D/Box.js#L117

**Comment by degorr** [comment]
But the Box node has no _center_ field and it would be a mistake to introduce it.

**Comment by mlimper** [comment]
Oh, you are so right :-D

Actually I thought this would just be missing in X3DOM. We are using "center/size" representations all the time, so I just assumed X3D boxes would have that.

But after checking the X3D spec, I see that this is not the case. Sorry for the trouble.
