### ISSUE TITLE
Last Viewpoint doesn't take precedence

### ISSUE THREAD

**Issue by sevaa** [x3dom/x3dom#524]
When there are several Viewpoint nodes in a scene, the standard says the last one should take precedence. Quoting:

"X3DViewpointNode nodes are bindable children nodes (...) and thus there exists an X3DViewpointNode stack in the browser in which the top-most X3DViewpointNode node on the stack is the currently active X3DViewpointNode node."

Notably, aopt -V does its model centering logic by inserting a Viewpoint at the end of the scene, while not eliminating the existing ones. Obiously, they expect the last Viewpoint to become the active one.

However, X3DOM doesn't respect that. To reproduce:

 - browse to http://www.jishop.com/temp/x3d/
 - click on "PDB-1XCT-surf-bychain-display"
 - click on "PDB-1XCT-surf-bychain-display with one VP", compare the camera position and rotation point location.

The only difference between those two models is the presence of intermediate Viewpoints in the former one. The last Viewpoint in both models is identical (and it comes from aopt -V).

**Comment by tsturm** [comment]
Hi sevaa,

the snippet of the Specification you have quoted only says:

> "the top-most X3DViewpointNode node on the stack is the currently active X3DViewpointNode node"

But the Specification also says:

> "During read, the first encountered X3DViewpointNode node is bound by pushing it to the top of the X3DViewpointNode node stack"

Therefore, the behaviour of X3DOM is totally standard-conform and all X3D-Viewers that I know do it the same way.

To solve your Problem you have to move the aopt-generated Viewpoint to the top of your file or center your model per javascript using the ```onload``` callback of the Inline-Node.

**Comment by sevaa** [comment]
One would wonder why doesn't aopt -V place their viewpoint in the top of the file, as opposed to bottom, and doesn't eliminate existing viewpoint either. When done this way, the model won't be centered by default - what's the point of that?

**Comment by tsturm** [comment]
To eliminate all existing Viewpoints and create only one centered Viewpoint you can use the following aopt commandline:

```
aopt -i src.x3d -l Viewpoint -V -x dst.x3d
```
