### ISSUE TITLE
Lineset coordinates switched

### ISSUE THREAD

**Issue by chriscarex** [x3dom/x3dom#525]
Hi, I was trying to use Lineset and realized that the coordinates are switched:
-lineset x-coord is equal to -y;
-lineset y-coord is equal to x;
-z stays the same.
Cannot find any expalnation about this behaviour, not sure if there's a reason or it's just a bug.

**Comment by mlimper** [comment]
Huh, looks like it would rotate everything by 90 degrees. I wouldn't suppose this happens accidentally... it would be interesting to see what the spec says.

@yjung: Any ideas why this could be rotated?

**Comment by tsturm** [comment]
I can't reproduce the behaviour in the latest dev-version, therefore I close the ticket.
