### ISSUE TITLE
ERROR: XHR status: 404 - XMLHttpRequest requires web server running!

### ISSUE THREAD

**Issue by krusk** [x3dom/x3dom#531]
Hi all,

I am trying to use the inline feature to load an external x3d file, but am receiving the following error:

ERROR: XHR status: 404 - XMLHttpRequest requires web server running!

In the console using Chrome it is stating that it can't find the file. If try to go directly to the file by browsing its directory location, it offers the following:

HTTP Error 404.3 - Not Found
The page you are requesting cannot be served because of the extension configuration. If the page is a script, add a handler. If the file should be downloaded, add a MIME map.

I have tested this using a Visual Studio Web site running locally and in an hosted Website. I am using the example here: http://doc.x3dom.org/tutorials/models/inline/example.html

Any clues?
K.

**Comment by krusk** [comment]
Odd, if I change the extension to .txt, it works. I am guessing I would need to add a mime type for x3d files, but should I??? Or should I just rename the x3d to .txt?

**Comment by mlimper** [comment]
Maybe it is a webserver issue - could you try with a minimalistic python server, for example?
http://doc.x3dom.org/gettingStarted/pythonSimpleHTTP/index.html

**Comment by krusk** [comment]
Thanks, but this will need to be hosted in Azure/IIS in the end. Renaming the x3d to .xml works great, so until x3d is recognized as a MIME type, I may go this way.

**Comment by krusk** [comment]
Actually! Adding this to the Web.config in IIS allows me to use the x3d formatted file:
  <system.webServer>
  <staticContent>
    <mimeMap fileExtension=".x3d" mimeType="application/xml" />
  </staticContent>
  </system.webServer>

**Comment by doczoidberg** [comment]
right mimeType should be

      <mimeMap fileExtension=".x3d" mimeType="model/x3d+xml"/>
