### ISSUE TITLE
Viewpoint auto reset in Examine navigation mode

### ISSUE THREAD

**Issue by ajcyeh** [x3dom/x3dom#544]
I just found this strange behaviour in the current 1.71 dev version (6 September). When in Examine mode, and I moved an object, the viewpoint will do a resetView call.

I have not yet narrowed down the reasons but thought someone might know why. 

Thanks,

Andy

**Comment by mlimper** [comment]
Thanks for reporting.
How did you move the object?

**Comment by ajcyeh** [comment]
Here is the link to test it. https://vrmath2.net/VRM2/?x3dom=dev (with x3dom version 1.7.1 dev)
To test, you can examine the turtle a bit, then click on "forward" icon in the Quick Command. You should find the viewpoint be reset.

This link is to my current working version https://vrmath2.net/VRM2 (with x3dom version 1.6.3 dev). There is no resetView problem with this version of x3dom.

In the turtle's 3D world, I have 3 viewpoints and some position and orientation chaser nodes. It is difficult for me to narrow down the cause. But if any of the developers who have touched on the resetView and/or the above nodes, then they may find the cause quicker.

Thanks,

Andy

**Comment by ajcyeh** [comment]
I traced back the commits and found this caused my viewpoint reset.
https://github.com/x3dom/x3dom/commit/16dc05fa5d180fb25f8887a3d96126a52ec952f4

Could someone please review the above commit and see if that is necessary or is there another way to fix #497 ?

My application has viewpointChanged event listener to viewpoint nodes. These viewpoint nodes are constantly updated (position & orientation) in order to follow the Turtle. The above commit will cause reseting viewpoint.

Thanks,

Andy

**Comment by mlimper** [comment]
> I traced back the commits and found this caused my viewpoint reset.
> 16dc05f

Very helpful, thanks a lot for that.
@tsturm Do you have the resources to take a look at the commit (issue with adding `resetNavHelpers`)?

**Comment by ajcyeh** [comment]
@tsturm Have you got a chance to look at this commit? https://github.com/x3dom/x3dom/commit/16dc05fa5d180fb25f8887a3d96126a52ec952f4

Is the resetNavHelpers still necessary? Every time I apply new dev version of x3dom, I need to comment it out in order for my VRMath2 Editor to work properly.

Thanks.

**Comment by tsturm** [comment]
Hi Andy,

can you build a small example outside of your Editor?
All your code is minified and it's hard to debug.

**Comment by ajcyeh** [comment]
Hi tsturm,

Thanks for looking into this. You can view this example to reproduce the auto reset view. 
https://vrmath2.net/VRM2/html/testResetView.html

To produce the auto reset viewpoint issue, please firstly examine a little bit (rotate the scene), then click on the forward button.

The forward effect is achieved by using a PositionChaser and Route. The forward button will set the destination of PositionChaser to 0 0 -1, the Route will then interpolate the turtle's position to 0 0 -1. The home button will set the destination of PositionChaser to 0 0 0, so the problem can be tested again.

The issue only happens when there are more than one viewpoint. There are two viewpoint nodes in this x3d scene. The second viewpoint is not used in this test but is used in VRMath2 Editor to produce the view from the turtle's position.

The possible cause may be in the resetNavHelpers(), which needs to ignore non-active viewpoints.

**Comment by tsturm** [comment]
Hi Andy, thanks for the example.

The issue should be fixed with my last commit.

**Comment by ajcyeh** [comment]
Thank you :-)
