### ISSUE TITLE
vertical and horizontal text positioning off

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#545]
Currently x3dom seems to position a text node too high:
x3dom rendering of 
http://x3dgraphics.com/examples/X3dForWebAuthors/Chapter02-GeometryPrimitives/GeometryPrimitiveNodes.xhtml
![image](https://cloud.githubusercontent.com/assets/6171115/9735106/57b92ae0-5606-11e5-883d-53b23626b93e.png)
expected rendering:
http://x3dgraphics.com/examples/X3dForWebAuthors/Chapter02-GeometryPrimitives/_viewpoints/GeometryPrimitiveNodes.x3d._VP_Default_viewpoint.png
![image](https://cloud.githubusercontent.com/assets/6171115/9735137/89a55830-5606-11e5-82af-d13020de7248.png)
and also too far left.
This is probably a result of x3dom centering the text box at the local origin. By default the origin should be close to the upper left corner.

**Comment by andreasplesch** [comment]
Here is a better defined example:
x3dom rendering of
http://www.web3d.org/x3d/content/examples/ConformanceNist/Appearance/FontStyle/default.xhtml
![stabilebssa14_fig8](https://cloud.githubusercontent.com/assets/6171115/9744680/4b54edf4-563b-11e5-89d6-ab78108c0fe6.png)
expected rendering:
http://www.web3d.org/x3d/content/examples/ConformanceNist/Appearance/FontStyle/_viewpoints/default.x3d._VP_Test_default_FontStyle_rendering.png
![web3d_screen](http://www.web3d.org/x3d/content/examples/ConformanceNist/Appearance/FontStyle/_viewpoints/default.x3d._VP_Test_default_FontStyle_rendering.png)
The text should be to the right of and under the green lines.

**Comment by mlimper** [comment]
Just figured out where in the code the actual placement of the geometry is happening:
https://github.com/x3dom/x3dom/blob/master/src/Texture.js#L550

The _positions buffer holds the four 3D positions of the corners of a screen-aligned quad (triangulated via the respective indices). It seems to add an offset of 0.4 to the y coordinate, for whatever reason (didn't play around with it).

It should be straightforward to change this. However, I'm not sure whether this makes things easier in case you want to center something around, say, a 3D marker. Clearly, it would make it easier if your intended text is supposed to appear next to / under a known 3D point... well, I'm sure the people who wrote the standard already thought about this.

My main concern is that people might have got used to X3DOMs current behavior of centering text, and if they want to keep this behavior, it should be clear how to achieve this.

**Comment by andreasplesch** [comment]
Yes, I saw that as well, and started to implement a more correct positioning:
http://andreasplesch.github.io/x3dom/x3dom_text/alignment.xhtml
I do think the default behaviour should be more compliant with the spec. but this would require then updating scenes which relied on the centered behaviour.
One option would be to have an additional switch for the node 'iso19775' or similar to enable spec. compliant positioning, with a default of 'true'. 'false' would provide traditional positioning.
Another option would be have a default for the justify field of '"MIDDLE" "MIDDLE"' which corresponds to the current behaviour (other than the 0.4 vertical offset). However, defaults are important and the spec. default is '"BEGIN" "FIRST"'.
Finally, a last option would be to simply document the changed behaviour in the documentation with a note explaining that '"MIDDLE" "MIDDLE"' provides the original behaviour.

,

**Comment by andreasplesch** [comment]
maxExtent could be quite straightforward since texture coordinates are set to cover all of the defined mesh. It should be sufficient to make the width of the mesh the smaller of maxExtent and (max.) measured width (if maxExtent is larger than 0).
The length field  could be implemented using the maxWidth parameter to ctx.fillText.
http://www.w3schools.com/tags/playcanvas.asp?filename=playcanvas_filltextmaxwidth
http://tutorials.jenkov.com/html5-canvas/text.html
However, maxWidth may not be supported by Safari. Although Safari 7.0 seems to do it:
http://dev.modern.ie/tools/screenshots/#http://tutorials.jenkov.com/html5-canvas/text.html#text-max-width

**Comment by andreasplesch** [comment]
Just a note that ctx.textBaseline="alphabetic" would allow for better 'FIRST' minor alignment, and "bottom" for better "END" minor alignment.

**Comment by andreasplesch** [comment]
Here is an implementation of a more correct major and minor alignment as well as support for topToBottom:

http://andreasplesch.github.io/x3dom/x3dom_text/driver_x3dom.xhtml

minor 'FIRST' is by using textBaseline 'alphabetic' and 'END' by 'bottom'. The length field is partially supported by using the maxWidth parameter, eg. only works to shorten the text not to expand it.

leftToRight = 'false' (right to left) and horizontal = 'false' (vertical) text is not supported due to lack of support by browser.  

https://github.com/x3dom/x3dom/compare/master...andreasplesch:text_work

This includes also a fix to make fieldchanged() work for the FontStyle node.

I propose to have a non-standard default of justify=' "MIDDLE" "MIDDLE" ' for backward compatibility, with a note in the generated documentation. In many ways this is the behavior which may be expected anyways if one is not familiar with the specification.

If this is acceptable I will remove most code comments, and prepare a PR.

**Comment by andreasplesch** [comment]
Updated example to test for correctness:
http://andreasplesch.github.io/x3dom/x3dom_text/driver_x3dom.xhtml
