### ISSUE TITLE
Using Xj3D binary .x3db with x3dom (Xj3D .wrl to .x3db conversion without BG_0_coordBinary.bin+8 or BG_0_normalBinary.bin+4)

### ISSUE THREAD

**Issue by ron190** [x3dom/x3dom#547]
Hello, I'm trying to use Xj3D binary conversion with x3dom but it fails to render the scene in the web canvas.

If I convert the file with aopt into .x3db binary format, it works just fine with x3dom though I notice that additional files are created like BG_0_coordBinary.bin+8 or BG_0_normalBinary.bin+4. Also a problem is that aopt is not allowed for commercial use.

With Xj3D I convert my .wrl file with following command :

```
converter.bat input.wrl output.x3db -exportVersion 3.3 -compressionMethod FASTEST -exportType BINARY
```

What I get is a single binary .x3db file which works fine with InstantPlayer (included in aopt folder from Instant Reality editor). I must define -compressionMethod as FASTEST or STRINGS because LOSSY and SMALLEST don't render in InstantPlayer. All four methods are working with Xj3D browser (but scene exploration does not seem to work anyway, does someone know the trick to activate mouse exploration ?).

With aopt we use a small readable .x3d file which links to coord .bin+4 files and normal .bin+8 files, the .x3d is like this one :

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE X3D PUBLIC "ISO//Web3D//DTD X3D 3.0//EN" "http://www.web3d.org/specifications/x3d-3.0.dtd">
<X3D xmlns:xsd='http://www.w3.org/2001/XMLSchema-instance' profile='Full' version='3.0' xsd:noNamespaceSchemaLocation='http://www.web3d.org/specifications/x3d-3.0.xsd'>
  <Scene DEF='scene'>
    <WorldInfo info='"File created using CATIA"'/>
    <NavigationInfo type='"EXAMINE" "WALK" "FLY"'/>
    <Background/>
    <Viewpoint description='Main Viewpoint' orientation='0.187053 0.451587 0.872399 2.44808' position='0.058386 0.044886 0.040924' fieldOfView='0.523583'/>
    <Viewpoint description='Iso View' orientation='0.187053 0.451587 0.872399 2.44808' position='0.058386 0.044886 0.040924' fieldOfView='0.523583'/>
    <Viewpoint description='Front View' orientation='0.57735 0.57735 0.57735 2.09439' position='0.088317 0.004 3.8e-005' fieldOfView='0.523583'/>
    <Viewpoint description='Back View' orientation='0.57735 -0.57735 -0.57735 2.09439' position='-0.053317 0.004 3.8e-005' fieldOfView='0.523583'/>
    <Viewpoint description='Left View' orientation='1 -0.000173 0.000173 1.5708' position='0.0175 -0.066817 3.8e-005' fieldOfView='0.523583'/>
    <Viewpoint description='Right View' orientation='-0.000122 -0.707107 -0.707107 3.14135' position='0.0175 0.074817 3.8e-005' fieldOfView='0.523583'/>
    <Viewpoint description='Top View' orientation='0 0 1 1.5708' position='0.0175 0.004 0.070855' fieldOfView='0.523583'/>
    <Viewpoint description='Bottom View' orientation='0.707107 0.707107 0 3.14159' position='0.0175 0.004 -0.070779' fieldOfView='0.523583'/>
    <Shape DEF='_G_1'>
      <Appearance>
        <Material DEF='_material0' diffuseColor='0.823529 0.823529 1'/>
      </Appearance>
      <BinaryGeometry DEF='BG_0' vertexCount='36' primType='"TRIANGLES"' position='0.0175000000745 0.00400000018999 3.80000019504e-005' size='0.035000000149 0.00800000037998 7.60000039008e-005' coord='../binGeo_output/BG_0_coordBinary.bin+8' normal='../binGeo_output/BG_0_normalBinary.bin+4' coordType='Int16' normalType='Int8'/>
    </Shape>
  </Scene>
</X3D>
```

The URL to this .x3d file generated by aopt is then included in the tag inline between X3D and scene and it works OK :

``` html
<X3D showLog='true' id="the-one" xmlns="http://www.web3d.org/specifications/x3d-namespace">
    <scene>
        <inline url="tiny-scene-from-aopt.x3d" />
    </scene>
</X3D>
```

As I'm using Xj3D binary .x3db without coord and normal files, do you know how to define the web scene in order to render this single .x3db from Xj3D with x3dom ?

**Comment by ron190** [comment]
I'm trying to load the .x3db like this :
```html
<X3D showLog='true' id="the-one" xmlns="http://www.web3d.org/specifications/x3d-namespace">
    <scene>
        <inline url="binary-file-from-xj3d.x3db" />
    </scene>
</X3D>
```
The console is showing 'not well-formed' because binary does not match xmlns I guess.
Is there another method to load the .x3db file ?

**Comment by mlimper** [comment]
Hi,

unfortunately, X3DOM cannot parse x3db files inside the browser. This was not done for performance reasons, as there is no native implementation to decompress the compressed XML.

Nevertheless, this is not a real problem. With X3DOM binary geometry, it is usually not necessary to compress the XML for delivery, since the XML without the vertex data etc. will typically become quite compact anyway.

**Comment by ron190** [comment]
Thank you for this information.

I have tested Binary Geometry from aopt on massive 3D objects and rendering performance with X3DOM is impressive. Currently aopt is the only utility I found which can build optimized files that are rendered with X3DOM.

[Maybe off topic] I have just found about PostGIS which seems to propose [x3d](http://postgis.net/docs/ST_AsX3D.html) and [binary](http://postgis.net/docs/ST_AsBinary.html) compatibility. 
Can this database be used as some kind of converter for the purpose of rendering optimized files into X3DOM ?
Is there some existing or future compatibility planned for rendering PostGIS Well-Known Binary geometry representation (WKB) or extended Well Known Binary (EWKB) into X3DOM ?

[On topic] Is there a solution to create optimized x3d with Xj3D or another tool in order to render the scene with X3DOM ?

**Comment by ron190** [comment]
> [...] does someone know the trick to activate mouse exploration [in Xj3D] ?

You can force browser to change rendering from GLWindow (NEWT) to GLCanvas (AWT) for your mouse to work. Add the tag -swing to launch the browser in this mode : 
```
browser.bat -swing
```

**Comment by brutzman** [comment]
1.  The Xj3D build has not been very active but it is maintained by @terry-norbraten and I at NPS.  Suggested changes are always welcome, for example your "-swing" switch on browser.bat.

- Savage Developers Guide, Xj3D viewer: NPS source
- https://savage.nps.edu/Savage/developers.html#Xj3D
