### ISSUE TITLE
node.getFieldValue('anybool') produces exception

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#553]
Currently returns exception since .copy() not implemented for SFBool:

http://andreasplesch.github.io/x3dom/x3dom_text/getFieldValueBool.html

fix by checking for bool in .getFieldValue() function (similar to .setFieldValue()) or

workaround by using .getAttribute()

**Comment by tsturm** [comment]
Fixed with commit 00940b29e3f14a40decb67e2191245e899150372

**Comment by andreasplesch** [comment]
thanks, looks good.
