### ISSUE TITLE
x3dom.ready override not executed

### ISSUE THREAD

**Issue by plitzenberger** [x3dom/x3dom#554]
Trying to override x3dom.ready, I have the following minimal example.

```
   ...
    <script src="assets/x3dom-1.7.0/x3dom-full.js"></script>
    <script type="text/javascript">
      x3dom.ready = function(element) {
        alert("ready dude")      
      }
    </script>
   ...
```

Other than expected, the function never appears to be called. Can someone explain why that might be the case or what I am missing?

**Comment by andreasplesch** [comment]
Try x3dom.runtime.ready

I was confused by the documentation as well.

**Comment by tsturm** [comment]
@plitzenberger: Can we close this issue?

**Comment by plitzenberger** [comment]
@tsturm: That's fine with me.
