### ISSUE TITLE
Style modification of the `body` tag in x3dom.css

### ISSUE THREAD

**Issue by fabienrohrer** [x3dom/x3dom#564]
The x3dom.css file is modifying the main body tag:

https://github.com/x3dom/x3dom/blob/master/src/x3dom.css#L12

I think this is a bad practice, because it has some side effects when importing the .css file in a page in which we don't want to modify the font.

I would propose to either drop these lines or to encapsulate this modification into an HTML class. .. and to fix accordingly the examples.

**Comment by mlimper** [comment]
I agree that this is bad practice. I have just removed this part:
https://github.com/x3dom/x3dom/commit/a5bf1c3b18998da7ccf7b8d38da30de510e8dbbb

Thanks for reporting this.

**Comment by fabienrohrer** [comment]
Thank you very much.
