### ISSUE TITLE
Show JT files 

### ISSUE THREAD

**Issue by akramDev** [x3dom/x3dom#567]
Hello 

I know that X3dom support only x3d files. but is there any api or extension to make it support JT(https://en.wikipedia.org/wiki/JT_(visualization_format)) ?
maybe an API to convert JT to x3d ?

Thanks

**Comment by mlimper** [comment]
There have been a lot of X3DOM demos which were actually showing data converted from JT.

Two examples:
http://x3dom.org/pop/landinggear.html
http://x3dom.org/src/exampleData/bloodhound/X3D-ExternalGeometry/bloodhound-src-extgeo_x3dom16.html

Siemens provides an Open JT library for this.

Commercial block:
If you are interested in transcoding services for CAD and CAD visualization, consider Fraunhofer IGDs instant3Dhub solution (www.instant3dhub.org), or licensed transcoding via instantreality's aopt tool (also reads JT).
