### ISSUE TITLE
The "Marines" text not on the wing on the Harrier model

### ISSUE THREAD

**Issue by sevaa** [x3dom/x3dom#568]
Navigate to http://www.jishop.com/temp/x3d/, click on the Harrier model in the left menu. Rotate the airplane so that the top portion of the wings is facing you. See the "Marines" text being not on the wing, where it probably should be.

![image](https://cloud.githubusercontent.com/assets/5807738/10829942/50a7027a-7e53-11e5-8c19-134237fadfc3.png)

**Comment by andreasplesch** [comment]
To me it almost likes look it is the other way around, eg. the wing should be where the text is. There is also a small piece floating around well below and separate from the main body of the plane. I believe here is the source x3d to look at:
https://savage.nps.edu/Savage/AircraftFixedWing/AV8B-Harrier-UnitedStates/_pages/page01.html

**Comment by sevaa** [comment]
That's another issue I've filed, #566.

**Comment by sevaa** [comment]
The issue is not what I thought. The text is in the right place; the wings aren't.

And, interestingly enough, it's not X3DOM's fault. The problem is in the X3D standard itself. The wings in that model are implemented as extrusions in the -Y direction. That kind of geometry is UNDEFINED under the X3D standard as of v3.3. 

See http://www.web3d.org/wiki/index.php/Extrusion_Edge_Cases#Straight_spine_in_-Y_direction for a longer explanation as to what's wrong with the spec.

**Comment by andreasplesch** [comment]
Thanks for the detailed explanation, it would be otherwise very hard to figure out what is going on.

**Comment by sevaa** [comment]
X3DOM *does* have a problem with straight spines though. Read the wiki article please.
