### ISSUE TITLE
Large scene suddenly gets culled

### ISSUE THREAD

**Issue by mlimper** [x3dom/x3dom#571]
Can be reproduced with this scene:

```
    <x3d width="800" height="800">
       <scene>
           
        <viewpoint position="-120.00000 150.00000 -60.00000"
                  orientation="-0.08439 -0.99625 0.01896 1.40963"
                  centerOfRotation="288.7862050354876 88.71837554889501 -92.561225028907"
                  zNear="1.00000" zFar="10000.00000">
        </viewpoint>
                      
        <Transform>            
            <Shape>
              <Appearance>
                <Material diffuseColor='1 0 0'/>
              </Appearance>
              <Box size="15000 0 15000"/>
            </Shape>              
        </Transform>
                 
        <Transform translation="271 130 -100">         
             <Shape>
              <Appearance>
                <Material diffuseColor='0 1 0'/>
              </Appearance>
              <Box size="50 50 50"/>
            </Shape>            
        </Transform>
           
       </scene>
    </x3d>
```

**Comment by mlimper** [comment]
Seems this behavior was caused by a rare case where all sides of an object's bounding box intersect with the frustum. This should not be happening if (1) the user doesn't set zNear / zFar and lets X3DOM compute it or (2) all objects are small enough too never cause this situation. However, there has been an application where this occurred.

What I don't understand right now is why this seems to cause all other objects also to disappear. I have tried to fix this first by setting the planeMask (which was zero in that rare case) to MASK_SET instead - see https://github.com/x3dom/x3dom/commit/05ac1df0807e139bb4bde592feefff3174726be1
But (maybe not surprisingly) this caused the opposite behavior, i.e., if we have the edge case, suddenly everything is considered visible, making culling actually not doing anything (can be seen through stats display). This behavior seems like another bug to me, as I would expect the culling of a single object not to influence the culling of the others... 

To "fix" this, I just added another commit:
https://github.com/x3dom/x3dom/commit/d7963a039470f2155b6c53956fa5d332d7549940

Not sure whether this makes sense - we should have another look to identify what's going on with the culling (why is the culling of one object having an impact on the others)?

@chrstein Do you have a spontaneous idea?

**Comment by chrstein** [comment]
@mlimper This reminds me of an article i read a while ago ( http://www.iquilezles.org/www/articles/frustumcorrect/frustumcorrect.htm). We probably have the same problem in the hare3d culling code.

The impact on other elements should be a result of the respective X3D scene, where volumes are combined on transformation nodes higher up in the hierarchy. The error in the culling code combined with the "oversized" bounding volume triggers the culling of the whole subtree. In your testcase the node in question should be the scene node.

**Comment by mlimper** [comment]
Thanks for the quick response!


> The impact on other elements should be a result of the respective X3D scene, where volumes are combined on transformation nodes higher up in the hierarchy.

You're right, I totally forgot about the fact that X3DOM, although it doesn't use a spatial hierarchy for culling, still uses the scene hierarchy for that purpose...

That article is indeed interesting, and the problem seems related. I think what is different from our problem is that the "most implementations" code from the article tries to _falsify_ that the object is inside the frustum. Therefore, if something goes wrong, it will get you a false positive. In contrast, our implementation was giving us false negatives, since the code is trying to _verify_ that the object is inside with respect to at least one plane of the frustum:
https://github.com/x3dom/x3dom/blob/05d58c2457c0035e11fb5ec4b7a43c49c82d718c/src/fields.js#L4023

In the mentioned special case, no such plane can be found, but the object is still overlapping with the frustum.

I think the purpose of trying to find the plane is the following algorithm for hierarchical frustum culling (correct me if I'm wrong):
* When traversing the hierarchy downwards, collect the `planeMask`, a set of "trivial accept" planes for which we know that the full subtree must be "inside" with respect to them.
* When computing the `planeMask` of a child node, the already known "trivial accept" planes of the parent can be skipped (https://github.com/x3dom/x3dom/blob/master/src/fields.js#L4067)
* As soon as all planes of the frustum have been identified to be "trivial accept" planes, the subtree fully lies inside the frustum, without intersections, and the `planeMask` is equal to `MASK_SET`. In that case, no frustum intersection computations need to be performed for child nodes (https://github.com/x3dom/x3dom/blob/master/src/util/DrawableCollection.js#L89).

And this algorithm is probably still okay, but we should take care of the case where no "trivial reject" planes were found (i.e., `planeMask` is zero):
https://github.com/x3dom/x3dom/blob/master/src/util/DrawableCollection.js#L101

In the previous implementation, the culling function would return -1 if  `planeMask` was zero, which would mean the subtree gets culled, and that caused the bug. My bad "fix" was now to set `planeMask`to 1 in that case.

After writing this down, I believe that the right solution is to leave it as zero and simply adapt every call to the culling function to treat "0" as inside, for example here:
https://github.com/x3dom/x3dom/blob/7d104d9717d12e1670b1ef40f5b83beeb590df83/src/nodes/Grouping/X3DGroupingNode.js#L59
This would also mean to change the case where "render" is set to "false" to return -1 instead of 0:
https://github.com/x3dom/x3dom/blob/master/src/util/DrawableCollection.js#L71

Does that make sense, would you agree on this changes?
