### ISSUE TITLE
text with material is not working

### ISSUE THREAD

**Issue by mvidiassov** [x3dom/x3dom#578]
In the current dev version of x3dom Text with Material does not show correctly.
[Example](http://www2.iaas.msu.ru/tmp/u3d/x3d_text_material.xhtml)
In the above example Text with empty Material or with some material appears as a rectangle, and only Text without Material can be read.
1.7 is OK

**Comment by mlimper** [comment]
Thanks a lot for reporting this.

@andreasplesch Do you have an idea of any changes in the text rendering which could have caused this? Maybe something went wrong with alpha values?

**Comment by tsturm** [comment]
Should be fixed with my last commit 89a3dee65e42b1c335c6b59144df4d9b4a54d12e

**Comment by mlimper** [comment]
Thanks Timo :-)
