### ISSUE TITLE
texture not combined with diffuse color

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#579]
The conformance test

http://www.web3d.org/x3d/content/examples/ConformanceNist/Appearance/ImageTexture/greyscale_jpg_diffuseColor.xhtml

produces only a greyscale texture, without the red tinting from the diffuse color.

**Comment by tsturm** [comment]
Hi Andreas,

blending a texture color with a material color should only work if you set the `origChannelCount` of the `ImageTexture` to `1` or `2`.

`<ImageTexture url="..." origChannelCount="1"></ImageTexture>`

See [Table 17.2](http://www.web3d.org/documents/specifications/19775-1/V3.2/Part01/components/lighting.html#t-Unlitcolourandalpha) of the X3D Specification.

Regards
Timo

**Comment by andreasplesch** [comment]
Yes, x3dom has origChannelCount but x3d does not:  http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/texturing.html#ImageTexture

So should 1 be the default ? This may have been discussed ?
