### ISSUE TITLE
IndexedLineSet with single colorindex does not render

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#580]
An IndexLineSet with a colorindex with a single index in http://andreasplesch.github.io/x3dom/earclipping/ColorPerVertexExamples.xhtml
provokes a TypeError in IndexedLineSet.js
There is TODO for colorindex which already seems to address this. Still may be good to have an issue with an example. The original is here:
http://x3dgraphics.com/examples/X3dForWebAuthors/Chapter06-GeometryPointsLinesPolygons/ColorPerVertexExamples.xhtml

**Comment by ajcyeh** [comment]
This issue seems to have been fixed already.

**Comment by andreasplesch** [comment]
Ok. I close this.
The issue now morphs into that colorpervertex=false means that all of the polyline should have the same color. Currently the setting is essentially ignored.

http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/rendering.html#IndexedLineSet
requires that there enough color indices to determine the color each polyline. In the example there is one polyline, so one index is sufficient.
