### ISSUE TITLE
x3dom dist for Node.js and livereload server boilerplate

### ISSUE THREAD

**Issue by fibo** [x3dom/x3dom#592]
Hi all,

today I was at [X3DOM: Instant 3D, the HTML way](http://www.meetup.com/it/Khronos-Milano-Chapter/events/226051523/) presentation at **Khronos Milano Chapter** meetup, and I watched a presentation about x3dom. I really liked this technology!

I think having x3dom package for [npm](https://www.npmjs.com/) could be really useful, so I started putting it on a package [x3dom-dist](https://github.com/fibo/x3dom-dist) which is not published on npm registry yet. It could also packaged and published on [bower](http://bower.io/) registry.

This means that for many users that feel comfortable with one of the package managers above, could install x3dom with something like

```
bower install x3dom
```

or

```
npm install x3dom
```

By now it is already possible to install x3dom with

```
npm install fibo/x3dom-dist
```

Having a repo **x3dom/dist** on x3dom GitHub organization would be great and it would be an honor for me to be the mantainer.
This has a lot of advantages, like

* getting more people into the community and using x3dom, since many people use bower or npm.
* having a package manager let you install a specific version of x3dom, so examples that need a specific version would not break.
* installation is easier and can integrate with other tools, as well as automated.

For example I created a [x3dom-livereload](https://github.com/fibo/x3dom-livereload) boilerplate, you can use to start playing with x3dom.
First install [Node.js][3]. Then copy and paste the following code into a terminal

```
npm install -g grunt-cli
git clone https://github.com/fibo/x3dom-livereload
cd x3dom-livereolad
npm install
grunt
```

Then point your browser to *http://localhost:3000* and start editing *index.html*.
Play with [x3dom][1] and every time you save the *index.html* your 3d scene will be updated
magically without reloading your browser, thanks to [livereload][2].

  [1]: http://www.x3dom.org/ "x3dom"
  [2]: http://livereload.com/ "livereload"
  [3]: https://nodejs.org/ "Node.js"

**Comment by mlimper** [comment]
Dear Gianluca,

thanks a lot for this very helpful proposal!

In fact, people already asked for npm or bower support in the past, but 
AFAIK nobody really provided a package until now.

I have just created a new project on Github, as you proposed, and made 
you maintainer:
https://github.com/x3dom/dist

As soon as this is working, we can put an example into the x3dom docs.

Best Regards,
Max


On 18.12.2015 00:36, Gianluca Casati wrote:
>
> Hi all,
>
> today I was at X3DOM: Instant 3D, the HTML way 
> <http://www.meetup.com/it/Khronos-Milano-Chapter/events/226051523/> 
> presentation at *Khronos Milano Chapter* meetup, and I watched a 
> presentation about x3dom. I really liked this technology!
>
> I think having x3dom package for npm <https://www.npmjs.com/> could be 
> really useful, so I started putting it on a package x3dom-dist 
> <https://github.com/fibo/x3dom-dist> which is not published on npm 
> registry yet. It could also packaged and published on bower 
> <http://bower.io/> registry.
>
> This means that for many users that feel comfortable with one of the 
> package managers above, could install x3dom with something like
>
> |bower install x3dom |
>
> or
>
> |npm install x3dom |
>
> By now it is already possible to install x3dom with
>
> |npm install fibo/x3dom-dist |
>
> Having a repo *x3dom/dist* on x3dom GitHub organization would be great 
> and it would be an honor for me to be the mantainer.
> This has a lot of advantages, like
>
>   * getting more people into the community and using x3dom, since many
>     people use bower or npm.
>   * having a package manager let you install a specific version of
>     x3dom, so examples that need a specific version would not break.
>   * installation is easier and can integrate with other tools, as well
>     as automated.
>
> For example I created a x3dom-livereload 
> <https://github.com/fibo/x3dom-livereload> boilerplate, you can use to 
> start playing with x3dom.
> First install Node.js <https://nodejs.org/>. Then copy and paste the 
> following code into a terminal
>
> |npm install -g grunt-cli git clone 
> https://github.com/fibo/x3dom-livereload cd x3dom-livereolad npm 
> install grunt |
>
> Then point your browser to /http://localhost:3000/ and start editing 
> /index.html/.
> Play with x3dom <http://www.x3dom.org/> and every time you save the 
> /index.html/ your 3d scene will be updated
> magically without reloading your browser, thanks to livereload 
> <http://livereload.com/>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/x3dom/x3dom/issues/592>.
>

-- 
Dipl.-Inform. Max Limper

Visual Computing System Technologies
Fraunhofer-Institut für Graphische Datenverarbeitung IGD
Fraunhoferstraße 5      | 64283 Darmstadt
Phone: +49 6151 155-554 | Fax: -196
max.limper@igd.fraunhofer.de

**Comment by fibo** [comment]
Great! Thank you, here it is a [first version](https://github.com/x3dom/dist/blob/master/README.md).

**Comment by mlimper** [comment]
Cool!
Just tried "npm install x3dom" - worked just smoothly.

I'll let this thread open so we don't forget to mention this in the docs.
BTW, we just updated to stable 1.7.1^^

**Comment by fibo** [comment]
Ok, I just registered on bower.

**Comment by fibo** [comment]
I updated to version 1.7.1 https://github.com/x3dom/dist/commit/2df115fbe8d9d3101c21b1086dc7508376dbad39

Question before publishing on the bower and npm registers: I included x3dom.js and x3dom.css; should I include also x3dom.swf or other files file components and full build?

**Comment by mlimper** [comment]
SWF maybe not, but the CSS should be in the package.

Not sure about the components... Here's how they work:
http://doc.x3dom.org/gettingStarted/x3domVersions/index.html

If we put everything into the package, would that mean developers using the package would, by default, distribute everything with their application, even if they don't need all the components? Some components are quite large.

How is this case usually handled? Does one typically provide multiple packages for adding more functionality?

**Comment by fibo** [comment]
Probably the best option is to put x3dom.js and x3dom.css, as is right now, the componente could be packaged one by one separately, having x3dom as dependency.

**Comment by fibo** [comment]
Closing this issue, cause it is already done.
