### ISSUE TITLE
Use MutationObserver

### ISSUE THREAD

**Issue by coderextreme** [x3dom/x3dom#595]
I got the following in my Firefox console using x3dom.org/release/:

Use of Mutation Events is deprecated. Use MutationObserver instead. x3dom-full.js:874:169

Using:
        <link rel="stylesheet" type="text/css" href="http://x3dom.org/release/x3dom.css" />
        <script type="text/javascript" src="http://x3dom.org/release/x3dom-full.js"></script>

**Comment by mlimper** [comment]
thanks for reporting

this is a known issue:
https://github.com/x3dom/x3dom/issues/165
(so I'm closing this to avoid a duplicate)
