### ISSUE TITLE
Index not considered for FloatVertexAttribute in IndexedFaceSet

### ISSUE THREAD

**Issue by YuanxiangFranck** [x3dom/x3dom#596]
Hello,

In my project, I have a mesh with data associated to each vertices and I wanted to hide part of the mesh if the data are to lower than a chosen value.
To do that, I used an IndexedFaceSet for the geometry and add the attribute to the shaders with FloatVertexAttribute. 
In the example below I created 2 triangles with 4 points, so I can set normal, texture coordinate, for the 4 points: 3* 4 values for coordinate, 2*4 for texture coordinate...
The problem is when I tired to set only 4 values  I got the webgl warning : 

[GroupMarkerNotSet(crbug.com/242999)!:D0DAD8CDB47F0000]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: attempt to access out of range vertices in attribute 3

For x3dom there is 6 points (some points are duplicated during the creation of the faces). When I tried to set the FloatVertexAttribute, it asked for 6 values not 4. After reading a parts of x3dom code I believe that FloatVertexAttribute should be parsed with the other attributes (normal, positions...)

Franck

```html
<shape >
  <appearance>
    <ComposedShader id='ComposedShader'>
      <field name='threshold' type='SFFloat' value='0.'></field>
      <ShaderPart type='VERTEX' style="display:none;" >
        #ifdef GL_FRAGMENT_PRECISION_HIGH
        precision highp float;
        #else
        precision mediump float;
        #endif

        attribute vec3 position;
        attribute vec3 color;
        attribute float data;

        uniform mat4 modelViewProjectionMatrix;

        varying float fragData;
        varying vec3 fragColor;

        void main()
        {
        fragData = data;
        fragColor = color;
        gl_Position = modelViewProjectionMatrix * vec4(position,1.);
        }
      </ShaderPart>
      <ShaderPart type='FRAGMENT' style="display:none;">
        #ifdef GL_FRAGMENT_PRECISION_HIGH
        precision highp float;
        #else
        precision mediump float;
        #endif

        uniform float threshold;

        varying vec3 fragColor;
        varying float fragData;

        void main()
        {
        if ( threshold > fragData) { discard; }
        gl_FragColor = vec4(fragColor, 1.0);
        }
      </ShaderPart>
    </ComposedShader>
  </Appearance>
  <IndexedFaceSet id="faceSet" solid="false"
                  coordIndex='0 2 1 -1 0 1 3'
                  normalPerVertex='false'
                  ccw='false'>
    <Color color="1 1 0, 0 1 0, 0 0 1, 1 0 0,"></Color>
    <Coordinate point="0 0 0, 0 1 0, 0 0 1, 1 0 0,"></Coordinate>
    <Normal vector="1 0 0, 0 0 1" ></Normal>
    <FloatVertexAttribute
       name="data" numComponents="1" value="1 2 -3 4 -5 6">
    </FloatVertexAttribute>
    <!-- Works -->
    <!-- Return webGL out of range error
         <FloatVertexAttribute id="faceSetAttr" name="data"
                               numComponents="1" value="1 2 3 4">
         </FloatVertexAttribute>
         -->
  </IndexedFaceSet>
</shape>
```
[EDIT] : I changed the exemple to make it simpler

**Comment by andreasplesch** [comment]
Could you try creaseAngle='3.14' as an IndexedFaceSet attribute ? I believe the default creaseAngle='0' leads to duplication of shared vertices to be able to have segmented shading with the default shading. Unfortunately, the default is required by the spec. to be 0.
If this works, it could be documented in the FloatVertexAttribute docs as a  workaround.
May you be able to fix parsing since you started to look at the code ?

**Comment by YuanxiangFranck** [comment]
It did not worked. It indeed removed the duplicated points but now I always have the WebGL error (L_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 1) with 4, 6 or more values for the data.
Right now I have no idea why it display this error message. 

But event without duplication that would not work. The FloatVertexAttribute are set following the order of the given indices. 
For exemple if if only draw one triangle with coordIndex="0 2 1" for the IndexedFaceSet 
If set value="0.1   0.2   0.3" for the FloatVertexAttribute

in the shaders the data would be associated like that : 0.1 for point 0, 0.2 for point 2, 0.3 for point 1
This is because it seems to set values following the given indices.
(This can be tested in my exemple by changing the values and indices)

**Comment by YuanxiangFranck** [comment]
My mistake, it works well!

**Comment by andreasplesch** [comment]
Ok ! But the mapping of the FloatVertexAttributes uses the coordIndex indices as you explained ? 
The spec. does not seem to clearly define how the association should be done:
http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/shaders.html#FloatVertexAttribute

**Comment by YuanxiangFranck** [comment]
Without duplication, there is no problem the first data is associated to the first color and position...
I think that it is important to add it to the documentation. 

But the problem is when someone need duplicate points for each faces (it is the case for some scientific data mesh).

**Comment by andreasplesch** [comment]
But it does here in the third paragraph:

http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/shaders.html#Pervertexattributes

So it should be like you had expected in the first place.

**Comment by andreasplesch** [comment]
If you need duplicate points for each faces, could you just specify duplicate points in the coords ?

**Comment by YuanxiangFranck** [comment]
Yes that a solution.

I can try to fix the parsing of the FloatVertexAttribute. 

I encountered another problem:

It seems that creaseAngle='3.14' disable normalPerVertex='false'
```html
<IndexedFaceSet id="faceSet" solid="false"
                          coordIndex='0 1 2 -1 0 1 3 -1 '
                          creaseAngle='3.14'
                          normalPerVertex='false'>
<Coordinate point="0 0 0, 0 1 0, 1 0 0, 0 0 1,"></Coordinate>
<Normal vector="1 0 0, 0 0 1, 0 0 1, 0 0 1" ></Normal>
<!-- Expected but did not work : 
<Normal vector="1 0 0, 0 0 1," ></Normal>
-->
```
Should I open a new issue?

**Comment by andreasplesch** [comment]
Yes, I would suggest to open a new issue.

**Comment by andreasplesch** [comment]
Thinking a bit more about what the goal was, a solution is often to use a 1d texture map to visualize data on geometry. The data then become the texture coordinates for each vertex.

**Comment by YuanxiangFranck** [comment]
I already have a function code using textureCooridinate (the texCoord are computed from the data, so I computed the data from the texCoord), but in order to have a simpler and more direct code I would like to use FloatVertexAttribute.

**Comment by andreasplesch** [comment]
OK.

**Comment by YuanxiangFranck** [comment]
The issue can be solved by redefining the handleAttribs function in handle attribut. (inherited from X3DComposedGeometry ).
I belive the problem is the same for all Indexed___ elements. A solution is to change handleAttribs in each class, but that mean lot of copy pasted code...
I think the best is to create a new classe that separate Indexed geometries with the other.

**Comment by andreasplesch** [comment]
This brings up if you could just use IndexedTriangleSet or TriangleSet since they do not have creaseAngle ?
Although they still may duplicate vertices in the normals per face case.

**Comment by andreasplesch** [comment]
http://stackoverflow.com/questions/4580690/normals-per-index
And
http://stackoverflow.com/questions/1664402/how-can-i-specify-per-face-colors-when-using-indexed-vertex-arrays-in-opengl-3-x

Explain how normals per face are really multiple normals per vertex for the GPU which means duplication of vertices.

So it is best to supply normals per vertex in the first place.

**Comment by YuanxiangFranck** [comment]
In this issue I think that duplication isn't the problem. The problem is to have a natural input for the FloatVertexAttribute for the Indexed elements. (IndexedFaceSet , IndexedTriangleSet... )

**Comment by andreasplesch** [comment]
I thought duplication in the creaseAngle=0 case was the problem, since without duplication the FloatVertexAttributes are actually associated with correct vertices ?
Both, creaseAngle=3.14 or normalsPerVertex=false, require duplication of vertices (and normals) for the GPU. So I think the solution you have in mind is to also duplicate the FloatVertexAttributes (just like normals) in this case, and I think this makes sense and should be done.
However, it may be easier to just produce and provide vertices, (constant) per vertex normals and FloatVertexAttributes, eg. all information for each triangle individually, in the first place.
Could you also export (averaged) normals per vertex in a .vtk file ?

**Comment by YuanxiangFranck** [comment]
well, for my project can duplicate the normals in order to have the normal per vertex.
For the fix my idea is to allow anyone to use the FloatVertexAttribute easily and naturally. 
So my solution was to fix the parsing for the attributes in the IndexesFaceSet , so one can use FloatVertexAttribute without settings crease angle=3.14 or have problems with normals

**Comment by andreasplesch** [comment]
Sounds good to me.

**Comment by mlimper** [comment]
Thanks to you two for the analysis!

With the new open issue, would it be fine to close this one?

**Comment by andreasplesch** [comment]
I think a fix which treats FloatVertexAttributes the same way as colors and normals would be good. Could it go into X3DComposedGeometry.js ?
Franck, the spec. defines how nodes should be inherited, so it would better to not have a new class in my view. But x3dom does not always exactly adhere to the spec. in this regard, I believe.

**Comment by YuanxiangFranck** [comment]
Well I have two solution, 
The first is to do a little modification in the FieldChanged function in IndexedFaceSet. Like that from the raw data in _cf._attrib I can use indices to change the data befor saving the in node._shape._dynamyField

The second solution change the handleAttritut function in X3DComposedGeometry, and I can change the data before saving them into _cf._attrib.

The problem with the first solution is that I sould copy/past the modification for each Indexed Geometry like : IndexedTriangleSet, IndexedLineSet ...
