### ISSUE TITLE
Hit position offset for some browsers

### ISSUE THREAD

**Issue by KitWallace** [x3dom/x3dom#602]
The example 

http://doc.x3dom.org/tutorials/animationInteraction/picking/example.html

works correctly in Chrome Version 47.0.2526.111 m

but in Opera 	34.0.2036.47 and Firefox 43.0.4 the hit position is displaced some distance to the right and down. 

Oddly, this behaviour also happens on Chrome when the page is generated from my database (eXistdb with XQuery) although I can't see any significant differences:

http://kitwallace.co.uk/KWMC/eg1.xq

behaviour is the same with both stable and dev versions of x3dom

OS is Windows 7

**Comment by andreasplesch** [comment]
Both work correctly for me on FF 38.5.0 on linux.

**Comment by KitWallace** [comment]
Thanks for testing - I thought this was maybe linked to screen resolution  but both fail for me at widescreen 1600 x 900 and 1280 x 1024

**Comment by KitWallace** [comment]
I've found one source of problem -  if the text is enlarged in the display settings, Firefox and Opera will not set the hitpoint correctly.  However in Chrome, in my setup the hit point is still displaced right and down. However I know Chrome to work on other platforms so there must be some other cause to be found.

**Comment by KitWallace** [comment]
The Chrome problem was due to scaling within the Chrome window so it seems that my problem is really about devicePixelRatio as reported in issue 612.
