### ISSUE TITLE
Node list is duplicated many times in documentation

### ISSUE THREAD

**Issue by mlimper** [x3dom/x3dom#603]
The page at http://doc.x3dom.org/developer/x3dom/nodeTypes/index.html has multiple (>100) copies of the node list

Thanks to @DrX3D for reporting

**Comment by bhaettasch** [comment]
I will look into this.

**Comment by andreasplesch** [comment]
The Viewpoint documentation at

http://doc.x3dom.org/author/Navigation/Viewpoint.html

has duplicated zNear and zFar rows. 

Let me know if I should file a separate issue for this.

**Comment by jamesleesaunders** [comment]
It looks like the node list duplication is still an issue. All the sections are still repeated lots of times.

**Comment by tsturm** [comment]
I think I found the bug in one of the jsdoc templates and fixed it with my last commit f2c9530a6284f84e628bb73bc56c2b2c2c87ba8c
