### ISSUE TITLE
On retina displays, the mouse coordinates will be incorrect.

### ISSUE THREAD

**Issue by rdking** [x3dom/x3dom#612]
On Apple displays, you need to scale your mouse coordinates by window.devicePixelRatio to ensure that logic like "onclick" handlers work properly. Currently, unless the devicePixelRatio is 1, attempts to click an object will fail for those objects not currently very near the top-left corner of the canvas.

**Comment by andreasplesch** [comment]
Just to confirm and to have a concrete case:  this example does not work correctly on Macs ?

http://examples.x3dom.org/example/x3dom_onClickEvent.xhtml

**Comment by rdking** [comment]
Correct. It doesn't work on any display that doesn't have a 1:1
display-to-logical pixel ratio. That includes mobile devices as well.

**Comment by andreasplesch** [comment]
Thanks for confirming. Somebody else would need to figure out how to fix
this.

On Jan 30, 2016 6:25 PM, "rdking" <notifications@github.com> wrote:
>
> Correct. It doesn't work on any display that doesn't have a 1:1
> display-to-logical pixel ratio. That includes mobile devices as well.
> On Jan 28, 2016 12:33 PM, "Andreas Plesch" <notifications@github.com>
wrote:

**Comment by KitWallace** [comment]
I don't think this problem is specific to retinal displays - when this example is run on Firefox or Opera the hit point is displayed - see https://github.com/x3dom/x3dom/issues/602

**Comment by adhoch** [comment]
I seem to have gotten it to work by resizing the canvas and using the solution in #558 the javascript I added is:
`

    function initResize() {
    var desiredWidthInCSSPixels = $('#x3delement').width();
    var desiredHeightInCSSPixels = $('#x3delement').height();
    // Gets the canvas element
    var canvas = document.getElementById("x3dom-x3delement-canvas");
    
    
    // set the display size of the canvas.
    canvas.style.width = desiredWidthInCSSPixels + "px";
    canvas.style.height = desiredHeightInCSSPixels + "px";
    canvas.width = desiredWidthInCSSPixels;
    canvas.height = desiredHeightInCSSPixels;
    }
    function resizeCanvas(event) {
    // Sets the desired dimensions from the x3d element
    // Gets the canvas element
    var canvas = document.getElementById("x3dom-x3delement-canvas");
    canvas.width *= window.devicePixelRatio;
    canvas.height *= window.devicePixelRatio;
    }`

I implemented it  at https://iub.edu/~cyberdh/retinaDisplay/x3dom_onClickEvent.xhtml

**Comment by KitWallace** [comment]
My issue  #602 was also due to pixel ratio since this can be changed by:
 - enlarging text in the display settings 
 - zooming a browser window

**Comment by stephenne** [comment]
Is there a suggested work around as this is a very serious problem

**Comment by tsturm** [comment]
Should be fixed with my last commit 3430335c0088bba5a914e1a028d79b13948c3775

**Comment by stephenne** [comment]
I confirm it now works when I serve it locally. Thank you! BTW The linked version still needs to be brought into step.

**Comment by andreasplesch** [comment]
Can this issue be closed ?

**Comment by stephenne** [comment]
Yes,

Stephenne

> On Mar 17, 2016, at 6:07 AM, Andreas Plesch <notifications@github.com> wrote:
> 
> Can this issue be closed ?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub <https://github.com/x3dom/x3dom/issues/612#issuecomment-197849934>

Stephenne­­­­ Lynne Rhodes
stephenne@rhodesresearch.com
+1 575 201 3241
