### ISSUE TITLE
Shader uniforms not being updated with setAttribute

### ISSUE THREAD

**Issue by coderextreme** [x3dom/x3dom#624]
I have some uniforms/fields on a vertex shader which modify geometry (position and normal).  Changing those fields or uniforms with element.setAttribute doesn't seem to modify the geometry.  I was able to ask recently for a shader cube map uniform to be updateable and Timo did that.  Now I'm asking for scalar uniforms.  Thanks!

**Comment by mlimper** [comment]
Did you try the example from this tutorial?
http://doc.x3dom.org/tutorials/lighting/customShader/index.html

It uses custom uniforms and updates them dynamically when the user manipulates the slider, using "setAttribute".

**Comment by coderextreme** [comment]
Yes, seems to work.  Here’s what doesn’t work for me http://coderextreme.net/sphere.html  I don’t know if it makes a difference that I am changing geometry.  Maybe there’s some caching going on in the shader?  I’m sorry but I must be blind or not know something. I’ll create a very small example.

John

**Comment by coderextreme** [comment]
Okay, I got it working.  The key seemed to be using this function in my animation:

 function changeShaderParamValue(fieldElementName, value)
        {
            var fieldDOMElement = document.getElementById(fieldElementName);

            if (fieldDOMElement)
            {
                fieldDOMElement.setAttribute("value", parseFloat(value));

                var labelElement = document.getElementById(fieldElementName + "Label");

                if (labelElement)
                {
                    labelElement.innerHTML = value;
                }
            }
        }

I am not sure why mine didn’t work.  Puzzling.  Here’s the results: http://coderextreme.net/bumpy.html  The sliders might not work yet.

Thanks,

John

**Comment by coderextreme** [comment]
The problem was that I was trying to set the id attribute as the id, not the value attribute.

John

**Comment by mlimper** [comment]
I see - thanks for clarifying what was the issue.

**Comment by coderextreme** [comment]
Files attached.  See subject.  It could be an old version of X3D?

John
