### ISSUE TITLE
Render Performance

### ISSUE THREAD

**Issue by zhanyiaini** [x3dom/x3dom#628]
I want to optimize my web application. when I rotate the model ,I want to render the model with low quality;when I stop rotate or drag ,I want to render the model with high quality.

X3dom can realize such functionality?

**Comment by zhanyiaini** [comment]
Thanks a lot...

**Comment by andreasplesch** [comment]
AFAIK x3dom does not have a such a built-in option but it is probably possible for you to develop additional code which swaps out complicated elements when the view changes. I would start by simply hiding these to see how well it would work. The time may be better spent on optimization of the content in general, using aopt or features like LOD or culling options.

**Comment by mlimper** [comment]
X3DOM can do this!

You have to use the POP Buffer method to encode your geometry:

http://x3dom.org/pop/

See the examples to see the effect, which can also be tuned using the sliders.

POPGeometry nodes can be created using instantReality aopt, using the "-K" command (similar to binary geometry)

**Comment by mlimper** [comment]
(apart from that, @andreasplesch is also right, of course - if your model is large, it will not only cause slow rendering but also slow downloads, for example)

**Comment by zhanyiaini** [comment]
thanks for all.
I will try it right now.
