### ISSUE TITLE
NurbsPatchSurface not rendered in browsers whereas rendered in x3d viewers

### ISSUE THREAD

**Issue by shivajiwagh** [x3dom/x3dom#640]
I have an x3d file which has few surfaces created using NurbsPatchSurface. These surfaces are rendered properly when I view it in x3d viewer (bitmanagement contact).  
View in firefox 
![111](https://cloud.githubusercontent.com/assets/16300506/14980952/738e49d6-1149-11e6-9926-65f6733bd0df.JPG)
View in Chrome
![2222](https://cloud.githubusercontent.com/assets/16300506/14980965/8ddbef1e-1149-11e6-9ed3-36a877e0d2d6.JPG)
View in Bitmanagement x3d viewer (BS Contact)
![3333](https://cloud.githubusercontent.com/assets/16300506/14980988/ae917274-1149-11e6-8b88-4e259028f62c.JPG)

Why these surfaces created with NurbsPatchSurface are not rendered in browsers? Please share email id so that I can send the actual x3d file for reference. 

following is the short version of  the file I created with only one surface.
<X3D version="3.1" profile="Immersive">
  <Scene>
    <NavigationInfo  headlight="false" type="WALK" avatarSize=" 3.0 68.0 16.0"/>

    <DirectionalLight intensity="0.8" direction="0 1 0"/>
    <DirectionalLight intensity="0.9" direction="0 -1 0"/>
    <DirectionalLight intensity="0.6" direction="1 0 -1"/>
    <DirectionalLight intensity="0.6" direction="-1 0 -1"/>
    <DirectionalLight intensity="0.6" direction="-1 0 1"/>
    <DirectionalLight intensity="0.6" direction="1 0 1"/>

    <Shape>
      <Appearance>
        <Material ambientIntensity="0.2" diffuseColor="1 1 1" emissiveColor="0 0 0" shininess="0.2" specularColor="1 1 1" transparency="0"/>
        
      </Appearance>
      <NurbsPatchSurface solid="false" uDimension="4" uKnot="0 0 0 0.33 1 1 1 1 " vDimension="2" vKnot="0 1 " vOrder="2">
        <Coordinate containerField="controlPoint" point="132.2349 0 569.598 104.8261 0 548.8805 78.77134 0 504.4987 74.03987 0 470.4683 132.2349 120 569.598 104.8261 120 548.8805 78.77134 120 504.4987 74.03987 120 470.4683 "/>
      </NurbsPatchSurface>
    </Shape>

    <Viewpoint description="Center of Space" fieldOfView="0.785" position="553.1368 60 450.348"/>
  </Scene>
</X3D>

**Comment by andreasplesch** [comment]
I believe NurbsPatchSurface is not supported by x3dom. x3d has profiles which define what set of nodes is supported. Here is x3dom's:
http://www.x3dom.org/nodes-2/

**Comment by shivajiwagh** [comment]
Thanks Andreasplesch, is there any other way to create smooth surfaces in x3dom?

**Comment by andreasplesch** [comment]
you can use creaseAngle to get a smoothed display of triangles.

**Comment by andreasplesch** [comment]
@shivajiwagh: Can this issue closed ? If yes, please do.
