### ISSUE TITLE
IndexedFaceSet creates extra faces

### ISSUE THREAD

**Issue by shivajiwagh** [x3dom/x3dom#641]
I have an x3d file created using x3dom and following is the content of the x3d file.

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE X3D PUBLIC "ISO//Web3D//DTD X3D 3.0//EN" "http://www.web3d.org/specifications/x3d-3.0.dtd">
<X3D profile='Interchange' version='3.0' xmlns:xsd='http://www.w3.org/2001/XMLSchema-instance' xsd:noNamespaceSchemaLocation='http://www.web3d.org/specifications/x3d-3.0.xsd'>
  <Scene>
    <NavigationInfo type='"EXAMINE" "WALK" "FLY" "ANY"'/>
    <DirectionalLight intensity="0.8" direction="0 1 0"/>
    <DirectionalLight intensity="0.9" direction="0 -1 0"/>
    <DirectionalLight intensity="0.6" direction="1 0 -1"/>
    <DirectionalLight intensity="0.6" direction="-1 0 -1"/>
    <DirectionalLight intensity="0.6" direction="-1 0 1"/>
    <DirectionalLight intensity="0.6" direction="1 0 1"/>
    <Shape>
      <Appearance>
        <Material ambientIntensity="0.2" diffuseColor="0.1 0.5 0.9" emissiveColor="0 0 0" shininess="0.2" specularColor="0 0 0" transparency="0"/>
        
      </Appearance>
      <IndexedFaceSet coordIndex="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 -1 " ccw="true">
        <Coordinate point="132.2349 0 329.9732 123.0347 0 336.9273 109.9391 0 350.0229 102.985 0 359.223 82.26761 0 386.6317 69.30841 0 436.438 74.03987 0 470.4683 78.77134 0 504.4987 104.8261 0 548.8805 132.2349 0 569.598 191.8598 0 569.598 191.8598 0 689.9727 911.8589 0 689.9727 1032.234 0 569.598 1032.234 0 270.3483 852.2339 0 270.3483 852.2339 0 210.7232 371.8596 0 210.7232 371.8596 0 329.9732"/>
      </IndexedFaceSet>
    </Shape>
    <Viewpoint description="Center of Space" fieldOfView="0.785" position="553.1368 60 450.348"/>
  </Scene>
</X3D>`

The above file creates two extra faces as highlighted by red color in the image below.
![indexface1](https://cloud.githubusercontent.com/assets/16300506/15009679/9163152e-1205-11e6-8d05-b48a841729cf.JPG)

Rotating the view will display the extra faces. 
![indexface2](https://cloud.githubusercontent.com/assets/16300506/15009714/af7d1668-1205-11e6-916e-b04ffb8abe6c.JPG)
Any idea what is wrong in the co-ordinates? or is there something else I need to take care?

**Comment by andreasplesch** [comment]
In what sense are these extra?  Hard to tell from the images what may be wrong. If you want to be safe you could provide the indices for all triangles.

**Comment by shivajiwagh** [comment]
The code is already there in my question. Save the above code as .x3d file you should be able to see it.
However, please find below the points.
`<IndexedFaceSet coordIndex="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 -1 " ccw="true"> <Coordinate point="132.2349 0 329.9732 123.0347 0 336.9273 109.9391 0 350.0229 102.985 0 359.223 82.26761 0 386.6317 69.30841 0 436.438 74.03987 0 470.4683 78.77134 0 504.4987 104.8261 0 548.8805 132.2349 0 569.598 191.8598 0 569.598 191.8598 0 689.9727 911.8589 0 689.9727 1032.234 0 569.598 1032.234 0 270.3483 852.2339 0 270.3483 852.2339 0 210.7232 371.8596 0 210.7232 371.8596 0 329.9732"/> </IndexedFaceSet>`

**Comment by andreasplesch** [comment]
I think what you are trying to say is that the borders of the surface is not what you expect ?

By default IndexedFaceSet ( http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/geometry3D.html#IndexedFaceSet ) has a convex attribute which is set to true. This means that x3dom or other x3d browsers can (or should) assume that the surface border is everywhere convex which helps with performance. If you have a surface which has concave sections ('bays') you need to specify convex='false'. 

The x3d spec. at http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/X3D.html
serves as good documentation for x3dom as well.

**Comment by andreasplesch** [comment]
Here are views with convex='false'
x3dom
![snapshot1](https://cloud.githubusercontent.com/assets/6171115/15015343/5ecaad60-11d9-11e6-87c6-f95bf517e360.png)
cobweb wireframe
![snapshot1](https://cloud.githubusercontent.com/assets/6171115/15015366/82454b06-11d9-11e6-9f7a-d9c272f7b194.png)

**Comment by andreasplesch** [comment]
Can this issue be closed ? If so, please do.

**Comment by shivajiwagh** [comment]
Sure, I will close it.

Thanks
Shivaji

**Comment by andreasplesch** [comment]
thanks
