### ISSUE TITLE
Offset on onClick-event

### ISSUE THREAD

**Issue by cDanowski** [x3dom/x3dom#648]
Hi,

when I try to use onClick-event on any shape, I experience a strange offset to trigger the event. This means, when I click on the actual shape, nothing happens! But when I click right below the shape, then the click event is triggered, although I am visually not hitting the object at all! 

E.g. I used the official test scene located [here](http://doc.x3dom.org/tutorials/animationInteraction/picking/example.html) and to pick any shape I have to use a constant offset as seen in the following screenshot (my curser must be in that position to cause the click event on the box):
![image](https://cloud.githubusercontent.com/assets/11268338/16005944/6887bf72-316a-11e6-9af5-e7e4c5c41a67.png)

I tested a previous x3dom-version (1.6.2 and 1.7.0) and that works as expected! Current version (1.7.1) requires this offset. I also tested it on several browsers. So it seems to be an issue of the current version. Or am I missing something?

**Comment by andreasplesch** [comment]
#612 may be related?

**Comment by cDanowski** [comment]
yes, seems to be related! SInce it has been fixed there, this could be closed.

**Comment by andreasplesch** [comment]
Excellent. Could you close yourself ?

**Comment by feifang** [comment]
Hi, may I ask have your problem been solved? I seem to encounter the exactly same issue with you when using my Macbook Pro Retina. Is there anything we need to modify in our code to change the devicePixelRatio, which was mentioned in #612 ? 
![hoverobject](https://cloud.githubusercontent.com/assets/3634284/18946280/b9d8fb02-8660-11e6-9176-270f205abac7.png)
