### ISSUE TITLE
Need X3DOM HTTPS server to support https site.  Otherwise, content is mixed.

### ISSUE THREAD

**Issue by coderextreme** [x3dom/x3dom#650]
Mixed Content: The page at 'https://www.carlsonsolutiondesign.com/X3DJSONLD/' was loaded over HTTPS, but requested an insecure stylesheet 'http://www.x3dom.org/download/1.7.1/x3dom.css'. This request has been blocked; the content must be served over HTTPS.
www.carlsonsolutiondesign.com/:1 Mixed Content: The page at 'https://www.carlsonsolutiondesign.com/X3DJSONLD/' was loaded over HTTPS, but requested an insecure script 'http://www.x3dom.org/download/1.7.1/x3dom-full.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by cecilemuller** [comment]
I'd recommend using [Let's encrypt](https://letsencrypt.org) to add https support on x3dom.com, it works well and it's out of beta now.

**Comment by andreasplesch** [comment]
I think the recommendation by FHG is to serve x3dom.css and x3dom-full.js from the same server as the web page.
It would be great if x3dom could be on a CDN, however: https://github.com/jsdelivr/jsdelivr

**Comment by alen12345** [comment]
@cecilemuller 
+1 for Let's Encrypt and redirecting all http traffic to https, thus current scripts will not be broken.

That is something we really need.

**Comment by MMesch** [comment]
:+1:  I need this as well!

**Comment by tsturm** [comment]
Loading x3dom over HTTPS should work now ;)

https://www.x3dom.org/download/x3dom.js

**Comment by tsturm** [comment]
The HTTP to HTTPS redirection should also work now:

http://x3dom.org/download/x3dom.js

**Comment by andreasplesch** [comment]
Many examples now do not work from https://x3dom.org since they use http to load x3dom.js:
https://doc.x3dom.org/tutorials/animationInteraction/navigation/example.html 
They need to also start to use https for x3dom.js or protocol relative URLs, //

**Comment by tsturm** [comment]
The Tutorial & Example updating is already in progress.

**Comment by tsturm** [comment]
Tutorials are up to date.

**Comment by andreasplesch** [comment]
Thanks.
