### ISSUE TITLE
Dynamically load x3d-files

### ISSUE THREAD

**Issue by bauerj** [x3dom/x3dom#651]
I'm trying to use x3dom to display dynamically loaded 3D-scenes. The URL to the x3d-file isn't known until after the page loaded.

However, for dynamically added x3d-nodes, the inline-node doesn't get inflated. No request at all is made to the URL.

I slightly modified the inline-example to demonstrate the issue:

[JSfiddle :cloud: ](http://jsfiddle.net/edve4pkd/4/)

The element is properly injected, but it seems like it doesn't load:
![image](https://cloud.githubusercontent.com/assets/598790/17138013/8a4e2858-533e-11e6-955b-4a72c9a83340.png)

Do I need to call an event on the inline-element? Should I download the x3d-file myself and just add it to the DOM? By the looks of the[ loadInline](https://github.com/x3dom/x3dom/blob/442d7e8f2b8dfbb83706c9a6c92c4dcb47054f25/src/nodes/Networking/Inline.js#L153) function, there seems to be a lot more to do.

**Comment by andreasplesch** [comment]
The JSfiddle seems incomplete ? No Deer.x3d and redNose() js function ? In the JSfiddle it looks like x3dom.js is loaded only after the html is rendered/parsed ?

I think Sevaa does something similar here:

http://www.jishop.com/temp/x3d

**Comment by bauerj** [comment]
Indeed, I removed the `redNose` function. You are also correct that it couldn't download `Deer.x3d` but it didn't even try to do so.

This is an example without the reference to `redNose` and with a direct link to `Deer.x3d`:

http://jsfiddle.net/edve4pkd/7/

**Comment by bauerj** [comment]
Thanks for the link, that is essentially what I am trying to do.

**Comment by bauerj** [comment]
So it's possible to change the url of an inline-element to load a new model. That's enough for my use-case and works flawlessly. :+1:

**Comment by andreasplesch** [comment]
Just a note that in jsFiddle, loading x3dom.js last works better:

http://jsfiddle.net/v8b5L60s/

**Comment by bauerj** [comment]
Well yes, that works better because x3dom gets loaded after the element got injected into the DOM :wink: 

If I wait until after  x3dom loaded, the issue shows again:
http://jsfiddle.net/v8b5L60s/2/

**Comment by bauerj** [comment]
Okay, to solve the initial issue, a simple

    x3dom.reload()

does the trick.
