### ISSUE TITLE
LARGE MODEL MISSING FACES

### ISSUE THREAD

**Issue by softscan** [x3dom/x3dom#652]
I have a large X3D model of a Dam and Lake.  The X3D file renders all in InstantReality Viewer and the Blaxxun browser plugin
I converted this to X3DOM-html5 using http://doc.instantreality.org/tools/x3d_encoding_converter/
Now several large planes (Dam Wall and Lake ) and associated Textures do not render
Could Normals be reversed on some ?..very weird- I mainly used  cubes or simple extrusions with texture maps. The lake terrain uses converted DEMs so complex IFS geometry
[X3DOMDam&Lake.zip](https://github.com/x3dom/x3dom/files/389475/X3DOMDam.Lake.zip)
Can send code if that helps

**Comment by andreasplesch** [comment]
The zipped html is an openoffice document saved as html with added formatting. Here is the 'real' html after saving in libreoffice as raw text.
[X3DOMDam&Lake.txt](https://github.com/x3dom/x3dom/files/390619/X3DOMDam.Lake.txt)

**Comment by andreasplesch** [comment]
A screenshot and/or a life x3dom page would help.
x3dom has problems with some extrusions. There is a long Issue.
There is a vrml .wrl inline which x3dom would not be able to render.
If no textures render at all, the web browser may not be able to access the texture files ?
You could remove the <normal></normal> fields for testing since x3dom autogenerates normals.

**Comment by softscan** [comment]
Thanks Andreas. I should have done that instead. The text file is difficult to read in notepad as the formatting is missing. The formatting looks fine in Notepad++ and  loads slowly when renamed to *.html but   a lot is missing .    
I ran it as an inline and it loads rapidly and the faults are evident

**Comment by softscan** [comment]
Hi Andreas
Here are screenshots of the X3D and two X3DOMs (one without the lake)
Hope that helps. Point taken about the file with the inline linked.
I saw some humanoid animation on Instant Reality site- is this possible on X3DOM ?
![x3domdamwall](https://cloud.githubusercontent.com/assets/1946192/17251716/e6dfd536-5577-11e6-88dd-30d455801da5.png)

![damlake_x3d](https://cloud.githubusercontent.com/assets/1946192/17251631/9a40262c-5577-11e6-913f-2c54e30f8cd6.png)
![x3domdamwallinline](https://cloud.githubusercontent.com/assets/1946192/17251653/a615ce52-5577-11e6-91b8-2b744fae414a.png)

**Comment by andreasplesch** [comment]
You need to use x3dom-full.js if you have extrusions. There are two vrml inlines: barracade.wrl and  LakeOnlyCHIZL.wrl. You need to convert those to x3d as well.

**Comment by softscan** [comment]
With x3dom-full.js is that declared as the src = url in the <script> tag ?  OK found the code!. Will fix the vrml. Do I need "physics" for humanoid animation. ? Thanks. A BIG! help.

**Comment by softscan** [comment]
Changed to the following  <link rel='stylesheet' type='text/css' href='http://www.x3dom.org/x3dom/release/x3dom.css'></link>
    <script type='text/javascript' src='http://www.x3dom.org/x3dom/release/x3dom.js'></script> ...   Converted inline wrl files to x3d....  In X3domDam&Lake LakeOnlyCHIZL is an inline : its elevation grid (mountains) is not visible  and Lake is visible. 
The Dam wall is an extrusion see file below
[DamWallExtrusion2.txt](https://github.com/x3dom/x3dom/files/391053/DamWallExtrusion2.txt)
It still does not render

**Comment by andreasplesch** [comment]
For html you will need a full closing a tag. Sorry, but all this looks more like it would be best to read up on x3dom first, then isolate any problems, then look at any debug output (d key) and then perhaps email x3dom-user.

**Comment by softscan** [comment]
Hi Andreas
I have downloaded from the x3d archives BoxMan.xhtml and NancyShootsRifleM24.xhtml (and Json files) and converted the X3d files for these as "X3dom with html5" using the Instant Reality converter and the xhtlm files load but are not animated. The converted x3D files do not load content.
Do you have working X3Dom H-anim animated examples that I can look at?
John
