### ISSUE TITLE
IndexedFaceSet triangulation is incorrect

### ISSUE THREAD

**Issue by sevaa** [x3dom/x3dom#653]
Navigate to http://www.jishop.com/temp/x3d/#facesettrioff

This scene has an IndexedFaceSet which goes:

`<IndexedFaceSet coordIndex="0 1 2 3 4" solid="false">`
`          <Coordinate point="-1 0 0 0 2 0 1 1 0 2 2 0 3 -1 0"/>`
`</IndexedFaceSet>`

See how the green dot doesn't coincide with the angle in the polygon? It should. The third vertex of the polygon is at (1 1 0) and so it the dot.

A copy of the scene file is attached.

[facesettrioff.x3d.txt](https://github.com/x3dom/x3dom/files/390770/facesettrioff.x3d.txt)

**Comment by andreasplesch** [comment]
It looks like a triangulation issue. Here is a map of the vertices with their indices

```
-3x-2x-1xx0xx1xx2xx3x
x
3
x
x
2---------1-----3----
x
x
1------------2-------
x
x
0------0-------------
x
-
1------------------4-
x
```
Vertex 2 defines a concave boundary. Did you try convex='false' ?

**Comment by sevaa** [comment]
Good point. With convex=false, it triangulates right. The standard doesn't say what should the browser do if the convex flag doesn't match the geometry. Using convexity as a hint as to which triangulation algorithm to employ is a reasonable optimization.

Close the issue.

**Comment by andreasplesch** [comment]
http://web3d.org/pipermail/x3d-public_web3d.org/2015-November/003824.html
http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/rendering.html#CommonGeometryFields
