### ISSUE TITLE
Identical geometry, different shading: TriangleSet vs IndexedTriangleSet

### ISSUE THREAD

**Issue by sevaa** [x3dom/x3dom#657]
Browse to http://www.jishop.com/temp/x3d/#TriVsIndTri

The three pyramids are identical, except the bottom one is implemented as an IndexedTriangleSet, the middle one is a TriangleSet, and the top one is an IndexedTriangleStripSet. Why is the first one shaded differently?

IndexedTriangleStripSet is shaded the same as TriangleSet, so it's probably not a vertex reuse/nonreuse issue.

The scene is attached.

[TriVsIndTri.x3d.txt](https://github.com/x3dom/x3dom/files/416335/TriVsIndTri.x3d.txt)

**Comment by andreasplesch** [comment]
Here is a jsbin for quick viewing of the attached x3d:
http://jsbin.com/viyegaluha/edit?html,js,output

The triangles of the indexedTriangleSet do share vertices and normals need to be averaged there. This leads to the interpolated shading across the faces. 
http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/rendering.html#IndexedTriangleSet
says that the default of normalPerVertex is true which means averaged normals.

**Comment by sevaa** [comment]
Triangles in an IndexedTriangleStripSet also share vertices, and there's an identical rule in the spec about normal averaging. In that case, IndexedTriangleStripSet is misshaded. Still a bug.

**Comment by andreasplesch** [comment]
It would be best to close this issue and open a new one for stripset.

**Comment by sevaa** [comment]
Done, #658
