### ISSUE TITLE
WebVR integration

### ISSUE THREAD

**Issue by mkeblx** [x3dom/x3dom#667]
The [WebVR](https://w3c.github.io/webvr/) draft is coming along, with it getting closer to a spec, and with breaking changes since initial draft. It would be useful to have a simple way of getting x3dom content rendering in VR without too much work (i.e. having to manually set up L/R render targets, other setup, etc.), and in an optimized way. Ideally as simple as adding an attribute.

**Comment by mkeblx** [comment]
Working on a PR. Inbound shortly.

**Comment by DrX3D** [comment]
mkeblx,
I was about to start on a branch of X3DOM for that purpose, then Max pointed out your comment. I am happy to support you in any way you need to get this done.

**Comment by jamesleesaunders** [comment]
This is now actively being developed on the webVR branch.
https://github.com/x3dom/x3dom/tree/webVR

**Comment by jamesleesaunders** [comment]
WebVR is now in 1.8.0 :-) This can be closed?
