### ISSUE TITLE
x3dom.DownloadManager.removeDownload example

### ISSUE THREAD

**Issue by bogdanelloo** [x3dom/x3dom#673]
I am trying to use the x3dom.DownloadManager.removeDownload function in order to remove all PENDING XHR calls.
Is there a sandbox || basic example somewhere that I can start with?

Thank you,
bogdan.

**Comment by tsturm** [comment]
Hi, I've add a new function to the DownloadManger to remove all downloads.
Now, you can use ``x3dom.DownloadManger.abortAllDownloads()`` to remove all active XHR calls.

**Comment by bogdanelloo** [comment]
Thank you!
I will check and give feedback asap.

**Comment by bogdanelloo** [comment]
Hi,

The provided: abortAllDownloads, cancelDownload and removeDownload work as expected!

This might sound lazy on my side, but is there a way to get all XHRs assoc. with the object currently being rendered in X3DOM (or which is about to be rendered) without having to keep track myself (in this case through get() function) of the requests map?

Thank you,
Bogdan.

**Comment by bogdanelloo** [comment]
While integrating the DownloadManager with my app I have encountered the following:

1. **Bug** 
_abortAllDownloads()_ function has a typo: j iterator upper range limit is not properly computed.
so replace this: 
_for (var j = 0; j < this.requests.length; j++)_ 
with this:
_for (var j = 0; j < this.requests**[i]**.length; j++)_

2. **Bug** or **Impediment**
_requests_ map property instantiation should also happen inside the Request class, together with the other properties, as below (see **bold**):
       _var Request = function(url, onloadCallback, priority) {
	this.url = url;
	this.priority = priority;
	this.xhr = new XMLHttpRequest();
	this.onloadCallbacks = [ onloadCallback ];_

	**// instantiate requests[priority].array
	if (x3dom.DownloadManager.requests[this.priority] === undefined) {
		x3dom.DownloadManager.requests[this.priority] = [];
	}**
...

I will also create a MR for the above.

**Comment by tsturm** [comment]
I have fixed point one with my last commit 6380a3f2667f406d60ddad2aea079325e1c25d85

To point two: I think it is the right place to instantiate  the request map, because the requests-map is a property of the DownloadManager an not of the Request.

**Comment by bogdanelloo** [comment]
Got it!
