### ISSUE TITLE
texture blinking

### ISSUE THREAD

**Issue by hsinewu** [x3dom/x3dom#679]
Hi, I'm using ImageTexture to display a series of images.

But when I change the url property, it will have a very short period of time the geometry becomes black, and then texture pops up.

I even have a texture below it, but it doesn't change the blinking behavior.

Although I do notice that, once those textures have been displayed once, the second time it can be animated without blinking.

So I wonder if there are some ways I can preload those textures before I call `setAttribute('url', ...)`
, or if there are better ways to do this kind of animation.

Following is the geometry that would have url changed frequently.

```html
<shape>
    <sphere radius="2" subdivision="96,96" solid="false"></sphere>
    <appearance>
        <material transparency="0.1"></material>
        <ImageTexture id="layer1" url="texture1.png">
                <TextureProperties minificationFilter='NEAREST' magnificationFilter='NEAREST'></TextureProperties>
        </ImageTexture>
    </appearance>
</shape>
```

Thanks.

**Comment by tsturm** [comment]
For texture preloading you can simply use a Javascript function like that:

```
function preload( textures )
{
    for ( var i = 0; i < textures.length; i++ )
    {
        var img = new Image();
        img.src = textures[ i ];
    }
}

window.onload = function ()
{
    var textures = ["texture1.png", "texture2.png", "texture3.png", ... ];
    preload( textures );
}

**Comment by hsinewu** [comment]
Thanks @tsturm 
I did try to preload using js (I tried `fetch` and others), but it doesn't seem to have any visible difference, so I was suspicious if there are some x3dom specific loading/buffering or so.

If the answer is not, then I might have to reexamine the code to checkout what was wrong, although it's unlikely I would work on that piece of code anymore.
