### ISSUE TITLE
x3dom "Request" class conflicts with new standard "Request" interface that is part of fetch API

### ISSUE THREAD

**Issue by opticode** [x3dom/x3dom#680]
The x3dom Request class defined in DownloadManager.js conflicts with the new standard Request interface that is part of the (standard) fetch API. See https://developer.mozilla.org/en-US/docs/Web/API/Request

**Comment by mlimper** [comment]
Thanks for pointing this out!

We should probably refactor the Request class to be part of the X3DOM namespace (x3dom.Request), or rename it.

**Comment by bogdanelloo** [comment]
While on the refactoring you should also consider this: https://github.com/x3dom/x3dom/issues/673

**Comment by Sinjins** [comment]
+1 for refactoring Request to be part of the X3DOM namespace

**Comment by mlimper** [comment]
> +1 for refactoring Request to be part of the X3DOM namespace

@bogdanelloo Thanks for your efforts regarding #673! Do you think you could even do this "on the way"?

**Comment by bogdanelloo** [comment]
Yes, I can.
But right now I am full, so I cannot promise any date.

**Comment by tsturm** [comment]
I have moved the Request-Object to the x3dom namespace in my last commit 6380a3f2667f406d60ddad2aea079325e1c25d85.
