### ISSUE TITLE
x3dom object is rendered out of sight after showAll(axis, updateCenterOfRotation) call

### ISSUE THREAD

**Issue by bogdanelloo** [x3dom/x3dom#682]
_Quick description_:
The x3dom object is rendered out of sight after multiple showAll(axis, updateCenterOfRotation) function calls.
I was able to reproduce the issue on this sandbox: http://www.x3dom.org/x3dom/test/functional/runtime.html#
Just click on all: Show all X, Show all -X, Show all Y, Show all -Y, Show all Z, Show all -Z options under _Viewpoint_ list and you will see it.

_Stacktrace_:
_e.runtime.showAll(orientation, true)_ calls _x3dom.Viewarea.prototype.showAll_ which calls _x3dom.fields.SFVec3f_ in order to set the _to_ variable.
After all the other variables are computed a call to animateTo() function is made and our x3dom object is "lost".

_Dirty fix_ (take it as a hint):
Call _runtime.resetView()_ before calling _showAll(axis, updateCenterOfRotation)_

**Comment by bogdanelloo** [comment]
Anyone?

**Comment by tsturm** [comment]
Hi @bogdanelloo,

the issue should be fixed with my last commit 3f212f2c0c0a6bc75424dd8b33d55b14d1b865d8.
Can you try it again with the latest develop version?

**Comment by bogdanelloo** [comment]
Nice @tsturm,

I will try it and get back to you.

Thanks,
Bogdan.

**Comment by bogdanelloo** [comment]
Fix is good!
