### ISSUE TITLE
NavigationInfo before shape results in no content

### ISSUE THREAD

**Issue by splace** [x3dom/x3dom#685]
below shows nothing..
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE X3D PUBLIC "ISO//Web3D//DTD X3D 3.0//EN" "http://www.web3d.org/specifications/x3d-3.0.dtd">
<X3D profile='Immersive' version='3.0' xmlns:xsd='http://www.w3.org/2001/XMLSchema-instance' >
  <Scene>
 <NavigationInfo type='"EXAMINE" "WALK" "FLY" "ANY"'/>
<Shape>
<Appearance><Material diffuseColor=".5 0.5 0"/></Appearance>
<Box size="10 1 1"/>
</Shape>
</Scene>
</X3D>
```   

but moving after shape makes  it work..
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE X3D PUBLIC "ISO//Web3D//DTD X3D 3.0//EN" "http://www.web3d.org/specifications/x3d-3.0.dtd">
<X3D profile='Immersive' version='3.0' xmlns:xsd='http://www.w3.org/2001/XMLSchema-instance' >
  <Scene>
<Shape>
<Appearance><Material diffuseColor=".5 0.5 0"/></Appearance>
<Box size="10 1 1"/>
</Shape>
    <NavigationInfo type='"EXAMINE" "WALK" "FLY" "ANY"'/>
  </Scene>
</X3D>

```

**Comment by andreasplesch** [comment]
Both examples work when I copy and paste them here:
http://andreasplesch.github.io/Library/Viewer/x3dom.html

If used outside of an inline, on a html page, the self-closing tags would not work. You would use <Box></Box>.

**Comment by splace** [comment]
ummmm, these three issues seem related, is it anything to do with xhtml,

i notice this in your viewer
```
<!DOCTYPE html>
<!--html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"-->
<html>
```

doesn't xhtml work?

**Comment by splace** [comment]
thanks for the quick reply BTW

**Comment by andreasplesch** [comment]
x3dom should support xhtml, and therefore strict xml for x3d element content. But it is less tested, and therefore full closing tags are recommended in any case.

The viewer was first intended for cobweb which works with strict xml: http://andreasplesch.github.io/Library/Viewer . You can also paste a .x3d url into the viewer at http://titania.create3000.de/cobweb/

**Comment by splace** [comment]
i will test the effects of doc type on this issue, finding the point between that in-line viewer and my page, where this happens, should reveal much more info.

ironically what im doing is polishing up some old code i wrote for drag/dropping 3d files into a web-page and viewing it using x3dom, prompted by seeing Cobweb.

although Cobweb isn't working for me in Firefox yet (in chrome its ok).

**Comment by andreasplesch** [comment]
A x3dom viewer like that would be great. http://andreasplesch.github.io/Library/Viewer/x3dweb.html is a version for side-by-side viewing of x3dom and cobweb. It looks like your examples work in both.

FF sometimes silently disables functionality after a crash. Then resetting all gfx.* settings in about:config to defaults and restarting works for me,

**Comment by splace** [comment]
well it does seem to be simple the self-closing tags that was the issue, same with the other two reports i will close them.

but, the x3d is generated in javascript; using {dom}.serializeToString, which doesn't seem to have an option to not produce self-closing tags.

however i can, i guess, just push the {dom} into the Scene rather than a string, i was intending this, just hadn't got round to it.

**Comment by splace** [comment]
>  A x3dom viewer like that would be great.

yes, i think so. 

BTW it's, mostly, able to convert wrl (vrml 2.0) and .x3dv () into x3d, and i was looking at a general system that should be able to cope, eventually, with a large number of formats.(some easier than others mind you.) 

it's got a half-way complete .ptx importer.(fairly simple)

i intend to put it on github.io.

also:

it  decompresses (.gz'ed) files on the fly.
and you can drag html links, as long as they are on the same domain or have cross-domain access set.

**Comment by andreasplesch** [comment]
You are referring to http://ptex.us/documentation.html#fileformat ?
cobweb has a full vrml parser, not sure if this would be helpful.
Even if not quite complete/working it might be nice to see a first implementation.

**Comment by splace** [comment]
> You are referring to http://ptex.us/documentation.html#fileformat ?

no, .ptx is a point cloud format, very basic. (VERY like .pts, or .xyx) 

> cobweb has a full vrml parser, not sure if this would be helpful.

does cobweb use x3dom? 

and

i was thinking this should be extensible to a lot of formats, in a way .wrl is a test, if the pattern can cope with that, the majority of formats would be simpler.

> Even if not quite complete/working it might be nice to see a first implementation.

well, im thinking of github as sort of advertising myself, and this was just a testing hack, which is why i'm fixing it up, but don’t see why it should take more than a couple of  weeks.

**Comment by andreasplesch** [comment]
Cobweb does not use x3dom, or three.js. It has vrml format support, protos and scripts and is more a traditional x3d browser. It does not have the advanced features of x3dom such as render texture or the binary nodes. Also by default it is not DOM integrated.

**Comment by splace** [comment]
ok thanks, i'll comment here when i get it up loaded.
