### ISSUE TITLE
Including x3dom.js twice results in infinite recursion

### ISSUE THREAD

**Issue by martinal** [x3dom/x3dom#687]
This is a problem when using x3dom in output cells in Jupyter Notebooks, see this page using Chromium:
http://nbviewer.jupyter.org/github/garth-wells/fenics-x3dom/blob/master/DOLFIN_X3DOM.ipynb

Chromium devs have investigated the issue, and found the culprit. Quoting https://bugs.chromium.org/p/chromium/issues/detail?id=663288#c6

> The problem on http://nbviewer.jupyter.org/github/garth-wells/fenics-x3dom/blob/master/DOLFIN_X3DOM.ipynb is caused by including x3dom.js twice on the same page.
> 
> Including x3dom.js twice causes infinite recursion due to the way it hooks getElementsByTagName:
> 
> // inside x3dom.js
> document.__getElementsByTagName = document.getElementsByTagName;
> document.getElementsByTagName = function(tag) {
>   // ... (calls __getElementsByTagName) ...
> };
> 
> When the second <script> tag referecing x3dom.js is removed, the script successfully renders the <x3d> elements.
>

**Comment by tsturm** [comment]
Should be fixed with my last commit bf647208e0968dfc766e985cb2a17f4863f6f572

**Comment by martinal** [comment]
Following the example link above I can confirm it now works. Thanks!
