### ISSUE TITLE
Track Downloads per Multipart Node

### ISSUE THREAD

**Issue by mlimper** [x3dom/x3dom#688]

**Comment by bogdanelloo** [comment]
I am already using an slightly extended version of DownloadManager and a x3dom implementation with respect to the previously mentioned DM in order to have full control on all XHR calls in the executionqueue such that I can cancel them on geom/mesh change event => increased speed, lower bandwidth, better UX and it is working as a charm!

**Comment by mlimper** [comment]
That sounds great - looking forward to your PR!

**Comment by david-zacharias** [comment]
@bogdanelloo Please share more information about your extended version.

**Comment by bogdanelloo** [comment]
Hi,

I have checked with our legal dept. and it seems that we need some approval in order for me to be able to post the sources here.

While waiting for the approval:
@mlimper - I can send it to you over e-mail.
@david-zacharias - I cannot share the full source at this moment, but I would be happy to answer any specific questions that you have.

**Comment by mlimper** [comment]
> @mlimper - I can send it to you over e-mail.

You could, but then I am not sure how we would proceed - our goals would anyway be to have this functionality in the main X3DOM repository. Another way would be to set up NDAs to share this feature "offline" with selected partners - but this is against the spirit of X3DOM, and also makes things pretty complicated.

Maybe we can discuss at a higher level, without source code, while waiting for approval.
So, here's a more specific question, related to this ticket:

Is your current implementation able to tell how many downloads are currently left for a specific MultiPart? Imagine, for example, your scene would consist of three major components, each in one MultiPart, and you would like to see, for each MultiPart, when its downloads have been finished. This is the essential feature we are looking for right now.

**Comment by bogdanelloo** [comment]
@mlimper 

> Is your current implementation able to tell how many downloads are currently left for a specific MultiPart? 
No, it is not!
I am currently tracking all async XHR calls in the execution queue without diff. with respect to a specific multi-part.

**Comment by tsturm** [comment]
I inspect the code and the DownloadManager was only used for the PopGeometry, not for BinaryGeometry and not for anything else.

To not break the PopGeometry I added the new RequestManager, which now handles all x3dom downloads with the ecxeption of the PopGeometry.

With the new RequestManager you are able to:

* Set the maximum number of parallel requests:

    ```x3dom.RequestManager.maxParallelRequests```

* Set the withCredentials flag for all requests:

    ```x3dom.RequestManager.withCredentials```

* Add request headers for all requests:

   ```x3dom.RequestManager.addRequestHeader( header, value );```

* Abort all requests:

    ```x3dom.RequestManager.abortAllRequests();```

The best place to setup the RequestManager is the document or window onload-callback:

```javascript
document.onload = function()
{
    x3dom.RequestManager.maxParallelRequests = 50;
    x3dom.RequestManager.withCredentials = true;
    x3dom.RequestManager.addRequestHeader( "Cache-Control", "no-cache");
};
```

**Comment by bogdanelloo** [comment]
Thank you @tsturm

I do have one question: 
`x3dom.RequestManager.maxParallelRequests` is set by default to **40**, while `x3dom.DownloadManager.maxDownloads` is set by default to **6**, why?

Cheers,
Bogdan.

**Comment by mlimper** [comment]
> x3dom.DownloadManager.maxDownloads is set by default to 6

Regarding this point: we learned that the parallel number of downloads which a browser will perform is usually a fixed, low number - such as 6:
http://stackoverflow.com/questions/5765113/do-modern-browsers-still-limit-parallel-downloads

That's why we thought it doesn't make sense to have a higher number in the Download Manager.

**Comment by bogdanelloo** [comment]
Yes, I am aware of this, but then how come max parallel requests is by default set to 40?

**Comment by tsturm** [comment]
The original DownloadManager was implemented mid of 2012 for a very specific task (PopGeometry) and also the stackoverflow post is five years old.

I have made good experiences in different other projects with ~40 max. parallel requests. Really low max. parallel requests often kills the performance.

@bogdanelloo Do you have any issues with the current default?

**Comment by bogdanelloo** [comment]
@tsturm No, no issues. BTW: this can be closed.
