### ISSUE TITLE
withCredentials Setting in DownloadManager

### ISSUE THREAD

**Issue by mlimper** [x3dom/x3dom#689]
This involves encapsulation of all XHR construction calls inside the X3DOM DownloadManager

**Comment by bogdanelloo** [comment]
I am already using an slightly extended version of DownloadManager and a x3dom implementation with respect to the previously mentioned DM and it is working as expected!

**Comment by mlimper** [comment]
Sounds great!
Could you contribute this as a PR?

**Comment by tsturm** [comment]
I inspect the code and the DownloadManager was only used for the PopGeometry, not for BinaryGeometry and not for anything else.

To not break the PopGeometry I added the new RequestManager, which now handles all x3dom downloads with the ecxeption of the PopGeometry.

With the new RequestManager you are able to:

* Set the maximum number of parallel requests:

    ```x3dom.RequestManager.maxParallelRequests```

* Set the withCredentials flag for all requests:

    ```x3dom.RequestManager.withCredentials```

* Add request headers for all requests:

   ```x3dom.RequestManager.addRequestHeader( header, value );```

* Abort all requests:

    ```x3dom.RequestManager.abortAllRequests();```

The best place to setup the RequestManager is the document or window onload-callback:

```javascript
document.onload = function()
{
    x3dom.RequestManager.maxParallelRequests = 50;
    x3dom.RequestManager.withCredentials = true;
    x3dom.RequestManager.addRequestHeader( "Cache-Control", "no-cache");
};
```
