### ISSUE TITLE
"Zoom full" button

### ISSUE THREAD

**Issue by glr91** [x3dom/x3dom#691]
Hello.

I would like to make a "zoom full" button to display objects as big as possible, but without altering its orientation (which may have been modified interactively). I have tried with `showAll` and `showObject`, but these change the orientation. 

The only idea I have is to get the equivalent viewpoint after rotating the objects interactively, and set this as
the current viewpoint, but I do not know how to do this. Then I would change de field of view to adjust the object to the scene.

Any help to solve the problem, or any other approach to implement the "zoom all" button would be appreciated, thanks.

**Comment by bogdanelloo** [comment]
Hi,

HI,

Have you tried fitAll?

Cheers,
Bogdan.

**Comment by bogdanelloo** [comment]
PS: you may also try showAll(true, '') - which will show all setting the center of rotation nad keeping the current orientation. If you do not wanna set the center of rotation just set the boolean param to false.
What x3dom version are you using?

**Comment by glr91** [comment]
Thank you so much, `fitAll` seems to work correctly.

**Comment by glr91** [comment]
I am using version 1.7.1. I have tried `showAll`, as you have proposed, but it changes the orientation. Thank you for your advice, it has been very helpful.

**Comment by bogdanelloo** [comment]
You are welcome!
PS: it is working properly in version 1.7.2-dev
