### ISSUE TITLE
Unexpected Zoom result

### ISSUE THREAD

**Issue by glr91** [x3dom/x3dom#692]
Hello.

When I get very close to a 3D object using the mouse wheel and the navigation mode _examine_, the axes  of the object are inverted, as well as the effect of the mouse wheel. As a result, if I keep turning it, I see the object further. I noticed that this only happens when using an `OrthoViewpoint` node. If I use a `Viewpoint` node, the result of turning the mouse wheel is as I would expect to.

Is this the expected result? Thanks.

**Comment by bogdanelloo** [comment]
Hi,

What x3dom version are you using?
Try with the last stable version 1.7.2

**Comment by glr91** [comment]
I was using version 1.7.1. With version 1.7.2 it works as expected. Thank you!

**Comment by bogdanelloo** [comment]
I was also experiencing this behaviour with a previous x3dom version and this might be related with the fact that zooming through objects while using the orthographic viewpoint is not possible because the , so instead a mirroring  was happening.

**Comment by glr91** [comment]
Yes, I agree with you. I think that the result of the new version is more sensible.
