### ISSUE TITLE
X3DOMMetaGroup not setup for dynamically added nodes

### ISSUE THREAD

**Issue by david-zacharias** [x3dom/x3dom#693]
Nodes added to `<X3DOMMetaGroup>` at runtime are detected by x3doms  _onNodeInserted_-Handler, but since parent is a `<X3DOMMetaGroup>` without `_x3domNode`-Propert, these nodes won't get processed. Fix would be to find parentNode by walking up the DOM as long as parentNode is `<X3DOMMetaGroup>`.

I will supply a PR.

**Comment by tsturm** [comment]
Merged ;)
