### ISSUE TITLE
Texture not loaded

### ISSUE THREAD

**Issue by gravivector** [x3dom/x3dom#704]
Hi,

In my application the same external x3d model loaded and erased dynamically. Model are loaded, but texture are not shown. Sometime it is happens and sometime is not. What is a right procedure to load external file ? Shall I use some additional function or shall I wait some period of time ? Sometime texture do not present if it is a static loading. For example:

                <transform id="model_0_transform" render="true" translation="1,0,0">
                    <Inline id="x3d_model_0" nameSpaceName="x3d_model_0" url="x3d/human/0.x3d" />
                </transform>
                <transform id="model_1_transform" render="true" translation="2,0,0">
                    <Inline id="x3d_model_1" nameSpaceName="x3d_model_1" url="x3d/human/1.x3d" />
                </transform>
                <transform id="model_2_transform" render="true" translation="3,0,0">
                    <Inline id="x3d_model_2" nameSpaceName="x3d_model_2" url="x3d/human/2.x3d" />
                </transform>
                <transform id="model_3_transform" render="true" translation="4,0,0">
                    <Inline id="x3d_model_3" nameSpaceName="x3d_model_3" url="x3d/human/3.x3d" />
                </transform>
                <transform id="model_4_transform" render="true" translation="5,0,0">
                    <Inline id="x3d_model_4" nameSpaceName="x3d_model_4" url="x3d/human/4.x3d" />
                </transform>

**Comment by andreasplesch** [comment]
If you can provide more information, or a reproducible example scene, there is a better chance to get a useful response.

**Comment by andreasplesch** [comment]
Possibly a cors issue. Try adding crossOrigin='anonymous' to the TextureImage node.
