### ISSUE TITLE
Texture is not displayed correctly There is a glTF model

### ISSUE THREAD

**Issue by cx20** [x3dom/x3dom#707]
I tried to display the glTF sample using X3DOM 1.7.3-dev

https://cx20.github.io/gltf-test/examples/x3dom/index.html?category=sampleModels&model=BoxTextured&scale=1&type=glTF-Binary

However, the texture is attached to only one side of the box.
![image](https://cloud.githubusercontent.com/assets/1833979/21813709/7a8d9c10-d79a-11e6-91c2-cde9db781d52.png)

The texture should be affixed to all sides of the cube.
https://github.com/cx20/gltf-test/tree/master/sampleModels/BoxTextured

<img src="https://raw.githubusercontent.com/cx20/gltf-test/master/sampleModels/BoxTextured/screenshot/screenshot.png">

**Comment by cx20** [comment]
The following models also have no texture.

https://cx20.github.io/gltf-test/examples/x3dom/index.html?category=sampleModels&model=Avocado&scale=0.5&type=glTF-Binary
![image](https://cloud.githubusercontent.com/assets/1833979/21854545/736bae9e-d85e-11e6-94ff-680c95aa92cd.png)

https://cx20.github.io/gltf-test/examples/x3dom/index.html?category=sampleModels&model=BarramundiFish&scale=0.05&type=glTF-Binary
![image](https://cloud.githubusercontent.com/assets/1833979/21854618/c0eb2bfe-d85e-11e6-8fca-4e82714bb690.png)

https://cx20.github.io/gltf-test/examples/x3dom/index.html?category=sampleModels&model=SmilingFace&scale=1&type=glTF-Binary
![image](https://cloud.githubusercontent.com/assets/1833979/21854690/0504c340-d85f-11e6-9d22-0df9f3c4ac58.png)

**Comment by skluge** [comment]
Thanks. I will look into this issue.

**Comment by skluge** [comment]
This pull request should solve the texture issues. 
I tested all the mentioned cases and they now seem to work fine.

The hardest one was the cube, because everything seemed to work fine. It was a problem with non power of two textures and in webgl not supported sampling options. These textures are now automatically resized.

@mlimper Please merge pull request

**Comment by mlimper** [comment]
> @mlimper Please merge pull request

Done - thanks for the fixes.

@cx20 Could you try again with the latest dev?

**Comment by cx20** [comment]
I confirmed that it was fixed in the latest version of x3dom.js.
The sample below has been updated.
https://cx20.github.io/gltf-test/

https://cx20.github.io/gltf-test/examples/x3dom/index.html?category=sampleModels&model=BoxTextured&scale=1&type=glTF-Binary
![image](https://cloud.githubusercontent.com/assets/1833979/22066245/6fffb306-ddcf-11e6-9b26-e543cd8848ae.png)

**Comment by mlimper** [comment]
Thanks a lot to both of you!
