### ISSUE TITLE
ColorRGBA node not working

### ISSUE THREAD

**Issue by glr91** [x3dom/x3dom#713]
Hello.

I have been using the `ColorRGBA`  node in an external x3d file (read in my html file with an `inline` node) and it works correctly. I now need to insert my x3d directly into my html file. So, I copied the `Shape` node which is in my x3d file into my html file (inside an `Scene` node). However, the browser now does not change the color of the mesh, keeping it gray. 

The code in my x3d file is something like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE X3D PUBLIC "ISO//Web3D//DTD X3D 3.3//EN"  "http://www.web3d.org/specifications/x3d-3.3.dtd">
<x3d>
  <head>
    <meta name="title"/>
  </head>
  <Scene>
    <Shape id="shape_id">
      <Appearance>
        <Material DEF="MA_Nose" id="piece_material"/>
      </Appearance>
      <IndexedFaceSet coordIndex="bla bla bla" solid="true">
        <Coordinate point="bla bla bla"/>
        <colorrgba color="bla bla bla" id="geometry_colors"/>
      </IndexedFaceSet>
    </Shape>
  </Scene>
</x3d>
```

My html file initially looks like this:

```
<!DOCTYPE html>
<html> 
 <head>
  <script type='text/javascript' src='http://www.x3dom.org/download/x3dom.js'></script> 
  <link rel='stylesheet' type='text/css' href='http://www.x3dom.org/download/x3dom.css'></link> 
 </head>
 <body> 
  <x3d> 
    <scene>
      <inline url="my_file.x3d/"> </inline>
    </scene>
  </x3d>
 </body>
</html>
```

And I have changed it to:

```
<!DOCTYPE html>
<html> 
 <head>
  <script type='text/javascript' src='http://www.x3dom.org/download/x3dom.js'></script> 
  <link rel='stylesheet' type='text/css' href='http://www.x3dom.org/download/x3dom.css'></link> 
 </head>
 <body> 
  <x3d> 
    <scene>
      <Shape id="shape_id">
        <Appearance>
          <Material DEF="MA_Nose" id="piece_material"/>
        </Appearance>
        <IndexedFaceSet coordIndex="bla bla bla" solid="true">
          <Coordinate point="bla bla bla"/>
          <colorrgba color="bla bla bla" id="geometry_colors"/>
        </IndexedFaceSet>
      </Shape>
    </scene>
  </x3d>
 </body>
</html>
```

Is it a bug, or am I doing something wrong? Thank you so much.

**Comment by andreasplesch** [comment]
The .x3d inline is read as XML which supports self-closing tags. The .html file does not support self-closing tags. Try explicit closing tags, such as </Material> and </Coordinate>. Also, colorrgba presumably needs to be closed. The console may report some related errors.

**Comment by glr91** [comment]
Sorry, I forgot the `/` character in the colorrgba tags. As you have suggested, by closing all the tags explictly in the html file, the problem is solved. Thanks, your advice has been very helpful.

**Comment by andreasplesch** [comment]
Glad to help.
