### ISSUE TITLE
Browser Support Google Chrome

### ISSUE THREAD

**Issue by messerbill** [x3dom/x3dom#719]
Hi,
i just implemented X3Dom into my Angular2 application and it seems to work correctly. But only in Firefox, when i try to test it in my google chrome browser, i recieve a "browser does not support x3dom" warning.

Initially i thought this may happen because of Angular2, but that is not the problem, because the example at https://doc.x3dom.org/tutorials/basics/hello/index.html is also not working in google chrome. 

But documentation tells that chrome is supported. What is the problem here?

**Comment by andreasplesch** [comment]
Chrome is supported. Webgl may have become disabled on your chrome. Does
https://get.webgl.org work ?

**Comment by messerbill** [comment]
https://get.webgl.org is not working at my place. All WebGL relevant settings are enabled. 

http://doesmybrowsersupportwebgl.com/ also tells me "Nay" on chrome. My Chrome Version is latest (Version 56.0.2924.87 (64-bit))

**Comment by andreasplesch** [comment]
Please feel free to close the issue as it seems not related to x3dom.

**Comment by andreasplesch** [comment]
Thanks. After crashes chrome sometimes disables webgl. Chrome://gpu may be helpful.

**Comment by messerbill** [comment]
Yes that seems to be happened in my case. Your Chrome://gpu link made me find the solution. I've had to activate "Override Software rendering list" in my chrome://flags to make it working (following this link: http://stackoverflow.com/questions/40472961/webgl-unavailable-gpu-process-unable-to-boot)

Thanks again & best regards,
Ole

**Comment by andreasplesch** [comment]
No problem.
