### ISSUE TITLE
TextureProperties.anisotropicDegree doesn't seem to work

### ISSUE THREAD

**Issue by stefaniapedrazzi** [x3dom/x3dom#740]
Independently on the value set to the `TextureProperties.anisotropicDegree` field, I'm getting the same texture filtering result.
I tested values between 0 and 1 and up to 360, but I couldn't notice any difference.
https://doc.x3dom.org/author/Texturing/TextureProperties.html

Here is my test object:
```
<Shape id='19' isPickable='false'>
 <Appearance id='20'>
  <Material id='21'>
  </Material>
  <ImageTexture id='22' url='"textures/road.jpg"' containerField='' origChannelCount='3'>
   <TextureProperties anisotropicDegree="16" generateMipMaps="true" minificationFilter="AVG_PIXEL" magnificationFilter="AVG_PIXEL"/>
  </ImageTexture>
 </Appearance>
 <IndexedFaceSet id='23' DEF='ROAD_GEOMETRY' coordIndex='0 1 2 -1 1 0 3 -1 3 4 1 -1 4 3 5 -1 5 6 4 -1 6 5 7 -1 7 8 6 -1 8 7 9 -1' normalIndex='0 0 0 -1 0 0 0 -1 0 0 0 -1 0 0 0 -1 0 0 0 -1 0 0 0 -1 0 0 0 -1 0 0 0 -1' texCoordIndex='0 1 2 -1 1 0 3 -1 3 4 1 -1 4 3 5 -1 5 1 4 -1 1 5 3 -1 3 2 1 -1 2 3 0 -1'>
  <Coordinate point='-3.6 0 100, -1.8 0 0, -3.6 0 0, -1.8 0 100, 0 0 0, 0 0 100, 1.8 0 0, 1.8 0 100, 3.6 0 0, 3.6 0 100'>
  </Coordinate>
  <Normal vector='0 1 0'>
  </Normal>
  <TextureCoordinate point='50 1, 0 0.833, 0 1, 50 0.833, 0 0.667, 50 0.667'>
  </TextureCoordinate>
 </IndexedFaceSet>
</Shape>
```

**Comment by andreasplesch** [comment]
A quick search

https://github.com/x3dom/x3dom/search?utf8=%E2%9C%93&q=anisotropicDegree&type=

indicates that this field (http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/texturing.html#TextureProperties) is not implemented.

**Comment by andreasplesch** [comment]
https://github.com/create3000/cobweb/search?utf8=✓&q=anisotropicDegree&type=

Cobweb also does not implement the field.

**Comment by andreasplesch** [comment]
https://www.khronos.org/registry/webgl/extensions/EXT_texture_filter_anisotropic/

exists, so it could be supported.

**Comment by tsturm** [comment]
Now, it should work if the extension is available.

**Comment by andreasplesch** [comment]
I believe most if not all system would have it by now. Here is quick hack which force enables:

https://gist.github.com/andreasplesch/eba7386c110100190bfa99a6a75047c1/raw/6dacff99f4f195356d053c45c714f40818793108/x3dom_force_anisotropic_filtering.user.js

before:

![image](https://cloud.githubusercontent.com/assets/6171115/25668930/20e34fac-2ff6-11e7-910f-a7a516197d6b.png)

after force enabling at max. degree:

![image](https://cloud.githubusercontent.com/assets/6171115/25668781/aa14a09c-2ff5-11e7-8bb6-359ac3c9ea15.png)

I think well worth supporting, no ?

**Comment by andreasplesch** [comment]
Ah, I see:

https://github.com/x3dom/x3dom/commit/87a5c8575948cc07a3c9b28963e77a65ddbb9f71

Perhaps also update the Siena example to use the dev build ?

**Comment by stefaniapedrazzi** [comment]
Thank you to look at this issue so quickly!

**Comment by andreasplesch** [comment]
Here is the Siena example without and with (forced) anisotropic filtering using the nightly build after Timo's commit:
without:
![image](https://cloud.githubusercontent.com/assets/6171115/25708667/2a39592e-30b5-11e7-9e2a-2941a3211e64.png)

with:
![image](https://cloud.githubusercontent.com/assets/6171115/25708298/14ffb770-30b4-11e7-8930-f6dfe701fd85.png)
works great !
You could close this issue yourself if your use case is resolved.

**Comment by stefaniapedrazzi** [comment]
Ok, I will test and close the issue.

Thank you for mentioning the nightly build.
Previously I didn't know where to find the latest x3dom-full.js, but now I found it.

**Comment by stefaniapedrazzi** [comment]
It is fixed for my scene too. Thank you!
