### ISSUE TITLE
Extending CardboardVR example, forked version?

### ISSUE THREAD

**Issue by AlbertoSanBaz** [x3dom/x3dom#743]
Hello,

I've been trying to extend the Google Cardboard Classroom Example (https://examples.x3dom.org/Demos/ClassroomVR/classroom-cardboard.html) from www.x3dom.org for a university proyect. I realized that using current release of x3dom.js brings me to a canvas loading forever.

When a looked at the local file of x3dom.js used by the example, it is marked as version 2.0.0-dev, although it also said to be from 2014. Does anybody know if this is some kind of fork or the kind of code that it is including (maybe an early version of webVR)?

Thanks a lot.

**Comment by paulmasson** [comment]
Tested the linked example on an Oculus Go and was able to load it and enter VR without any problems. This issue can likely be closed.
