### ISSUE TITLE
TwoSidedMaterial tag not working

### ISSUE THREAD

**Issue by dpkchaudhary** [x3dom/x3dom#745]
There is a bug in the library. see this example [Link](https://examples.x3dom.org/example/x3dom_twoSidedMaterial.html) . This example shows a single material (red) instead of two (red and blue):

**Comment by andreasplesch** [comment]
It looks like x3dom 1.6.2 is the last version when it still worked:
https://alabaster-celsius.glitch.me/
1.7.1, 1.7.2 and 1.7.3dev all do not work.
So perhaps you can just go back to 1.6.2 ?

**Comment by dpkchaudhary** [comment]
It's working. Thanks.
Actually we are looking for Two side texture tag in x3dom. I will open an issue for it.
