### ISSUE TITLE
All JS files minified?

### ISSUE THREAD

**Issue by DanielRuf** [x3dom/x3dom#75]
Where are the unminified / human readable versions? 

On x3dom.org/download are just minified versions
Human readable is something other

Also I need the answers to my issues but it seems you just reference to sourceforge. But why? You changed from SF to Github. Why should I subscribe there when you develop here?

**Comment by doczoidberg** [comment]
there are still no separate .min.js and .min.css files?

**Comment by godenji** [comment]
@doczoidberg apparently not. I'd argue the far bigger problem is the 5MB+ whitespace laden XML file that one has to send over the wire. While gzip'ing helps (only transfer @1MB) it would be nice to strip down the XML file to the bare minimum *before* gzip'ing.

FWIW, the css file is all of 6KB, much more time savings to be had minifying the js file. Anyway, GruntJS/Gulp can handle this task easily...if you know these build tools that is.
