### ISSUE TITLE
Error inserting texture on face

### ISSUE THREAD

**Issue by JohnTuga** [x3dom/x3dom#750]
I'm making a futuristic car in X3DOM. When I add the texture to one of the faces, the message appears in the viewer: HARDWARE-RENDERING. The car disappear. Without texture everything works. What I'm doing wrong? Thanks for helping.

My code:
<!doctype html>
<html>

<head>
    <meta encoding="utf-8">
    <title>Carro futurista</title>
    <script src="./lib/x3dom-full.js"></script>
    <link rel="stylesheet" href="./lib/x3dom.css">
</head>

<body>
    <x3d width="500px" height="500px">
        <Scene>

            <shape DEF="cubo">
                <appearance>
                    <material diffuseColor="#787878">
                    </material>
                </appearance>
                
                <indexedfaceset id="formaCarro" coordIndex="
                    0 8 7 6 5 4 3 2 1 0 -1 
                    9 10 11 12 13 14 15 16 17 9 -1
                    18 26 25 24 23 22 21 20 19 18 -1
                    27 28 29 30 31 32 33 34 35 27 -1

                    0 1 10 9 -1
                    1 2 11 10 -1
                    2 3 12 11 -1
                    3 4 13 12 -1
                    4 5 14 13 -1
                    5 6 15 14 -1
                    6 7 16 15 -1
                    7 8 17 16 -1
                    8 0 9 17 -1

                    18 19 1 0 -1
                    19 20 2 1 -1
                    20 21 3 2 -1
                    21 22 4 3 -1
                    22 23 5 4 -1
                    23 24 6 5 -1
                    24 25 7 6 -1
                    25 26 8 7 -1
                    26 18 0 8 -1

                    9 10 28 27 -1
                    10 11 29 28 -1
                    11 12 30 29 -1
                    12 13 31 30 -1
                    13 14 32 31 -1
                    14 15 33 32 -1
                    15 16 34 33 -1
                    16 17 35 34 -1
                    17 9 27 35 -1
                ">
                    
                    <coordinate point="
                        0.975 -0.75 0.6
                        -0.975 -0.75 0.6
                        -1 -0.725 0.6
                        -1 0.725 0.6
                        -0.975 0.75 0.6
                        0.775 0.75 0.6
                        0.8 0.725 0.6
                        1 0 0.6
                        1 -0.725 0.6
                        
                        0.975 -0.75 -0.6
                        -0.975 -0.75 -0.6
                        -1 -0.725 -0.6
                        -1 0.725 -0.6
                        -0.975 0.75 -0.6
                        0.775 0.75 -0.6
                        0.8 0.725 -0.6
                        1 0 -0.6
                        1 -0.725 -0.6

                        0.95 -0.725 0.625
                        -0.95 -0.725 0.625
                        -0.975 -0.7 0.625
                        -0.975 0.7 0.625
                        -0.95 0.725 0.625
                        0.75 0.725 0.625
                        0.775 0.7 0.625
                        0.975 0 0.625
                        0.975 -0.7 0.625

                        0.95 -0.725 -0.625
                        -0.95 -0.725 -0.625
                        -0.975 -0.7 -0.625
                        -0.975 0.7 -0.625
                        -0.95 0.725 -0.625
                        0.75 0.725 -0.625
                        0.775 0.7 -0.625
                        0.975 0 -0.625
                        0.975 -0.7 -0.625
                    ">
                    </coordinate>
                </indexedfaceset>
            </shape>

            <shape>
                <appearance>
                    <ImageTexture url="./media/lateral.jpg">
                        <ImageTexture/>
                </appearance>
                <IndexedFaceSet solid="true" ccw="true" coordIndex="18 26 25 24 23 22 21 20 19 -1">
                    <Coordinate USE="formaCarro">
                    </Coordinate>
                </IndexedFaceSet>
            </shape>
        </Scene>
    </x3d>
</body>

</html>

This is the error:
![capturar](https://user-images.githubusercontent.com/29932477/27887682-e06c18c6-61d9-11e7-955c-a9f3579ef8d6.PNG)

**Comment by andreasplesch** [comment]
The end tag is </imagetexture>, not <imagetexture/> .

**Comment by JohnTuga** [comment]
Thanks, I have already corrected this error but it remains the same.

**Comment by andreasplesch** [comment]
https://juniper-wool.glitch.me/

The DEF for USE was missing.

**Comment by JohnTuga** [comment]
Thanks, really, you save me.

**Comment by andreasplesch** [comment]
You are welcome. Please feel free to close this issue.

**Comment by JohnTuga** [comment]
I had a one more problem. I need to put this box upright. I can not figure out how the 4 coordinates work. How to solve it? Thanks.

My code:
<!doctype html>
<html>

<head>
    <meta encoding="utf-8">
    <title>Carro futurista</title>
    <script src="./lib/x3dom-full.js"></script>
    <link rel="stylesheet" href="./lib/x3dom.css">
</head>

<body>
    <x3d width="500px" height="500px">
        <Scene>
            
            <transform translation="-0.5 0 0.6">
                <transform rotation="0 0 0 0">
                    <shape>
                        <appearance>
                            <material diffuseColor="#989c8e">
                            </material>
                        </appearance>
                        <box size="1.55 0.05 0.15" />
                    </shape>
                </transform>
            </transform>
        </Scene>
    </x3d>
</body>

</html>

**Comment by JohnTuga** [comment]
I had a one more problem. I need to put this box upright. I can not figure out how the 4 coordinates work. How to solve it? Thanks.

My code:

            <transform translation="-0.5 0 0.6">
                <transform rotation="0 0 0 0">
                    <shape>
                        <appearance>
                            <material diffuseColor="#989c8e">
                            </material>
                        </appearance>


                        <box size="1.55 0.05 0.15" />
                    </shape>
                </transform>
            </transform>
