### ISSUE TITLE
how to have multi view of same scene and updating the multi views at same time

### ISSUE THREAD

**Issue by jhcjorge** [x3dom/x3dom#765]
i am work actually with technology 3XD and 3XDOM, and I have a question about of a web page with multi view of the same scene. I see the example of webpage the x3dom.org of the `[multiview](https://examples.x3dom.org/example/x3dom_multiView.xhtml)` but of different scenes. I wish know if you can help me, or  else linking me others one that you will believe can help me.
I need to have a webpage with mutiview of same scene at same time. A view of bird, and two more of the front and back.

**Comment by andreasplesch** [comment]
Generally it is more appropriate to use the x3dom-user mailing list for questions. You would probably need to just duplicate the bird for each view. One easy way to do this is to use an Inline node and link to the same url from each scene.
It sounds like you may want to disable mouse navigation for each view: https://doc.x3dom.org/author/Navigation/NavigationInfo.html, explorationMode='none'
