### ISSUE TITLE
regression-suite billboard.html broken?

### ISSUE THREAD

**Issue by bmaLPC** [x3dom/x3dom#766]
I was looking for functionaility in X3DOM to get the same data as X3D proximitySensor position_changed and orientation_changed fields and I came across  x3dom/test/regression-suite/test/cases/billboard/billboard.html which seems to accomplish the same thing with the methods viewMatrix and getWorldToCameraCoordinatesMatrix. But the method set_cot generates an error because there is no element with id someUniqueId. Is something broken? How can I accomplish what I am trying to do?

**Comment by andreasplesch** [comment]
In the example, 'x3d' would need to replace 'someuniqueid' since runtime is a property of the x3d element.

#638 shows how to get position and orientation of the current viewpoint from the viewpointchanged event object.

**Comment by andreasplesch** [comment]
Here is the example, somewhat adjusted:

https://jsfiddle.net/7f1oprk0/

(Not sure how the center of rotation was actually meant to behave)

**Comment by bmaLPC** [comment]
Thank you. Is there documentation on the X3DOM events?

**Comment by andreasplesch** [comment]
I had a similar question a while ago: https://github.com/x3dom/x3dom/issues/464#issuecomment-70726114
I believe the viewpointChanged may be the only event documented only in issues and posts but not on the web site.
