### ISSUE TITLE
Touch Sensor are not working in HTML after converted from .x3d or .wrl

### ISSUE THREAD

**Issue by shona14** [x3dom/x3dom#774]
Touch sensor are not working in browser but it is working in x3d player, In this BE1 file there are two buttons red and green when we press green wheel rotates and red stops when we play in player, but html file is not reacting it. Please give the solution as soon as possible.

[BE1.zip](https://github.com/x3dom/x3dom/files/1349951/BE1.zip)

**Comment by andreasplesch** [comment]
I suspect the missing touchtime field is the issue: See
https://github.com/x3dom/x3dom/search?q=touchsensor&type=Issues&utf8=%E2%9C%93

Please narrow down the example to confirm.

**Comment by andreasplesch** [comment]
Ok, the issue is not touchtime and not TouchSensor but a Script node. The scene uses a X3D script node which conflicts with HTML Script elements. You could replace the script node with Event Utility nodes for which I have prototype x3dom implementations (some here #770) . Alternatively, you could replace the X3D script and related ROUTEs with HTML scripting and onclick event handlers.

**Comment by andreasplesch** [comment]
A BooleanFilter to only react to isActive true events for both buttons, and an additional BooleanFilter to negate to false for the stop button may do the trick.

**Comment by andreasplesch** [comment]
After including BooleanFilter.js

```js
<script type='text/javascript' src='https://rawgit.com/andreasplesch/x3dom/EventUtilities/src/nodes/EventUtilities/BooleanFilter.js'></script>
```

it may be possible to use this adaption instead of the Script node:


```xml
      <!--Script DEF='PLATFORMFILTER'>
      <field accessType='inputOnly' name='input' type='SFBool'/>
      <field accessType='inputOnly' name='stopme' type='SFBool'/>
      <field accessType='initializeOnly' name='boolValue' type='SFBool' value='false'/>
      <field accessType='outputOnly' name='output' type='SFBool'/><![CDATA[javascript:
      function input(value, time) {
         if (!boolValue) boolValue = value; output = boolValue;
      } 
	  function stopme(value, time){
          boolValue = FALSE; 
		  output = FALSE;
      }	  
	]]>
    </Script-->
    <BooleanFilter DEF='onlyTrue' ></BooleanFilter>
    <BooleanFilter DEF='flip' ></BooleanFilter>
    
    <!--ROUTE fromNode='greenme' fromField='isActive' toNode='PLATFORMFILTER' toField='input'/-->
    <ROUTE fromNode='greenme' fromField='isActive' toNode='onlyTrue' toField='set_boolean'></ROUTE>
    <!--ROUTE fromNode='PLATFORMFILTER' fromField='output' toNode='timer' toField='set_loop'/-->
    <ROUTE fromNode='onlyTrue' fromField='inputTrue' toNode='timer' toField='set_loop'></ROUTE>
    <!--ROUTE fromNode='redme' fromField='isActive' toNode='PLATFORMFILTER' toField='stopme'/-->
    <ROUTE fromNode='redme' fromField='isActive' toNode='onlyTrue' toField='set_boolean'></ROUTE>
    <ROUTE fromNode='onlyTrue' fromField='inputTrue' toNode='flip' toField='set_boolean'></ROUTE>
    <ROUTE fromNode='flip' fromField='inputNegate' toNode='timer' toField='set_loop'></ROUTE>
```

**Comment by shona14** [comment]
not working can u please make change to file directly please...

**Comment by andreasplesch** [comment]
Please narrow down the example.
