### ISSUE TITLE
camelcase convention

### ISSUE THREAD

**Issue by pgruenbacher** [x3dom/x3dom#776]
React 16 just unexpectedly broke all my x3dom components because it refuses to output html elements or attributes in camelcase, but forces them into lowercase. https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html

Any thoughts on how feasible it is for me to fork x3dom in order to have x3dom handle lowercase node names and all lowercase attributes?

**Comment by andreasplesch** [comment]
All lowercase attributes should be fine in html:
https://bl.ocks.org/andreasplesch/d26be938673f7cd89194377111173ef6

unless in xhtml and in Inlines which need to be proper x3d xml, eg. case sensitive.

**Comment by pgruenbacher** [comment]
@andreasplesch you're right, the lowercase convention works actually since getAttribute and setAttribute cast to lowercase anyways.

However there's still this issue where React16 will not accept custom elements that don't have a dash in them. See the issue below:

https://github.com/facebook/react/issues/11184#issuecomment-335903935

I'm already mantaining a fork of x3dom, so I may just refactor all of the node logic to accept x3d- prefixes to the elements.

**Comment by pgruenbacher** [comment]
I resolved the issue by changing all custom elements from `<customElement is customAttr="0.3"/>` to `<custoElement is="x3d" customAttr="0.3"/>`. I had accidentally thought **is** attribute was deprecated. No need for the dash convention.

**Comment by andreasplesch** [comment]
Glad it worked out. Do you have a blog post or similar that talks a bit about react and x3dom ?

For reference:

https://github.com/facebook/react/issues/11184

X3DOM existed before the dash recommendation. X3DOM tries to adhere to the X3D standard which does not use dashes.

The only conflict between X3D and HTML is the script element. But x3dom does not implement the X3D script element anyways.

**Comment by pgruenbacher** [comment]
I don't have a blog post, but I should. React encapsulates x3dom components pretty well and is a good use-case for making x3dom applications at the level of CAD editor complexity. I do sometimes wonder what it would take to directly convert x3dom nodes to React components instead of React outputting the x3dom tags and having x3dom read from the dom. Hard to say if that would make any difference on performance or not.
