### ISSUE TITLE
Support for data urls?

### ISSUE THREAD

**Issue by tom95** [x3dom/x3dom#785]
It appears that assigning data urls to the url property of ImageTexture is currently not possible (or I'm doing something wrong)

Code like the following results in the default grid texture being displayed:
```
document.getElementById('floor-texture').setAttribute('url', canvas.toDataURL('image/png'))
```
floor-texture being an ImageTexture element and canvas a HTMLCanvasElement

**Comment by andreasplesch** [comment]
Hmm, it should work, see #373:

http://rawgit.com/mabuchner/c879283f913ceff54b29/raw/e93d7eee3498f40de6c7c98dc0c8076441bcd2d6/dataURLTest.html

Probably best to provide a short example gist,fiddle,glitch .

**Comment by andreasplesch** [comment]
You may be able to use the canvas element directly as the texture:

https://examples.x3dom.org/example/x3dom_canvas.html

**Comment by andreasplesch** [comment]
It may interesting to find out if ObjectUrls work:

ImageTextureEl.url = URL.createObjectURL(canvas.toBlob()) or so.

This would avoid the large DataURI strings.

https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

**Comment by tom95** [comment]
All of the above work indeed, thanks a lot for the pointers and sorry for the false alarm!

toBlob/createObjectURL is indeed working:
```
canvas.toBlob(blob => {
  let objUrl = URL.createObjectURL(blob)
  document.getElementById('floor-texture').setAttribute('url', objUrl)
})
```

The pointer to the canvas "embedding" was particularly helpful (including the hack with `invalidateGLObject`)

**Comment by andreasplesch** [comment]
Excellent. `invalidateGLObject` , I think, is for forcing updates.
