### ISSUE TITLE
Synchronized Viewpoints

### ISSUE THREAD

**Issue by PCH3DPrintLab** [x3dom/x3dom#790]
Can anyone recommend a pathway for me to synchronize viewpoints over two x3d scenes similar to a main x3d and a helper x3d?

The more simple, the better. I won't need viewpoint resetting or orthogonal view buttons, just a very simple synchronization over two viewpoints.

**Comment by andreasplesch** [comment]
#638 might help. In the viewpointchanged handler you would set the other viewpoint's attributes.

These kind of questions are a better fit for x3dom-user mailing list.

**Comment by andreasplesch** [comment]
Here is what I had in mind:
https://bl.ocks.org/andreasplesch/0914a2e3119237335a703806ed97de7a

**Comment by andreasplesch** [comment]
It gets more tricky if the viewpoints are inside inlined x3d content. The x3d spec. requires that IMPORT/EXPORT statements are used to make this viewpoints available. x3dom actually will treat any inlined content just as children of the inline node and you can use the namespacename attribute to avoid collisions.

https://bl.ocks.org/andreasplesch/fcffcce2722eb0a5b9520d8a52ee732e

**Comment by PCH3DPrintLab** [comment]
That did it, Thank you so much. I will put together a second prototype with public domain files - with the same intent of my prototype - for an example that you may use.

**Comment by andreasplesch** [comment]
Excellent. I updated the sync code a bit to avoid the globals.

**Comment by PCH3DPrintLab** [comment]
Just FYI, the latest code doesn't seem to be working for me anymore. The previous iteration is still completely workable for my prototype though. Thank you again.
