### ISSUE TITLE
multiline stringsensor

### ISSUE THREAD

**Issue by shona14** [x3dom/x3dom#792]
[StringSensor.zip](https://github.com/x3dom/x3dom/files/1503806/StringSensor.zip)
I want to write multiple line in this code. as this code write in a single line..

#VRML V2.0 utf8
# X3D-to-VRML-97 XSL translation autogenerated by X3dToVrml97.xslt
# http://www.web3d.org/x3d/content/X3dToVrml97.xslt
# Generated using XSLT processor: SAXON 9.1.0.2 from Saxonica

# [X3D] VRML V3.3 utf8
# PROFILE Immersive
# [X3D] version=3.3
# [X3D] noNamespaceSchemaLocation=http://www.web3d.org/specifications/x3d-3.3.xsd
# [head]

# META "title" "StringSensor.x3d"
# META "description" "A StringSensor example that displays typed text in the world."
# META "creator" "Leonard Daly and Don Brutzman"
# META "created" "7 June 2006"
# META "modified" "15 September 2008"
# META "reference" "http://X3dGraphics.com"
# META "reference" "http://www.web3d.org/x3d/content/examples/X3dResources.html"
# META "rights" "Copyright (c) 2006, Daly Realism and Don Brutzman"
# META "subject" "X3D book, X3D graphics, X3D-Edit, http://www.x3dGraphics.com"
# META "identifier" "http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter08-UserInteractivity/StringSensor.x3d"
# META "generator" "X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit"
# META "license" "../license.html"

# [Scene] ========== ========== ==========

NavigationInfo { type [ "EXAMINE" "ANY" ] } ###  Default X3D NavigationInfo

Background {
  skyColor [ 1 1 1 ]
}
Viewpoint {
  description "Book View"
  position -0.02 0.01 6.85
}
DEF GenText StringSensor {
  deletionAllowed TRUE
  enabled TRUE
}
Transform {
  children [
      Transform {
        translation 0 0 -.1
        children [
            Shape {
              appearance Appearance {
                material Material {
                  diffuseColor 1 1 .6
                }
              }
              geometry Box {
                size 8 1.5 .01
              }
            }
        ]
      }
      Transform {
        translation -3.8 0.2 0
        children [
            Shape {
              appearance Appearance {
                material Material {
                  diffuseColor 0 0 1
                }
              }
              geometry DEF DisplayText Text {
                length [2] 
				fontStyle FontStyle {
                  justify [ "BEGIN" "MIDDLE"  ] 
                  size 0.75
				  
                }
              }
            }
        ]
      }
      # convert StringSensor SFString into Text node MFString by using explicit typecasting in ECMAScript
      DEF Converter Script {
        eventIn      SFString	SFString_MFString
        eventOut     MFString	MFString_out

	url [ "converter.js" "http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter08-UserInteractivity/converter.js"
 ]
      }
  ]
ROUTE GenText.enteredText TO Converter.SFString_MFString
ROUTE Converter.MFString_out TO DisplayText.string
}

**Comment by andreasplesch** [comment]
A question for saxonica  or the x3d-public@web3d mailing list ?
