### ISSUE TITLE
glTF x3dom support

### ISSUE THREAD

**Issue by chmouton** [x3dom/x3dom#799]
Dear all,

I would like to demonstrate how x3dom could display some gltf files from different 3D datawarehouse like Poly, remix3d (for example this nice model of three snowy houses https://www.remix3d.com/details/G009SWMNX5FF?section=remixes ) etc. 
It seems that the official glTF x3dom example is broken: https://examples.x3dom.org/gltf/

Do you know if x3dom could load such gltf models?
Kind regards

Christophe

**Comment by andreasplesch** [comment]
If Paint 3D can export gltf 1.0 binary format then there is a chance that it will work:

https://andreasplesch.github.io/gltf-test/

But most exporters/editors are moving on to gltf 2.0 which is not yet supported in x3dom.

**Comment by andreasplesch** [comment]
Pretty sure Paint 3d only supports glTF 2.0. Part of the challenge for supporting it will be PBR materials  as these require different shaders than x3d materials, but have to coexist somehow.

**Comment by andreasplesch** [comment]
[just a note: the externalshape in the example now does not show the milktruck because in the .glb (gltf v.1.0) it is actually defined as completely transparent, it needs to be fixed]
