### ISSUE TITLE
Regeneration of online documentation

### ISSUE THREAD

**Issue by paulmasson** [x3dom/x3dom#810]
The most recent update to the documentation on x3dom.org appears to be 14 March 2016, almost two years ago. Some of the documentation pages have even older dates. That is not a good sign for an active project.

Many of the pages documenting nodes are unusable on a mobile device due to a CSS wrapping issue. This was corrected by me on #780, and I've made additional improvements to tutorial files. It would be nice to see my changes as well as those that have accumulated in the last two years in the publicly available files.

I sent an email to @jbehr in early December concerning this issue, since he is listed as the administrative contact for the organization. I received no response and there has been no change since then.

Andreas Plesch is aware of this issue, but has not told me who has access to the x3dom.org server and can update the documentation. I'm mentioning major contributors below in the hope that someone will tell me who can take care of regenerating the documentation on the server.

@aha @aarbelaiz @bhaettasch @chrstein @mlimper @mthoener @tsturm @yjung 

Thank you in advance for your response.

**Comment by andreasplesch** [comment]
Thanks for the reminder. I do not know who could publish regenerated docs
on x3dom.org. You are right, FHG is not very responsive these days.

Another minor doc issue is that some fields of some nodes are marked x3dom
although they are official x3d fields and vice versa.

For now, you could perhaps generate and publish somewhere else, gh pages or
glitch ?

Thanks again for your help.

**Comment by paulmasson** [comment]
So here's a freshly generated version of the documentation:

https://paulmasson.github.io/x3dom-docs/

I spent time over the last two years contributing to the [SageMath](https://github.com/sagemath) project, and perhaps their model for handling documentation would be appropriate here. They maintain a repository that is just a copy of the documentation generated from source code and redirect its GitHub pages to their custom subdomain. All pull requests for updates still go into the main code repository, not the copy.

That would make it easy for a concerned party to regenerate the documentation any time, but still requires someone at FHG to configure the redirection. Here are the relevant instructions:

https://help.github.com/articles/quick-start-setting-up-a-custom-domain/
https://help.github.com/articles/setting-up-a-www-subdomain/

**Comment by andreasplesch** [comment]
To me, any way to make it easier to contribute and help with maintenance would be a plus. I added a provisional link from the github x3dom wiki to the freshly generated docs here:

https://github.com/x3dom/x3dom/wiki

Let me know if this is ok. It may be helpful for those who actually discover the wiki.

**Comment by paulmasson** [comment]
@andreasplesch fine with me, but in my experience GitHub wikis are not particularly discoverable. The information is better off in the main repository. 

Then again, if FHG fails to respond there’s not much point in working on this repository.

**Comment by mlimper** [comment]
> Hey FHG, is anyone alive?

Alive, but not enough time to work on X3DOM (that didn't change)... in my personal opinion, it looks like one should check options regarding the future hosting / maintenance of the Web page, but that should probably be done offline / via skype / via email, probably also together with the Web3D working group - I'm not in the loop there, so don't know what's the state of discussion, and I'm also not responsible on the FHG side (-> won't decide if FHG will give away the Web page), so that's just my two cents here.

**Comment by paulmasson** [comment]
@tsturm could someone please update the official documentation? Thank you!
