### ISSUE TITLE
Compatibility with DOM libraries.

### ISSUE THREAD

**Issue by trusktr** [x3dom/x3dom#816]
Hello there,

I tried to select an x3dom element from the DOM (f.e. using jQuery), then modify an attribute (f.e. setting `translation` to something else) but it doesn't seem to work.

Or, for example, I tried to use the element inspector to find the element, then I manually modified attributes in the inspector, but that didn't do anything.

For these elements to be compatible with common HTML tools like React, Angular, Vue, and even jQuery, the elements would need to react to these changes.

This would be a great addition to x3dom. 😃

**Comment by trusktr** [comment]
Another thing to consider, which not even A-Frame does yet, is to make these elements compatible with Shadow DOM.

This would make them highly composable in reusable web components.

**Comment by andreasplesch** [comment]
Thanks for your interest. x3dom should be generally compatible with DOM libraries:

https://examples.x3dom.org/editor/component_editor/
#776 
https://mavo-issue-317.glitch.me/
http://bl.ocks.org/camio/5087116

Since x3dom is around for a longer time, it uses older methods and could use an overhaul with respect to events and attribute management. Contributions always welcome.

Here is an exploration of making web components:
https://x3dom-webprotos-3.glitch.me/

**Comment by trusktr** [comment]
Hmmm, I wonder why it wasn't working for me. I'll have to take another look...

**Comment by andreasplesch** [comment]
I noticed that modifying attributes in the inspector does not trigger changes anymore as well. You can use the property tab in the inspector or the console $0.setAttribute().

https://examples.x3dom.org/example/x3dom_jQueryManip.xhtml

**Comment by andreasplesch** [comment]
Please feel free to continue here, in the closed issue.

**Comment by trusktr** [comment]
I made an [issue about this](https://bugs.chromium.org/p/chromium/issues/detail?id=804610) in the Chromium tracker. Let's see what they say.

**Comment by andreasplesch** [comment]
Let's see, it may be too exotic an application. Does it work with other custom elements ?

**Comment by trusktr** [comment]
Yeah, for example with my custom elements in [this demo](https://codepen.io/trusktr/pen/rpegZR), right-click-inspect one of the buttons, then on the parent `i-dom-plane` element adjust the values of the `align` or `mountpoint` attributes and you'll see that the buttons will move to new positions. (the values are 3 numbers for X Y a Z axis)

**Comment by andreasplesch** [comment]
Yes, that works. (The demo makes my browser very unresponsive, especially with devtools).
It may have to do with x3dom redefining .setAttribute here:
https://github.com/x3dom/x3dom/blob/343d2d1148dfea3c514453cc8a3f01b709e3bbb3/src/NodeNameSpace.js#L319
(I believe this is from before MutationObserver was widely available).
Devtools may not use the current .setAttribute function.
