### ISSUE TITLE
X3DOM needs to support glTF image and shader base64 encoded uri property

### ISSUE THREAD

**Issue by cx20** [x3dom/x3dom#822]
[COLLADA2GLTF](https://github.com/KhronosGroup/COLLADA2GLTF/) v1.0 compatibility feature is currently being developed in Khronos repository.
I tried the v1.0 output of `glTF-Binary` with the new COLLADA2GLTF and found that it can not be displayed with X3DOM.

```
x3dom.debug.js:8230 
Uncaught TypeError: Cannot read property 'KHR_binary_glTF' of undefined
    at x3dom.glTF.glTFLoader._loadShaderSource (x3dom.debug.js:8230)
    at x3dom.glTF.glTFLoader.loadShaderProgram (x3dom.debug.js:8190)
    at x3dom.glTF.glTFLoader.loadMaterial (x3dom.debug.js:8144)
    at x3dom.glTF.glTFLoader.loadglTFMesh (x3dom.debug.js:7949)
    at x3dom.glTF.glTFLoader.updateMesh (x3dom.debug.js:7774)
    at x3dom.glTF.glTFLoader.traverseNode (x3dom.debug.js:7737)
    at x3dom.glTF.glTFLoader.traverseNode (x3dom.debug.js:7728)
    at x3dom.glTF.glTFLoader.updateScene (x3dom.debug.js:7715)
    at x3dom.glTF.glTFLoader.getScene (x3dom.debug.js:7671)
    at XMLHttpRequest.xhr.onload (x3dom.debug.js:36500)
```
It is probably because the layout of the glTF file has changed. However, there is no problem with the specification.

![image](https://user-images.githubusercontent.com/1833979/36347534-5279e1b2-149c-11e8-9c0b-68a96517ab8b.png)

X3DOM needs to support glTF image and shader base64 encoded uri property. For details, please refer to the link below.
https://github.com/KhronosGroup/COLLADA2GLTF/pull/83#issuecomment-366480453

**Comment by andreasplesch** [comment]
I believe this is the test URL ?
https://cdn.rawgit.com/cx20/gltf-test/31f4e4de4e2a82894af84f8803a47c11bb0a34ef/examples/x3dom/index.html?category=sampleModels&model=Duck&scale=1&type=glTF-Binary

**Comment by andreasplesch** [comment]
https://github.com/x3dom/x3dom/blob/master/src/util/glTF/glTFLoader.js

loadImage() currently does not but could deal with data Uris.
_loadShaderSource() currently does not but could also do so.

**Comment by andreasplesch** [comment]
Do you happen to know which data source should be preferred if both bufferview and URI are available  ?

**Comment by cx20** [comment]
> I believe this is the test URL ?

Yes. It is that URL. All other samples can be tried below. It is a test of the model outputted by COLLADA2GLTF v 1.0 compatible feature.
https://cdn.rawgit.com/cx20/gltf-test/31f4e4de4e2a82894af84f8803a47c11bb0a34ef/index.html

> loadImage() currently does not but could deal with data Uris.
> _loadShaderSource() currently does not but could also do so.

I think that it is desirable to support Data URI.

> Do you happen to know which data source should be preferred if both bufferview and URI are available ?

I am sorry but I do not know the order of precedence when both are set. However other libraries may be helpful. For example Three.js seems to see extension first.
https://github.com/mrdoob/three.js/blob/r86/examples/js/loaders/GLTFLoader.js#L968-L1003

**Comment by andreasplesch** [comment]
https://github.com/KhronosGroup/glTF/blob/master/extensions/1.0/Khronos/KHR_binary_glTF/README.md#gltf-schema-updates

actually says
```
To support embedded shaders and images, shader and image glTF properties have new KHR_binary_glTF extension properties that should be used instead of the uri property. See Listings 2 and 3.
```

So supporting data urls seems like going the wrong direction.

**Comment by andreasplesch** [comment]
For reference: glTF 2.0 only allows one data source:

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#images

So the behaviour is undefined in case of multiple sources. So probably should just follow three.js.

**Comment by cx20** [comment]
I understand. I think you don't have to think about the case where both data sources exist.

**Comment by andreasplesch** [comment]
Here are the tests with a patch applied to the glTF loader in x3dom:
https://rawgit.com/andreasplesch/gltf-test/1.0-collada2gltf-compatible-test/index.html
The patch allows for data urls for shader sources, and all static examples seem to work.
Do you know if any of the examples use data urls for images (for textures) ? WIthout an example it is hard to produce to come up with a good solution.
In any case, I can PR the patch if you can confirm that it addresses the issue.

I noticed that some of the animated examples like brainstem do not display anymore although they used to with the original glTFs. Any idea what change could have caused this ?

**Comment by andreasplesch** [comment]
https://github.com/x3dom/x3dom/pull/823 is submitted and was merged. The dev version build should be available in 24h.
Please give it a try and feel free to reopen the issue if issues remain.

**Comment by andreasplesch** [comment]
https://github.com/cx20/gltf-test/pull/29
