### ISSUE TITLE
How is "metadata" put in an X3DNode?

### ISSUE THREAD

**Issue by BrunoB69** [x3dom/x3dom#826]
There is no example in the docs, how to give "metadata" in an X3DNode and all of its descendants. The only information that is given on this topic is:

<X3DNode metadata='X3DMetadataObject' ></X3DNode> 

which is insufficient. How do i put an 'X3DMetadataObject' in the XML node. Clearly nested XML Tags are forbidden so i can not simply put one as it is described in the doc page for "Node: X3DMetadataObject".

**Comment by andreasplesch** [comment]
markdown swallowed the tag in your comment:

> The only information that is given on this topic is:

```<X3DNode metadata='X3DMetadataObject' ></X3DNode> ```

x3dom tries to follow the x3d standard which is a good resource for documentation purposes:
http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/core.html#Metadata
http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/core.html#Nodereference

The spec. is linked from each x3dom node doc. page.

Here is an example scene:

http://x3dgraphics.com/examples/X3dForWebAuthors/Chapter15Metadata/MetadataNodeExamplesIndex.html

Here is a chapter out of a x3d book:

http://x3dgraphics.com/examples/X3dForWebAuthors/Chapter15Metadata/Chapter15MetadataInformation.html

Note the use of the containerfield attribute.

**Comment by BrunoB69** [comment]
Well unfortunately the specs and the example in you links are not very helpfull. I am looking for a way to add a single string of meta data to a grouping node. This case is not covered in the example. The spec lists in section 2.1 "purpose and functionality"  in b. my case of use, but does not give any explanation an no example how to do that. I can not see how the containerfield attribute can be usefull in this my case.

**Comment by andreasplesch** [comment]
containerField is a quite unintuitive concept to understand. Here is how you could proceed if you are willing to spend some time:

- lookup group: https://doc.x3dom.org/author/Grouping/Group.html
- notice it has a metadata field of type SFNode
- notice that it has a children field of type MFNode
- notice that by default in examples children of the Group element are the value of the 'children' field as you would expect.
- discover the tooltips (http://www.web3d.org/x3d/content/X3dTooltips.html#Group).
- learn how containerfield (a strange concept) can be used to define a specific parent field - child link
- apply to your use case:
```
<Group DEF='USA'>
  <MetaDataString containerField='metadata' value=' "all States of the USA" '></MetaDataString>
  <Shape USE='CA'></Shape>
  <Shape USE='MA'></Shape>
  <Shape USE='NY'></Shape>
</Group>
```

**Comment by andreasplesch** [comment]
Let me close this but feel free to continue on the mailing list, or perhaps here.

**Comment by BrunoB69** [comment]
Thanks for guiding me through the maze of x3dom documentation. Anyways, I have just added a custom attribute to the group nodes in question in my project, because time was tight. 
By the way the link to x3d docs on the in  https://doc.x3dom.org/author/Grouping/Group.html is broken.

**Comment by andreasplesch** [comment]
Very good. Use of custom data attributes is definitely a good option possible with x3dom. Metadata would allow compatibility with other X3D systems.
