### ISSUE TITLE
Z-Fighting rendering problem for overlapping planes.

### ISSUE THREAD

**Issue by tomssd** [x3dom/x3dom#827]
We have a scene with terrain that is built using an ElevationGrid.

When the ElevationGrid overlaps an IndexedFaceSet or any plane (box, etc..) there is flickering (Z-Fighting).

Example:
http://contractsoftware.com/flicker/

I have tried a few things (w/no luck) to solve this problem:

Adjusting the visibility limit based on the advice below from:
   http://www.web3d.org/x3d/content/X3dTooltips.html#NavigationInfo
   (visibilityLimit / avatarSize.CollisionDistance) < 10,000

Adding DepthMode based on issue 13 (Rendering Bug (DepthMode))
<DepthMode readOnly="true"></DepthMode>

**Comment by andreasplesch** [comment]
The heights of the el. grid range from 0 to 0.02 but it is shifted by -0.01. So the y range is from -0.01 to 0.01. The top of box is at 0.005, the bottom at -0.005, both intersect. The flickering occurs around the intersections, for a limited y range, say 0.001. The horizontal dimension is 10, eg. 10000x this y range. It could be just a numerical precision limit, of GL or doubles. Not sure how to get around this, increase the rendering depth precision. There may worth checking other x3d browsers to see if this achievable.

**Comment by andreasplesch** [comment]
Closing. Please reopen as necessary.
