### ISSUE TITLE
x3db in browser

### ISSUE THREAD

**Issue by n4562** [x3dom/x3dom#832]
Hello,

I am using paraview to export a scene to x3d and x3db format.
x3db format is 5.5MiB while x3d is 31.5 MiB, therefore I'd like to use the x3db format. But I can't seem to be able to inline it in html?

Regards,
Nr

**Comment by andreasplesch** [comment]
x3dom does not support the x3d binary encoding, .x3db . You may be able to use aopt (https://doc.x3dom.org/tutorials/models/aopt/index.html) to optimize the x3d. Keep in mind that the large x3d file is automatically gzip compressed and uncompressed by the web server and browser when transported.
