### ISSUE TITLE
Discuss these patches.  I think these patches are essential.  Do you?  Thanks!

### ISSUE THREAD

**Issue by coderextreme** [x3dom/x3dom#833]
```
diff --git a/src/fields.js b/src/fields.js
index 484b5c4e..dc9d70f0 100755
--- a/src/fields.js
+++ b/src/fields.js
@@ -2914,7 +2914,7 @@ x3dom.fields.MFVec3f.parse = function(str) {

 x3dom.fields.MFVec3f.prototype.copy = function()
 {
-    x3dom.fields.MFVec3f.copy(this);
+    return x3dom.fields.MFVec3f.copy(this);
 };

 x3dom.fields.MFVec3f.prototype.setValueByStr = function(str) {
@@ -2937,6 +2937,13 @@ x3dom.fields.MFVec3f.prototype.toGL = function() {
     return a;
 };

+x3dom.fields.MFVec3f.prototype.toString = function () {
+    var str = "";
+    for (var i=0, n=this.length; i<n; i++) {
+                str = str + this[i].toString() + " ";
+    }
+    return str;
+};

 ///////////////////////////////////////////////////////////////////////////////
 /** MFVec2f constructor.
diff --git a/src/nodes/Core/X3DNode.js b/src/nodes/Core/X3DNode.js
index b94e33b0..84405b72 100644
--- a/src/nodes/Core/X3DNode.js
+++ b/src/nodes/Core/X3DNode.js
@@ -293,6 +293,9 @@ x3dom.registerNodeType(
                                 case "string":
                                     this._vf[field] = msg;
                                     break;
+                               default:
+                                    this._vf[field] = msg;
+                                    break;
                             }
                         }
                         catch (exc2) {
```

**Comment by coderextreme** [comment]
Really, I just want a place to check them in. I could probably create a branch.  But discussing them is OK too.

**Comment by andreasplesch** [comment]
.copy should return the value, agreed.

Would probably prefer for .toString() something like

```
return
this.map(function (sf) { return sf.toString(); }).join(' '); // untested
```
Not sure about adding the default case in X3DNode    ?

**Comment by coderextreme** [comment]
I’m not sure either on the default case.  I can test without.

Agreed on your preference.  Should I test here?

Can you get those two changes into X3DOM?  They are pretty critical for me.  I can use my own X3DJSONLD, ProtoExpander, and ScriptPreprocessor, but I need some basic services to work if I want to use the distribution from the website.

Thanks,

John

Sent from Mail for Windows 10

**Comment by coderextreme** [comment]
I don’t need the toString for my files, but someone else may need it using my code.  My nodeUtil has change, and I don’t know if I need it anymore.

So only the copy should be necessary, I guess, for now.

Please patch, if possible.

Thanks,

John

Sent from Mail for Windows 10

**Comment by coderextreme** [comment]
Actually, I think I used toString for debugging, or getAttribute, not suere.

John

Sent from Mail for Windows 10

**Comment by andreasplesch** [comment]
Since MFVec3f arrays can be large and .map would duplicate the array, I think now your approach is oreferable:

```
x3dom.fields.MFVec3f.prototype.toString = function () {

   var str = "", i, n = this.length;

   for (i=0; i<n; i++) {

               str = str + this[i].toString() + " ";

    }

   return str.trim();

};

```
If you could test and prepare a small PR, that would be great.

**Comment by coderextreme** [comment]
Uh, I'm not sure how to make a pull request when I've modified my master (not in a branch) and I have other pull requests pending.  Help!  I have the diffs here on my local system.
