### ISSUE TITLE
Search to build x3d file with metaData.txt & binGeo folder

### ISSUE THREAD

**Issue by Rom1Linux** [x3dom/x3dom#839]
Hello, i work with pythonocc for a web viewer like the "cad-viewer", i see you used x3d files with metadata.txt and binGeo folder.

Actually, when i export my CAD file (.stp) by pythonocc-core, i read an html page (with x3dom-full.js) with many x3d files as parts in the assembly.

I search to build an assembly with this method, one x3d file, metadata.txt and binGeo folder.

Thanks in advance.

**Comment by andreasplesch** [comment]
Is this related to x3dom or a more general general programming question ? If there is a x3dom issue, please provide an example which shows the the problem.

**Comment by Rom1Linux** [comment]
Thanks Andreas  for the answer, my question is not about x3dom programming issue.
I search how manage an exported file, in my case it's a STEP file, convert by Pythonocc.
Actually the X3DExporter of pythonocc give me an assembly with many x3d files and I try to change the export mod to have a simple x3d file with metadata.txt & binGeo folder.

I think we can include that in the X3DExporter used by x3dom_renderer.py of pythonocc.
I try to catch the right process in the x3d documentation.
our goal is to provided an assembly in the scene where we can show the tree of bodies. like i see in the example of CAD-Viewer.
I hope my comment explain more my request.

[https://github.com/tpaviot/pythonocc-core/blob/master/src/Display/WebGl/x3dom_renderer.py](url)

**Comment by andreasplesch** [comment]
That would be a question for the x3dom-user mailing list:
https://sourceforge.net/p/x3dom/mailman/x3dom-users/
Perhaps someone is  more familiar with cad-viewer.

Your best bet for generating binary geometry files may be to use aopt as a postprocessing step after exporting. Longer term, glTF may be more appropriate.

It should also be quite possible to adapt cad-viewer for use with textual geometry if it is not already working as is. Binary geometry would be mostly for better performance if that is desird.

Looking at cad-viewer, it looks like it constructs the collapsible tree directly from the .x3d hierarchy, using id names (constructed from DEF names. or else perhaps text nodes) as names in the tree. So it looks like the exporter would need to generate a single ,x3d file with proper hierarchy using Groups or Transforms.

https://github.com/tpaviot/pythonocc-core/blob/master/src/Display/WebGl/x3dom_renderer.py
uses Inline to pull together .x3d files wilth single Shapes. Cad-viewer does not traverse into Inlines, I believe. Although Inlines with nameSpaceNames get added to the DOM, so cad-viewer actually would descend into Inlines after the main .x3d is completely loaded. Actually, this is what the x3dom examples do, for a single Inline, but it may work for multiple Inlines as well, perhaps best grouped under a single root group.
For optimization with aopt a large single .x3d file may be needed anyways.

MetaData.txt, I think, is for a jquery helper module.

[It would be best to include the metadata in a x3d Metadata node for a Shape, and then use this node with the viewer. The changes to cad-viewer may not be too severe.]

**Comment by Rom1Linux** [comment]
Many thanks Andreas for your answer.
I will get closer to the x3dom-users about that and we go to modifiy our x3dom_renderer.py to extract data as id names and the next step is will be make Inlines x3d file.
Next time, we try to use aopt if these previous steps runs.

I'll keep you informed, i closed that 

Romain
