### ISSUE TITLE
www.x3dom.org has been unavailable for days. any ideas where it comes from ?

### ISSUE THREAD

**Issue by bebeun** [x3dom/x3dom#845]
Hello, 

I have found no other place where to report this problem. the website www.x3dom.org has now been unavailable for days. any ideas what is the problem ? I need to access the doc and the last version of x3d.js...but I am unable ...

Regards

**Comment by paulmasson** [comment]
Documentation available here: https://paulmasson.github.io/x3dom-docs/

**Comment by bebeun** [comment]
Thank you very much !! You saved my day :-)



2018-05-18 11:49 GMT+02:00 Paul Masson <notifications@github.com>:

**Comment by bebeun** [comment]
Sorry to disturb you again but do you have any ideas where I could find the
latest x3d.js and x3d.css ?

http://x3dom.org/download/1.3/x3dom.js is the link given on your website
but it doesn't work.

I am also interested in
https://www.x3dom.org/documentation/tutorials/css-integration-2/ ant I am
unable to find it on your mirror site.

Regards

2018-05-18 11:49 GMT+02:00 Benoît Schulman <benoit.schulman@gmail.com>:

**Comment by andreasplesch** [comment]
There are experimental builds available here:

http://x3dom-builds.surge.sh/

These are meant to test PRs before they are commited but are close to the latest master (dev) version.

There are quite a few example pages in the test/ folder in this repo, for example:

https://github.com/x3dom/x3dom/blob/master/test/regression-suite/test/cases/cssTransforms/cssTransforms.html

@tsturm, @mlimper, @jbehr may have some insight into x3dom.org ?

**Comment by andreasplesch** [comment]
There are now 1.7.2 builds available from the 1.7.2 release page:

https://github.com/x3dom/x3dom/releases/tag/1.7.2

**Comment by katechap** [comment]
these links in the 1.7.2 build linked above are all inactive- does anyone know where we should be pointing to now?

x3dNS    : 'http://www.web3d.org/specifications/x3d-namespace',
x3dextNS : 'http://philip.html5.org/x3d/ext',
xsltNS   : 'http://www.w3.org/1999/XSL/x3dom.Transform',

**Comment by andreasplesch** [comment]
https://github.com/x3dom/x3dom/releases/download/1.7.2/x3dom.js

should work ?

But github does not serve .css properly. One could use rawgit

https://rawgit.com/x3dom/x3dom/1.7.2/src/x3dom.css

but it would be most safe in any case to serve from whereever the html is served from, eg. get a copy.

**Comment by paulmasson** [comment]
@bebeun the page on CSS integration is not part of the GitHub repository, which is the source of my documentation mirror. If you search for the page using a desktop browser, then Google offers the option of see a cached page:

https://webcache.googleusercontent.com/search?q=cache:O9ZwZYuxH1gJ:https://www.x3dom.org/documentation/tutorials/css-integration-2/

**Comment by andreasplesch** [comment]
https://x3dom-dev.surge.sh/latest/

serves builds for the latest master branch, eg. the nightly dev builds.

The builds are updated each time there is a new commit to the master branch, using Travis (and Zapier as a workaround since I cannot enable Travis directly).

**Comment by tsturm** [comment]
Thanks Andreas for your fast help!

We have a bigger infrastructure problem at the moment, which hopefully will be fix early next.

**Comment by bebeun** [comment]
Thank you very much Paul, Andreas for your precious help !

I realised after 2 days bouncing my head against the walls that <Extrusion
/> need x3d full js ...

I grab the occasion to ask this: I see that the x3d js plugin is still
maintained but that x3d is not very much documented and used (very low x3d
topics number on stackoverflow). is there a deprecation to expect soon ? I
am creating all a website with it and I dont want to invest so much energy
in dying tech.

Thk U very very much for all your precious help !

2018-05-20 10:53 GMT+02:00 Timo Sturm <notifications@github.com>:

**Comment by andreasplesch** [comment]
@bebeun, there is a large variety of webgl frameworks, engines and helpers available, each with its own design and philosophy. x3dom is used in many real world applications, and its underlying technology, X3D, will be around for the foreseeable future. Its foundations, a long-standing declarative 3d language and tight integration into the DOM, are sound.
But you are right that x3dom has more of a niche than a large share of the web 3d space. In the end it depends on many factors what works best for a specific set if circumstances which you may have to assess.

**Comment by andreasplesch** [comment]
@bebeun : Hi Benoit, understood, three is very attractive. Do you think you can expand on what your needs are other than popularity and level of contributions ?

**Comment by tsturm** [comment]
[x3dom.org](https://www.x3dom.org/) is back, sorry for the long downtime!
