### ISSUE TITLE
Namespace Errors using x3dom.js and x3dom-full.js

### ISSUE THREAD

**Issue by katechap** [x3dom/x3dom#847]
I get an error with the x3d viewer in a site I've recently come onto the project for:
 "TypeError: null is not an object (evaluating 'this._nameSpace.doc')"

I am wondering if this is because most of the namespace docs referenced are no longer active urls- is anyone else running into this issue or know how to resolve it? (screenshots of the errors and with one expanded)

Thank you

![screen shot 2018-05-21 at 12 47 14 pm](https://user-images.githubusercontent.com/10950166/40319393-05f2d676-5cf6-11e8-9562-11d2a92171ae.png)
![screen shot 2018-05-21 at 12 47 32 pm](https://user-images.githubusercontent.com/10950166/40319399-0bfbbfa6-5cf6-11e8-93a9-12e0574fdf45.png)

**Comment by andreasplesch** [comment]
This rather looks like there is no X3D tag in the document or that it cannot be parsed. It is best to share a jsfiddle or similar for a live example. Otherwise we can only guess.

**Comment by andreasplesch** [comment]
Please reopen as necessary.
