### ISSUE TITLE
Proposal for enhancement: importJS to import JSON

### ISSUE THREAD

**Issue by coderextreme** [x3dom/x3dom#851]
I propose an importJS which will use src/util/json/JSONParser.js to import an X3D JSON JavaScript object into a scene, and another importJS used to replace a world in the browser (perhaps specified by a selector).   This will match importJS in X_ITE.  It will also allow me to move X3D JSON support out of X3DJSONLD and more directly into X3DOM and X_ITE, although I will maintain X3DJSONLD for JSON -> XML and other conversions.  Where should I put importJS in the source code?

Thanks,

John

**Comment by coderextreme** [comment]
There's also the Proto expander that I was thinking of encapsulating.   I
will make a separate function, and then we can discuss.

John

**Comment by andreasplesch** [comment]
JSONParser could be used like this:
```js
domScene = new x3dom.JSONParser().parseJavaScript(JSON.parse(jsonSceneStr));
domScene.id='unique';
divele.appendChild(domScene);
x3dom.reload();
```
if the json is a complete scene.

**Comment by andreasplesch** [comment]
Yes, how would one use the ProtoExpander after JSON.parse ?

**Comment by coderextreme** [comment]
It would be a lot easier if someone could just specify a complete X3D JSON string or object, including head, etc, and the function would look for the scene in the JSON, extract it, etc.   But we could document the whole thing, and have a bunch of versions running around.  I would prefer a single maintainable function or three, comparable to X3D SAI and X_ITE.  If someone wants to replace the functions, they can in their own code.

I will have this in X3DJSONLD, if not brought into X3DOM:
	         // initialize Scripts – comments not implemented
	        //  jsobject = JSON.parse(jsonX3dStr)	; // implemented outside the function
	         jsobject = protoExpander.prototypeExpander(url, jsobject, ""); // see X3DOM’s Inline.js for usage
	  element = new x3dom.JSONParser().parseJavaScript(jsobject);
	  scene = $(element.querySelector("Scene"));
	  // first function, importJS would return scene here.

	      // other functions, getBrowser and replaceWorld begins here
	      selector = “#sceneele”;
	     browser = $(selector);
                        browser.empty();
                       scene.children().appendTo(selector /* or more likely, browser--untested */);
                        try {
                                x3dom.reload();  // This may be necessary
                        } catch (e) {
                                console.error(e);
                                alert("Problem with x3dom.reload() "+ e);
                        }
                        // remove all text nodes in scripts (and fields too, sigh)
                        // run script preprocessor and script and route starter.


Of course, we can’t use JQuery in X3DOM (can you translate to pure JS?).  So something that does the above in X3DOM succinctly would be nice.  I can empty the Scripts outside of it, of course, since I have my script preprocessor in X3DJSONLD still, which does evals, so Scripts aren’t present in HTML, just in sources.

I have found that keeping the Scene in HTML seems to be best, but that’s not really my call I guess.

Ultimately, we may want to bring in the script preprocessor, so this snippet will get a lot longer, or there will be a function around it.   We just have to figure out the right interface.  I think scene selector, jsobject, and url may be best.

Note that the requirement is currently to have Script processing outside the function, since there may be multiple X3DOM browsers running, and I only initialize the scripts once per 2 browsers.

I suggest breaking the function into two functions, one to load the JSON into a DOM element (importJS, which returns a scene), and one to do push the element scene children into the scene (replaceWorld).

I already have most of this implemented in X3DJSONLD, except for:

element = new x3dom.JSONParser().parseJavaScript(jsobject);

and the X3DOM protoExpander.

I just need to bring it into SAI-like form.  Also, there is the subject of JSON Schema validation, which X3DJSONLD already does (which really confounds this).  I tried to unify loading and validation, and it created a hairy mess—trying to come up with a better solution.

I don’t mind adding a getBrowser() function either, which takes #sceneele selector and returns an element.

I think X_ITE’s interface it nearly perfect, except for the requirement to specify the url to the protoexpander.  Perhaps we can separate out the protoexpander? IDK.  Really, I am trying to figure out how to make use of JSON -> DOM and the ProtoExpander (see Inline.js for usage) from X3DOM inside of X3DJSONLD...the solution seems easy enough already without all this mucking with X3DOM, and I can still use JQuery.

Sorry to bother you!

John
Sent from Mail for Windows 10

**Comment by andreasplesch** [comment]
Since JSONParser and ProtoExpander is already provided with x3dom now, it may as well be made easy to use.

I agree that the X3D dom element should be used as the x3d browser object. Actually, x3dom uses x3delement.runtime as the point to attach x3d browser methods to. So it would make sense to keep using that, eg.
```
.runtime.replaceWorld(SceneDom)
.runtime.createX3DFromString(jsonOrXMLString, optionalURL) (returns scene dom)
.runtime.createX3DFromURL(url, optionalURL) (returns scene dom)
.runtime.createX3DFromJS(jsobject, optionalURL) (returns scene dom)
```

.replaceWorld is just what you have above, except for JQuery (use document.querySelector and node.remove()).
optionalURL would indicate if Prototype expanding should be used.
(Why does the expander need the url ? For relative links ?)
.runtime.createX3DFromJS(jsobject, optionalURL) is I think what you had in mind with importJS. It is there because it takes jsobject which could have been constructed in any way.

To me it may make sense to have that option also for JSONParser.parseJavaScript(json, optionalURL) .
If optionalURL is provided ProtoExpander is invoked before the json parsing.
Or maybe have JSONParser.expandAndParse(json, url).
.runtime.createX3DFromJS(json, optionalURL) would then become probably just
```
JSONParser.parseJavaScript(json, optionalURL).querySelector('Scene');
```
.runtime.createX3DFromString(jsonOrXMLString, optionalURL) and .runtime.createX3DFromURL(url, optionalURL) would need to do the try catch test parsing to detect json.

**Comment by coderextreme** [comment]
Yes, I believe the expander needs the url for relative links.  I am not sure there’s an alternative, a separate call to the protoexpander?

createX3DFromURL(url, optionalURL) does not need 2 URLs, a simple flag would do for the protoExpander, unless you wanted to load ExternProto’s from another site (probably not allowed with CORS) or a different relative URL, which might be useful. So test optionalURL for Boolean or String, if Boolean value === true, then protoexpand based on url, if optionalURL is string, protoexpand based on optionalURL.

I like the design as you have it, except for the above.  Do you want to do the PR, or do you want me to?  I have to work on the x3dom protoexpander (misplaced @value as a different attribute) and x_ite JSON loading (embedded shaders), once I can build x_ite again.  I’m also will be working on reorganizing X3DJSONLD as X3dJson2Dom (JSONParser) so X3D JSON -> DOM in all it’s stripes can be used separately from X3DJSONLD.

If you do the PR, notify me, and I will test your test environment, or pull your branch to mine.

I will have to change my selectors in X3DJSONLD to x3delement, or go after the scene parent, which is fine. I hope that x3dom doesn’t start hogging webgl contexts.  I will let you know.

If JSONParser does protoexpanding, we can take it out of Inline.js.

I will review if you do the PR.

If I do the PR, where are most of the .runtime. methods located?  X3DElement.js???

There may be another way to load ExternProto’s.  We probably need to investigate that.  I do believe they have to be synchronous, I haven’t found a way around that yet, unless we queue up the location to put the ProtoDeclare in the scenegraph, and I think that the protoexpander won’t be running by that time, so that’s why I chose synchronous.  Promises…what a mess!?

Thanks,

John

Sent from Mail for Windows 10

**Comment by coderextreme** [comment]
I have attempted to create a couple of these functions that I am immediately interested in, and wasn’t sure if this would work:

x3dom.Runtime.prototype.replaceWorld = function(scene) {
    this.canvas.doc._scene = scene;
    x3dom.reload();
};

I will do a PR.

Thanks,

John

Sent from Mail for Windows 10

**Comment by andreasplesch** [comment]
No this will not work for various reasons. I will comment in the PR.
