### ISSUE TITLE
bindables in WebVR : Background

### ISSUE THREAD

**Issue by npolys** [x3dom/x3dom#875]
The default Background is substituted for the currently bound one
 - when a user enters VR mode.

**Comment by andreasplesch** [comment]
I seem to have trouble using a cubemap background with the webVR emulator.

**Comment by andreasplesch** [comment]
But with regular skyColor backgrounds I can bind a new one, switch to VR, and the background will stay bound. This is with the webVR simulator.
Do you have a example scene ?

**Comment by andreasplesch** [comment]
Cubemap backgrounds are not working anymore with the webVR branch.

Here is the cubemap regression test fixed for cors with the master branch:

https://rawgit.com/andreasplesch/x3dom/cubemap2/test/regression-suite/test/cases/cubemap/cubemap.html

Here is the same regression test with (a branch of) the webVR branch:

https://rawgit.com/andreasplesch/x3dom/webVR_background/test/regression-suite/test/cases/cubemap/cubemap.html
