### ISSUE TITLE
x3dom doesn't work in internet explorer

### ISSUE THREAD

**Issue by venkatrajgm** [x3dom/x3dom#888]
I have an IE11 version with me. x3d models is not getting rendered in the browser. But when i try this link [https://www.x3dom.org/check/] I can see that it supports x3dom. what is the issue. Can anyone please help.

**Comment by jamesleesaunders** [comment]
I have not got IE11 to check but do you get any JavaScript errors in the console? (Developer Tools Shift-F12 I think).

**Comment by andreasplesch** [comment]
I just checked the examples on x3dom.org. They still worked on IE11 in Windows 7. It is possible that there is a straightforward fix for the issue you may have, for example with a polyfill. Why not just just a modern browser ?

**Comment by andreasplesch** [comment]
Please reopen as needed.

**Comment by venkatrajgm** [comment]
Sorry for late reply. There is no error in console box. I can see the x3d models loaded in console but it is not visible in the canvas. Is there meta tags i should introduce in the my html page. I tried IE=11, IE=Edge, Chrome=1 everything.

**Comment by andreasplesch** [comment]
Can you provide an example which does not work in IE11 ? Does the page work in other browsers ?

**Comment by venkatrajgm** [comment]
All the examples from x3dom.org are working fine in IE11. Its a webpage that I created for a project using x3dom is not working in IE11. Is it because of the coding in JS I'm not sure. But this project of mine works in all other browsers including edge.

**Comment by andreasplesch** [comment]
Please provide the web page or an equivalent page. Without more information, it is not possible to respond constructively.

**Comment by venkatrajgm** [comment]
Here I have attached the html page. One thing I noticed is that when i move the first 'transform' element in the html to the last, then it is loading properly in IE. In the first transform element, I kept the url for x3d model empty. I will load the x3d models based on selection, that's the plan. Please let me know does the location of transform elements affects the rendering of models in browser.

![capture](https://user-images.githubusercontent.com/39547348/44391869-8c9e0b00-a54e-11e8-8958-c5f131b3b1f6.PNG)

[index.zip](https://github.com/x3dom/x3dom/files/2305556/index.zip)

**Comment by tsturm** [comment]
You can't use self-closing tags in html5.
Can you try to change your inline to <inline ...></inline>

**Comment by andreasplesch** [comment]
Formatted for md: `<inline ..></inline>`

**Comment by venkatrajgm** [comment]
@andreasplesch @tsturm Cool. It just fixed the issue with IE11. I didn't look at this </inline> tag as it was working in other browsers well and good. Anyway thanks a lot for your help and patience.
