### ISSUE TITLE
glTF: rename buffergeometryaccessor  to bufferaccessor

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#898]
Since buffers are used not just for geometry but also other data such as animation data, renaming the buffergeometryaccessor/view nodes to buffer accessor/view would allow use of those more generally.

I can work on a PR if desired.

**Comment by tsturm** [comment]
Sounds good for me.

**Comment by andreasplesch** [comment]
@jamesleesaunders : do you want to give this a try ?

It is just a find and replace renaming of occurrences of 

BufferGeometryView to BufferView
buffergeometryview to bufferview
BufferGeometryAccessor to BufferAccessor
buffergeometryaccessor to bufferaccessor

These files are involved:
src/nodes/Geometry3D/BufferGeometry.js
src/nodes/Geometry3D/BufferGeometryAccessor.js
src/nodes/Geometry3D/BufferGeometryViews.js (should be be probably singular)
src/util/glTF/glTF2Loader.js
tools/packages.json

as far as I can tell.

**Comment by jamesleesaunders** [comment]
Sure! Happy to give it a go! Thanks for the offer.

**Comment by andreasplesch** [comment]
Thanks.

**Comment by tsturm** [comment]
merged
