### ISSUE TITLE
How to change the mouse scroll zoom speed 

### ISSUE THREAD

**Issue by venkatrajgm** [x3dom/x3dom#905]
I have a model for which i have to scroll the mouse wheel a lot to get a good zoom in. I need to increase the zoom speed for each scroll. Where can i manipulate this factor. I tried adding 'speed' attribute in 'navigationInfo', but its not affecting the zoom speed.

Or another way I'm looking for is that, double clicking on the scene should automatically zoom to the clicked area

**Comment by andreasplesch** [comment]
The '+' and '-' keys seem to work in the examples, to adjust the wheel scroll speed. You also hack the mousewheel event handlers in X3DCanvas.js .

**Comment by venkatrajgm** [comment]
Is this the one? Snipped this from x3dom.js. what can i change here
`this.onMouseWheel=function(evt){
    if(!this.isMulti)
    {
        this.focus();
        var originalY=this.parent.mousePosition(evt).y;
        this.mouse_drag_y-0.1*evt.wheelDelta;
        this.parent.doc.onWheel(that.gl,this.mouse_drag_x,this.mouse_drag_y,originalY);
        this.parent.doc.needRender=true;
        evt.preventDefault();
        evt.stopPropagation();
    }}`

**Comment by andreasplesch** [comment]
The 0.1 scaling factor. You can probably use the Chrome Devtools overrides to experiment.

**Comment by venkatrajgm** [comment]
Thanks. It worked.
