### ISSUE TITLE
INVALID_VALUE: texImage2D: no canvas

### ISSUE THREAD

**Issue by jamesleesaunders** [x3dom/x3dom#910]
I have been developing a D3.js + X3DOM chart library d3-x3dom. I often see the following console warnings on Chrome but have no idea why?

```
11WebGL: INVALID_VALUE: texImage2D: no canvas
245[.WebGL-0x7fc3bc0dd000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
BarChartMultiSeries.html:1 WebGL: too many errors, no more errors will be reported to the console for this context.
```
These errors can be seen on the following example:
https://jamesleesaunders.github.io/d3-x3dom/examples/BarChartMultiSeries.html

<img width="1151" alt="screen shot 2018-10-24 at 20 38 57" src="https://user-images.githubusercontent.com/13055416/47456704-14adc480-d7cd-11e8-802e-97b5f0128c50.png">

Is there something I have done wrong in d3-x3d or should I not be concerned? It does not seem to have any effect on the result.

**Comment by jamesleesaunders** [comment]
I am not sure if related (or a different issue) but I also see the following error in the X3DOM debug console:

`ERROR: GL-Error (on searching uniforms): 1281`

<img width="533" alt="screen shot 2018-10-24 at 20 50 54" src="https://user-images.githubusercontent.com/13055416/47457254-89353300-d7ce-11e8-98f1-b9bdc42974cc.png">

**Comment by jamesleesaunders** [comment]
If interested you can find d3-x3dom here:
https://github.com/jamesleesaunders/d3-x3dom

**Comment by jamesleesaunders** [comment]
@andreasplesch you genius! Thank you! I will fix this bug in d3-x3dom!
Would you say this is also a small bug which could be fixed in x3dom? I could try and have a go at fixing it?
Thanks again!
Jim

btw If you(or anyone) have any comments, tips or ideas for d3-x3dom I would love to hear them. At the very least I created it to promote x3dom!

**Comment by andreasplesch** [comment]
The spec. does not have any specific guidance on what to do if the string is empty. I think it would be best to return early from updateText:

https://github.com/x3dom/x3dom/blob/master/src/Texture.js#L425

as then there is nothing to do. It would be a reasonable fix.

On the other hand, Firefox is not complaining anyways, only Chrome is. It might be worth checking Edge. Another first step would be to find out what the WebGL spec. says should be done if a canvas is empty, as passed to gl.texImage2D(). Chrome thinks it is INVALID but perhaps it is not as FF does not mind.
