### ISSUE TITLE
"INFO: Found 0 x3d..." message when using x3d with blazor

### ISSUE THREAD

**Issue by CobraCalle** [x3dom/x3dom#919]
Hello,

I would like to use X3D with Blazor (server components), because it would be a perfect match and would enable build dynamic 3D-content from .NET/c#.

But when generate an X3 node from blazor, only get a small dot (that reacts to the cursor and changes it to a hand when hovering above it). And at the end of the page I get a message generated "INFO: Found 0 X3D .... nodes".

So I think the problem is, that the x3d-node is generated after the script hat checked the DOM (because blazor builds the dom by a java-script)... how can I work around this? Is there a java method or something like that, that I can invoke to "rescan" the DOM... or something like that=

![image](https://user-images.githubusercontent.com/6218368/50654097-04b01f00-0f8c-11e9-835b-047592f52c14.png)

**Comment by andreasplesch** [comment]
You seem to be using version 1.5.0. Could you try with the latest stable or dev version ?

There is a global x3dom.reload() function https://github.com/x3dom/x3dom/blob/9892db4f81460c76c96808fcdad1f56fd8a1ca9b/src/Main.js#L227

to try but it may be better to figure out the loading sequence, eg. make sure that x3dom.js is only loaded after the DOM is ready.

**Comment by CobraCalle** [comment]
Perfect… that worked! Thanks alot
