### ISSUE TITLE
EnvironmentLight SRGB or linear

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#924]
gltf viewers typically treat LDR cubemaps as SRGB and translate the light color to linear in the shader. Currently, the .dds image is treated as linear in the pbr shader and used as is. Should it be or should there be a field in the node to indicate the appropriate gamma correction ?

**Comment by tsturm** [comment]
The PhysicalEnvironmentLight supports only pre-computed HDR .dds files and they should be linear by default.
