### ISSUE TITLE
vertex color artefact when switching lights

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#927]
When switching from env. light only to headlight only, I get these artefacts with box with vertex colors:

![image](https://user-images.githubusercontent.com/6171115/51956450-ac96fc00-2415-11e9-9e5d-ac7900382b25.png)

They disappear when switching models and then back. The box with vertex colors is the only model with these artefacts. Very weird.

https://raw.githack.com/andreasplesch/x3dom/aad5604052e8b02481e0cd0a7a8b42fc34e71e6d/test/functional/inline-gltf.html

**Comment by tsturm** [comment]
fixed 34eca67e326de4ee15a98ef15fbd0cc9195920de
