### ISSUE TITLE
gltf extras as metadata

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#928]
gltf json has the extras property for any node to allow for meta information.
extras can be anything but is supposed to be an object with name-value pairs. This maps pretty well to x3d Metadata or MetadataSet: http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/core.html#Nodereference

Here is a mapping:

--- extras value is: initial key value is 'extras'
---- string: MetadataString with name=key
---- number: MetadataFloat with name=key
---- boolean: MetadataBoolean with name=key
---- array: convert to object with indices as keys (automatic)
---- object: MetadataSet with name key+'_set', rinse repeat

Asset properties (https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#asset) would map best into WorldInfo since they have or are expected to have string values.
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#reference-asset

**Comment by tsturm** [comment]
merged

**Comment by andreasplesch** [comment]
blender-io can generate extras scene:
https://github.com/KhronosGroup/glTF-Blender-IO/pull/138/files
need to add somewhere in inline
