### ISSUE TITLE
gltf: high zfar leads to z-fighting

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#931]
The Buggy, Gearbox, ReciprocatingSaw and 2Cylinder gltf examples all have a zfar of 1000000 for their camera which then leads to z-fighting when the camera is as a viewpoint.

Should there be a cutoff perhaps using a caertain znear/zfar ratio ?

**Comment by tsturm** [comment]
Yes, sounds good! PR is merged.
