### ISSUE TITLE
logic for `disableKeys` appears backwards

### ISSUE THREAD

**Issue by asottile** [x3dom/x3dom#934]
either that or I'm confused about the ternary 😆 

https://github.com/x3dom/x3dom/blob/57bbd8ade9d97aabd9550976973e8cb459aebc33/src/X3DCanvas.js#L158-L159

It appears to be this logic:

```
keysDisabled = `keysEnabled` property is present  and the value is equal to true
```

so keypresses are disabled when `keysEnabled=true`, otherwise they are enabled

**Comment by nedbat** [comment]
Judging from the other attributes nearby, this should have been called "keysDisabled".

**Comment by andreasplesch** [comment]
For a fix, there are three options:
- [ ] rename the attribute from 'keysEnabled' to 'disableKeys'
- [x] change the logic
```js
this.disableKeys = this.disableKeys ? (this.disableKeys.toLowerCase() === "false") : false; 
```
- [ ] change the logic
```js
this.disableKeys = this.disableKeys ? (this.disableKeys.toLowerCase() !== "true") : false; 
```
Preferred change would be:
```js
 var keysEnabled = x3dElem.getAttribute("keysEnabled") || "true";
 this.disableKeys = (keysEnabled.toLowerCase() === "false");
```
Does that look right ?

**Comment by nedbat** [comment]
I don't know how much you want to preserve the old behavior.  Another option would be to check both `keysEnabled` (with the current backward logic) and also `disableKeys` (with correct logic).  Then document `disableKeys`.  This would keep old code working, but also give a give a good implementation for the future.

**Comment by tsturm** [comment]
Renamed: 2e0ba18490b3aa07ffb2af4052e83329e5ef3712

```
// 1.7.3-dev
// Disable all x3dom default key bindings
<x3d disableKeys="true">
...
</x3d>
```
