### ISSUE TITLE
Getting PlaneSensor to work with Multitouch.

### ISSUE THREAD

**Issue by alauder1** [x3dom/x3dom#935]
I have been using an OnClick Event to run some Javascript that adds a sensor plane and route to a shape. This is so a shape can be selected then dragged around.

It works in a desktop browser (Chrome on Windows 10 with a mouse) I can't get it to work with  multitouch (Safari, IOS  on i-phone)  

The Onclick works sometimes but does not seem reliable.

I can't drag the box once it turns red (is selected).

Here is a small text example.
http://www.pcdesignfoundry.com/test/onclick_test.html
[onclick_test.zip](https://github.com/x3dom/x3dom/files/2828486/onclick_test.zip)

This Previous Teapot Example does not work for me using multitouch either.
http://doc.x3dom.org/tutorials/animationInteraction/transformations/example.html

However, dragging the window in this playroom example does work with multitouch.
http://www.web3d.org/x3d/content/examples/StudentProjects/PlayRoomIndex.html

What am I doing wrong? How is it that the playroom works? Thanks for any help.

Andy

**Comment by tsturm** [comment]
Hi @alauder1,

I have checked the code and there was no touch support for the sensors.
The linked playroom example is not rendered with x3dom.

I have added basic touch support to the current dev version.
Maybe, you can try if it works like expected.

I have uploaded a minimal changed version of your example here:

[https://examples.x3dom.org/touchSensor/](https://examples.x3dom.org/touchSensor/)

**Comment by alauder1** [comment]
Hi @tsturm 

That fixed the problem. The example works as expected now.  Selecting and moving with the sensor planes using Multitouch on my iPhone.   

Is there a way to get this fix in a version of x3dom-full.js.  I use Extrusion nodes in my main project and these seem to have stopped working with the dev version from your example.

Thanks

**Comment by tsturm** [comment]
You can find the current dev-version here:

[https://x3dom.org/download/dev/](https://x3dom.org/download/dev/)

**Comment by jamesleesaunders** [comment]
@tsturn Is it worth deleting the .zip out of the dev folder to avoid confusion?

**Comment by tsturm** [comment]
@jamesleesaunders: removed ;)

**Comment by alauder1** [comment]
@tsturm  The x3dom-full.js  version at the dev build link worked thanks.

If you are interested you can see the project here.

http://www.pcdesignfoundry.com/test/pc_builder.html
