### ISSUE TITLE
Snapshot in Safari upside down and reversed

### ISSUE THREAD

**Issue by ssdmike** [x3dom/x3dom#937]
When taking a snapshot the image is upside down and reversed. This happens in Safari but not chrome or firefox.

SAFARI:
![snapshot](https://user-images.githubusercontent.com/5717739/52535729-e6bea280-2d1f-11e9-81c4-b96e7f329bdc.png)

CHROME:
![snapshot 26](https://user-images.githubusercontent.com/5717739/52535736-f342fb00-2d1f-11e9-87a4-5245c0c218c1.png)

FIREFOX:
![snapshot ff](https://user-images.githubusercontent.com/5717739/52535742-03f37100-2d20-11e9-8b62-44befd9f3e4c.png)

**Comment by paulmasson** [comment]
Testing in Safari 12 on macOS Mojave using this link

https://doc.x3dom.org/tutorials/applicationTutorials/screenshot/example/index.html

Safari behaves exactly like Firefox and Chrome and this issue does not occur. How exactly are you taking the screenshot? Are you using the most current version of x3dom.js?

**Comment by ssdmike** [comment]
@paulmasson i realized that our code was using the Canvas.toBlob function rather than the x3dom getScreenshot

old code:
```
const canvas = document.getElementById('x3dom-x3dElement-canvas');
  canvas.toBlob(function(blob) {
    downloadSnapshot(blob, 'snapshot');
  });
```

new code:
```
const imgUrl = document.getElementById("x3dElement").runtime.getScreenshot();
  downloadSnapshot(imgUrl, 'snapshot');
```

Thanks for helping.
