### ISSUE TITLE
Reorientation Gizmo

### ISSUE THREAD

**Issue by alauder1** [x3dom/x3dom#939]
I am trying to create a simple rotation/rorient gizmo that only rotates in 90 degree increments about x y and z.  Total of 24 orientations.  I am using onclick for this instead of a cylinder sensor.     I am also trying to do it in just one Transform  Rotation instead of nested transforms.   The problem I have is that each gizmo only does one axis. But the Axis orientation changes when you do compound rotations,  I would like the rotator shapes to switch which axis they rotate depending on orientation to make them more intuitive.

I still have some combinations of the rotations not mapped to the resultant orientation of the object.
Is there a way to do this that is much simpler using matrix multiplication or programmatically maps the combinations to the orientations?

Test Here 
http://www.pcdesignfoundry.com/test/RotatorTest.html

[RotatorTest.zip](https://github.com/x3dom/x3dom/files/2853424/RotatorTest.zip)

**Comment by jamesleesaunders** [comment]
As this is more of a general question than bug report this may be better asked on the x3dom-users  mailing list: 
https://sourceforge.net/p/x3dom/mailman/x3dom-users/

**Comment by alauder1** [comment]
ok thanks.

**Comment by andreasplesch** [comment]
x3dom-users is more appropriate but let me outline here another way, using x3dom.fields methods. You would have one Matrix4f variable holding the current orientation and then three 90 deg. rotation matrices, one for each axis. Then on each click you multiply the current orientation with the appropriate rotation matrix, and convert the matrix to axis angle for transform.setAttribute, or quaternion for transform.setFieldValue. That should be it.
