### ISSUE TITLE
IndexedFaceSet colorPerVertex problem

### ISSUE THREAD

**Issue by kimrj** [x3dom/x3dom#941]
Neither Chrome nor Firefox (on Windows) displays this HTML file:
http://www.ravn-jensen.dk/diverse/201902-x3domproblem/test5d.html
as expected, that is, with color contours.

I consider this x3d file:
http://www.ravn-jensen.dk/diverse/201902-x3domproblem/test5d.x3d
equivalent. However, the freeWRL applications displays the color contours as expected.

I see no error messages anywhere. Where did I go wrong?

**Comment by andreasplesch** [comment]
html requires full closing tags, eg. use ```<color></color>```, not ```<color/>```.
https://jsfiddle.net/wxt9sjyk/
(xhtml would let you use self-closing tags but is very strict).

**Comment by kimrj** [comment]
Hello Andreas,
You nailed it - thank you very much! Btw., the ParaView x3d export driver is to blame. Now that I know and understand the problem, I can code an "afterburner".

**Comment by andreasplesch** [comment]
Good to know. Alternatively, you may be able to use an Inline node which accepts XML including self-closing tags. This way you can probably use Paraview's X3D as is.
