### ISSUE TITLE
Plane Sensor Movement not proportional and can flip direction when near horizontal.

### ISSUE THREAD

**Issue by alauder1** [x3dom/x3dom#946]
I am trying to crate drag handles to move an object around.  I am currently using three plane sensors and routes almost works but the green axis movement seems to be scaled strangely and is somehow related to the view rotation.

If you have the green axis aligned close to horizontal on the screen the translations go wild and sometimes invert.

https://jsfiddle.net/andyscript/0e26znd8/10/

This also seems to happen  with the x3dom example.

https://doc.x3dom.org/tutorials/animationInteraction/transformations/example.html

![teapot](https://user-images.githubusercontent.com/47212803/54696319-83e0d800-4b23-11e9-855f-1a8b4fe109bd.PNG)

**Comment by alauder1** [comment]
I have improved the problem quite a bit since my first example be making the plane sensors be parents of the transforms they are routed to. Instead of children.

https://jsfiddle.net/andyscript/0e26znd8/20/

But the problem still exists to some degree. It seems to be related to movements in the mouse pointer in a  direction perpendicular to that which the drag handle is moving causes this jumping around.

In the above example.  If the Blue drag handle is horizontal to the view  then any vertical movement in the mouse while you are dragging horizontally makes it jump around wildly.

**Comment by andreasplesch** [comment]
Great examples. I thought it may have to do with feedback of how the planesensor translation changes the local coordinate system of the planesensor itself. But during dragging the implementation, I think correctly, keeps using the initial local sensor coordinate system.

It may have to do with nested transforms. It will be important to come up with a minimal example, a single planesensor, and the minimal number of transforms.

**Comment by alauder1** [comment]
Testing it out further the orientation has to be very specific.   

It only happens when the blue handle is horizontal and the red one is vertical.
![jumpingarround](https://user-images.githubusercontent.com/47212803/54763524-0930bf00-4bee-11e9-8167-da641ec12309.PNG)

 If the Blue is horizontal and the Green is vertical then the dragging is OK.
![nojumping](https://user-images.githubusercontent.com/47212803/54763577-236a9d00-4bee-11e9-80a8-4bddb0e691de.PNG)


https://jsfiddle.net/andyscript/0e26znd8/20/

**Comment by andreasplesch** [comment]
http://web3d.org/pipermail/x3d-public_web3d.org/2014-March/002773.html has some history on the same issue.

**Comment by andreasplesch** [comment]
Looking at the discussion and trying a couple of things this seems to be fundamental limitation of PlaneSensor. By its nature of using a plane and intersections with this plane, it will act very sensitively whenever the view is parallel to the plane, looking at the edge of the sensor plane. In this case, a tiny movement of the pointer will result in a large translation on the plane.

A potential solution is to detect this situation and inhibit the sensor. In this fiddle, the PlaneSensor js has a fix for axisRotation (fixed matrix multiplication order) and a check for small angles between view direction and the plane (the early return if the dot product is small):

https://jsfiddle.net/andreasplesch/mzg9dqyc/62/

This maybe a fairly robust solution since sensing in this edge situation is rarely wanted.

**Comment by alauder1** [comment]
Thanks.   It will take me a while to go through that and understand it all.

One   thought  I had.   Would it be possible to rotate the plane sensor 90 degrees about the axis that is horizontal when ever the sensor plane gets close to being edge on so  that  the plane normal is then pointing at you.  Is it possible to do that by  changing the  axisRotation of the plane sensor. Also might you have to switch the max and min values (0, 5) becomes (5,0)?    

Possibly  when ever you stop rotating the viewpoint a script then checks if any sensorPlanse are close to edge on and flips them yo be normal?  It could do this before you actually start dragging the  handles.

**Comment by andreasplesch** [comment]
Yeah, in this case the edge on view is actually a common situation which needs to be handled more graciously.

I think, you could probably come up with something, although currently PlaneSensor cannot be modified dynamically (but you could make new ones).

There is also a x3dom draggable (or so). There is somewhere an example

I think, as hinted at in the list discussion, the real solution would be to have a proper LineSensor which could always use an appropriate intersection plane. Let's see:

- the Line would be the x axis of the local coordinate system. 
- a intersection plane would include the x axis and perhaps the cross product of x axis and view direction.
- so the normal of that intersection plane would be the cross product of x axis and (cross product of x axis and view direction).
- and the intersection point would be projected onto the x axis, I think, just by dot product

**Comment by andreasplesch** [comment]
Based on the above idea, I have modified PlaneSensor in this fiddle to recognize when it is used as a LineSensor:

https://jsfiddle.net/andreasplesch/mzg9dqyc/111/

This is the case for all of the handles. In LineSensor mode, it now does not use the XY plane anymore but an arbitrary plane which contains the Line axis and which is at high angle with the view direction.

It seems to work well, and turned out to be not too complex to add. Take a look.

**Comment by alauder1** [comment]
That totally fixed the problem.  Now if you move the mouse  perpendicular to  the drag handle when dragging is there is no movement or  jumping around crazily.  It works with multi touch too.  Very nice fix!

**Comment by andreasplesch** [comment]
For now you can just include a patched PlaneSensor.js after x3dom-full.js .

I will generate a PR with the patch so it can be applied to the dev version when appropriate.

**Comment by andreasplesch** [comment]
After a discussion on the x3d-public list, I also added a point sensor mode to PlaneSensor here:

https://jsfiddle.net/andreasplesch/mzg9dqyc/158/

It is activated by adding a planeOrientation='screen' attribute to PlaneSensor. This causes the reported translation_changed vector to be in the plane parallel to the screen, and therefore allows dragging in the screen plane which is what is often expected. Currently, in this mode the mix/maxPosition fields are ignored.

**Comment by andreasplesch** [comment]
https://jsfiddle.net/andreasplesch/mzg9dqyc/201/

I added for min/maxPosition for screen mode. It restricts dragging in the screen directions.

I also added the standard trackPoint_changed event which provides the intersection point in local coordinates.

**Comment by alauder1** [comment]
Hi Andreas.  Those look like useful additions.  I made a separate js file from your jsfiddle.  It worked fine for the local version of my simple drag example.   However  when I included it in my main app that I am working on it stopped the drag function altogether.  I have no idea why.  Should I send you a link via email  to the non functioning App to take a look at?

**Comment by andreasplesch** [comment]
I have given the approach that the PlaneSensors affect their parent transforms another try:

https://jsfiddle.net/andreasplesch/mvkdnjwx/42/

It avoids a lot of routes and having separate transform hierarchies for each handle.

 But I had to disable the trackpoint since I could not figure out how to place it so it is only affected by the trackPoint_changed event and not by the translation_changed event. Also, the min/maxPosition restriction for screen parallel mode did not work properly anymore, probably due to hard to reason about bug.

**Comment by alauder1** [comment]
Those are really excellent improvements.  Getting the Plane sensors to work correctly on parent transformation will simplify my  application a huge amount.  Will take a few days or so to rewrite it so will let you know if it works out.

**Comment by andreasplesch** [comment]
Here is an attempt at basic snapping:

https://jsfiddle.net/andreasplesch/mvkdnjwx/149/

**Comment by alauder1** [comment]
Here is an example with snapping working for multiple added components including rotation/orientation  and translation handles.  The Unsnap Feature is not working in  this example though.

https://jsfiddle.net/andyscript/5gL9e1o0/30/

Should I close this bug since the Sensor Planes  are working now or leave it open till the sensor plane in the X3DOM-full or X3DOM-full.debug  has been updated to include the new sensor plane fixes.

**Comment by alauder1** [comment]
I have updated  the snapping example.  Added in two innovations.

1)  unsnap is accomplished by just looking at direction of the distance change.  If the object is being dragged away (new distance is greater than old distance) then it will not snap.  It only snaps if it is moving closer and is within the snap range.

2) I no longer have a separate transform for the snap event. Instead I just add the x y z distances to the main X Y Z transforms used for dragging. This is because the old way of doing  it when you unsnap it would jump to the location as it was before the snap as that was still in the drag handle object memory.

There is still one problem.  When you select an object that has already been snapped. It activates the dragging on one axis and keeps dragging even though you have let go of the mouse button.  It is not suppose to be dragging.  You have to stop this by trying to catch one of the drag arrows and clicking on them.    I sometimes see this behaviour if your mouse goes outside the rendered scene when you are dragging.

https://jsfiddle.net/andyscript/5gL9e1o0/47/

**Comment by alauder1** [comment]
Updated the snapping and unsnapping again.   I was finding that disabling and enabling the plane sensors pragmatically while dragging meant that strange things happen.  Components jump around and don't react to mouse clicks properly.   A better way to do it is to simulate a mouse up event when  the snap happens so that dragging is stopped.

  var clickEvent = document.createEvent('MouseEvents');
  clickEvent.initEvent("mouseup", true, true);
  var upthis = document.getElementById("x3dom-x3d-canvas")
  upthis.dispatchEvent(clickEvent);

https://jsfiddle.net/andyscript/5gL9e1o0/49/
