### ISSUE TITLE
Changelog for the upcoming release

### ISSUE THREAD

**Issue by tsturm** [x3dom/x3dom#955]
Hi @andreasplesch, @aarbelaiz, @jamesleesaunders,

please feel free to extend the changelog for the upcoming release:

Version 1.8.0
-------------
* Features
  * webGL 2.0 support
  * glTF 2.0 support
  * Physically-based materials & lighting
  * webVR integration
  * Nurbs
  * Allow multiple planes on a single MPR Volume style element
  * HAnim CPU skinning
  * scene X3D SAI methods
  * X3D JSON encoding for inlines
  * Content negotiation  support for Inlines

* Nodes
  * Shape
    * PhysicalMaterial
  * Lighting
    * PhysicalEnvironmentLight
  * Interpolation
    * PositionInterpolator2D
  * Geometry3D
    * BufferAccessor
    * BufferGeometry
    * BufferView
  * Rendering
    * CoordinateDouble
  * EventUtilitie
    * BooleanFilter
    * BooleanSequencer
    * BooleanToggle
    * BooleanTrigger
    * IntegerSequencer
    * IntegerTrigger
    * TimeTrigger
    * X3DSequencerNode
    * X3DTriggerNode
  * VolumeRendering
    * MPRPlane
  * NURBS
    * Contour2D
    * ContourPolyline2D
    * NurbsCurve
    * NurbsCurve2D
    * NurbsOrientationInterpolator
    * NurbsPatchSurface
    * NurbsPositionInterpolator
    * NurbsSurfaceInterpolator
    * NurbsTrimmedSurface
    * X3DNurbsSurfaceGeometryNode
    * X3DParametricGeometryNode

* Fixes & enhancements
   * Sphere
      * Allow fieldChanged by always setting qfactor.
      * Improved texture coordinates
   * Improved caching.
   * Bounding box fixes.
   * Documentation Updates.
   * New global ‘useGeoCache’ param option to toggle use of GeoCache.
   * log div id change to x3dom-log.
   * Many fixes and enhancements by the X3DOM core team and the X3DOM community.

**Comment by andreasplesch** [comment]
- HAnim CPU skinning
- scene X3D SAI methods
- X3D JSON encoding for inlines

**Comment by jamesleesaunders** [comment]
Good work! Looks great. v.excited to see new release soon :-)

Some comments from a quick scan of past commits and PR's...

* "Multiple arbitrary MPR" .. could be reworded.. "Allow multiple planes on a single MPR Volume style element"

Sphere:
* Allow fieldChanged by always setting qfactor.
* Improved MovieTexture.

Fixes:
* Adds basic touch support.
* Improved caching.
* Bounding box fixes.
* Documentation Updates
* Refactoring, JSDoc, Linting?

(I don't know if some of these are too low level feel free to ignore some if you think not appropriate)

Do let me know if there is anything else I can do to help!

**Comment by jamesleesaunders** [comment]
Oh and IMO I think as this is such a jump it warrants a jump to 1.8.0.

**Comment by aarbelaiz** [comment]
> "Multiple arbitrary MPR" .. could be reworded.. "Allow multiple planes on a single MPRVolumeStyle element"

:+1:

**Comment by andreasplesch** [comment]
log div id change to x3dom-log, see

https://sourceforge.net/p/x3dom/mailman/message/36676582/

**Comment by andreasplesch** [comment]
x3dom.css changes:  x3dom-progress has pointer-events:none

**Comment by jamesleesaunders** [comment]
New global ‘useGeoCache’ param option to toggle use of GeoCache.

**Comment by jamesleesaunders** [comment]
What’s the latest ETA for the next release?

**Comment by tsturm** [comment]
Release is planned for next week.

**Comment by jamesleesaunders** [comment]
Cool! Just in time for the Web 3D 2019 conference :-)
