### ISSUE TITLE
Prevent mouse navigation

### ISSUE THREAD

**Issue by tocloco** [x3dom/x3dom#956]
Hi there,
Is there any way to prevent the user from being able to navigate using the mouse?

I am using external buttons to handle navigation and so don't want the user to be able to click and drag the model around, or walk around etc.

I thought maybe I could use preventDefault on the mousedown event on the x3d node but at the same time I do want the user to be able to click on touchtriggers.

Any suggestions gratefully received.

**Comment by tsturm** [comment]
You can use NavigationInfo-Node to set the navigation type to "NONE":

```
<X3D>
    <Scene>
        <NavigationInfo type="NONE"></NavigationInfo>
        ....
    </Scene>
</X3D>
````

**Comment by tsturm** [comment]
@tocloco Can we close the issue?

**Comment by tocloco** [comment]
@tsturm Apologies for the delay. Yes I tested it and this works great thanks.
