### ISSUE TITLE
large (Geo)Elevationgrid incomplete

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#957]
A regression: A 600x300 grid is now rendered only to about a third of the grid points.

https://bl.ocks.org/andreasplesch/c7d9812e8d0cd8eab7f97454572aab87/9ea781f4f69c162942e813f3a5d4f6392f397b06
no console errors. Not sure what happened.

**Comment by andreasplesch** [comment]
also regression for regular ElevationGrid:

https://bl.ocks.org/andreasplesch/6d722cfe860b430886344d9ebc908afa

**Comment by andreasplesch** [comment]
https://jsfiddle.net/andreasplesch/u97rapk4/1/

large pointsets still work

**Comment by andreasplesch** [comment]
large indexedtrianglesets also still work:
https://x3dom-large-itriangleset.glitch.me/
and also indexedfaceset:
https://x3dom-large-ifs.glitch.me/

**Comment by tsturm** [comment]
fixed with 86005478fa165c940c581b087d580bb1fd263625

**Comment by andreasplesch** [comment]
confirmed, thanks !
