### ISSUE TITLE
viewpointChanged event has disappeared?

### ISSUE THREAD

**Issue by dmorehead** [x3dom/x3dom#958]
within the last week, (may 16 2019) this viewpoint event has stopped working.

https://codepen.io/mrmernan/pen/RmVyma?editors=1010

in the HTML section, enable line 9 to break it

..working (for the past few years)
src="https://www.x3dom.org/download/1.7.2/x3dom-full.js"

..not working as of this week
src="https://www.x3dom.org/download/dev/x3dom.js"

**Comment by tsturm** [comment]
should be fixed with: 2a9ed5a0b788b2707e9d4b6da53034165144b9ee

**Comment by andreasplesch** [comment]
Hm, it just occurred to me that the fix overwrites existing node.onviewpointchanged assignment by user code. So you could not have both, listeners added with the property and in parallel listeners added with addEventListener.

Hm, also you could only have one listener function, not multiple.

See my comment on the commit for another solution.

**Comment by andreasplesch** [comment]
https://codepen.io/anon/pen/GaEJEm?editors=1010 is the example with two handlers. The first one defined by node.onviewpointchanged and the second one by .addEventListener().

This happens to work with stable and the dev before the fix.

With the fix the .onviewpointchanged property gets overwritten and so the handler function is not called anymore.

This is probably rare but a possible solution is this small edit:

https://github.com/x3dom/x3dom/commit/34d7185f1b1e40c9510f355923b837881910fddb#r33577237

and not overwriting the property (eg. reverting the commit).

**Comment by dmorehead** [comment]
thanks for jumping on this quickly, ..just remembered that even when working correctly, viewpointChanged is kinda incomplete as it never gets fired when animating the VP matrix directly (in the case of binding from one VP to another etc) i.e. x3dCanvas.parent.doc._viewarea.animateTo() ..that likely opens up bigger problems but I thought it was worth mentioning.

**Comment by andreasplesch** [comment]
I added another viewpoint to https://codepen.io/anon/pen/GaEJEm?editors=1010

viewpointchanged of cam gets not called when animating to cam2 by pressing PgUp. But the handler gets called when animating from cam2 to cam. I guess the target viewpoint is considered the active viewpoint right away, and then considered changing.

https://github.com/x3dom/x3dom/blob/86005478fa165c940c581b087d580bb1fd263625/src/gfx_webgl.js#L3918 is where the handler gets called. It just checks if the current viewpoint viewMatrix changed.

**Comment by tsturm** [comment]
@andreasplesch You are right.
I changed it with 2d664cd1d71fdfca1371222aaaf2de3113222960

**Comment by andreasplesch** [comment]
Let's see what else comes up ...
BTW, the auto_syncs are from a zapier zap to keep my fork in sync. The cross-referencing of the PR here is a little noisy. Perhaps I can change it to not mention the PR.

**Comment by tsturm** [comment]
If you the switch the viewpoint with pgup/pgdown you need a change listener on all of your viewpoints.

With my last commit I added the ability to add viewpointChanged-Listeners also to the Scene-Node.
This listener is triggered independent of the currently bound viewpoint node.

```
document.querySelector( "scene" ).addEventListener( "viewpointChanged", ( e ) =>
{
    console.log( e );
});
```

**Comment by tsturm** [comment]
@dmorehead Can we close the issue?

**Comment by dmorehead** [comment]
yes, ..really like the idea of adding the event listener to the scene to handle any VP ..that seems more like what I imagined viewpointChanged to do.
many thanks!
