### ISSUE TITLE
Regression: transparency for triangleset

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#960]
Transparency for TriangleSet stopped working:

http://bl.ocks.org/andreasplesch/c345fd9431a39f2bc81757c6bcbc1222

**Comment by andreasplesch** [comment]
Hm, looks like a more general problem. Sphere does have transparency:

http://x3dgraphics.com/examples/X3dForWebAuthors/Chapter05AppearanceMaterialTextures/TransparencyX3dom.xhtml

**Comment by andreasplesch** [comment]
This should work, too, but does not:

http://www.web3d.org/x3d/content/examples/ConformanceNist/Appearance/Material/transparency_complexX3dom.xhtml

**Comment by andreasplesch** [comment]
thanks looks good

**Comment by dmorehead** [comment]
When an imageTexture node is present, material transparency no longer works.  Transparent pixels within the imageTexture still work though!  The black pixels on the torus are semi-transparent when comparing to x3dom-1.7.2 

https://codepen.io/mrmernan/pen/RwrPLXx

**Comment by andreasplesch** [comment]
According to the spec, how alpha is modulated depends on the number of color components in the texture. To modulate/blend provide origChannelCount="2" to the texture node since x3dom cannot easily determine the number of color components in a png image:

https://jsitor.com/embed/nMRPPm_t8?html&result&

**Comment by dmorehead** [comment]
ah ..I should have used an image with some color. origChannelCount looks promising but when using an image with color, only the blue channel appears to be 'lit' ..red & green are black. origChannelCount="3" (or more) restores all color but disables material transparency again.

..updated my pen with color image
https://codepen.io/mrmernan/pen/RwrPLXx

**Comment by andreasplesch** [comment]
I think the spec. requires that a full color texture ignores the material transparency. There may be a workaround.

**Comment by andreasplesch** [comment]
https://jsitor.com/gD0TX42-f

shows as a workaround how to force modulating/blending material and full color texture.

I think X3DV4 may require blending, eg. multiplying color and texture.

**Comment by andreasplesch** [comment]
slightly updated making the material color white:
https://jsitor.com/gD0TX42-f

**Comment by dmorehead** [comment]
Excellent, material transparency with full color texture SOLVED!
