### ISSUE TITLE
Background urls out of order

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#972]
The provided urls for back,fron,top,bottom,left,right are used out of order:

https://raw.githack.com/x3dom/x3dom/background_test/doc/misc/iX/sonnensystem_x3dom.html

https://raw.githack.com/x3dom/x3dom/background_test/test/regression-suite/test/cases/cubemap/cubemap.html

**Comment by elmkni** [comment]
Hi Andreas,

I tested the incorrect mapping of the 6 cubemap images myself.

Indeed they are not correctly placed! See my screenshot:

![cubemap_space](https://user-images.githubusercontent.com/53652478/62457322-e1945a80-b77a-11e9-850b-486da1ccec9b.png)

I added my test-files in [cubemap_space.zip](https://github.com/x3dom/x3dom/files/3467112/cubemap_space.zip)

cubemap_space.html
cubemap_space.png
cubemap_space.txt

With best regards,

Elmar

**Comment by andreasplesch** [comment]
Thanks for the confirmation. Fix in #973 .

**Comment by tsturm** [comment]
@andreasplesch Should we add the last commits as a patch to the current stable release?

**Comment by jamesleesaunders** [comment]
Shouldn’t it just follow the semver standard (major, minor, patch) release version numbering? I also feel that having regular patch releases gives a good impression that a prone t is current and active. Maybe not for a single bug but if we collect a few then I think 1.8.1 I think is worth it.
Also the npm version will have to be 1.8.1 as you can not easily update versions on npm.

**Comment by andreasplesch** [comment]
Let's get this out sooner rather than later. I would just agree to what @tsturm wants to do but having a quick 1.8.1 seems cleanest. 1.8.0 could perhaps even be removed from the x3dom.org server if there are constraints.

**Comment by tsturm** [comment]
Okay, then let us collect some bugs and release 1.8.1 in a few weeks.
