### ISSUE TITLE
Debug-Log: 'v'-key still does not display 'fieldOfView' and 'centerOfRotation' values

### ISSUE THREAD

**Issue by elmkni** [x3dom/x3dom#974]
Hi there,

I have just tested the latest 1.8.1-dev-release of X3DOM and
found that the 'v'-key (when debug-log is switched on) still
does not display the 'fieldOfView' value, which is needed to
reproduce the present view by copying/pasting the \<Viewpoint\>
node to the displayed file. 'centerOfRotation' is also missing.

Could it be possible to add this features to X3DOM?

With best regards

Elmar Knittel

P.S.:

Thanks for having restored text-selection to the debug-log
and of re-establishing the un-documented feature to be able
to set a static background-image by defining only 'backUrl'
in the \<Background\> node!

**Comment by tsturm** [comment]
fixed with a59e99b64645b294603c382825f53fd958e45aca

**Comment by elmkni** [comment]
Thank you very much, I appreciate it!

Maybe you should have a look at issue #975 too ...

With best regards,

Elmar
