### ISSUE TITLE
ComposedShader works in v1.7.2 but does **not** work in v1.8.1-dev

### ISSUE THREAD

**Issue by elmkni** [x3dom/x3dom#981]
Hi volks,

it's me again: Elmar!

I am back with a new issue: A **ComposedShader**, that worked flawlessly at least since **X3DOM v1.6.2** (**tested!**), has stopped working under **X3DOM v1.8.0**!

**Am I missing something?**

I know **X3DOM v1.8.0/v1.8.1-dev** is **WebGL-2.0/OpenGL-ES-3.0** etc., but what's **wrong** with my shader?
```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv='Content-Type'    content='text/html;charset=utf-8'/>
    <meta http-equiv="X-UA-Compatible" content="chrome=1,IE=edge" />

    <title>Advanced Shader Material</title>

    <link   type='text/css' rel='stylesheet' href='x3dom.css'/>
    <script type="text/javascript"            src="x3dom.js"></script>
  </head>
  <body>
    <X3D showStat='false' showLog='false' width='512px' height='512px'>
      <Scene>
        <Viewpoint></Viewpoint>
        <Shape>
          <Appearance>
            <ComposedShader language='GLSL'>
              <ShaderPart type='VERTEX' style="display:none;">
                attribute vec3 normal;
                attribute vec3 position;

                uniform mat4 normalMatrix;
                uniform mat4 texTrafoMatrix;
                uniform mat4 modelViewMatrix;
                uniform mat4 modelViewProjectionMatrix;

                varying vec2 index;

                void main(void)
                {
                 vec3 P = ( modelViewMatrix * vec4( position,  1.0 ) ).xyz;
                 vec3 N = (    normalMatrix * vec4( normal,    1.0 ) ).xyz;
                 vec3 R = normalize( reflect( P, N ) ); R.z += 1.0;

                 index = R.xy / 2.0 / sqrt( dot( R, R ) ) + 0.5;
                 index = ( texTrafoMatrix * vec4( index, 1.0, 1.0 ) ).xy;

                 gl_Position = modelViewProjectionMatrix * vec4(position, 1.0);
                }
              </ShaderPart>
              <ShaderPart type='FRAGMENT' style="display:none;">
                #ifdef GL_FRAGMENT_PRECISION_HIGH
                  precision highp float;
                #else
                  precision mediump float;
                #endif

                varying vec2 index;

                uniform sampler2D chrome;

                void main(void) { gl_FragColor = texture2D( chrome, index ); }
              </ShaderPart>
            </ComposedShader>
            <Material diffuseColor='1 0 0'></Material>
            <PixelTexture image='2 2 1 0 255 255 0'></PixelTexture>
            <TextureTransform scale='5 5' rotation='.7854' translation='.05 0'>
            </TextureTransform>
          </Appearance>
          <Box size='4 4 4'></Box>
        </Shape>
      </Scene>
    </X3D>
  </body>
</html>
```
In **X3DOM v1.7.2** the render looks like this:

![v3_chrome_transform_new_172](https://user-images.githubusercontent.com/53652478/63224903-4912c700-c1cb-11e9-913c-778cc8cabf1d.png)

But in **X3DOM v1.8.1-dev** the render looks like this:

![v3_chrome_transform_new_181](https://user-images.githubusercontent.com/53652478/63224916-634ca500-c1cb-11e9-9e37-0f5918de659b.png)

**Please help me!**

With best regards,

Elmar

P.S.: As always, the used files: [x3dom_github_issue_981.zip](https://github.com/x3dom/x3dom/files/3513074/x3dom_github_issue_981.zip)

**Comment by tsturm** [comment]
Should be fixed with 1b02b2a

**Comment by andreasplesch** [comment]
https://jsitor.com/eL-zgpvTL for live experiments.
Does the regex allow white space before and/or after the optional "void" ?
\(\s*(void)*\s*\) may be an option: https://regex101.com/r/DsEEoi/1

**Comment by tsturm** [comment]
Yes, that makes sense.
Added with c55b83f138a2ce86d57280c9b49d1c18553bc7e0

**Comment by elmkni** [comment]
Hi volks,

**thank you very much** for the fast fix!

I wouldn't have thought, that it's the '**void**' that caused all the trouble! **Finally the shader works again**:

![v3_chrome_transform_new](https://user-images.githubusercontent.com/53652478/63244576-1665de80-c25e-11e9-9146-c8e0e3d521a6.png)

So I can close this (#981) issue!

With best regards,

Elmar
