### ISSUE TITLE
shader parsing too early

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#984]
https://raw.githack.com/x3dom/x3dom/master/test/functional/shadowIdTest/highlighting_test.html

currently fails because the shader is not yet loaded from the file when extractShaderSection tries to parse it. It does get loaded then shortly afterwards.

**Comment by andreasplesch** [comment]
The problem occurs with 
https://raw.githack.com/andreasplesch/x3dom/shaderUrl/test/functional/shadowIdTest/highlighting_test.html

The shaderpart with the url is programmatically included.

but not with

https://raw.githack.com/andreasplesch/x3dom/shaderUrl/test/regression-suite/test/cases/composedShader/composedShaderUrl.html

The shaderpart with the url is directly provided.

**Comment by andreasplesch** [comment]
I could not figure out how to delay creation of the gl shader until after the xhr returns.

**Comment by andreasplesch** [comment]
x3dom 1.7.2 has the same problem: `ERROR: [ComposedShader] VertexShader ERROR: 0:1: 'shader' : syntax error`

**Comment by andreasplesch** [comment]
branch stable/1.6.x does not have the problem in the example (but other issues, probably unrelated)

**Comment by andreasplesch** [comment]
In 1.7 and later RequestManager is used to for fetching the url:
https://github.com/x3dom/x3dom/blob/master/src/nodes/Shaders/ShaderPart.js#L82
in 1.6, the request is sent immediately.
RequestManager has limit for 40 parallel downloads. In the example this limit is exceeded before the ShaperPart url is requested. So the request is queued and the shader not available when the shader is compiled.
A quick fix to make the example work a bit better is to increase the max parallel download limit for RequestManager. I am actually not sure what the purpose of the limit is since the browser itself has a smaller limit of concurrent connections.
Another option is to not use RequestManager and go back to just directly sending the request with .send.

**Comment by andreasplesch** [comment]
https://github.com/x3dom/x3dom/commit/bf102b10a1e6689d6713ef0d9c2120e7cd406828
uses option 1 to increase the limit to 50.

**Comment by tsturm** [comment]
Hi @andreasplesch,

sorry for the late response.

With fc3a39b I have introduced two simple default shaders which are used until the real shaders are loaded. This should fix the Issue.

**Comment by andreasplesch** [comment]
I tested with max. request reverted to 40, and it works fine. Do you want to revert https://github.com/x3dom/x3dom/commit/bf102b10a1e6689d6713ef0d9c2120e7cd406828 then, or just leave it ?

**Comment by tsturm** [comment]
I would just leave it.

**Comment by andreasplesch** [comment]
ok
