### ISSUE TITLE
minify with uglify

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/x3dom#987]
I added a uglifyjs minifying step for CI building on netlify which results in about 300KB savings over the jsmin versions. It works but I could not find a python port of uglifyjs, so currently it requires node. I simply invoke uglifyjs after the python building in the build script:
```bash
  cd dist &&
  echo "build command: uglifyjs x3dom.js -o x3dom.min.js -c -m && ..." &&
  uglifyjs x3dom.js -o x3dom.min.js -c -m &&
  echo "build command: uglifyjs x3dom-full.js -o x3dom-full.min.js -c -m && ..." &&
  uglifyjs x3dom-full.js -o x3dom-full.min.js -c -m &&
  echo "build command: uglifyjs x3dom-full-physics.js -o x3dom-full-physics.min.js -c -m && ..." &&
  uglifyjs x3dom-full-physics.js -o x3dom-full-physics.min.js -c -m &&
  cd ../ &&
```
It may be worth considering to do this on the x3dom.org build server as well.

**Comment by andreasplesch** [comment]
All test examples in the repo continue to work with the minified versions. I also experimented with closure but could not get it to work for the -full versions.

**Comment by jamesleesaunders** [comment]
+1 for using Node and uglifyjs :-) Well done! 
This also paved the way for using Node testing frameworks :-)

**Comment by andreasplesch** [comment]
https://x3dom.netlify.com/x3dom.min.js and https://x3dom.netlify.com/x3dom-full.min.js could use more scrutiny. I am using uglifjs-es which may not be as well tested.
node is preinstalled on the netlify docker image, so it was just a matter of installing uglifyjs with npm.

**Comment by tsturm** [comment]
A first version of a completely Node-based Build-System is now available in the [new_build_system ](https://github.com/x3dom/x3dom/tree/new_build_system) branch.

```git checkout origin/new_build_system```

```npm install```

```npm run build```

**Comment by tsturm** [comment]
The new build system is using **terser**, a fork of the no longer maintained **uglify-es**
