### ISSUE TITLE
If fragEyeIdx == -1.0 or fragEyeIdx == -1.0

### ISSUE THREAD

**Issue by Sgeo** [x3dom/x3dom#991]
https://github.com/x3dom/x3dom/blob/1da33bd3a930609af7015fcfa5cfbf10a4e6cd79/src/shader/ShaderComposed.js#L90

Was trying to browse the code to understand something unrelated to VR (specifically ignoring diffuseColors when a texture is present) when I stumbled on this, which looks a bit strange. If fragEyeIdx == -1 do something, otherwise if it's still -1 do something else.

**Comment by andreasplesch** [comment]
https://github.com/x3dom/x3dom/commit/ec5a66603263afb850d5c23c356d22855eed6929 introduced that. Perhaps @tsturm put it in as a placeholder ?
eyeIdx = 1 goes with the matrices ending with 2 (right eye I believe), so you give that a quick try (perhaps with devtools overrides).

**Comment by tsturm** [comment]
Looks like a copy/paste bug. I will fix it.

**Comment by andreasplesch** [comment]
Thanks. Did anybody have a chance to test the fix with a VR setup ?
