### ISSUE TITLE
Release v1.8.1

### ISSUE THREAD

**Issue by jamesleesaunders** [x3dom/x3dom#992]
@tsturn Can we release v1.8.1 now?
This version contains a number of great bug fixes which it would be good to get into release :-)

It would also be good to get it published to npm also.

There has been an increased developer interest in x3dom in recent months and I think it is important to keep regular incremental releases flowing so people can see x3dom is a active project.

**Comment by tsturm** [comment]
Release is out!

@jamesleesaunders, @andreasplesch: Can one of you write a mail to the mailing lists: x3dom-users, x3dom-developers, x3d-public, etc.

@fibo Can you publish the new version to npm, please.

**Comment by jamesleesaunders** [comment]
Thanks @tsturm ! 
Sure I’ll pop message out to mailing lists.

**Comment by jamesleesaunders** [comment]
Post sent out to mailing list, twitter and Reddit.

**Comment by fibo** [comment]
Published on the registry.
