### ISSUE TITLE
diffuseColor incorrectly(?) ignored when grayscale(?) ImageTexture present

### ISSUE THREAD

**Issue by Sgeo** [x3dom/x3dom#993]
According to the [X3D spec](https://www.web3d.org/documents/specifications/19775-1/V3.2/Part01/components/lighting.html#Lightingon), when the ImageTexture is an intensity texture, the diffuse factor used in the lighting calculation should be based on the diffuseColor, unlike RGB textures, where the diffuseColor is ignored. The [VRML 2.0 spec](http://gun.teipir.gr/VRML-amgem/spec/part1/nodesRef.html#ImageTexture) uses clearer language to basically say the same thing, although it does state that diffuseColor can be ignored with grayscale ImageTextures as an optimization.

I am also unclear from the spec how it is determined that an image is grayscale.

In the below samples, I have set diffuseColor to `1 0 0`. The first image shown for each program uses a full color texture and so diffuseColor should be ignored and the globe should appear normal. The second image shown uses the same texture converted to grayscale, and so diffuseColor should be used and the globe should appear red.

### InstantReality Viewer
![image](https://user-images.githubusercontent.com/251161/65811470-b7618680-e186-11e9-86ef-34a3bc2132f9.png)
![image](https://user-images.githubusercontent.com/251161/65811477-da8c3600-e186-11e9-8c4a-61a4cab2d2f8.png)

### X3DOM
![image](https://user-images.githubusercontent.com/251161/65811492-fdb6e580-e186-11e9-9042-e72021c3b6ea.png)
![image](https://user-images.githubusercontent.com/251161/65811494-060f2080-e187-11e9-8896-a2c7e1245c49.png)

I wish to note that this does affect real world assets. Below shows a Cybertown home in Blaxxun vs X3DOM
### Blaxxun
![image](https://user-images.githubusercontent.com/251161/65811506-54bcba80-e187-11e9-8a5b-0b32756d0fe5.png)

### X3DOM
![image](https://user-images.githubusercontent.com/251161/65811509-64d49a00-e187-11e9-8178-4bfda1f71013.png)

Sample globe files: [DiffuseColor.zip](https://github.com/x3dom/x3dom/files/3665095/DiffuseColor.zip)

**Comment by Sgeo** [comment]
It looks like this issue has come up before: https://github.com/x3dom/x3dom/issues/579

So for optimization purposes, scene authors are expected to set origChannelCount instead of having X3DOM attempt an autodetection? I suppose I could write some code to go through, find each ImageTexture node, and attempt to automatically set origChannelCount

**Comment by tsturm** [comment]
The main problem is that there is no solution to automaticly detect the original channel count of an image in Javascript. Every image in Javascript is a four channel image. This is the reason for the introduction of the origChannelCount-Attribute in x3dom.

**Comment by splace** [comment]
> I am also unclear from the spec how it is determined that an image is grayscale.

i always thought that grey scale was defined from the images format, any sort of sniffing was not what was meant. it would be bound to cause confusion/browser-dependence.

so a jpg can never hold a greyscale, just convert to a format where you can specify greyscale.(png) 

(a png could still contain all grey colours, and not be a greyscale, just like jpg.)

**Comment by Sgeo** [comment]
I was looking at the Blaxxun Contact 4.3 code (which is non-commercial, not sure how much I can say), and that seemed to check all the pixels of the image, but it does look like that's off [spec](https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/texturing.html#TextureMapImageFormats), which does say to just look at the image format, I think.

In theory X3DOM could separately retrieve and parse the image file manually, although I suppose that wouldn't be great for performance.

**Comment by andreasplesch** [comment]
Yes, it looks like the spec relies on the information provided by the image format itself:

https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/texturing.html#ImageTexture

HTML does not care much about the number of channels in an image. The user agent is responsible for rendering an image. An HTML canvas is always rendered as RGBA.

It is possible to use JS libraries to parse PNG, JPG and others but it would be inefficient and would increase the code base.

**Comment by splace** [comment]
> In theory X3DOM could separately retrieve and parse the image file manually, although I suppose that wouldn't be great for performance.

yes but a second file load would be from cache, so no more traffic.

> so a jpg can never hold a greyscale, just convert to a format where you can specify greyscale.(png)

NO my mistake,  jpeg does have a greyscale version, doesn't seem to be well used now. it just has no transparency.

**Comment by jamesleesaunders** [comment]
Just to keep discussions in sync here is a similar but different discussion over on x_ite https://github.com/create3000/x_ite/issues/50

**Comment by tsturm** [comment]
In the current [dev-Version](https://x3dom.org/download/dev/) I try to detect the original channel count from the image header or the global color palette of the image.

An example can be found here:
[https://examples.x3dom.org/channelCount/](https://examples.x3dom.org/channelCount/)

**Comment by andreasplesch** [comment]
I found this example:

https://www.web3d.org/x3d/content/examples/ConformanceNist/Appearance/ImageTexture/greyscale_jpg_diffuseColorX3dom.xhtml

It works correctly now with the dev version.

Here is a similar example which uses a Color node instead of a Material node:

https://www.web3d.org/x3d/content/examples/ConformanceNist/Appearance/Appearance/unlit_greyscale_color_blendX3dom.xhtml

It shows black with the dev version.

**Comment by jamesleesaunders** [comment]
I don’t know if you have seen the discussions from @michaliskambi and @splace at
https://github.com/create3000/x_ite/issues/50#issuecomment-537438619
But (as I understand it) there is a proposal to simplify this in X3D 4, draft at:
https://github.com/michaliskambi/x3d-tests/wiki/Make-RGB-and-grayscale-textures-treatment-consistent

**Comment by tsturm** [comment]
@andreasplesch For me it looks correct with the current dev-Version:
![unlit_greyscale_color_blend](https://user-images.githubusercontent.com/864076/66226850-17eb4900-e6dc-11e9-950e-07ff3547a755.PNG)

**Comment by andreasplesch** [comment]
Hm, https://examples.x3dom.org/channelCount/unlit_greyscale_color_blend.html is black for me also:
![image](https://user-images.githubusercontent.com/6171115/66233131-97672100-e6b8-11e9-9873-415a2af174ab.png)
Chrome Version 77.0.3865.75 (Official Build) (64-bit) Linux, no errors

**Comment by tsturm** [comment]
Really strange. Works for me with

* Chrome Version 77.0.3865.90 (Official Build) (64-Bit), Windows 10
* Firefox 69.0.2 (64-Bit), Windows 10
* Microsoft Edge 44.18362.387.0, Windows 10

**Comment by andreasplesch** [comment]
Also black on Firefox 60.9.0esr (64-bit) Linux .

**Comment by tsturm** [comment]
Do you get some errors in the x3dom console?

**Comment by andreasplesch** [comment]
No, all green in x3dom debug console.

**Comment by andreasplesch** [comment]
Should we also add channel count auto-detection to PixelTexture:

https://www.web3d.org/x3d/content/examples/ConformanceNist/Appearance/PixelTexture/greyscale_diffuseColorX3dom.xhtml

It would be the easiest of all the formats since the number of channels/components is directly provided.

**Comment by andreasplesch** [comment]
Perhaps a webgl/driver issue ?
I have
```
Quadro P4000/PCIe/SSE2
OpenGL 4.6.0 NVIDIA 418.74
```

**Comment by tsturm** [comment]
PixelTexture: Yes, we should :)

Example: I will try to debug the example on a Linux system with Quadro next week.

**Comment by andreasplesch** [comment]
PixelTexture: I think it may be almost a one line fix Texture.js . I am trying some things.

**Comment by andreasplesch** [comment]
https://github.com/x3dom/x3dom/pull/999

**Comment by tsturm** [comment]
merged ;) Thanks!

**Comment by andreasplesch** [comment]
https://examples.x3dom.org/channelCount/unlit_greyscale_color_blend.html is balck for me on Android Chrome as well as on linux.

**Comment by tsturm** [comment]
Sorry, there was no Linux/Quadro system available this week. Hope I can debug it next week.

Can you try this example:

https://examples.x3dom.org/channelCount/unlit_greyscale_color_blend2.html

**Comment by brutzman** [comment]
Question: is this driving to closure satisfactorily? Are precise changes expected for [X3Dv4](https://www.web3d.org/X3D4)?

The X3D Architecture Specification must have consistent rendering well defined.  This is critical path forward, the X3D Working Group will refine or amend the X3Dv4 specification as needed to ensure consistent results.  This is a primary feature of X3D, especially for archival publication and sharing of models.

Getting X3D Appearance of materials and texture unambiguously defined and consistently implemented is very important, especially in preparation for addition of Physically Based Rendering (PBR) and correspondingly advanced lighting model to X3Dv4.

Thanks in advance for all scrutiny and progress.

**Comment by andreasplesch** [comment]
https://examples.x3dom.org/channelCount/unlit_greyscale_color_blend2.html

is also black on my Linux/Quadro system.

No debug or console messages.

**Comment by andreasplesch** [comment]
The focus here was on making x3dom more v3.3 compliant. For v4, a rough draft for language for v4 requiring always multiplication for diffuse and texture would be the next step. Perhaps just modifying the tables suffices ?

**Comment by tsturm** [comment]
The Quadro/Android issues should be fixed with my last commit 301a0e6fec27fad8dbeb8624010cc6d3547bc935

@andreasplesch Can you try it again?

https://examples.x3dom.org/channelCount/unlit_greyscale_color_blend.html

**Comment by andreasplesch** [comment]
Yes, that example works on Linux/Quadro, and on Android.

**Comment by tsturm** [comment]
Perfect!
