### ISSUE TITLE
X3DTextureNode origChannelCount unresponsive to dynamic changes

### ISSUE THREAD

**Issue by Sgeo** [x3dom/x3dom#994]
https://github.com/x3dom/x3dom/blob/e4b752ec0858aeb1ca1c40e2d3b2e9feffe5d947/src/nodes/Texturing/X3DTextureNode.js#L105

If I want to automatically detect whether a texture is grayscale and redo the `origChannelCount` if it is (see #993), I would like to simply set the `origChannelCount` instead of reconstructing the node. However, it looks like `origChannelCount` is used only during the constructor and changing it later on will not impact the end result.

**Comment by tsturm** [comment]
Fixed with 6771687df13ab668da3b7428fa9891b94f5b7eff
