### ISSUE TITLE
Volume rendering example error

### ISSUE THREAD

**Issue by sina-masoud-ansari** [x3dom/x3dom#995]
In trying to load the Aorta volume rendering example shown here:

https://examples.x3dom.org/volren/volrenOpacityTestTF_aorta.xhtml

I'm getting this error on Chrome Version 77.0.3865.75 (Official Build) (64-bit)

Uncaught TypeError: Cannot set property 'width' of undefined
    at x3dom.X3DCanvas._createHTMLCanvas (x3dom-full.js:1669)
    at new x3dom.X3DCanvas (x3dom-full.js:1573)
    at onload (x3dom-full.js:1755)

**Comment by andreasplesch** [comment]
Firefox 60.9.0esr has a similar error:

```TypeError: x3dElem.style is undefined[Learn More]```

**Comment by andreasplesch** [comment]
x3dElem is an UnknownElement:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLUnknownElement

It should have a style property.

Hm, the example works with 1.7.2, without the error.

**Comment by andreasplesch** [comment]
The x3dElem.style.width setting apparently was added with a large webvr merge:
https://github.com/x3dom/x3dom/commit/fe75af722d97bc5f103aa99d914ce6d37fe4c9d2
by @tsturm ;

**Comment by andreasplesch** [comment]
The workaround for now is to use proper styling for the x3d element, and avoid the width and height attributes.

**Comment by tsturm** [comment]
Seems like a problem with the deprecated .xhtml format. The .html version works fine:

[https://examples.x3dom.org/volren/volrenOpacityTestTF_aorta.html](https://examples.x3dom.org/volren/volrenOpacityTestTF_aorta.html)

**Comment by andreasplesch** [comment]
Perhaps ultimately a browser support issue although both FF and Chrome complain.  XHTML is less popular but alive and undeprecated:

https://html.spec.whatwg.org/multipage/introduction.html#html-vs-xhtml

**Comment by andreasplesch** [comment]
` .setAttribute('style","width:" + ..)` may be an alternative.

**Comment by sina-masoud-ansari** [comment]
@tsturm @andreasplesch Thanks for looking into this, great to see it working.

**Comment by andreasplesch** [comment]
https://gist.githack.com/andreasplesch/86f041891959e8ff224ac9738225635b/raw/99d4c3690d313c77c0a20e2eabf2b17e64192398/UnknownElementStyle.xhtml works.

Not sure what else to try.
